// SPDX-License-Identifier: BSD-3-Clause

package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestRunDispatchesRenderFreeBSD(t *testing.T) {
	dir := t.TempDir()
	configPath := filepath.Join(dir, "router.yaml")
	if err := os.WriteFile(configPath, []byte(testRouterYAML("render-dispatch")), 0644); err != nil {
		t.Fatalf("write config: %v", err)
	}
	var stdout strings.Builder
	if err := run([]string{"render", "freebsd", "--config", configPath}, &stdout, os.Stderr); err != nil {
		t.Fatalf("routerd render freebsd: %v", err)
	}
	if !strings.Contains(stdout.String(), "# Generated by routerd.") {
		t.Fatalf("render freebsd stdout missing rc.conf header:\n%s", stdout.String())
	}
}

func TestRenderCommandRejectsUnknownTarget(t *testing.T) {
	err := renderCommand([]string{"linux"}, &strings.Builder{})
	if err == nil || !strings.Contains(err.Error(), `unknown render target "linux"`) {
		t.Fatalf("renderCommand(linux) err = %v, want unknown render target", err)
	}
	if err := renderCommand(nil, &strings.Builder{}); err == nil || !strings.Contains(err.Error(), "render requires a target") {
		t.Fatalf("renderCommand() err = %v, want missing target error", err)
	}
}

func TestRenderFreeBSDUsesFreeBSDValidationTarget(t *testing.T) {
	dir := t.TempDir()
	configPath := filepath.Join(dir, "carp.yaml")
	config := `apiVersion: routerd.net/v1alpha1
kind: Router
metadata: {name: carp}
spec:
  resources:
    - apiVersion: net.routerd.net/v1alpha1
      kind: Interface
      metadata: {name: lan}
      spec: {ifname: em0, managed: false, owner: external}
    - apiVersion: net.routerd.net/v1alpha1
      kind: VirtualAddress
      metadata: {name: vip}
      spec:
        family: ipv4
        interface: lan
        address: 198.18.232.100/32
        mode: vrrp
        vrrp: {virtualRouterID: 232, priority: 150}
`
	if err := os.WriteFile(configPath, []byte(config), 0644); err != nil {
		t.Fatal(err)
	}
	if err := renderFreeBSDCommand([]string{"--config", configPath}, &strings.Builder{}); err != nil {
		t.Fatalf("renderFreeBSDCommand rejected FreeBSD-valid CARP: %v", err)
	}
}
