.PHONY: run render-compatibility graceful-vrrp-activation vxlan-l2-transparency vxlan-l2-mss-clamp
run:
	sudo ./run-all.sh

render-compatibility:
	./render-compatibility.sh

graceful-vrrp-activation:
	sudo ./graceful-vrrp-activation.sh

vxlan-l2-transparency:
	sudo ./vxlan-l2-control-plane-transparency.sh

vxlan-l2-mss-clamp:
	sudo ./vxlan-l2-mss-clamp.sh
