.PHONY: run render-compatibility vxlan-l2-transparency vxlan-l2-mss-clamp
run:
	sudo ./run-all.sh

render-compatibility:
	./render-compatibility.sh

vxlan-l2-transparency:
	sudo ./vxlan-l2-control-plane-transparency.sh

vxlan-l2-mss-clamp:
	sudo ./vxlan-l2-mss-clamp.sh
