// SPDX-License-Identifier: BSD-3-Clause

package api

type ResourceKindSchema struct {
	APIVersion string
	Kind       string
	Spec       any
}

func ConfigResourceKinds() []ResourceKindSchema {
	return []ResourceKindSchema{
		{PluginAPIVersion, "Plugin", PluginSpec{}},
		{PluginAPIVersion, "DynamicConfigSource", DynamicConfigSourceSpec{}},
		{ConfigAPIVersion, "DynamicOverridePolicy", DynamicOverridePolicySpec{}},
		{SystemAPIVersion, "LogSink", LogSinkSpec{}},
		{ObservabilityAPIVersion, "Telemetry", TelemetrySpec{}},
		{SystemAPIVersion, "ObservabilityPipeline", ObservabilityPipelineSpec{}},
		{SystemAPIVersion, "LogRetention", LogRetentionSpec{}},
		{SystemAPIVersion, "Sysctl", SysctlSpec{}},
		{SystemAPIVersion, "SysctlProfile", SysctlProfileSpec{}},
		{SystemAPIVersion, "Package", PackageSpec{}},
		{SystemAPIVersion, "NTPClient", NTPClientSpec{}},
		{SystemAPIVersion, "NTPServer", NTPServerSpec{}},
		{SystemAPIVersion, "WebConsole", WebConsoleSpec{}},
		{SystemAPIVersion, "RouterdCluster", RouterdClusterSpec{}},
		{NetAPIVersion, "Interface", InterfaceSpec{}},
		{NetAPIVersion, "PPPoESession", PPPoESessionSpec{}},
		{NetAPIVersion, "WireGuardInterface", WireGuardInterfaceSpec{}},
		{NetAPIVersion, "WireGuardPeer", WireGuardPeerSpec{}},
		{NetAPIVersion, "TailscaleNode", TailscaleNodeSpec{}},
		{NetAPIVersion, "IPsecConnection", IPsecConnectionSpec{}},
		{NetAPIVersion, "VRF", VRFSpec{}},
		{NetAPIVersion, "VXLANTunnel", VXLANTunnelSpec{}},
		{NetAPIVersion, "IPv4StaticAddress", IPv4StaticAddressSpec{}},
		{NetAPIVersion, "VirtualAddress", VirtualAddressSpec{}},
		{NetAPIVersion, "BGPRouter", BGPRouterSpec{}},
		{NetAPIVersion, "BGPPeer", BGPPeerSpec{}},
		{NetAPIVersion, "BGPDynamicPeer", BGPDynamicPeerSpec{}},
		{NetAPIVersion, "BFD", BFDSpec{}},
		{NetAPIVersion, "DHCPv4Client", DHCPv4ClientSpec{}},
		{NetAPIVersion, "ClusterNetworkRoute", ClusterNetworkRouteSpec{}},
		{NetAPIVersion, "DHCPv4Server", DHCPv4ServerSpec{}},
		{NetAPIVersion, "DHCPv4Reservation", DHCPv4ReservationSpec{}},
		{NetAPIVersion, "DHCPv6Address", DHCPv6AddressSpec{}},
		{NetAPIVersion, "IPv6RAAddress", IPv6RAAddressSpec{}},
		{NetAPIVersion, "DHCPv6PrefixDelegation", DHCPv6PrefixDelegationSpec{}},
		{NetAPIVersion, "IPv6DelegatedAddress", IPv6DelegatedAddressSpec{}},
		{NetAPIVersion, "DHCPv6Information", DHCPv6InformationSpec{}},
		{NetAPIVersion, "IPv6RouterAdvertisement", IPv6RouterAdvertisementSpec{}},
		{NetAPIVersion, "DHCPv6Server", DHCPv6ServerSpec{}},
		{NetAPIVersion, "DHCPv4ServerLeaseSync", DHCPv4ServerLeaseSyncSpec{}},
		{NetAPIVersion, "DHCPv6ServerLeaseSync", DHCPv6ServerLeaseSyncSpec{}},
		{NetAPIVersion, "DHCPv6PrefixDelegationLeaseSync", DHCPv6PrefixDelegationLeaseSyncSpec{}},
		{NetAPIVersion, "DHCPv4Relay", DHCPv4RelaySpec{}},
		{NetAPIVersion, "SelfAddressPolicy", SelfAddressPolicySpec{}},
		{NetAPIVersion, "DNSZone", DNSZoneSpec{}},
		{NetAPIVersion, "DNSResolver", DNSResolverSpec{}},
		{NetAPIVersion, "DNSForwarder", DNSForwarderSpec{}},
		{NetAPIVersion, "DNSUpstream", DNSUpstreamSpec{}},
		{NetAPIVersion, "DSLiteTunnel", DSLiteTunnelSpec{}},
		{HybridAPIVersion, "TunnelInterface", TunnelInterfaceSpec{}},
		{HybridAPIVersion, "OverlayPeer", OverlayPeerSpec{}},
		{HybridAPIVersion, "HybridRoute", HybridRouteSpec{}},
		{HybridAPIVersion, "AddressMobilityDomain", AddressMobilityDomainSpec{}},
		{HybridAPIVersion, "CloudProviderProfile", CloudProviderProfileSpec{}},
		{HybridAPIVersion, "RemoteAddressClaim", RemoteAddressClaimSpec{}},
		{HybridAPIVersion, "ProviderActionPolicy", ProviderActionPolicySpec{}},
		{FederationAPIVersion, "EventGroup", EventGroupSpec{}},
		{FederationAPIVersion, "EventPeer", EventPeerSpec{}},
		{FederationAPIVersion, "EventSubscription", EventSubscriptionSpec{}},
		{FederationAPIVersion, "FederationSLO", FederationSLOSpec{}},
		{MobilityAPIVersion, "MobilityPool", MobilityPoolSpec{}},
		{MobilityAPIVersion, "MobilityMemberSet", MobilityMemberSetSpec{}},
		{MobilityAPIVersion, "SAMNodeSet", SAMNodeSetSpec{}},
		{MobilityAPIVersion, "SAMPeerGroup", SAMPeerGroupSpec{}},
		{MobilityAPIVersion, "SAMTransportProfile", SAMTransportProfileSpec{}},
		{MobilityAPIVersion, "SAMSubnetPolicy", SAMSubnetPolicySpec{}},
		{NetAPIVersion, "IPv4Route", IPv4RouteSpec{}},
		{NetAPIVersion, "HealthCheck", HealthCheckSpec{}},
		{NetAPIVersion, "EgressRoutePolicy", EgressRoutePolicySpec{}},
		{NetAPIVersion, "EventRule", EventRuleSpec{}},
		{NetAPIVersion, "DerivedEvent", DerivedEventSpec{}},
		{NetAPIVersion, "NAT44Rule", NAT44RuleSpec{}},
		{NetAPIVersion, "NAT44SessionSync", NAT44SessionSyncSpec{}},
		{NetAPIVersion, "ManagementAccess", ManagementAccessSpec{}},
		{FirewallAPIVersion, "PortForward", PortForwardSpec{}},
		{FirewallAPIVersion, "IngressService", IngressServiceSpec{}},
		{NetAPIVersion, "IPAddressSet", IPAddressSetSpec{}},
		{FirewallAPIVersion, "LocalServiceRedirect", LocalServiceRedirectSpec{}},
		{NetAPIVersion, "TrafficFlowLog", TrafficFlowLogSpec{}},
		{FirewallAPIVersion, "FirewallZone", FirewallZoneSpec{}},
		{FirewallAPIVersion, "FirewallPolicy", FirewallPolicySpec{}},
		{FirewallAPIVersion, "ClientPolicy", ClientPolicySpec{}},
		{FirewallAPIVersion, "FirewallRule", FirewallRuleSpec{}},
		{FirewallAPIVersion, "FirewallEventLog", FirewallEventLogSpec{}},
		{NetAPIVersion, "Hostname", HostnameSpec{}},
	}
}
