// SPDX-License-Identifier: BSD-3-Clause

import http from "node:http";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { chromium } from "playwright";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const webconsoleDir = path.resolve(scriptDir, "..");
const repoRoot = path.resolve(webconsoleDir, "..");
const staticDir = path.resolve(repoRoot, "pkg", "webconsole", "static");
const outputDir = process.env.ROUTERD_WEB_CONSOLE_SCREENSHOT_DIR
  ? path.resolve(process.env.ROUTERD_WEB_CONSOLE_SCREENSHOT_DIR)
  : path.resolve(repoRoot, "dist", "webconsole-screenshots");

if (!existsSync(path.join(staticDir, "index.html"))) {
  throw new Error(`missing built Web Console at ${staticDir}; run npm run build first`);
}

await mkdir(outputDir, { recursive: true });

const server = http.createServer(async (req, res) => {
  try {
    const url = new URL(req.url ?? "/", "http://127.0.0.1");
    if (url.pathname === "/api/v1/summary") return json(res, summaryFixture());
    if (url.pathname === "/api/v1/config") return json(res, configFixture());
    if (url.pathname === "/api/v1/generations") return json(res, generationsFixture());
    if (url.pathname.startsWith("/api/v1/generations/")) return generationResponse(url.pathname, res);

    const requestedPath = url.pathname === "/" ? "/index.html" : url.pathname;
    const filePath = path.resolve(staticDir, `.${requestedPath}`);
    if (!filePath.startsWith(staticDir)) return notFound(res);
    if (!existsSync(filePath)) return notFound(res);
    const data = await readFile(filePath);
    res.writeHead(200, {
      "content-type": contentType(filePath),
      "cache-control": "no-store",
    });
    res.end(data);
  } catch (error) {
    res.writeHead(500, { "content-type": "text/plain; charset=utf-8" });
    res.end(String(error));
  }
});

await new Promise(resolve => server.listen(0, "127.0.0.1", resolve));
const address = server.address();
const port = typeof address === "object" && address ? address.port : 0;
const baseURL = `http://127.0.0.1:${port}/`;

const browser = await chromium.launch();
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 980 }, deviceScaleFactor: 1 });
  await capture(page, "#overview", "overview-desktop.png");
  await capture(page, "#controllers", "controllers-desktop.png");
  await capture(page, "#connections", "connections-desktop.png");
  await capture(page, "#clients/inventory", "clients-desktop.png");
  await capture(page, "#firewall/timeline", "firewall-desktop.png");
  await capture(page, "#config", "config-desktop.png");

  const mobile = await browser.newPage({
    viewport: { width: 390, height: 844 },
    deviceScaleFactor: 2,
    isMobile: true,
    hasTouch: true,
  });
  await capture(mobile, "#overview", "overview-mobile.png");
  await capture(mobile, "#connections", "connections-mobile.png");
  await capture(mobile, "#clients/inventory", "clients-mobile.png");
} finally {
  await browser.close();
  server.close();
}

await writeFile(
  path.join(outputDir, "README.txt"),
  `Generated by webconsole/scripts/screenshot.mjs\nBase URL: ${baseURL}\n`,
);
console.log(`Wrote Web Console screenshots to ${outputDir}`);

async function capture(page, hash, fileName) {
  await page.goto(`${baseURL}${hash}`, { waitUntil: "networkidle" });
  await page.waitForSelector("main");
  await page.screenshot({ path: path.join(outputDir, fileName), fullPage: true });
}

function json(res, body) {
  res.writeHead(200, {
    "content-type": "application/json; charset=utf-8",
    "cache-control": "no-store",
  });
  res.end(JSON.stringify(body));
}

function notFound(res) {
  res.writeHead(404, { "content-type": "text/plain; charset=utf-8" });
  res.end("not found");
}

function generationResponse(urlPath, res) {
  const configMatch = urlPath.match(/^\/api\/v1\/generations\/(\d+)\/config$/);
  if (configMatch) {
    res.writeHead(200, { "content-type": "text/plain; charset=utf-8" });
    res.end(configFixture().text);
    return;
  }
  const diffMatch = urlPath.match(/^\/api\/v1\/generations\/(\d+)\/diff\/(\d+)$/);
  if (diffMatch) {
    res.writeHead(200, { "content-type": "text/plain; charset=utf-8" });
    res.end("--- generation-12.yaml\n+++ generation-13.yaml\n@@\n-  listenAddress: 127.0.0.1\n+  listenAddressFrom:\n+    resource: Interface/mgmt\n+    field: status.addresses[0]\n");
    return;
  }
  notFound(res);
}

function contentType(filePath) {
  if (filePath.endsWith(".html")) return "text/html; charset=utf-8";
  if (filePath.endsWith(".js")) return "text/javascript; charset=utf-8";
  if (filePath.endsWith(".css")) return "text/css; charset=utf-8";
  if (filePath.endsWith(".svg")) return "image/svg+xml";
  return "application/octet-stream";
}

function summaryFixture() {
  const now = new Date().toISOString();
  return {
    generatedAt: now,
    status: {
      status: {
        phase: "Healthy",
        generation: 13,
        resourceCount: 42,
      },
    },
    controllers: [
      { name: "address", mode: "live", reason: "Live", message: "controller is applying host state", resourceKinds: ["IPv4StaticAddress", "IPv6DelegatedAddress"] },
      { name: "firewall", mode: "dry-run", reason: "Manual", message: "controller-chain dry-run flag is true; firewall rules are observed but not enforced by this controller", resourceKinds: ["FirewallZone", "FirewallPolicy", "FirewallRule"] },
      { name: "dns-resolver", mode: "live", reason: "Live", message: "controller is applying host state", resourceKinds: ["DNSResolver", "DNSZone"] },
    ],
    phases: { Healthy: 39, "Dry-run": 3 },
    resources: resourceFixture(),
    interfaces: interfaceFixture(),
    events: eventFixture(now),
    connections: connectionFixture(),
    dnsQueries: [
      { questionName: "www.google.com", answers: ["142.250.207.68"] },
      { questionName: "api.github.com", answers: ["140.82.112.6"] },
      { questionName: "routerd.net", answers: ["2606:4700:3030::6815:1001"] },
    ],
    trafficFlows: [
      { clientAddress: "172.18.0.150", peerAddress: "142.250.207.68", resolvedHostname: "www.google.com", accounting: true, bytesOut: 512000, bytesIn: 9400000 },
      { clientAddress: "172.18.1.110", peerAddress: "140.82.112.6", resolvedHostname: "api.github.com", accounting: true, bytesOut: 88000, bytesIn: 1200000 },
    ],
    firewallLogs: [
      { id: 91, ts: now, action: "drop", srcAddress: "192.168.178.40", dstAddress: "172.18.0.1", protocol: "tcp", l3Proto: "ipv4", dstPort: 8080, inIface: "ens18", outIface: "ens19", packetBytes: 60 },
      { id: 90, ts: now, action: "drop", srcAddress: "35.72.114.176", dstAddress: "172.18.1.110", protocol: "udp", l3Proto: "ipv4", dstPort: 41641, inIface: "ds-lite-a", packetBytes: 92 },
    ],
    dhcpLeases: [
      { expiresAt: now, mac: "18:ec:e7:33:12:6c", ip: "172.18.0.150", hostname: "aiseg2", family: "ipv4", source: "dnsmasq" },
      { expiresAt: now, mac: "4e:20:15:aa:e0:67", ip: "172.18.1.110", hostname: "mcberry", family: "ipv4", source: "dnsmasq" },
    ],
    neighbors: [
      { ip: "2409:10:3d60:1271:879:3d5a:205d:ba39", ifname: "ens19", mac: "4e:20:15:aa:e0:67", state: "reachable", source: "ip-neigh" },
      { ip: "172.18.0.150", ifname: "ens19", mac: "18:ec:e7:33:12:6c", state: "reachable", source: "arp" },
    ],
    clients: [
      { id: "18:ec:e7:33:12:6c", hostname: "aiseg2", mac: "18:ec:e7:33:12:6c", vendor: "Panasonic", addresses: ["172.18.0.150"], state: "reachable", sources: ["dhcpv4", "neighbor"], bytesOut: 512000, bytesIn: 9400000, peers: ["www.google.com"] },
      { id: "4e:20:15:aa:e0:67", hostname: "mcberry", mac: "4e:20:15:aa:e0:67", vendor: "Apple", addresses: ["172.18.1.110", "2409:10:3d60:1271:879:3d5a:205d:ba39"], state: "reachable", sources: ["dhcpv4", "neighbor"], bytesOut: 88000, bytesIn: 1200000, peers: ["api.github.com"] },
    ],
    vpn: {
      wireGuard: [
        { name: "wg0", publicKey: "wg-interface-public", listenPort: 51820, peers: [{ publicKey: "peer-public", endpoint: "203.0.113.10:51820", allowedIPs: ["10.10.0.2/32"], latestHandshake: now, transferRxBytes: 2048, transferTxBytes: 4096, persistentKeepaliveSec: 25 }] },
      ],
      tailscale: { backendState: "Running", hostName: "homert02", dnsName: "homert02.tailnet.ts.net", tailscaleIPs: ["100.64.87.102"], online: true, active: true, exitNodeOption: true, peers: [{ id: "peer1", hostName: "phone", dnsName: "phone.tailnet.ts.net", online: true, active: true, relay: "tok", rxBytes: 123456, txBytes: 654321 }] },
    },
  };
}

function resourceFixture() {
  return [
    { apiVersion: "net.routerd.net/v1alpha1", kind: "EgressRoutePolicy", name: "ipv4-default", status: { phase: "Healthy", selectedCandidate: "ds-lite-a", selectedDevice: "ds-lite-a" } },
    { apiVersion: "net.routerd.net/v1alpha1", kind: "HealthCheck", name: "internet-via-dslite-a", status: { phase: "Healthy", target: "9.9.9.9" } },
    { apiVersion: "net.routerd.net/v1alpha1", kind: "DSLiteTunnel", name: "ds-lite-a", status: { phase: "Up", address: "192.0.0.2/29" } },
    { apiVersion: "net.routerd.net/v1alpha1", kind: "DNSResolver", name: "lan-resolver", status: { phase: "Ready", address: "172.18.0.1" } },
    { apiVersion: "firewall.routerd.net/v1alpha1", kind: "FirewallPolicy", name: "three-role", status: { phase: "Observed", changedFields: "dry-run" } },
    { apiVersion: "system.routerd.net/v1alpha1", kind: "Package", name: "router-tools", status: { phase: "Healthy" } },
  ];
}

function interfaceFixture() {
  return [
    { name: "wan", ifname: "ens18", phase: "Up", role: "untrust", zone: "wan", managed: false, mtu: 1454, hardwareAddress: "bc:24:11:aa:bb:01", addresses: ["192.168.1.249/24", "2409:10:3d60:1200::249/64"] },
    { name: "lan", ifname: "ens19", phase: "Up", role: "trust", zone: "lan", managed: true, mtu: 1454, hardwareAddress: "bc:24:11:aa:bb:02", addresses: ["172.18.0.1/16", "2409:10:3d60:1271::11/64", "2409:10:3d60:1271:be24:11ff:fee0:8e3a/64"] },
    { name: "mgmt", ifname: "ens20", phase: "Up", role: "mgmt", zone: "management", managed: false, mtu: 1500, hardwareAddress: "bc:24:11:aa:bb:03", addresses: ["192.168.123.129/24"] },
    { name: "tailscale", ifname: "tailscale0", phase: "Up", role: "trust", zone: "lan", managed: true, mtu: 1280, addresses: ["100.64.87.102/32"] },
  ];
}

function eventFixture(now) {
  return [
    { id: 1001, createdAt: now, severity: "info", topic: "routerd.resource.status.changed", resourceKind: "HealthCheck", resourceName: "internet-via-dslite-a", attributes: { phase: "Healthy", previousPhase: "Pending" } },
    { id: 1000, createdAt: now, severity: "info", topic: "routerd.dhcp.lease.renewed", resourceKind: "IPv4DHCPServer", resourceName: "lan-dhcp4", attributes: { mac: "18:ec:e7:33:12:6c", ip: "172.18.0.150", hostname: "aiseg2" } },
    { id: 999, createdAt: now, severity: "warn", topic: "routerd.firewall.packet.dropped", resourceKind: "FirewallPolicy", resourceName: "three-role", attributes: { action: "drop", source: "35.72.114.176", destination: "172.18.1.110", protocol: "udp" } },
  ];
}

function connectionFixture() {
  return {
    count: 635,
    max: 262144,
    byFamily: { ipv4: 410, ipv6: 225 },
    entries: [
      { family: "ipv4", protocol: "tcp", state: "ESTABLISHED", assured: true, timeout: 431999, original: { source: "172.18.1.110", sourcePort: "55124", destination: "140.82.112.6", destinationPort: "443" } },
      { family: "ipv4", protocol: "udp", state: "ASSURED", assured: true, timeout: 179, original: { source: "172.18.0.150", sourcePort: "53210", destination: "1.1.1.1", destinationPort: "53" } },
      { family: "ipv6", protocol: "tcp", state: "ESTABLISHED", assured: true, timeout: 431991, original: { source: "2409:10:3d60:1271:879:3d5a:205d:ba39", sourcePort: "55244", destination: "2606:4700:3030::6815:1001", destinationPort: "443" } },
      { family: "ipv6", protocol: "udp", state: "ASSURED", assured: true, timeout: 150, original: { source: "2409:10:3d60:1271:be24:11ff:fee0:8e3a", sourcePort: "41641", destination: "2606:4700:4700::1111", destinationPort: "53" } },
    ],
  };
}

function configFixture() {
  return {
    path: "/usr/local/etc/routerd/router.yaml",
    text: `apiVersion: routerd.net/v1alpha1\nkind: Router\nmetadata:\n  name: homert02\nspec:\n  resources:\n    - apiVersion: net.routerd.net/v1alpha1\n      kind: Interface\n      metadata:\n        name: lan\n      spec:\n        ifname: ens19\n        role: trust\n    - apiVersion: system.routerd.net/v1alpha1\n      kind: WebConsole\n      metadata:\n        name: mgmt-console\n      spec:\n        listenAddressFrom:\n          resource: Interface/mgmt\n          field: status.addresses[0]\n`,
  };
}

function generationsFixture() {
  return [
    { generation: 13, startedAt: "2026-05-11T03:30:00Z", finishedAt: "2026-05-11T03:30:04Z", phase: "Healthy", configHash: "aabbccddeeff001122334455", hasYaml: true },
    { generation: 12, startedAt: "2026-05-11T02:30:00Z", finishedAt: "2026-05-11T02:30:05Z", phase: "Healthy", configHash: "00112233445566778899aabb", hasYaml: true },
  ];
}
