// SPDX-License-Identifier: BSD-3-Clause

package render

import (
	"bytes"
	"fmt"
	"net/netip"
	"sort"
	"strings"
	"time"

	"routerd/pkg/api"
)

type bgpRouterConfig struct {
	Name            string
	ASN             uint32
	RouterID        string
	VRFName         string
	ListenAddress   string
	ListenPort      int
	AllowedPrefixes []string
	ExportPrefixes  []string
	Redistribute    bgpRedistribute
	Communities     bgpCommunities
	Timers          bgpTimers
	GracefulRestart bgpGracefulRestart
	Peers           []bgpPeerConfig
}

type bgpPeerConfig struct {
	ResourceName   string
	Peer           string
	ASN            uint32
	Password       string
	ExportPrefixes []string
	Timers         bgpTimers
	Communities    bgpCommunities
	BFD            bgpBFD
	VRFName        string
}

type bgpRedistribute struct {
	Connected []string
	Static    []string
}

type bgpCommunities struct {
	Send   string
	Accept []string
	SetIn  []string
	SetOut []string
}

type bgpTimers struct {
	KeepaliveSeconds    int
	HoldTimeSeconds     int
	ConnectRetrySeconds int
}

type bgpGracefulRestart struct {
	Enabled              bool
	RestartTimeSeconds   int
	StalePathTimeSeconds int
}

type bgpBFD struct {
	Enabled          bool
	Interface        string
	MinRxMS          int
	MinTxMS          int
	DetectMultiplier int
}

func FRRConfig(router *api.Router) ([]byte, error) {
	routers, err := bgpRouterConfigs(router)
	if err != nil {
		return nil, err
	}
	if len(routers) == 0 {
		return nil, nil
	}
	var buf bytes.Buffer
	buf.WriteString("! Generated by routerd. Do not edit by hand.\n")
	buf.WriteString("frr defaults traditional\n")
	buf.WriteString("hostname routerd\n")
	buf.WriteString("service integrated-vtysh-config\n")
	buf.WriteString("!\n")
	for _, router := range routers {
		writeFRRRouter(&buf, router)
	}
	return buf.Bytes(), nil
}

func bgpRouterConfigs(router *api.Router) ([]bgpRouterConfig, error) {
	if router == nil {
		return nil, nil
	}
	byName := map[string]*bgpRouterConfig{}
	vrfs := bgpVRFIfNames(router)
	bfdSpecs := bgpBFDSpecs(router)
	ifNames := bgpInterfaceNames(router)
	var names []string
	for _, res := range router.Spec.Resources {
		if res.APIVersion != api.NetAPIVersion || res.Kind != "BGPRouter" {
			continue
		}
		spec, err := res.BGPRouterSpec()
		if err != nil {
			return nil, err
		}
		if strings.TrimSpace(spec.Backend) != "" && spec.Backend != "frr" {
			continue
		}
		listenPort := spec.Listen.Port
		if listenPort == 0 {
			listenPort = 179
		}
		vrfRef := strings.TrimSpace(spec.VRF)
		vrfName := vrfs[bgpVRFRefName(vrfRef)]
		if vrfRef != "" && vrfName == "" {
			return nil, fmt.Errorf("%s spec.vrf references missing VRF %q", res.ID(), spec.VRF)
		}
		cfg := bgpRouterConfig{
			Name:            res.Metadata.Name,
			ASN:             spec.ASN,
			RouterID:        strings.TrimSpace(spec.RouterID),
			VRFName:         vrfName,
			ListenAddress:   strings.TrimSpace(spec.Listen.Address),
			ListenPort:      listenPort,
			AllowedPrefixes: compactStrings(spec.ImportPolicy.AllowedPrefixes),
			ExportPrefixes:  compactStrings(spec.ExportPolicy.AllowedPrefixes),
			Redistribute: bgpRedistribute{
				Connected: compactStrings(spec.Redistribute.Connected.AllowedPrefixes),
				Static:    compactStrings(spec.Redistribute.Static.AllowedPrefixes),
			},
			Communities:     renderBGPCommunities(spec.Communities, bgpCommunities{}),
			Timers:          renderBGPTimers(spec.Timers, bgpTimers{}),
			GracefulRestart: renderBGPGracefulRestart(spec.GracefulRestart),
		}
		sort.Strings(cfg.AllowedPrefixes)
		sort.Strings(cfg.ExportPrefixes)
		sort.Strings(cfg.Redistribute.Connected)
		sort.Strings(cfg.Redistribute.Static)
		byName[res.Metadata.Name] = &cfg
		names = append(names, res.Metadata.Name)
	}
	for _, res := range router.Spec.Resources {
		if res.APIVersion != api.NetAPIVersion || res.Kind != "BGPPeer" {
			continue
		}
		spec, err := res.BGPPeerSpec()
		if err != nil {
			return nil, err
		}
		_, routerName, ok := strings.Cut(strings.TrimSpace(spec.RouterRef), "/")
		if !ok {
			return nil, fmt.Errorf("%s spec.routerRef must be BGPRouter/<name>", res.ID())
		}
		cfg := byName[routerName]
		if cfg == nil {
			return nil, fmt.Errorf("%s references missing BGPRouter %q", res.ID(), spec.RouterRef)
		}
		for _, peer := range compactStrings(spec.Peers) {
			password, err := secretValue(spec.Password, spec.PasswordFrom)
			if err != nil {
				return nil, fmt.Errorf("%s spec.passwordFrom: %w", res.ID(), err)
			}
			cfg.Peers = append(cfg.Peers, bgpPeerConfig{
				ResourceName:   res.Metadata.Name,
				Peer:           peer,
				ASN:            spec.PeerASN,
				Password:       password,
				ExportPrefixes: sortedUniqueStrings(spec.ExportPolicy.AllowedPrefixes),
				Timers:         renderBGPTimers(spec.Timers, cfg.Timers),
				Communities:    renderBGPCommunities(spec.Communities, cfg.Communities),
				BFD:            renderBGPBFDResource(res.ID(), peer, spec.BFD, bfdSpecs, ifNames),
				VRFName:        cfg.VRFName,
			})
		}
	}
	sort.Strings(names)
	out := make([]bgpRouterConfig, 0, len(names))
	for _, name := range names {
		cfg := *byName[name]
		sort.Slice(cfg.Peers, func(i, j int) bool {
			if cfg.Peers[i].Peer != cfg.Peers[j].Peer {
				return cfg.Peers[i].Peer < cfg.Peers[j].Peer
			}
			return cfg.Peers[i].ResourceName < cfg.Peers[j].ResourceName
		})
		out = append(out, cfg)
	}
	return out, nil
}

func writeFRRRouter(buf *bytes.Buffer, cfg bgpRouterConfig) {
	prefixListName := "ROUTERD-" + frrName(cfg.Name) + "-IMPORT"
	prefixListNameV6 := prefixListName + "-V6"
	routeMapInName := "ROUTERD-" + frrName(cfg.Name) + "-IN"
	routeMapInNameV6 := routeMapInName + "-V6"
	routeMapOutName := "ROUTERD-" + frrName(cfg.Name) + "-OUT"
	routeMapOutNameV6 := routeMapOutName + "-V6"
	allowedV4, allowedV6 := splitBGPPrefixFamilies(cfg.AllowedPrefixes)
	exportV4, exportV6 := splitBGPPrefixFamilies(cfg.ExportPrefixes)
	connectedV4, connectedV6 := splitBGPPrefixFamilies(cfg.Redistribute.Connected)
	staticV4, staticV6 := splitBGPPrefixFamilies(cfg.Redistribute.Static)
	writeFRRPrefixList(buf, prefixListName, allowedV4, "ipv4")
	if len(allowedV6) > 0 || bgpHasIPv6Peer(cfg.Peers) {
		writeFRRPrefixList(buf, prefixListNameV6, allowedV6, "ipv6")
	}
	if len(exportV4) > 0 {
		writeFRRPrefixList(buf, routeMapOutPrefixList(cfg.Name, exportV4, "ipv4"), exportV4, "ipv4")
	}
	if len(exportV6) > 0 {
		writeFRRPrefixList(buf, routeMapOutPrefixList(cfg.Name, exportV6, "ipv6"), exportV6, "ipv6")
	}
	for _, peer := range cfg.Peers {
		if len(peer.ExportPrefixes) == 0 {
			continue
		}
		peerExportV4, peerExportV6 := splitBGPPrefixFamilies(peer.ExportPrefixes)
		if len(peerExportV4) > 0 {
			writeFRRPrefixList(buf, peerExportPrefixListName(cfg.Name, peer, "ipv4"), peerExportV4, "ipv4")
		}
		if len(peerExportV6) > 0 {
			writeFRRPrefixList(buf, peerExportPrefixListName(cfg.Name, peer, "ipv6"), peerExportV6, "ipv6")
		}
	}
	writeFRRRedistributePolicy(buf, cfg.Name, "CONNECTED", connectedV4, "ipv4")
	writeFRRRedistributePolicy(buf, cfg.Name, "STATIC", staticV4, "ipv4")
	writeFRRRedistributePolicy(buf, cfg.Name, "CONNECTED-V6", connectedV6, "ipv6")
	writeFRRRedistributePolicy(buf, cfg.Name, "STATIC-V6", staticV6, "ipv6")
	writeFRRBFDPeers(buf, cfg.Peers)
	writeFRRCommunityLists(buf, cfg)
	writeFRRRouteMap(buf, routeMapInName, bgpRouteMapSpec{
		PrefixList:       prefixListName,
		AddressFamily:    "ipv4",
		AcceptCommunity:  routerCommunityListForRouteMap(cfg),
		SetCommunities:   cfg.Communities.SetIn,
		NextHopPeer:      true,
		DefaultDeny:      true,
		PermitIfNoPolicy: true,
	})
	writeFRRRouteMap(buf, routeMapOutName, bgpRouteMapSpec{
		PrefixList:       routeMapOutPrefixList(cfg.Name, exportV4, "ipv4"),
		AddressFamily:    "ipv4",
		SetCommunities:   bgpOutboundSetCommunities(exportV4, cfg.Communities.SetOut),
		DefaultDeny:      true,
		PermitIfNoPolicy: false,
	})
	if len(allowedV6) > 0 || len(exportV6) > 0 || bgpHasIPv6Peer(cfg.Peers) {
		writeFRRRouteMap(buf, routeMapInNameV6, bgpRouteMapSpec{
			PrefixList:       prefixListNameV6,
			AddressFamily:    "ipv6",
			AcceptCommunity:  routerCommunityListForRouteMap(cfg),
			SetCommunities:   cfg.Communities.SetIn,
			DefaultDeny:      true,
			PermitIfNoPolicy: true,
		})
		writeFRRRouteMap(buf, routeMapOutNameV6, bgpRouteMapSpec{
			PrefixList:       routeMapOutPrefixList(cfg.Name, exportV6, "ipv6"),
			AddressFamily:    "ipv6",
			SetCommunities:   bgpOutboundSetCommunities(exportV6, cfg.Communities.SetOut),
			DefaultDeny:      true,
			PermitIfNoPolicy: false,
		})
	}
	for _, peer := range cfg.Peers {
		if bgpPeerNeedsRouteMap(peer, cfg) {
			writeFRRPeerRouteMaps(buf, cfg, peer, exportV4, exportV6)
		}
	}
	buf.WriteString("!\n")
	if cfg.VRFName != "" {
		buf.WriteString(fmt.Sprintf("router bgp %d vrf %s\n", cfg.ASN, cfg.VRFName))
	} else {
		buf.WriteString(fmt.Sprintf("router bgp %d\n", cfg.ASN))
	}
	buf.WriteString(" bgp router-id " + cfg.RouterID + "\n")
	if cfg.ListenPort != 179 {
		buf.WriteString(fmt.Sprintf(" bgp listen port %d\n", cfg.ListenPort))
	}
	if cfg.GracefulRestart.Enabled {
		buf.WriteString(" bgp graceful-restart\n")
		if cfg.GracefulRestart.RestartTimeSeconds > 0 {
			buf.WriteString(fmt.Sprintf(" bgp graceful-restart restart-time %d\n", cfg.GracefulRestart.RestartTimeSeconds))
		}
		if cfg.GracefulRestart.StalePathTimeSeconds > 0 {
			buf.WriteString(fmt.Sprintf(" bgp graceful-restart stalepath-time %d\n", cfg.GracefulRestart.StalePathTimeSeconds))
		}
	}
	for _, peer := range cfg.Peers {
		buf.WriteString(fmt.Sprintf(" neighbor %s remote-as %d\n", peer.Peer, peer.ASN))
		if peer.Password != "" {
			buf.WriteString(fmt.Sprintf(" neighbor %s password %s\n", peer.Peer, peer.Password))
		}
		if peer.Timers.KeepaliveSeconds > 0 || peer.Timers.HoldTimeSeconds > 0 {
			keepalive := peer.Timers.KeepaliveSeconds
			if keepalive == 0 {
				keepalive = 60
			}
			holdTime := peer.Timers.HoldTimeSeconds
			if holdTime == 0 {
				holdTime = 180
			}
			buf.WriteString(fmt.Sprintf(" neighbor %s timers %d %d\n", peer.Peer, keepalive, holdTime))
		}
		if peer.Timers.ConnectRetrySeconds > 0 {
			buf.WriteString(fmt.Sprintf(" neighbor %s timers connect %d\n", peer.Peer, peer.Timers.ConnectRetrySeconds))
		}
		if peer.BFD.Enabled {
			buf.WriteString(fmt.Sprintf(" neighbor %s bfd\n", peer.Peer))
		}
		writeFRRPeerSendCommunity(buf, peer)
		if bgpPeerFamily(peer.Peer) != "ipv4" {
			continue
		}
		inName := routeMapInName
		outName := routeMapOutName
		if bgpPeerNeedsRouteMap(peer, cfg) {
			inName = peerRouteMapName(cfg.Name, peer, "IN")
			outName = peerRouteMapName(cfg.Name, peer, "OUT")
		}
		buf.WriteString(fmt.Sprintf(" neighbor %s route-map %s in\n", peer.Peer, inName))
		buf.WriteString(fmt.Sprintf(" neighbor %s route-map %s out\n", peer.Peer, outName))
	}
	buf.WriteString(" address-family ipv4 unicast\n")
	if len(connectedV4) > 0 {
		buf.WriteString("  redistribute connected route-map " + redistributeRouteMapName(cfg.Name, "CONNECTED") + "\n")
	}
	if len(staticV4) > 0 {
		buf.WriteString("  redistribute static route-map " + redistributeRouteMapName(cfg.Name, "STATIC") + "\n")
	}
	for _, peer := range cfg.Peers {
		if bgpPeerFamily(peer.Peer) == "ipv4" {
			buf.WriteString(fmt.Sprintf("  neighbor %s activate\n", peer.Peer))
		}
	}
	buf.WriteString(" exit-address-family\n")
	if bgpHasIPv6Peer(cfg.Peers) || len(connectedV6) > 0 || len(staticV6) > 0 {
		buf.WriteString(" address-family ipv6 unicast\n")
		if len(connectedV6) > 0 {
			buf.WriteString("  redistribute connected route-map " + redistributeRouteMapName(cfg.Name, "CONNECTED-V6") + "\n")
		}
		if len(staticV6) > 0 {
			buf.WriteString("  redistribute static route-map " + redistributeRouteMapName(cfg.Name, "STATIC-V6") + "\n")
		}
		for _, peer := range cfg.Peers {
			if bgpPeerFamily(peer.Peer) != "ipv6" {
				continue
			}
			inName := routeMapInNameV6
			outName := routeMapOutNameV6
			if bgpPeerNeedsRouteMap(peer, cfg) {
				inName = peerRouteMapName(cfg.Name, peer, "IN-V6")
				outName = peerRouteMapName(cfg.Name, peer, "OUT-V6")
			}
			buf.WriteString(fmt.Sprintf("  neighbor %s activate\n", peer.Peer))
			buf.WriteString(fmt.Sprintf("  neighbor %s route-map %s in\n", peer.Peer, inName))
			buf.WriteString(fmt.Sprintf("  neighbor %s route-map %s out\n", peer.Peer, outName))
		}
		buf.WriteString(" exit-address-family\n")
	}
	buf.WriteString("!\n")
}

func writeFRRBFDPeers(buf *bytes.Buffer, peers []bgpPeerConfig) {
	var bfdPeers []bgpPeerConfig
	for _, peer := range peers {
		if peer.BFD.Enabled {
			bfdPeers = append(bfdPeers, peer)
		}
	}
	if len(bfdPeers) == 0 {
		return
	}
	buf.WriteString("bfd\n")
	for _, peer := range bfdPeers {
		line := " peer " + peer.Peer
		if peer.BFD.Interface != "" {
			line += " interface " + peer.BFD.Interface
		}
		if peer.VRFName != "" {
			line += " vrf " + peer.VRFName
		}
		buf.WriteString(line + "\n")
		if peer.BFD.MinRxMS > 0 {
			buf.WriteString(fmt.Sprintf("  receive-interval %d\n", peer.BFD.MinRxMS))
		}
		if peer.BFD.MinTxMS > 0 {
			buf.WriteString(fmt.Sprintf("  transmit-interval %d\n", peer.BFD.MinTxMS))
		}
		if peer.BFD.DetectMultiplier > 0 {
			buf.WriteString(fmt.Sprintf("  detect-multiplier %d\n", peer.BFD.DetectMultiplier))
		}
		buf.WriteString(" exit\n")
	}
	buf.WriteString("!\n")
}

func bgpVRFIfNames(router *api.Router) map[string]string {
	out := map[string]string{}
	if router == nil {
		return out
	}
	for _, res := range router.Spec.Resources {
		if res.APIVersion != api.NetAPIVersion || res.Kind != "VRF" {
			continue
		}
		spec, err := res.VRFSpec()
		if err != nil {
			continue
		}
		out[res.Metadata.Name] = defaultString(spec.IfName, res.Metadata.Name)
	}
	return out
}

func bgpInterfaceNames(router *api.Router) map[string]string {
	out := map[string]string{}
	if router == nil {
		return out
	}
	for _, res := range router.Spec.Resources {
		if res.APIVersion != api.NetAPIVersion || res.Kind != "Interface" {
			continue
		}
		spec, err := res.InterfaceSpec()
		if err != nil {
			continue
		}
		out[res.Metadata.Name] = defaultString(spec.IfName, res.Metadata.Name)
	}
	return out
}

func bgpBFDSpecs(router *api.Router) map[string]api.BFDSpec {
	out := map[string]api.BFDSpec{}
	if router == nil {
		return out
	}
	for _, res := range router.Spec.Resources {
		if res.APIVersion != api.NetAPIVersion || res.Kind != "BFD" {
			continue
		}
		spec, err := res.BFDSpec()
		if err != nil {
			continue
		}
		out[res.Metadata.Name] = spec
	}
	return out
}

func bgpVRFRefName(value string) string {
	value = strings.TrimSpace(value)
	if value == "" {
		return ""
	}
	if kind, name, ok := strings.Cut(value, "/"); ok && kind == "VRF" {
		return strings.TrimSpace(name)
	}
	return value
}

type bgpRouteMapSpec struct {
	PrefixList       string
	AddressFamily    string
	AcceptCommunity  string
	SetCommunities   []string
	NextHopPeer      bool
	DefaultDeny      bool
	PermitIfNoPolicy bool
}

func writeFRRPrefixList(buf *bytes.Buffer, name string, prefixes []string, family string) {
	keyword := "ip"
	deny := "0.0.0.0/0 le 32"
	if family == "ipv6" {
		keyword = "ipv6"
		deny = "::/0 le 128"
	}
	if len(prefixes) > 0 {
		for i, prefix := range prefixes {
			buf.WriteString(fmt.Sprintf("%s prefix-list %s seq %d permit %s\n", keyword, name, (i+1)*10, canonicalPrefix(prefix)))
		}
	}
	buf.WriteString(keyword + " prefix-list " + name + " seq 999 deny " + deny + "\n")
}

func writeFRRRouteMap(buf *bytes.Buffer, name string, spec bgpRouteMapSpec) {
	hasPolicy := spec.PrefixList != "" || spec.AcceptCommunity != "" || len(spec.SetCommunities) > 0 || spec.NextHopPeer
	if hasPolicy || spec.PermitIfNoPolicy {
		buf.WriteString("route-map " + name + " permit 10\n")
		if spec.PrefixList != "" {
			if spec.AddressFamily == "ipv6" {
				buf.WriteString(" match ipv6 address prefix-list " + spec.PrefixList + "\n")
			} else {
				buf.WriteString(" match ip address prefix-list " + spec.PrefixList + "\n")
			}
		}
		if spec.AcceptCommunity != "" {
			buf.WriteString(" match community " + spec.AcceptCommunity + "\n")
		}
		if spec.NextHopPeer && spec.AddressFamily != "ipv6" {
			buf.WriteString(" set ip next-hop peer-address\n")
		}
		if len(spec.SetCommunities) > 0 {
			buf.WriteString(" set community " + strings.Join(spec.SetCommunities, " ") + " additive\n")
		}
	}
	if spec.DefaultDeny {
		buf.WriteString("route-map " + name + " deny 999\n")
	}
}

func writeFRRRedistributePolicy(buf *bytes.Buffer, routerName, protocol string, prefixes []string, family string) {
	if len(prefixes) == 0 {
		return
	}
	list := redistributePrefixListName(routerName, protocol)
	writeFRRPrefixList(buf, list, prefixes, family)
	writeFRRRouteMap(buf, redistributeRouteMapName(routerName, protocol), bgpRouteMapSpec{
		PrefixList:    list,
		AddressFamily: family,
		DefaultDeny:   true,
	})
}

func writeFRRCommunityLists(buf *bytes.Buffer, cfg bgpRouterConfig) {
	writeFRRCommunityList(buf, communityListName(cfg.Name, "ACCEPT"), cfg.Communities.Accept)
	for _, peer := range cfg.Peers {
		if len(peer.Communities.Accept) == 0 || equalStringSet(peer.Communities.Accept, cfg.Communities.Accept) {
			continue
		}
		writeFRRCommunityList(buf, peerCommunityListName(cfg.Name, peer), peer.Communities.Accept)
	}
}

func writeFRRCommunityList(buf *bytes.Buffer, name string, communities []string) {
	for _, community := range communities {
		buf.WriteString(fmt.Sprintf("bgp community-list standard %s permit %s\n", name, community))
	}
}

func writeFRRPeerRouteMaps(buf *bytes.Buffer, cfg bgpRouterConfig, peer bgpPeerConfig, exportV4, exportV6 []string) {
	peerExportV4, peerExportV6 := peerEffectiveExportPrefixes(peer, exportV4, exportV6)
	writeFRRRouteMap(buf, peerRouteMapName(cfg.Name, peer, "IN"), bgpRouteMapSpec{
		PrefixList:      "ROUTERD-" + frrName(cfg.Name) + "-IMPORT",
		AddressFamily:   "ipv4",
		AcceptCommunity: communityListForPeer(cfg, peer),
		SetCommunities:  peer.Communities.SetIn,
		NextHopPeer:     true,
		DefaultDeny:     true,
	})
	writeFRRRouteMap(buf, peerRouteMapName(cfg.Name, peer, "OUT"), bgpRouteMapSpec{
		PrefixList:     peerRouteMapOutPrefixList(cfg.Name, peer, peerExportV4, "ipv4"),
		AddressFamily:  "ipv4",
		SetCommunities: bgpOutboundSetCommunities(peerExportV4, peer.Communities.SetOut),
		DefaultDeny:    true,
	})
	if bgpPeerFamily(peer.Peer) == "ipv6" || len(peerExportV6) > 0 {
		writeFRRRouteMap(buf, peerRouteMapName(cfg.Name, peer, "IN-V6"), bgpRouteMapSpec{
			PrefixList:      "ROUTERD-" + frrName(cfg.Name) + "-IMPORT-V6",
			AddressFamily:   "ipv6",
			AcceptCommunity: communityListForPeer(cfg, peer),
			SetCommunities:  peer.Communities.SetIn,
			DefaultDeny:     true,
		})
		writeFRRRouteMap(buf, peerRouteMapName(cfg.Name, peer, "OUT-V6"), bgpRouteMapSpec{
			PrefixList:     peerRouteMapOutPrefixList(cfg.Name, peer, peerExportV6, "ipv6"),
			AddressFamily:  "ipv6",
			SetCommunities: bgpOutboundSetCommunities(peerExportV6, peer.Communities.SetOut),
			DefaultDeny:    true,
		})
	}
}

func writeFRRPeerSendCommunity(buf *bytes.Buffer, peer bgpPeerConfig) {
	switch peer.Communities.Send {
	case "standard":
		buf.WriteString(fmt.Sprintf(" neighbor %s send-community\n", peer.Peer))
	case "extended", "both":
		buf.WriteString(fmt.Sprintf(" neighbor %s send-community %s\n", peer.Peer, peer.Communities.Send))
	}
}

func renderBGPTimers(spec api.BGPTimersSpec, fallback bgpTimers) bgpTimers {
	out := fallback
	switch strings.TrimSpace(spec.Profile) {
	case "fast":
		out.KeepaliveSeconds = 3
		out.HoldTimeSeconds = 9
		out.ConnectRetrySeconds = 5
	case "slow":
		out.KeepaliveSeconds = 30
		out.HoldTimeSeconds = 90
		out.ConnectRetrySeconds = 120
	}
	if seconds := durationSeconds(spec.Keepalive); seconds > 0 {
		out.KeepaliveSeconds = seconds
	}
	if seconds := durationSeconds(spec.HoldTime); seconds > 0 {
		out.HoldTimeSeconds = seconds
	}
	if seconds := durationSeconds(spec.ConnectRetry); seconds > 0 {
		out.ConnectRetrySeconds = seconds
	}
	return out
}

func renderBGPGracefulRestart(spec api.BGPGracefulRestartSpec) bgpGracefulRestart {
	out := bgpGracefulRestart{Enabled: api.BoolDefault(spec.Enabled, true)}
	if seconds := durationSeconds(spec.RestartTime); seconds > 0 {
		out.RestartTimeSeconds = seconds
	}
	if seconds := durationSeconds(spec.StalePathTime); seconds > 0 {
		out.StalePathTimeSeconds = seconds
	}
	return out
}

func renderBGPCommunities(spec api.BGPCommunitiesSpec, fallback bgpCommunities) bgpCommunities {
	out := fallback
	if send := strings.TrimSpace(spec.Send); send != "" {
		out.Send = send
	}
	if spec.Accept != nil {
		out.Accept = compactStrings(spec.Accept)
		sort.Strings(out.Accept)
	}
	if spec.Set.In != nil {
		out.SetIn = compactStrings(spec.Set.In)
		sort.Strings(out.SetIn)
	}
	if spec.Set.Out != nil {
		out.SetOut = compactStrings(spec.Set.Out)
		sort.Strings(out.SetOut)
	}
	return out
}

func renderBGPBFDResource(peerResourceID, peerAddress, ref string, specs map[string]api.BFDSpec, ifNames map[string]string) bgpBFD {
	ref = strings.TrimSpace(ref)
	if ref == "" {
		return bgpBFD{}
	}
	_, name, ok := strings.Cut(ref, "/")
	if !ok {
		return bgpBFD{}
	}
	spec, ok := specs[name]
	if !ok || !bfdAppliesToPeer(spec.Peer, peerResourceID, peerAddress) {
		return bgpBFD{}
	}
	out := bgpBFD{
		Enabled:          true,
		DetectMultiplier: spec.DetectMultiplier,
		MinRxMS:          durationMilliseconds(spec.MinRx),
		MinTxMS:          durationMilliseconds(spec.MinTx),
	}
	switch spec.Profile {
	case "fast":
		out.MinRxMS = defaultInt(out.MinRxMS, 300)
		out.MinTxMS = defaultInt(out.MinTxMS, 300)
		out.DetectMultiplier = defaultInt(out.DetectMultiplier, 3)
	case "slow":
		out.MinRxMS = defaultInt(out.MinRxMS, 3000)
		out.MinTxMS = defaultInt(out.MinTxMS, 3000)
		out.DetectMultiplier = defaultInt(out.DetectMultiplier, 3)
	default:
		out.MinRxMS = defaultInt(out.MinRxMS, 1000)
		out.MinTxMS = defaultInt(out.MinTxMS, 1000)
		out.DetectMultiplier = defaultInt(out.DetectMultiplier, 3)
	}
	if spec.Interface != "" {
		refKind, refName := bgpInterfaceRefName(spec.Interface)
		if refKind == "Interface" && ifNames[refName] != "" {
			out.Interface = ifNames[refName]
		} else {
			out.Interface = strings.TrimSpace(spec.Interface)
		}
	}
	return out
}

func bfdAppliesToPeer(specPeer, peerResourceID, peerAddress string) bool {
	specPeer = strings.TrimSpace(specPeer)
	if kind, name, ok := strings.Cut(specPeer, "/"); ok {
		return kind == "BGPPeer" && peerResourceID == api.NetAPIVersion+"/BGPPeer/"+name
	}
	return specPeer == strings.TrimSpace(peerAddress)
}

func bgpInterfaceRefName(value string) (string, string) {
	value = strings.TrimSpace(value)
	if kind, name, ok := strings.Cut(value, "/"); ok {
		return kind, name
	}
	return "Interface", value
}

func FRRDaemons(existing []byte, router *api.Router) ([]byte, error) {
	if !routerUsesBGP(router) {
		return nil, nil
	}
	values := map[string]string{"bgpd": "yes"}
	if routerUsesBFD(router) {
		values["bfdd"] = "yes"
	}
	return renderFRRDaemons(existing, values), nil
}

func renderFRRDaemons(existing []byte, values map[string]string) []byte {
	lines := strings.Split(strings.TrimRight(string(existing), "\n"), "\n")
	if len(lines) == 1 && strings.TrimSpace(lines[0]) == "" {
		lines = []string{"# Generated by routerd. Preserve local daemon options outside managed keys."}
	}
	seen := map[string]bool{}
	for i, line := range lines {
		key, _, ok := strings.Cut(strings.TrimSpace(line), "=")
		if !ok {
			continue
		}
		key = strings.TrimSpace(key)
		if value, ok := values[key]; ok {
			lines[i] = key + "=" + value
			seen[key] = true
		}
	}
	keys := make([]string, 0, len(values))
	for key := range values {
		if !seen[key] {
			keys = append(keys, key)
		}
	}
	sort.Strings(keys)
	for _, key := range keys {
		lines = append(lines, key+"="+values[key])
	}
	return []byte(strings.Join(lines, "\n") + "\n")
}

func routerUsesBGP(router *api.Router) bool {
	if router == nil {
		return false
	}
	for _, res := range router.Spec.Resources {
		if res.APIVersion != api.NetAPIVersion || res.Kind != "BGPRouter" {
			continue
		}
		spec, err := res.BGPRouterSpec()
		if err == nil && (strings.TrimSpace(spec.Backend) == "" || spec.Backend == "frr") {
			return true
		}
	}
	return false
}

func routerUsesBFD(router *api.Router) bool {
	if router == nil {
		return false
	}
	for _, res := range router.Spec.Resources {
		if res.APIVersion != api.NetAPIVersion || res.Kind != "BGPPeer" {
			continue
		}
		spec, err := res.BGPPeerSpec()
		if err == nil && strings.TrimSpace(spec.BFD) != "" {
			return true
		}
	}
	return false
}

func splitBGPPrefixFamilies(prefixes []string) ([]string, []string) {
	var v4 []string
	var v6 []string
	for _, value := range prefixes {
		prefix, err := netip.ParsePrefix(strings.TrimSpace(value))
		if err != nil {
			continue
		}
		if prefix.Addr().Is4() {
			v4 = append(v4, value)
		} else if prefix.Addr().Is6() {
			v6 = append(v6, value)
		}
	}
	return sortedUniqueStrings(v4), sortedUniqueStrings(v6)
}

func bgpHasIPv6Peer(peers []bgpPeerConfig) bool {
	for _, peer := range peers {
		if bgpPeerFamily(peer.Peer) == "ipv6" {
			return true
		}
	}
	return false
}

func bgpPeerFamily(peer string) string {
	addr, err := netip.ParseAddr(strings.TrimSpace(peer))
	if err == nil && addr.Is6() {
		return "ipv6"
	}
	return "ipv4"
}

func bgpOutboundSetCommunities(exportPrefixes []string, communities []string) []string {
	if len(exportPrefixes) == 0 {
		return nil
	}
	return communities
}

func routeMapOutPrefixList(routerName string, exportPrefixes []string, family string) string {
	if len(exportPrefixes) == 0 {
		return ""
	}
	if family == "ipv6" {
		return "ROUTERD-" + frrName(routerName) + "-EXPORT-V6"
	}
	return "ROUTERD-" + frrName(routerName) + "-EXPORT"
}

func peerEffectiveExportPrefixes(peer bgpPeerConfig, routerV4, routerV6 []string) ([]string, []string) {
	if len(peer.ExportPrefixes) == 0 {
		return routerV4, routerV6
	}
	return splitBGPPrefixFamilies(peer.ExportPrefixes)
}

func peerRouteMapOutPrefixList(routerName string, peer bgpPeerConfig, exportPrefixes []string, family string) string {
	if len(exportPrefixes) == 0 {
		return ""
	}
	if len(peer.ExportPrefixes) > 0 {
		return peerExportPrefixListName(routerName, peer, family)
	}
	return routeMapOutPrefixList(routerName, exportPrefixes, family)
}

func peerExportPrefixListName(routerName string, peer bgpPeerConfig, family string) string {
	name := "ROUTERD-" + frrName(routerName) + "-" + frrName(peer.ResourceName+"-"+peer.Peer) + "-EXPORT"
	if family == "ipv6" {
		return name + "-V6"
	}
	return name
}

func redistributePrefixListName(routerName, protocol string) string {
	return "ROUTERD-" + frrName(routerName) + "-REDIST-" + frrName(protocol)
}

func redistributeRouteMapName(routerName, protocol string) string {
	return "ROUTERD-" + frrName(routerName) + "-REDIST-" + frrName(protocol)
}

func communityListName(routerName, suffix string) string {
	return "ROUTERD-" + frrName(routerName) + "-COMM-" + frrName(suffix)
}

func peerCommunityListName(routerName string, peer bgpPeerConfig) string {
	return communityListName(routerName, peer.ResourceName+"-"+peer.Peer+"-ACCEPT")
}

func routerCommunityListForRouteMap(cfg bgpRouterConfig) string {
	if len(cfg.Communities.Accept) == 0 {
		return ""
	}
	return communityListName(cfg.Name, "ACCEPT")
}

func communityListForPeer(cfg bgpRouterConfig, peer bgpPeerConfig) string {
	if len(peer.Communities.Accept) == 0 {
		return ""
	}
	if equalStringSet(peer.Communities.Accept, cfg.Communities.Accept) {
		return communityListName(cfg.Name, "ACCEPT")
	}
	return peerCommunityListName(cfg.Name, peer)
}

func peerRouteMapName(routerName string, peer bgpPeerConfig, direction string) string {
	return "ROUTERD-" + frrName(routerName) + "-" + frrName(peer.ResourceName+"-"+peer.Peer) + "-" + frrName(direction)
}

func bgpPeerNeedsRouteMap(peer bgpPeerConfig, router bgpRouterConfig) bool {
	return len(peer.ExportPrefixes) > 0 ||
		!equalStringSet(peer.Communities.Accept, router.Communities.Accept) ||
		!equalStringSet(peer.Communities.SetIn, router.Communities.SetIn) ||
		!equalStringSet(peer.Communities.SetOut, router.Communities.SetOut)
}

func sortedUniqueStrings(values []string) []string {
	out := compactStrings(values)
	sort.Strings(out)
	return out
}

func equalStringSet(a, b []string) bool {
	a = sortedUniqueStrings(a)
	b = sortedUniqueStrings(b)
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

func durationSeconds(value string) int {
	value = strings.TrimSpace(value)
	if value == "" {
		return 0
	}
	duration, err := time.ParseDuration(value)
	if err != nil || duration <= 0 {
		return 0
	}
	seconds := int(duration.Round(time.Second) / time.Second)
	if seconds < 1 {
		return 1
	}
	return seconds
}

func durationMilliseconds(value string) int {
	value = strings.TrimSpace(value)
	if value == "" {
		return 0
	}
	duration, err := time.ParseDuration(value)
	if err != nil || duration <= 0 {
		return 0
	}
	ms := int(duration.Round(time.Millisecond) / time.Millisecond)
	if ms < 1 {
		return 1
	}
	return ms
}

func canonicalPrefix(value string) string {
	if prefix, err := netip.ParsePrefix(value); err == nil {
		return prefix.Masked().String()
	}
	return strings.TrimSpace(value)
}

func frrName(value string) string {
	value = strings.ToUpper(strings.TrimSpace(value))
	var b strings.Builder
	for _, r := range value {
		switch {
		case r >= 'A' && r <= 'Z':
			b.WriteRune(r)
		case r >= '0' && r <= '9':
			b.WriteRune(r)
		default:
			b.WriteByte('-')
		}
	}
	out := strings.Trim(b.String(), "-")
	if out == "" {
		return "DEFAULT"
	}
	return out
}
