// SPDX-License-Identifier: BSD-3-Clause

package render

import (
	"bytes"
	"fmt"
	"net/netip"
	"sort"
	"strings"

	"routerd/pkg/api"
)

type bgpRouterConfig struct {
	Name            string
	ASN             uint32
	RouterID        string
	ListenPort      int
	AllowedPrefixes []string
	Peers           []bgpPeerConfig
}

type bgpPeerConfig struct {
	ResourceName string
	Peer         string
	ASN          uint32
	Password     string
}

func FRRConfig(router *api.Router) ([]byte, error) {
	routers, err := bgpRouterConfigs(router)
	if err != nil {
		return nil, err
	}
	if len(routers) == 0 {
		return nil, nil
	}
	var buf bytes.Buffer
	buf.WriteString("! Generated by routerd. Do not edit by hand.\n")
	buf.WriteString("frr defaults traditional\n")
	buf.WriteString("hostname routerd\n")
	buf.WriteString("service integrated-vtysh-config\n")
	buf.WriteString("!\n")
	for _, router := range routers {
		writeFRRRouter(&buf, router)
	}
	return buf.Bytes(), nil
}

func bgpRouterConfigs(router *api.Router) ([]bgpRouterConfig, error) {
	if router == nil {
		return nil, nil
	}
	byName := map[string]*bgpRouterConfig{}
	var names []string
	for _, res := range router.Spec.Resources {
		if res.APIVersion != api.NetAPIVersion || res.Kind != "BGPRouter" {
			continue
		}
		spec, err := res.BGPRouterSpec()
		if err != nil {
			return nil, err
		}
		if strings.TrimSpace(spec.Backend) != "" && spec.Backend != "frr" {
			continue
		}
		listenPort := spec.Listen.Port
		if listenPort == 0 {
			listenPort = 179
		}
		cfg := bgpRouterConfig{
			Name:            res.Metadata.Name,
			ASN:             spec.ASN,
			RouterID:        strings.TrimSpace(spec.RouterID),
			ListenPort:      listenPort,
			AllowedPrefixes: compactStrings(spec.ImportPolicy.AllowedPrefixes),
		}
		sort.Strings(cfg.AllowedPrefixes)
		byName[res.Metadata.Name] = &cfg
		names = append(names, res.Metadata.Name)
	}
	for _, res := range router.Spec.Resources {
		if res.APIVersion != api.NetAPIVersion || res.Kind != "BGPPeer" {
			continue
		}
		spec, err := res.BGPPeerSpec()
		if err != nil {
			return nil, err
		}
		_, routerName, ok := strings.Cut(strings.TrimSpace(spec.RouterRef), "/")
		if !ok {
			return nil, fmt.Errorf("%s spec.routerRef must be BGPRouter/<name>", res.ID())
		}
		cfg := byName[routerName]
		if cfg == nil {
			return nil, fmt.Errorf("%s references missing BGPRouter %q", res.ID(), spec.RouterRef)
		}
		for _, peer := range compactStrings(spec.Peers) {
			cfg.Peers = append(cfg.Peers, bgpPeerConfig{
				ResourceName: res.Metadata.Name,
				Peer:         peer,
				ASN:          spec.PeerASN,
				Password:     spec.Password,
			})
		}
	}
	sort.Strings(names)
	out := make([]bgpRouterConfig, 0, len(names))
	for _, name := range names {
		cfg := *byName[name]
		sort.Slice(cfg.Peers, func(i, j int) bool {
			if cfg.Peers[i].Peer != cfg.Peers[j].Peer {
				return cfg.Peers[i].Peer < cfg.Peers[j].Peer
			}
			return cfg.Peers[i].ResourceName < cfg.Peers[j].ResourceName
		})
		out = append(out, cfg)
	}
	return out, nil
}

func writeFRRRouter(buf *bytes.Buffer, cfg bgpRouterConfig) {
	prefixListName := "ROUTERD-" + frrName(cfg.Name) + "-IMPORT"
	routeMapName := "ROUTERD-" + frrName(cfg.Name) + "-IN"
	if len(cfg.AllowedPrefixes) == 0 {
		buf.WriteString("ip prefix-list " + prefixListName + " seq 999 deny 0.0.0.0/0 le 32\n")
	} else {
		for i, prefix := range cfg.AllowedPrefixes {
			buf.WriteString(fmt.Sprintf("ip prefix-list %s seq %d permit %s\n", prefixListName, (i+1)*10, canonicalPrefix(prefix)))
		}
		buf.WriteString("ip prefix-list " + prefixListName + " seq 999 deny 0.0.0.0/0 le 32\n")
	}
	buf.WriteString("route-map " + routeMapName + " permit 10\n")
	buf.WriteString(" match ip address prefix-list " + prefixListName + "\n")
	buf.WriteString(" set ip next-hop peer-address\n")
	buf.WriteString("route-map " + routeMapName + " deny 999\n")
	buf.WriteString("!\n")
	buf.WriteString(fmt.Sprintf("router bgp %d\n", cfg.ASN))
	buf.WriteString(" bgp router-id " + cfg.RouterID + "\n")
	if cfg.ListenPort != 179 {
		buf.WriteString(fmt.Sprintf(" bgp listen port %d\n", cfg.ListenPort))
	}
	for _, peer := range cfg.Peers {
		buf.WriteString(fmt.Sprintf(" neighbor %s remote-as %d\n", peer.Peer, peer.ASN))
		if peer.Password != "" {
			buf.WriteString(fmt.Sprintf(" neighbor %s password %s\n", peer.Peer, peer.Password))
		}
		buf.WriteString(fmt.Sprintf(" neighbor %s route-map %s in\n", peer.Peer, routeMapName))
	}
	buf.WriteString(" address-family ipv4 unicast\n")
	for _, peer := range cfg.Peers {
		buf.WriteString(fmt.Sprintf("  neighbor %s activate\n", peer.Peer))
	}
	buf.WriteString(" exit-address-family\n")
	buf.WriteString("!\n")
}

func canonicalPrefix(value string) string {
	if prefix, err := netip.ParsePrefix(value); err == nil {
		return prefix.Masked().String()
	}
	return strings.TrimSpace(value)
}

func frrName(value string) string {
	value = strings.ToUpper(strings.TrimSpace(value))
	var b strings.Builder
	for _, r := range value {
		switch {
		case r >= 'A' && r <= 'Z':
			b.WriteRune(r)
		case r >= '0' && r <= '9':
			b.WriteRune(r)
		default:
			b.WriteByte('-')
		}
	}
	out := strings.Trim(b.String(), "-")
	if out == "" {
		return "DEFAULT"
	}
	return out
}
