package render

import (
	"bytes"
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"routerd/pkg/api"
	routerstate "routerd/pkg/state"
)

type DHCPCDConfig struct {
	Files []ManagedFile
	Units []string
}

func DHCPCD(router *api.Router, binaryPath, configDir, runtimeDir, unitDir string) (DHCPCDConfig, error) {
	return DHCPCDWithLeases(router, binaryPath, configDir, runtimeDir, unitDir, nil)
}

func DHCPCDWithLeases(router *api.Router, binaryPath, configDir, runtimeDir, unitDir string, leases map[string]routerstate.PDLease) (DHCPCDConfig, error) {
	aliases := map[string]string{}
	for _, res := range router.Spec.Resources {
		if res.Kind != "Interface" {
			continue
		}
		spec, err := res.InterfaceSpec()
		if err != nil {
			return DHCPCDConfig{}, err
		}
		aliases[res.Metadata.Name] = spec.IfName
	}

	var resources []api.Resource
	for _, res := range router.Spec.Resources {
		if res.Kind != "IPv6PrefixDelegation" {
			continue
		}
		spec, err := res.IPv6PrefixDelegationSpec()
		if err != nil {
			return DHCPCDConfig{}, err
		}
		if defaultString(spec.Client, "networkd") == "dhcpcd" {
			resources = append(resources, res)
		}
	}
	sort.Slice(resources, func(i, j int) bool { return resources[i].Metadata.Name < resources[j].Metadata.Name })

	var config DHCPCDConfig
	for _, res := range resources {
		spec, err := res.IPv6PrefixDelegationSpec()
		if err != nil {
			return DHCPCDConfig{}, err
		}
		ifname := aliases[spec.Interface]
		if ifname == "" {
			return DHCPCDConfig{}, fmt.Errorf("%s references interface with empty ifname", res.ID())
		}
		name := safeServiceName(res.Metadata.Name)
		confPath := filepath.Join(configDir, "dhcpcd-"+name+".conf")
		hookPath := filepath.Join(configDir, "dhcpcd-"+name+".hook")
		unit := "routerd-dhcpcd-" + name + ".service"
		profile := defaultString(spec.Profile, api.IPv6PDProfileDefault)
		pd := dhcpcdPD{
			Name:                res.Metadata.Name,
			IfName:              ifname,
			Profile:             profile,
			PrefixLength:        api.EffectiveIPv6PDPrefixLength(profile, spec.PrefixLength),
			IAID:                strings.TrimSpace(spec.IAID),
			DUIDRawData:         strings.TrimSpace(spec.DUIDRawData),
			ServerID:            strings.TrimSpace(spec.ServerID),
			PriorPrefix:         strings.TrimSpace(spec.PriorPrefix),
			AcquisitionStrategy: strings.TrimSpace(spec.AcquisitionStrategy),
			Lease:               leases[res.Metadata.Name],
		}
		configData, err := dhcpcdConfig(pd, hookPath)
		if err != nil {
			return DHCPCDConfig{}, err
		}
		config.Files = append(config.Files,
			ManagedFile{Path: confPath, Data: configData, Perm: 0644},
			ManagedFile{Path: hookPath, Data: DHCPCDHookScript(res.Metadata.Name), Perm: 0755},
			ManagedFile{Path: filepath.Join(unitDir, unit), Data: DHCPCDServiceUnit(binaryPath, confPath, runtimeDir, ifname, res.Metadata.Name), Perm: 0644},
		)
		config.Units = append(config.Units, unit)
	}
	return config, nil
}

type dhcpcdPD struct {
	Name                string
	IfName              string
	Profile             string
	PrefixLength        int
	IAID                string
	DUIDRawData         string
	ServerID            string
	PriorPrefix         string
	AcquisitionStrategy string
	Lease               routerstate.PDLease
}

func dhcpcdConfig(pd dhcpcdPD, hookPath string) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString("# Generated by routerd. Do not edit by hand.\n")
	buf.WriteString("# This file is used only when IPv6PrefixDelegation.spec.client is dhcpcd.\n")
	buf.WriteString(fmt.Sprintf("interface %s\n", pd.IfName))
	buf.WriteString("  ipv6rs\n")
	buf.WriteString("  ipv6only\n")
	buf.WriteString("  noipv4\n")
	if api.IsNTTIPv6PDProfile(pd.Profile) {
		buf.WriteString("  duid ll\n")
		buf.WriteString("  nooption rapid_commit\n")
	} else {
		buf.WriteString("  duid\n")
	}
	buf.WriteString("  option domain_name_servers\n")
	if hookPath != "" {
		buf.WriteString("  # routerd hook " + hookPath + "\n")
	}
	buf.WriteString("  ia_pd " + dhcpcdIAPD(pd) + "\n")
	writeDHCPCDObservedLeaseComments(&buf, pd)
	return buf.Bytes(), nil
}

func dhcpcdIAPD(pd dhcpcdPD) string {
	iaid := "1"
	if parsed, ok := parseIAID(pd.IAID); ok {
		iaid = fmt.Sprintf("%d", parsed)
	}
	prefix := strings.TrimSpace(pd.PriorPrefix)
	if prefix != "" {
		return iaid + "/" + prefix
	}
	if api.IsNTTIPv6PDProfile(pd.Profile) {
		return iaid + " -"
	}
	if pd.PrefixLength > 0 {
		return fmt.Sprintf("%s/::/%d", iaid, pd.PrefixLength)
	}
	return iaid
}

func writeDHCPCDObservedLeaseComments(buf *bytes.Buffer, pd dhcpcdPD) {
	strategy := defaultString(pd.AcquisitionStrategy, "hybrid")
	buf.WriteString("# routerd acquisition-strategy " + strategy + "\n")
	if pd.DUIDRawData != "" {
		buf.WriteString("# routerd duid-raw-data " + formatColonHex(pd.DUIDRawData) + "\n")
	}
	serverID := pd.ServerID
	if serverID == "" {
		serverID = pd.Lease.ServerID
	}
	if serverID != "" {
		buf.WriteString("# routerd observed-server-id " + formatColonHex(serverID) + "\n")
	}
	priorPrefix := pd.PriorPrefix
	if priorPrefix == "" {
		priorPrefix = pd.Lease.CurrentPrefix
	}
	if priorPrefix == "" {
		priorPrefix = pd.Lease.LastPrefix
	}
	if priorPrefix != "" {
		buf.WriteString("# routerd prior-prefix " + priorPrefix + "\n")
	}
}

func DHCPCDHookScript(resourceName string) []byte {
	return []byte(fmt.Sprintf(`#!/bin/sh
# Generated by routerd. Do not edit by hand.
# Reserved for future DHCPv6-PD event ingestion for %s.
exit 0
`, resourceName))
}

func DHCPCDServiceUnit(binaryPath, configPath, runtimeDir, ifname, resourceName string) []byte {
	return []byte(fmt.Sprintf(`[Unit]
Description=routerd dhcpcd DHCPv6-PD client %s
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=%s -B -6 -f %s %s
Restart=always
RestartSec=5s

[Install]
WantedBy=multi-user.target
`, resourceName, binaryPath, configPath, ifname))
}
