package render

import (
	"bytes"
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"routerd/pkg/api"
	routerstate "routerd/pkg/state"
)

type DHCP6CConfig struct {
	Files []ManagedFile
	Units []string
}

type DHCP6CStyle string

const (
	DHCP6CStyleLinux   DHCP6CStyle = "linux"
	DHCP6CStyleFreeBSD DHCP6CStyle = "freebsd"
)

func DHCP6C(router *api.Router, binaryPath, configDir, runtimeDir, unitDir string) (DHCP6CConfig, error) {
	return DHCP6CWithLeases(router, binaryPath, configDir, runtimeDir, unitDir, nil)
}

func DHCP6CWithLeases(router *api.Router, binaryPath, configDir, runtimeDir, unitDir string, leases map[string]routerstate.PDLease) (DHCP6CConfig, error) {
	aliases := map[string]string{}
	for _, res := range router.Spec.Resources {
		if res.Kind != "Interface" {
			continue
		}
		spec, err := res.InterfaceSpec()
		if err != nil {
			return DHCP6CConfig{}, err
		}
		aliases[res.Metadata.Name] = spec.IfName
	}

	var resources []api.Resource
	for _, res := range router.Spec.Resources {
		if res.Kind != "IPv6PrefixDelegation" {
			continue
		}
		spec, err := res.IPv6PrefixDelegationSpec()
		if err != nil {
			return DHCP6CConfig{}, err
		}
		if defaultString(spec.Client, "networkd") == "dhcp6c" {
			resources = append(resources, res)
		}
	}
	sort.Slice(resources, func(i, j int) bool { return resources[i].Metadata.Name < resources[j].Metadata.Name })

	var config DHCP6CConfig
	for _, res := range resources {
		spec, err := res.IPv6PrefixDelegationSpec()
		if err != nil {
			return DHCP6CConfig{}, err
		}
		ifname := aliases[spec.Interface]
		if ifname == "" {
			return DHCP6CConfig{}, fmt.Errorf("%s references interface with empty ifname", res.ID())
		}
		name := safeServiceName(res.Metadata.Name)
		confPath := filepath.Join(configDir, "dhcp6c-"+name+".conf")
		pidPath := filepath.Join(runtimeDir, "dhcp6c-"+name+".pid")
		unit := "routerd-dhcp6c-" + name + ".service"
		profile := defaultString(spec.Profile, api.IPv6PDProfileDefault)
		pd := freeBSDPD{
			Name:                res.Metadata.Name,
			IfName:              ifname,
			Profile:             profile,
			PrefixLength:        api.EffectiveIPv6PDPrefixLength(profile, spec.PrefixLength),
			IAID:                strings.TrimSpace(spec.IAID),
			ServerID:            strings.TrimSpace(spec.ServerID),
			PriorPrefix:         strings.TrimSpace(spec.PriorPrefix),
			AcquisitionStrategy: strings.TrimSpace(spec.AcquisitionStrategy),
			Lease:               leases[res.Metadata.Name],
		}
		data, err := dhcp6cConfig(router, aliases, pd)
		if err != nil {
			return DHCP6CConfig{}, err
		}
		config.Files = append(config.Files,
			ManagedFile{Path: confPath, Data: data, Perm: 0644},
			ManagedFile{Path: filepath.Join(unitDir, unit), Data: DHCP6CServiceUnit(binaryPath, confPath, pidPath, ifname, res.Metadata.Name, api.IsNTTIPv6PDProfile(profile), DHCP6CStyleLinux), Perm: 0644},
		)
		config.Units = append(config.Units, unit)
	}
	return config, nil
}

func dhcp6cConfig(router *api.Router, aliases map[string]string, pd freeBSDPD) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString("# Generated by routerd. Do not edit by hand.\n")
	iaid := 0
	if parsed, ok := parseIAID(pd.IAID); ok {
		iaid = int(parsed)
	}
	buf.WriteString(fmt.Sprintf("interface %s {\n", pd.IfName))
	buf.WriteString(fmt.Sprintf("  send ia-pd %d;\n", iaid))
	buf.WriteString("  request domain-name-servers;\n")
	buf.WriteString("};\n\n")
	buf.WriteString(fmt.Sprintf("id-assoc pd %d {\n", iaid))
	writeDHCP6CObservedLeaseComments(&buf, pd)
	for _, res := range router.Spec.Resources {
		if res.Kind != "IPv6DelegatedAddress" {
			continue
		}
		spec, err := res.IPv6DelegatedAddressSpec()
		if err != nil {
			return nil, err
		}
		if spec.PrefixDelegation != pd.Name {
			continue
		}
		ifname := aliases[spec.Interface]
		if ifname == "" {
			return nil, fmt.Errorf("%s references interface with empty ifname", res.ID())
		}
		buf.WriteString(fmt.Sprintf("  prefix-interface %s {\n", ifname))
		buf.WriteString(fmt.Sprintf("    sla-id %s;\n", defaultString(spec.SubnetID, "0")))
		if pd.PrefixLength > 0 && pd.PrefixLength <= 64 {
			buf.WriteString(fmt.Sprintf("    sla-len %d;\n", 64-pd.PrefixLength))
		}
		buf.WriteString("  };\n")
	}
	buf.WriteString("};\n")
	return buf.Bytes(), nil
}

func DHCP6CServiceUnit(binaryPath, configPath, pidPath, ifname, resourceName string, noRelease bool, style DHCP6CStyle) []byte {
	flags := []string{"-dDf"}
	if noRelease && style == DHCP6CStyleFreeBSD {
		flags = append(flags, "-n")
	}
	flags = append(flags, "-c", configPath, "-p", pidPath, ifname)
	return []byte(fmt.Sprintf(`[Unit]
Description=routerd DHCPv6-PD client %s
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=%s %s
Restart=always
RestartSec=5s

[Install]
WantedBy=multi-user.target
`, resourceName, binaryPath, strings.Join(flags, " ")))
}

func safeServiceName(name string) string {
	var b strings.Builder
	for _, r := range name {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '-' || r == '_' {
			b.WriteRune(r)
			continue
		}
		b.WriteByte('-')
	}
	if b.Len() == 0 {
		return "unnamed"
	}
	return b.String()
}
