package render

import (
	"bytes"
	"errors"
	"fmt"
	"net/netip"
	"sort"
	"strings"

	"routerd/pkg/api"
)

type DnsmasqRuntime struct {
	DHCPv4DNSServersByInterface map[string][]string
	DHCPv6DNSServersByInterface map[string][]string
	IPv6AddressesByInterface    map[string][]string
	IPv6PrefixesByInterface     map[string][]string
	RuntimeDir                  string
}

func DnsmasqConfig(router *api.Router, runtime DnsmasqRuntime) ([]byte, []string, error) {
	var warnings []string
	aliases, staticIPv4, delegatedIPv6, selfPolicies, err := dnsmasqInputs(router)
	if err != nil {
		return nil, nil, err
	}
	raMTUByScope, err := pathMTURAByScope(router)
	if err != nil {
		return nil, nil, err
	}

	var v4Scopes []api.Resource
	var v6Scopes []api.Resource
	v4Servers := map[string]api.DHCPv4ServerSpec{}
	v6Servers := map[string]api.DHCPv6ServerSpec{}
	v4ReservationsByScope := map[string][]api.Resource{}
	for _, res := range router.Spec.Resources {
		switch res.Kind {
		case "DHCPv4Server":
			spec, err := res.DHCPv4ServerSpec()
			if err != nil {
				return nil, warnings, err
			}
			v4Servers[res.Metadata.Name] = spec
		case "DHCPv6Server":
			spec, err := res.DHCPv6ServerSpec()
			if err != nil {
				return nil, warnings, err
			}
			v6Servers[res.Metadata.Name] = spec
		}
	}
	for _, res := range router.Spec.Resources {
		switch res.Kind {
		case "DHCPv4Scope":
			spec, err := res.DHCPv4ScopeSpec()
			if err != nil {
				return nil, warnings, err
			}
			server := v4Servers[spec.Server]
			if defaultString(server.Server, "dnsmasq") == "dnsmasq" && server.Managed && defaultString(server.Role, "server") != "transit" {
				v4Scopes = append(v4Scopes, res)
			}
		case "DHCPv4Reservation":
			spec, err := res.DHCPv4ReservationSpec()
			if err != nil {
				return nil, warnings, err
			}
			v4ReservationsByScope[spec.Scope] = append(v4ReservationsByScope[spec.Scope], res)
		case "DHCPv6Scope":
			spec, err := res.DHCPv6ScopeSpec()
			if err != nil {
				return nil, warnings, err
			}
			server := v6Servers[spec.Server]
			if defaultString(server.Server, "dnsmasq") == "dnsmasq" && server.Managed && defaultString(server.Role, "server") != "transit" {
				v6Scopes = append(v6Scopes, res)
			}
		}
	}
	hasDirect := hasDirectDnsmasqLANService(router)
	if len(v4Scopes) == 0 && len(v6Scopes) == 0 && !hasDirect {
		return nil, nil, nil
	}
	sort.Slice(v4Scopes, func(i, j int) bool { return v4Scopes[i].Metadata.Name < v4Scopes[j].Metadata.Name })
	sort.Slice(v6Scopes, func(i, j int) bool { return v6Scopes[i].Metadata.Name < v6Scopes[j].Metadata.Name })
	for scope := range v4ReservationsByScope {
		sort.Slice(v4ReservationsByScope[scope], func(i, j int) bool {
			return v4ReservationsByScope[scope][i].Metadata.Name < v4ReservationsByScope[scope][j].Metadata.Name
		})
	}
	v6Scopes, err = activeDnsmasqIPv6Scopes(v6Scopes, delegatedIPv6, runtime)
	if err != nil {
		return nil, warnings, err
	}

	var buf bytes.Buffer
	runtimeDir := defaultString(runtime.RuntimeDir, "/run/routerd")
	buf.WriteString("# Generated by routerd. Do not edit by hand.\n")
	buf.WriteString("dhcp-leasefile=" + strings.TrimRight(runtimeDir, "/") + "/dnsmasq.leases\n")
	buf.WriteString("port=0\n")
	buf.WriteString("no-resolv\n")
	var renderedScopes []string
	for _, res := range v4Scopes {
		spec, err := res.DHCPv4ScopeSpec()
		if err != nil {
			return nil, warnings, err
		}
		server := v4Servers[spec.Server]
		if !serverListensOn(server.ListenInterfaces, spec.Interface) {
			return nil, warnings, fmt.Errorf("%s interface %q is not listed in DHCPv4Server %q listenInterfaces", res.ID(), spec.Interface, spec.Server)
		}
		ifname := aliases[spec.Interface]
		if ifname == "" {
			return nil, warnings, fmt.Errorf("%s references interface with empty ifname", res.ID())
		}
		renderedScopes = append(renderedScopes, ifname)
	}
	for _, res := range v6Scopes {
		spec, err := res.DHCPv6ScopeSpec()
		if err != nil {
			return nil, warnings, err
		}
		delegated := delegatedIPv6[spec.DelegatedAddress]
		server := v6Servers[spec.Server]
		if !serverListensOn(server.ListenInterfaces, delegated.Interface) {
			return nil, warnings, fmt.Errorf("%s delegatedAddress interface %q is not listed in DHCPv6Server %q listenInterfaces", res.ID(), delegated.Interface, spec.Server)
		}
		if delegated.IfName == "" {
			return nil, warnings, fmt.Errorf("%s references delegated address with empty ifname", res.ID())
		}
		renderedScopes = append(renderedScopes, delegated.IfName)
	}
	renderedScopes = append(renderedScopes, directDnsmasqIfnames(router, aliases)...)
	buf.WriteString("bind-dynamic\n")
	for _, ifname := range uniqueStrings(renderedScopes) {
		buf.WriteString("interface=" + ifname + "\n")
	}
	for _, ifname := range dnsmasqExcludedInterfaces(aliases, renderedScopes) {
		buf.WriteString("except-interface=" + ifname + "\n")
	}
	if len(v6Scopes) > 0 {
		buf.WriteString("enable-ra\n")
	}
	writeDirectDnsmasqLANService(&buf, router, aliases)

	for _, res := range v4Scopes {
		spec, err := res.DHCPv4ScopeSpec()
		if err != nil {
			return nil, warnings, err
		}
		ifname := aliases[spec.Interface]
		addrPrefix := staticIPv4[spec.Interface]
		if !addrPrefix.IsValid() {
			return nil, warnings, fmt.Errorf("%s needs an IPv4StaticAddress on %s to derive DHCP netmask/options", res.ID(), spec.Interface)
		}
		netmask, err := ipv4Netmask(addrPrefix.Bits())
		if err != nil {
			return nil, warnings, fmt.Errorf("%s has invalid IPv4 prefix length: %w", res.ID(), err)
		}
		leaseTime := defaultString(spec.LeaseTime, "12h")
		tag := sanitizeDnsmasqTag(res.Metadata.Name)

		buf.WriteString("\n")
		if spec.Authoritative {
			buf.WriteString("dhcp-authoritative\n")
		}
		buf.WriteString(fmt.Sprintf("dhcp-range=set:%s,%s,%s,%s,%s\n", tag, spec.RangeStart, spec.RangeEnd, netmask, leaseTime))

		switch defaultString(spec.RouterSource, "interfaceAddress") {
		case "interfaceAddress":
			buf.WriteString(fmt.Sprintf("dhcp-option=tag:%s,option:router,%s\n", tag, addrPrefix.Addr()))
		case "static":
			buf.WriteString(fmt.Sprintf("dhcp-option=tag:%s,option:router,%s\n", tag, spec.Router))
		case "none":
			buf.WriteString(fmt.Sprintf("dhcp-option=tag:%s,option:router\n", tag))
		}

		dnsServers, err := dnsmasqDNSServers(spec, aliases, staticIPv4, runtime)
		if err != nil {
			if errors.Is(err, errObservedDataNotReady) {
				warnings = append(warnings, fmt.Sprintf("%s: %v; emitting empty DHCP dns-server option until observed", res.ID(), err))
				buf.WriteString(fmt.Sprintf("dhcp-option=tag:%s,option:dns-server\n", tag))
			} else {
				return nil, warnings, fmt.Errorf("%s: %w", res.ID(), err)
			}
		} else if len(dnsServers) == 0 {
			buf.WriteString(fmt.Sprintf("dhcp-option=tag:%s,option:dns-server\n", tag))
		} else {
			buf.WriteString(fmt.Sprintf("dhcp-option=tag:%s,option:dns-server,%s\n", tag, strings.Join(dnsServers, ",")))
		}
		for _, reservation := range v4ReservationsByScope[res.Metadata.Name] {
			reservationSpec, err := reservation.DHCPv4ReservationSpec()
			if err != nil {
				return nil, warnings, err
			}
			buf.WriteString("dhcp-host=" + dnsmasqHostReservation(reservationSpec, leaseTime) + "\n")
		}
		_ = ifname
	}
	for _, res := range v6Scopes {
		spec, err := res.DHCPv6ScopeSpec()
		if err != nil {
			return nil, warnings, err
		}
		delegated := delegatedIPv6[spec.DelegatedAddress]
		leaseTime := defaultString(spec.LeaseTime, "12h")
		tag := sanitizeDnsmasqTag(res.Metadata.Name)
		mode := defaultString(spec.Mode, "stateless")
		raMode := "ra-stateless"
		if mode == "ra-only" {
			raMode = "ra-only"
		}
		buf.WriteString("\n")
		buf.WriteString(fmt.Sprintf("dhcp-range=set:%s,::,constructor:%s,%s,64,%s\n", tag, delegated.IfName, raMode, leaseTime))
		raMTU := raMTUByScope[res.Metadata.Name]
		switch {
		case raMTU != 0 && !spec.DefaultRoute:
			buf.WriteString(fmt.Sprintf("ra-param=%s,%d\n", delegated.IfName, raMTU))
			buf.WriteString(fmt.Sprintf("ra-param=%s,0,0\n", delegated.IfName))
		case raMTU != 0:
			buf.WriteString(fmt.Sprintf("ra-param=%s,%d\n", delegated.IfName, raMTU))
		case !spec.DefaultRoute:
			buf.WriteString(fmt.Sprintf("ra-param=%s,0,0\n", delegated.IfName))
		}
		dnsServers, err := dnsmasqIPv6DNSServers(spec, delegated, selfPolicies[spec.SelfAddressPolicy], aliases, delegatedIPv6, runtime)
		if err != nil {
			return nil, warnings, fmt.Errorf("%s: %w", res.ID(), err)
		}
		if len(dnsServers) == 0 {
			buf.WriteString(fmt.Sprintf("dhcp-option=tag:%s,option6:dns-server\n", tag))
		} else {
			buf.WriteString(fmt.Sprintf("dhcp-option=tag:%s,option6:dns-server,%s\n", tag, strings.Join(wrapIPv6Servers(dnsServers), ",")))
		}
	}

	return buf.Bytes(), warnings, nil
}

func hasDirectDnsmasqLANService(router *api.Router) bool {
	for _, res := range router.Spec.Resources {
		switch res.Kind {
		case "DHCPv4Server":
			spec, err := res.DHCPv4ServerSpec()
			if err == nil && spec.Interface != "" {
				return true
			}
		case "DHCPv6Server":
			spec, err := res.DHCPv6ServerSpec()
			if err == nil && spec.Interface != "" {
				return true
			}
		case "IPv6RouterAdvertisement", "DHCPv4Relay":
			return true
		}
	}
	return false
}

func directDnsmasqIfnames(router *api.Router, aliases map[string]string) []string {
	var ifnames []string
	for _, res := range router.Spec.Resources {
		switch res.Kind {
		case "DHCPv4Server":
			spec, err := res.DHCPv4ServerSpec()
			if err == nil && spec.Interface != "" && aliases[spec.Interface] != "" {
				ifnames = append(ifnames, aliases[spec.Interface])
			}
		case "DHCPv6Server", "IPv6RouterAdvertisement":
			var iface string
			if res.Kind == "DHCPv6Server" {
				spec, err := res.DHCPv6ServerSpec()
				if err == nil && spec.Interface != "" {
					iface = spec.Interface
				}
			} else {
				spec, err := res.IPv6RouterAdvertisementSpec()
				if err == nil {
					iface = spec.Interface
				}
			}
			if aliases[iface] != "" {
				ifnames = append(ifnames, aliases[iface])
			}
		case "DHCPv4Relay":
			spec, err := res.DHCPv4RelaySpec()
			if err == nil {
				for _, iface := range spec.Interfaces {
					if aliases[iface] != "" {
						ifnames = append(ifnames, aliases[iface])
					}
				}
			}
		}
	}
	return uniqueStrings(ifnames)
}

func writeDirectDnsmasqLANService(buf *bytes.Buffer, router *api.Router, aliases map[string]string) {
	for _, res := range router.Spec.Resources {
		if res.Kind != "DHCPv4Server" {
			continue
		}
		spec, err := res.DHCPv4ServerSpec()
		if err != nil || spec.Interface == "" {
			continue
		}
		ifname := aliases[spec.Interface]
		if ifname == "" {
			continue
		}
		tag := sanitizeDnsmasqTag(res.Metadata.Name)
		buf.WriteString("\n")
		buf.WriteString("interface=" + ifname + "\n")
		leaseTime := defaultString(spec.AddressPool.LeaseTime, "12h")
		buf.WriteString(fmt.Sprintf("dhcp-range=set:%s,%s,%s,%s\n", tag, spec.AddressPool.Start, spec.AddressPool.End, leaseTime))
		if spec.Gateway != "" {
			buf.WriteString(fmt.Sprintf("dhcp-option=tag:%s,option:router,%s\n", tag, spec.Gateway))
		}
		if len(spec.DNSServers) > 0 {
			buf.WriteString(fmt.Sprintf("dhcp-option=tag:%s,option:dns-server,%s\n", tag, strings.Join(spec.DNSServers, ",")))
		}
		if len(spec.NTPServers) > 0 {
			buf.WriteString(fmt.Sprintf("dhcp-option=tag:%s,option:ntp-server,%s\n", tag, strings.Join(spec.NTPServers, ",")))
		}
		if spec.Domain != "" {
			buf.WriteString(fmt.Sprintf("dhcp-option=tag:%s,option:domain-name,%s\n", tag, spec.Domain))
		}
		for _, option := range spec.Options {
			buf.WriteString("dhcp-option=tag:" + tag + "," + dnsmasqDHCPv4Option(option) + "\n")
		}
		for _, reservation := range router.Spec.Resources {
			if reservation.Kind != "DHCPv4Reservation" {
				continue
			}
			reservationSpec, err := reservation.DHCPv4ReservationSpec()
			if err != nil || reservationSpec.Scope != "" || (reservationSpec.Server != "" && reservationSpec.Server != res.Metadata.Name) {
				continue
			}
			reservationTag := sanitizeDnsmasqTag(reservation.Metadata.Name)
			buf.WriteString("dhcp-host=" + dnsmasqIPv4Reservation(reservationSpec, reservationTag) + "\n")
			for _, option := range reservationSpec.Options {
				buf.WriteString("dhcp-option=tag:" + reservationTag + "," + dnsmasqDHCPv4Option(option) + "\n")
			}
		}
	}
	for _, res := range router.Spec.Resources {
		if res.Kind != "DHCPv6Server" {
			continue
		}
		spec, err := res.DHCPv6ServerSpec()
		if err != nil || spec.Interface == "" {
			continue
		}
		ifname := defaultString(aliases[spec.Interface], spec.Interface)
		tag := sanitizeDnsmasqTag(res.Metadata.Name)
		buf.WriteString("\n")
		buf.WriteString("interface=" + ifname + "\n")
		buf.WriteString("enable-ra\n")
		leaseTime := defaultString(defaultString(spec.AddressPool.LeaseTime, spec.LeaseTime), "12h")
		switch defaultString(spec.Mode, "stateless") {
		case "stateful":
			buf.WriteString(fmt.Sprintf("dhcp-range=set:%s,%s,%s,constructor:%s,64,%s\n", tag, spec.AddressPool.Start, spec.AddressPool.End, ifname, leaseTime))
		case "both":
			buf.WriteString(fmt.Sprintf("dhcp-range=set:%s,%s,%s,constructor:%s,slaac,64,%s\n", tag, spec.AddressPool.Start, spec.AddressPool.End, ifname, leaseTime))
		default:
			buf.WriteString(fmt.Sprintf("dhcp-range=set:%s,::,constructor:%s,ra-stateless,64,%s\n", tag, ifname, leaseTime))
		}
		for _, server := range spec.DNSServers {
			buf.WriteString(fmt.Sprintf("dhcp-option=tag:%s,option6:dns-server,[%s]\n", tag, strings.Trim(server, "[]")))
		}
		if len(spec.DomainSearch) > 0 {
			buf.WriteString(fmt.Sprintf("dhcp-option=tag:%s,option6:domain-search,%s\n", tag, strings.Join(spec.DomainSearch, ",")))
		}
		for _, server := range spec.SNTPServers {
			buf.WriteString(fmt.Sprintf("dhcp-option=tag:%s,option6:sntp-server,[%s]\n", tag, strings.Trim(server, "[]")))
		}
	}
	for _, res := range router.Spec.Resources {
		if res.Kind != "IPv6RouterAdvertisement" {
			continue
		}
		spec, err := res.IPv6RouterAdvertisementSpec()
		if err != nil {
			continue
		}
		ifname := aliases[spec.Interface]
		if ifname == "" {
			ifname = spec.Interface
		}
		buf.WriteString("interface=" + ifname + "\n")
		buf.WriteString("enable-ra\n")
		var params []string
		if spec.MTU != 0 {
			params = append(params, fmt.Sprintf("mtu:%d", spec.MTU))
		}
		switch spec.PRFPreference {
		case "high", "low":
			params = append(params, spec.PRFPreference)
		}
		if spec.ValidLifetime != "" {
			params = append(params, "0", spec.ValidLifetime)
		} else if spec.MTU != 0 && (spec.PRFPreference == "high" || spec.PRFPreference == "low") {
			params = append(params, "0")
		}
		if len(params) > 0 {
			buf.WriteString(fmt.Sprintf("ra-param=%s,%s\n", ifname, strings.Join(params, ",")))
		}
		for _, server := range spec.RDNSS {
			buf.WriteString(fmt.Sprintf("dhcp-option=option6:dns-server,[%s]\n", strings.Trim(server, "[]")))
		}
		if len(spec.DNSSL) > 0 {
			buf.WriteString("dhcp-option=option6:domain-search," + strings.Join(spec.DNSSL, ",") + "\n")
		}
	}
	for _, res := range router.Spec.Resources {
		if res.Kind == "DHCPv4Relay" {
			spec, err := res.DHCPv4RelaySpec()
			if err == nil {
				for _, iface := range spec.Interfaces {
					if ifname := aliases[iface]; ifname != "" {
						buf.WriteString(fmt.Sprintf("dhcp-relay=0.0.0.0,%s,%s\n", spec.Upstream, ifname))
					}
				}
			}
		}
	}
}

var errObservedDataNotReady = errors.New("observed runtime data not yet available")

func DnsmasqServiceUnit(configPath, dnsmasqPath string) []byte {
	return []byte(`[Unit]
Description=routerd managed dnsmasq DHCP service
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=` + dnsmasqPath + ` --keep-in-foreground --conf-file=` + configPath + ` --pid-file=/run/routerd/dnsmasq.pid
Restart=on-failure
RestartSec=2s

[Install]
WantedBy=multi-user.target
`)
}

func DnsmasqRCScript(configPath, runtimeDir string) []byte {
	if runtimeDir == "" {
		runtimeDir = "/var/run/routerd"
	}
	return []byte(`#!/bin/sh

# PROVIDE: routerd_dnsmasq
# REQUIRE: NETWORKING
# KEYWORD: shutdown

. /etc/rc.subr

name="routerd_dnsmasq"
rcvar="routerd_dnsmasq_enable"
command="/usr/local/sbin/dnsmasq"
pidfile="` + strings.TrimRight(runtimeDir, "/") + `/dnsmasq.pid"
command_args="--conf-file=` + configPath + ` --pid-file=${pidfile}"

load_rc_config ${name}
: ${routerd_dnsmasq_enable:="NO"}

run_rc_command "$1"
`)
}

func activeDnsmasqIPv6Scopes(scopes []api.Resource, delegatedIPv6 map[string]delegatedIPv6Address, runtime DnsmasqRuntime) ([]api.Resource, error) {
	var active []api.Resource
	for _, res := range scopes {
		spec, err := res.DHCPv6ScopeSpec()
		if err != nil {
			return nil, err
		}
		delegated := delegatedIPv6[spec.DelegatedAddress]
		if delegated.IfName == "" || hasUsableIPv6Prefix(runtime.IPv6PrefixesByInterface[delegated.IfName]) {
			active = append(active, res)
		}
	}
	return active, nil
}

func dnsmasqDNSEnabled(v4Scopes []api.Resource, servers map[string]api.DHCPv4ServerSpec, v6Scopes []api.Resource) (bool, error) {
	for _, res := range v4Scopes {
		spec, err := res.DHCPv4ScopeSpec()
		if err != nil {
			return false, err
		}
		if servers[spec.Server].DNS.Enabled || defaultString(spec.DNSSource, "self") == "self" {
			return true, nil
		}
	}
	for _, res := range v6Scopes {
		spec, err := res.DHCPv6ScopeSpec()
		if err != nil {
			return false, err
		}
		if defaultString(spec.DNSSource, "self") == "self" {
			return true, nil
		}
	}
	return false, nil
}

func writeDnsmasqDNSUpstreams(buf *bytes.Buffer, scopes []api.Resource, servers map[string]api.DHCPv4ServerSpec, aliases map[string]string, runtime DnsmasqRuntime, warnings *[]string) error {
	for _, res := range scopes {
		spec, err := res.DHCPv4ScopeSpec()
		if err != nil {
			return err
		}
		server := servers[spec.Server]
		dns := server.DNS
		if !dns.Enabled && defaultString(spec.DNSSource, "self") != "self" {
			continue
		}
		if dns.CacheSize != 0 {
			buf.WriteString(fmt.Sprintf("cache-size=%d\n", dns.CacheSize))
		}
		upstreamSource := defaultString(dns.UpstreamSource, "system")
		switch upstreamSource {
		case "dhcpv4":
			ifname := aliases[dns.UpstreamInterface]
			upstream := filterIPv4Strings(runtime.DHCPv4DNSServersByInterface[ifname])
			if len(upstream) == 0 {
				*warnings = append(*warnings, fmt.Sprintf("%s: no DHCPv4 DNS servers observed on %s yet; skipping upstream resolver until observed", res.ID(), ifname))
				continue
			}
			buf.WriteString("no-resolv\n")
			for _, server := range upstream {
				buf.WriteString("server=" + server + "\n")
			}
		case "static":
			buf.WriteString("no-resolv\n")
			for _, server := range dns.UpstreamServers {
				buf.WriteString("server=" + server + "\n")
			}
		case "none":
			buf.WriteString("no-resolv\n")
		case "system":
		default:
			return fmt.Errorf("unsupported dns.upstreamSource %q", dns.UpstreamSource)
		}
		return nil
	}
	return nil
}

type delegatedIPv6Address struct {
	Interface     string
	IfName        string
	AddressSuffix string
}

func dnsmasqInputs(router *api.Router) (map[string]string, map[string]netip.Prefix, map[string]delegatedIPv6Address, map[string]api.SelfAddressPolicySpec, error) {
	aliases := map[string]string{}
	staticIPv4 := map[string]netip.Prefix{}
	delegatedIPv6 := map[string]delegatedIPv6Address{}
	selfPolicies := map[string]api.SelfAddressPolicySpec{}
	for _, res := range router.Spec.Resources {
		switch res.Kind {
		case "Interface":
			spec, err := res.InterfaceSpec()
			if err != nil {
				return nil, nil, nil, nil, err
			}
			aliases[res.Metadata.Name] = spec.IfName
		}
	}
	for _, res := range router.Spec.Resources {
		switch res.Kind {
		case "IPv4StaticAddress":
			spec, err := res.IPv4StaticAddressSpec()
			if err != nil {
				return nil, nil, nil, nil, err
			}
			prefix, err := netip.ParsePrefix(spec.Address)
			if err != nil {
				return nil, nil, nil, nil, err
			}
			staticIPv4[spec.Interface] = prefix
		case "IPv6DelegatedAddress":
			spec, err := res.IPv6DelegatedAddressSpec()
			if err != nil {
				return nil, nil, nil, nil, err
			}
			delegatedIPv6[res.Metadata.Name] = delegatedIPv6Address{Interface: spec.Interface, IfName: aliases[spec.Interface], AddressSuffix: spec.AddressSuffix}
		case "SelfAddressPolicy":
			spec, err := res.SelfAddressPolicySpec()
			if err != nil {
				return nil, nil, nil, nil, err
			}
			selfPolicies[res.Metadata.Name] = spec
		}
	}
	return aliases, staticIPv4, delegatedIPv6, selfPolicies, nil
}

func dnsmasqExcludedInterfaces(aliases map[string]string, renderedScopes []string) []string {
	served := map[string]bool{}
	for _, ifname := range renderedScopes {
		if ifname != "" {
			served[ifname] = true
		}
	}
	var excluded []string
	for _, ifname := range aliases {
		if ifname != "" && !served[ifname] {
			excluded = append(excluded, ifname)
		}
	}
	return uniqueStrings(excluded)
}

func serverListensOn(listenInterfaces []string, iface string) bool {
	for _, candidate := range listenInterfaces {
		if candidate == iface {
			return true
		}
	}
	return false
}

func dnsmasqListenAddresses(v4Scopes, v6Scopes []api.Resource, aliases map[string]string, staticIPv4 map[string]netip.Prefix, delegatedIPv6 map[string]delegatedIPv6Address, selfPolicies map[string]api.SelfAddressPolicySpec, runtime DnsmasqRuntime) ([]string, error) {
	var addresses []string
	addresses = append(addresses, "127.0.0.1", "::1")
	for _, res := range v4Scopes {
		spec, err := res.DHCPv4ScopeSpec()
		if err != nil {
			return nil, err
		}
		if defaultString(spec.DNSSource, "self") != "self" {
			continue
		}
		for _, server := range dnsmasqSelfIPv4ListenAddresses(spec, staticIPv4) {
			addresses = append(addresses, server)
		}
	}
	for _, res := range v6Scopes {
		spec, err := res.DHCPv6ScopeSpec()
		if err != nil {
			return nil, err
		}
		if defaultString(spec.DNSSource, "self") != "self" {
			continue
		}
		delegated := delegatedIPv6[spec.DelegatedAddress]
		servers, err := dnsmasqIPv6DNSServers(spec, delegated, selfPolicies[spec.SelfAddressPolicy], aliases, delegatedIPv6, runtime)
		if err != nil {
			return nil, err
		}
		addresses = append(addresses, servers...)
	}
	return uniqueStrings(addresses), nil
}

func dnsmasqSelfIPv4ListenAddresses(spec api.DHCPv4ScopeSpec, staticIPv4 map[string]netip.Prefix) []string {
	addrPrefix := staticIPv4[spec.Interface]
	if !addrPrefix.IsValid() {
		return nil
	}
	return []string{addrPrefix.Addr().String()}
}

func dnsmasqDNSServers(spec api.DHCPv4ScopeSpec, aliases map[string]string, staticIPv4 map[string]netip.Prefix, runtime DnsmasqRuntime) ([]string, error) {
	switch defaultString(spec.DNSSource, "self") {
	case "dhcpv4":
		ifname := aliases[spec.DNSInterface]
		servers := filterIPv4Strings(runtime.DHCPv4DNSServersByInterface[ifname])
		if len(servers) == 0 {
			return nil, fmt.Errorf("no DHCPv4 DNS servers observed on %s: %w", ifname, errObservedDataNotReady)
		}
		return servers, nil
	case "static":
		return spec.DNSServers, nil
	case "self":
		prefix := staticIPv4[spec.Interface]
		if !prefix.IsValid() {
			return nil, fmt.Errorf("self DNS needs an IPv4StaticAddress on %s", spec.Interface)
		}
		return []string{prefix.Addr().String()}, nil
	case "none":
		return nil, nil
	default:
		return nil, fmt.Errorf("unsupported dnsSource %q", spec.DNSSource)
	}
}

func dnsmasqHostReservation(spec api.DHCPv4ReservationSpec, scopeLeaseTime string) string {
	parts := []string{strings.ToLower(spec.MACAddress), spec.IPAddress}
	if spec.Hostname != "" {
		parts = append(parts, spec.Hostname)
	}
	if leaseTime := defaultString(spec.LeaseTime, scopeLeaseTime); leaseTime != "" {
		parts = append(parts, leaseTime)
	}
	return strings.Join(parts, ",")
}

func dnsmasqIPv4Reservation(spec api.DHCPv4ReservationSpec, tag string) string {
	parts := []string{strings.ToLower(spec.MACAddress)}
	if tag != "" {
		parts = append(parts, "set:"+tag)
	}
	if spec.Hostname != "" {
		parts = append(parts, spec.Hostname)
	}
	parts = append(parts, spec.IPAddress)
	return strings.Join(parts, ",")
}

func dnsmasqDHCPv4Option(option api.DHCPv4OptionSpec) string {
	key := option.Name
	if key == "" {
		key = fmt.Sprintf("%d", option.Code)
	} else {
		key = "option:" + key
	}
	return key + "," + option.Value
}

func compactDNSRecordAddresses(values ...string) []string {
	var out []string
	for _, value := range values {
		if strings.TrimSpace(value) != "" {
			out = append(out, strings.TrimSpace(value))
		}
	}
	return out
}

func dnsmasqIPv6DNSServers(spec api.DHCPv6ScopeSpec, delegated delegatedIPv6Address, policy api.SelfAddressPolicySpec, aliases map[string]string, delegatedAddresses map[string]delegatedIPv6Address, runtime DnsmasqRuntime) ([]string, error) {
	switch defaultString(spec.DNSSource, "self") {
	case "self":
		return selectIPv6SelfAddress(defaultIPv6SelfAddressPolicy(spec, delegated, policy), delegatedAddresses, aliases, runtime)
	case "static":
		return spec.DNSServers, nil
	case "none":
		return nil, nil
	default:
		return nil, fmt.Errorf("unsupported dnsSource %q", spec.DNSSource)
	}
}

func defaultIPv6SelfAddressPolicy(spec api.DHCPv6ScopeSpec, delegated delegatedIPv6Address, policy api.SelfAddressPolicySpec) api.SelfAddressPolicySpec {
	if spec.SelfAddressPolicy != "" {
		return policy
	}
	return api.SelfAddressPolicySpec{
		AddressFamily: "ipv6",
		Candidates: []api.SelfAddressPolicyCandidate{
			{Source: "delegatedAddress", DelegatedAddress: spec.DelegatedAddress, AddressSuffix: delegated.AddressSuffix},
			{Source: "interfaceAddress", Interface: delegated.Interface, MatchSuffix: delegated.AddressSuffix},
			{Source: "interfaceAddress", Interface: delegated.Interface, Ordinal: 1},
		},
	}
}

func selectIPv6SelfAddress(policy api.SelfAddressPolicySpec, delegatedAddresses map[string]delegatedIPv6Address, aliases map[string]string, runtime DnsmasqRuntime) ([]string, error) {
	var errs []string
	for _, candidate := range policy.Candidates {
		address, err := selectIPv6SelfAddressCandidate(candidate, delegatedAddresses, aliases, runtime)
		if err == nil {
			return []string{address}, nil
		}
		errs = append(errs, err.Error())
	}
	return nil, fmt.Errorf("no IPv6 self address selected: %s", strings.Join(errs, "; "))
}

func selectIPv6SelfAddressCandidate(candidate api.SelfAddressPolicyCandidate, delegatedAddresses map[string]delegatedIPv6Address, aliases map[string]string, runtime DnsmasqRuntime) (string, error) {
	switch candidate.Source {
	case "delegatedAddress":
		delegated := delegatedAddresses[candidate.DelegatedAddress]
		if delegated.IfName == "" {
			return "", fmt.Errorf("delegated address %q is not available", candidate.DelegatedAddress)
		}
		suffix := defaultString(candidate.AddressSuffix, delegated.AddressSuffix)
		address, err := deriveIPv6Address(runtime.IPv6PrefixesByInterface[delegated.IfName], suffix)
		if err != nil {
			return "", fmt.Errorf("derive %s%s: %w", candidate.DelegatedAddress, suffix, err)
		}
		return address, nil
	case "interfaceAddress":
		ifname := aliases[candidate.Interface]
		if ifname == "" {
			return "", fmt.Errorf("interface %q is not available", candidate.Interface)
		}
		servers := filterGlobalIPv6Strings(runtime.IPv6AddressesByInterface[ifname])
		if candidate.MatchSuffix != "" {
			for _, server := range servers {
				if ipv6AddressMatchesSuffix(server, candidate.MatchSuffix) {
					return server, nil
				}
			}
			return "", fmt.Errorf("no IPv6 address on %s matches suffix %s", ifname, candidate.MatchSuffix)
		}
		ordinal := candidate.Ordinal
		if ordinal == 0 {
			ordinal = 1
		}
		if ordinal < 1 || ordinal > len(servers) {
			return "", fmt.Errorf("IPv6 address ordinal %d is outside available address count %d on %s", ordinal, len(servers), ifname)
		}
		return servers[ordinal-1], nil
	case "static":
		return candidate.Address, nil
	default:
		return "", fmt.Errorf("unsupported self address source %q", candidate.Source)
	}
}

func ipv6AddressMatchesSuffix(address, suffix string) bool {
	addr, addrErr := netip.ParseAddr(address)
	suffixAddr, suffixErr := netip.ParseAddr(suffix)
	if addrErr != nil || suffixErr != nil || !addr.Is6() || !suffixAddr.Is6() {
		return false
	}
	addrBytes := addr.As16()
	suffixBytes := suffixAddr.As16()
	for i := range suffixBytes {
		if suffixBytes[i] != 0 && addrBytes[i] != suffixBytes[i] {
			return false
		}
	}
	return true
}

func ipv4Netmask(bits int) (string, error) {
	if bits < 0 || bits > 32 {
		return "", fmt.Errorf("%d", bits)
	}
	mask := uint32(0xffffffff) << uint(32-bits)
	if bits == 0 {
		mask = 0
	}
	return fmt.Sprintf("%d.%d.%d.%d", byte(mask>>24), byte(mask>>16), byte(mask>>8), byte(mask)), nil
}

func filterGlobalIPv6Strings(values []string) []string {
	var out []string
	for _, value := range values {
		addr, err := netip.ParseAddr(value)
		if err == nil && addr.Is6() && !addr.IsLinkLocalUnicast() {
			out = append(out, addr.String())
		}
	}
	return uniqueStrings(out)
}

func deriveIPv6Address(prefixes []string, suffix string) (string, error) {
	suffixAddr, err := netip.ParseAddr(suffix)
	if err != nil || !suffixAddr.Is6() {
		return "", fmt.Errorf("invalid suffix %q", suffix)
	}
	suffixBytes := suffixAddr.As16()
	for _, value := range prefixes {
		prefix, err := netip.ParsePrefix(value)
		if err != nil || !prefix.Addr().Is6() || prefix.Addr().IsLinkLocalUnicast() {
			continue
		}
		addrBytes := prefix.Masked().Addr().As16()
		for i := range addrBytes {
			addrBytes[i] |= suffixBytes[i]
		}
		return netip.AddrFrom16(addrBytes).String(), nil
	}
	return "", fmt.Errorf("no IPv6 prefix available")
}

func hasUsableIPv6Prefix(prefixes []string) bool {
	for _, value := range prefixes {
		prefix, err := netip.ParsePrefix(value)
		if err == nil && prefix.Addr().Is6() && !prefix.Addr().IsLinkLocalUnicast() {
			return true
		}
	}
	return false
}

func filterIPv4Strings(values []string) []string {
	var out []string
	for _, value := range values {
		addr, err := netip.ParseAddr(value)
		if err == nil && addr.Is4() {
			out = append(out, addr.String())
		}
	}
	return uniqueStrings(out)
}

func wrapIPv6Servers(values []string) []string {
	out := make([]string, 0, len(values))
	for _, value := range values {
		out = append(out, "["+value+"]")
	}
	return out
}

func uniqueStrings(values []string) []string {
	seen := map[string]bool{}
	var out []string
	for _, value := range values {
		if value == "" || seen[value] {
			continue
		}
		seen[value] = true
		out = append(out, value)
	}
	sort.Strings(out)
	return out
}

func sanitizeDnsmasqTag(value string) string {
	var b strings.Builder
	for _, r := range value {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_' || r == '-' {
			b.WriteRune(r)
		} else {
			b.WriteByte('-')
		}
	}
	if b.Len() == 0 {
		return "scope"
	}
	return b.String()
}
