package render

import (
	"bytes"
	"fmt"
	"net/netip"
	"sort"
	"strings"

	"routerd/pkg/api"
)

type DnsmasqRuntime struct {
	DHCPv4DNSServersByInterface map[string][]string
	DHCPv6DNSServersByInterface map[string][]string
	IPv6AddressesByInterface    map[string][]string
	IPv6PrefixesByInterface     map[string][]string
}

func DnsmasqConfig(router *api.Router, runtime DnsmasqRuntime) ([]byte, error) {
	aliases, staticIPv4, delegatedIPv6, selfPolicies, err := dnsmasqInputs(router)
	if err != nil {
		return nil, err
	}

	var v4Scopes []api.Resource
	var v6Scopes []api.Resource
	v4Servers := map[string]api.IPv4DHCPServerSpec{}
	v6Servers := map[string]api.IPv6DHCPServerSpec{}
	for _, res := range router.Spec.Resources {
		switch res.Kind {
		case "IPv4DHCPServer":
			spec, err := res.IPv4DHCPServerSpec()
			if err != nil {
				return nil, err
			}
			v4Servers[res.Metadata.Name] = spec
		case "IPv6DHCPServer":
			spec, err := res.IPv6DHCPServerSpec()
			if err != nil {
				return nil, err
			}
			v6Servers[res.Metadata.Name] = spec
		}
	}
	for _, res := range router.Spec.Resources {
		switch res.Kind {
		case "IPv4DHCPScope":
			spec, err := res.IPv4DHCPScopeSpec()
			if err != nil {
				return nil, err
			}
			server := v4Servers[spec.Server]
			if defaultString(server.Server, "dnsmasq") == "dnsmasq" && server.Managed {
				v4Scopes = append(v4Scopes, res)
			}
		case "IPv6DHCPScope":
			spec, err := res.IPv6DHCPScopeSpec()
			if err != nil {
				return nil, err
			}
			server := v6Servers[spec.Server]
			if defaultString(server.Server, "dnsmasq") == "dnsmasq" && server.Managed {
				v6Scopes = append(v6Scopes, res)
			}
		}
	}
	if len(v4Scopes) == 0 && len(v6Scopes) == 0 {
		return nil, nil
	}
	sort.Slice(v4Scopes, func(i, j int) bool { return v4Scopes[i].Metadata.Name < v4Scopes[j].Metadata.Name })
	sort.Slice(v6Scopes, func(i, j int) bool { return v6Scopes[i].Metadata.Name < v6Scopes[j].Metadata.Name })

	dnsEnabled, err := dnsmasqDNSEnabled(v4Scopes, v4Servers, v6Scopes)
	if err != nil {
		return nil, err
	}

	var buf bytes.Buffer
	buf.WriteString("# Generated by routerd. Do not edit by hand.\n")
	if dnsEnabled {
		buf.WriteString("port=53\n")
		buf.WriteString("domain-needed\n")
		buf.WriteString("bogus-priv\n")
	} else {
		buf.WriteString("port=0\n")
		buf.WriteString("no-resolv\n")
	}
	var renderedScopes []string
	for _, res := range v4Scopes {
		spec, err := res.IPv4DHCPScopeSpec()
		if err != nil {
			return nil, err
		}
		server := v4Servers[spec.Server]
		if !serverListensOn(server.ListenInterfaces, spec.Interface) {
			return nil, fmt.Errorf("%s interface %q is not listed in IPv4DHCPServer %q listenInterfaces", res.ID(), spec.Interface, spec.Server)
		}
		ifname := aliases[spec.Interface]
		if ifname == "" {
			return nil, fmt.Errorf("%s references interface with empty ifname", res.ID())
		}
		renderedScopes = append(renderedScopes, ifname)
	}
	for _, res := range v6Scopes {
		spec, err := res.IPv6DHCPScopeSpec()
		if err != nil {
			return nil, err
		}
		delegated := delegatedIPv6[spec.DelegatedAddress]
		server := v6Servers[spec.Server]
		if !serverListensOn(server.ListenInterfaces, delegated.Interface) {
			return nil, fmt.Errorf("%s delegatedAddress interface %q is not listed in IPv6DHCPServer %q listenInterfaces", res.ID(), delegated.Interface, spec.Server)
		}
		if delegated.IfName == "" {
			return nil, fmt.Errorf("%s references delegated address with empty ifname", res.ID())
		}
		renderedScopes = append(renderedScopes, delegated.IfName)
	}
	var listenAddresses []string
	if dnsEnabled {
		var err error
		listenAddresses, err = dnsmasqListenAddresses(v4Scopes, v6Scopes, aliases, staticIPv4, delegatedIPv6, selfPolicies, runtime)
		if err != nil {
			return nil, err
		}
	}
	if len(listenAddresses) > 0 {
		buf.WriteString("bind-interfaces\n")
	} else {
		buf.WriteString("bind-dynamic\n")
	}
	if len(listenAddresses) == 0 {
		for _, ifname := range uniqueStrings(renderedScopes) {
			buf.WriteString("interface=" + ifname + "\n")
		}
	}
	for _, ifname := range dnsmasqExcludedInterfaces(aliases, renderedScopes) {
		buf.WriteString("except-interface=" + ifname + "\n")
	}
	if dnsEnabled {
		if len(listenAddresses) > 0 {
			buf.WriteString("listen-address=" + strings.Join(listenAddresses, ",") + "\n")
		}
		if err := writeDnsmasqDNSUpstreams(&buf, v4Scopes, v4Servers, aliases, runtime); err != nil {
			return nil, err
		}
	}
	if err := writeDNSConditionalForwarders(&buf, router, aliases, runtime); err != nil {
		return nil, err
	}
	if len(v6Scopes) > 0 {
		buf.WriteString("enable-ra\n")
	}

	for _, res := range v4Scopes {
		spec, err := res.IPv4DHCPScopeSpec()
		if err != nil {
			return nil, err
		}
		ifname := aliases[spec.Interface]
		addrPrefix := staticIPv4[spec.Interface]
		if !addrPrefix.IsValid() {
			return nil, fmt.Errorf("%s needs an IPv4StaticAddress on %s to derive DHCP netmask/options", res.ID(), spec.Interface)
		}
		netmask, err := ipv4Netmask(addrPrefix.Bits())
		if err != nil {
			return nil, fmt.Errorf("%s has invalid IPv4 prefix length: %w", res.ID(), err)
		}
		leaseTime := defaultString(spec.LeaseTime, "12h")
		tag := sanitizeDnsmasqTag(res.Metadata.Name)

		buf.WriteString("\n")
		if spec.Authoritative {
			buf.WriteString("dhcp-authoritative\n")
		}
		buf.WriteString(fmt.Sprintf("dhcp-range=set:%s,%s,%s,%s,%s\n", tag, spec.RangeStart, spec.RangeEnd, netmask, leaseTime))

		switch defaultString(spec.RouterSource, "interfaceAddress") {
		case "interfaceAddress":
			buf.WriteString(fmt.Sprintf("dhcp-option=tag:%s,option:router,%s\n", tag, addrPrefix.Addr()))
		case "static":
			buf.WriteString(fmt.Sprintf("dhcp-option=tag:%s,option:router,%s\n", tag, spec.Router))
		case "none":
			buf.WriteString(fmt.Sprintf("dhcp-option=tag:%s,option:router\n", tag))
		}

		dnsServers, err := dnsmasqDNSServers(spec, aliases, staticIPv4, runtime)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", res.ID(), err)
		}
		if len(dnsServers) == 0 {
			buf.WriteString(fmt.Sprintf("dhcp-option=tag:%s,option:dns-server\n", tag))
		} else {
			buf.WriteString(fmt.Sprintf("dhcp-option=tag:%s,option:dns-server,%s\n", tag, strings.Join(dnsServers, ",")))
		}
		_ = ifname
	}
	for _, res := range v6Scopes {
		spec, err := res.IPv6DHCPScopeSpec()
		if err != nil {
			return nil, err
		}
		delegated := delegatedIPv6[spec.DelegatedAddress]
		leaseTime := defaultString(spec.LeaseTime, "12h")
		tag := sanitizeDnsmasqTag(res.Metadata.Name)
		mode := defaultString(spec.Mode, "stateless")
		raMode := "ra-stateless"
		if mode == "ra-only" {
			raMode = "ra-only"
		}
		buf.WriteString("\n")
		buf.WriteString(fmt.Sprintf("dhcp-range=set:%s,::,constructor:%s,%s,64,%s\n", tag, delegated.IfName, raMode, leaseTime))
		if !spec.DefaultRoute {
			buf.WriteString(fmt.Sprintf("ra-param=%s,0,0\n", delegated.IfName))
		}
		dnsServers, err := dnsmasqIPv6DNSServers(spec, delegated, selfPolicies[spec.SelfAddressPolicy], aliases, delegatedIPv6, runtime)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", res.ID(), err)
		}
		if len(dnsServers) == 0 {
			buf.WriteString(fmt.Sprintf("dhcp-option=tag:%s,option6:dns-server\n", tag))
		} else {
			buf.WriteString(fmt.Sprintf("dhcp-option=tag:%s,option6:dns-server,%s\n", tag, strings.Join(wrapIPv6Servers(dnsServers), ",")))
		}
	}

	return buf.Bytes(), nil
}

func writeDNSConditionalForwarders(buf *bytes.Buffer, router *api.Router, aliases map[string]string, runtime DnsmasqRuntime) error {
	var forwarders []api.Resource
	for _, res := range router.Spec.Resources {
		if res.Kind == "DNSConditionalForwarder" {
			forwarders = append(forwarders, res)
		}
	}
	if len(forwarders) == 0 {
		return nil
	}
	sort.Slice(forwarders, func(i, j int) bool { return forwarders[i].Metadata.Name < forwarders[j].Metadata.Name })
	buf.WriteString("\n")
	for _, res := range forwarders {
		spec, err := res.DNSConditionalForwarderSpec()
		if err != nil {
			return err
		}
		domain := strings.Trim(spec.Domain, ".")
		servers, err := conditionalForwarderServers(spec, aliases, runtime)
		if err != nil {
			return fmt.Errorf("%s: %w", res.ID(), err)
		}
		for _, server := range servers {
			buf.WriteString("server=/" + domain + "/" + server + "\n")
		}
	}
	return nil
}

func conditionalForwarderServers(spec api.DNSConditionalForwarderSpec, aliases map[string]string, runtime DnsmasqRuntime) ([]string, error) {
	switch defaultString(spec.UpstreamSource, "static") {
	case "static":
		return spec.UpstreamServers, nil
	case "dhcp4":
		ifname := aliases[spec.UpstreamInterface]
		servers := filterIPv4Strings(runtime.DHCPv4DNSServersByInterface[ifname])
		if len(servers) == 0 {
			return nil, fmt.Errorf("no DHCPv4 DNS servers observed on %s", ifname)
		}
		return servers, nil
	case "dhcp6":
		ifname := aliases[spec.UpstreamInterface]
		servers := filterGlobalIPv6Strings(runtime.DHCPv6DNSServersByInterface[ifname])
		if len(servers) == 0 {
			return nil, fmt.Errorf("no DHCPv6 DNS servers observed on %s", ifname)
		}
		return servers, nil
	default:
		return nil, fmt.Errorf("unsupported upstreamSource %q", spec.UpstreamSource)
	}
}

func wrapDNSServer(server string) string {
	addr, err := netip.ParseAddr(server)
	if err == nil && addr.Is6() {
		return "[" + addr.String() + "]"
	}
	return server
}

func DnsmasqServiceUnit(configPath string) []byte {
	return []byte(`[Unit]
Description=routerd managed dnsmasq DHCP service
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/sbin/dnsmasq --keep-in-foreground --conf-file=` + configPath + ` --pid-file=/run/routerd/dnsmasq.pid
Restart=on-failure
RestartSec=2s
RuntimeDirectory=routerd

[Install]
WantedBy=multi-user.target
`)
}

func dnsmasqDNSEnabled(v4Scopes []api.Resource, servers map[string]api.IPv4DHCPServerSpec, v6Scopes []api.Resource) (bool, error) {
	for _, res := range v4Scopes {
		spec, err := res.IPv4DHCPScopeSpec()
		if err != nil {
			return false, err
		}
		if servers[spec.Server].DNS.Enabled || defaultString(spec.DNSSource, "self") == "self" {
			return true, nil
		}
	}
	for _, res := range v6Scopes {
		spec, err := res.IPv6DHCPScopeSpec()
		if err != nil {
			return false, err
		}
		if defaultString(spec.DNSSource, "self") == "self" {
			return true, nil
		}
	}
	return false, nil
}

func writeDnsmasqDNSUpstreams(buf *bytes.Buffer, scopes []api.Resource, servers map[string]api.IPv4DHCPServerSpec, aliases map[string]string, runtime DnsmasqRuntime) error {
	for _, res := range scopes {
		spec, err := res.IPv4DHCPScopeSpec()
		if err != nil {
			return err
		}
		server := servers[spec.Server]
		dns := server.DNS
		if !dns.Enabled && defaultString(spec.DNSSource, "self") != "self" {
			continue
		}
		if dns.CacheSize != 0 {
			buf.WriteString(fmt.Sprintf("cache-size=%d\n", dns.CacheSize))
		}
		upstreamSource := defaultString(dns.UpstreamSource, "system")
		switch upstreamSource {
		case "dhcp4":
			ifname := aliases[dns.UpstreamInterface]
			servers := filterIPv4Strings(runtime.DHCPv4DNSServersByInterface[ifname])
			if len(servers) == 0 {
				return fmt.Errorf("no DHCPv4 DNS servers observed on %s", ifname)
			}
			buf.WriteString("no-resolv\n")
			for _, server := range servers {
				buf.WriteString("server=" + server + "\n")
			}
		case "static":
			buf.WriteString("no-resolv\n")
			for _, server := range dns.UpstreamServers {
				buf.WriteString("server=" + server + "\n")
			}
		case "none":
			buf.WriteString("no-resolv\n")
		case "system":
		default:
			return fmt.Errorf("unsupported dns.upstreamSource %q", dns.UpstreamSource)
		}
		return nil
	}
	return nil
}

type delegatedIPv6Address struct {
	Interface     string
	IfName        string
	AddressSuffix string
}

func dnsmasqInputs(router *api.Router) (map[string]string, map[string]netip.Prefix, map[string]delegatedIPv6Address, map[string]api.SelfAddressPolicySpec, error) {
	aliases := map[string]string{}
	staticIPv4 := map[string]netip.Prefix{}
	delegatedIPv6 := map[string]delegatedIPv6Address{}
	selfPolicies := map[string]api.SelfAddressPolicySpec{}
	for _, res := range router.Spec.Resources {
		switch res.Kind {
		case "Interface":
			spec, err := res.InterfaceSpec()
			if err != nil {
				return nil, nil, nil, nil, err
			}
			aliases[res.Metadata.Name] = spec.IfName
		}
	}
	for _, res := range router.Spec.Resources {
		switch res.Kind {
		case "IPv4StaticAddress":
			spec, err := res.IPv4StaticAddressSpec()
			if err != nil {
				return nil, nil, nil, nil, err
			}
			prefix, err := netip.ParsePrefix(spec.Address)
			if err != nil {
				return nil, nil, nil, nil, err
			}
			staticIPv4[spec.Interface] = prefix
		case "IPv6DelegatedAddress":
			spec, err := res.IPv6DelegatedAddressSpec()
			if err != nil {
				return nil, nil, nil, nil, err
			}
			delegatedIPv6[res.Metadata.Name] = delegatedIPv6Address{Interface: spec.Interface, IfName: aliases[spec.Interface], AddressSuffix: spec.AddressSuffix}
		case "SelfAddressPolicy":
			spec, err := res.SelfAddressPolicySpec()
			if err != nil {
				return nil, nil, nil, nil, err
			}
			selfPolicies[res.Metadata.Name] = spec
		}
	}
	return aliases, staticIPv4, delegatedIPv6, selfPolicies, nil
}

func dnsmasqExcludedInterfaces(aliases map[string]string, renderedScopes []string) []string {
	served := map[string]bool{}
	for _, ifname := range renderedScopes {
		if ifname != "" {
			served[ifname] = true
		}
	}
	var excluded []string
	for _, ifname := range aliases {
		if ifname != "" && !served[ifname] {
			excluded = append(excluded, ifname)
		}
	}
	return uniqueStrings(excluded)
}

func serverListensOn(listenInterfaces []string, iface string) bool {
	for _, candidate := range listenInterfaces {
		if candidate == iface {
			return true
		}
	}
	return false
}

func dnsmasqListenAddresses(v4Scopes, v6Scopes []api.Resource, aliases map[string]string, staticIPv4 map[string]netip.Prefix, delegatedIPv6 map[string]delegatedIPv6Address, selfPolicies map[string]api.SelfAddressPolicySpec, runtime DnsmasqRuntime) ([]string, error) {
	var addresses []string
	addresses = append(addresses, "127.0.0.1", "::1")
	for _, res := range v4Scopes {
		spec, err := res.IPv4DHCPScopeSpec()
		if err != nil {
			return nil, err
		}
		if defaultString(spec.DNSSource, "self") != "self" {
			continue
		}
		for _, server := range dnsmasqSelfIPv4ListenAddresses(spec, staticIPv4) {
			addresses = append(addresses, server)
		}
	}
	for _, res := range v6Scopes {
		spec, err := res.IPv6DHCPScopeSpec()
		if err != nil {
			return nil, err
		}
		if defaultString(spec.DNSSource, "self") != "self" {
			continue
		}
		delegated := delegatedIPv6[spec.DelegatedAddress]
		servers, err := dnsmasqIPv6DNSServers(spec, delegated, selfPolicies[spec.SelfAddressPolicy], aliases, delegatedIPv6, runtime)
		if err != nil {
			return nil, err
		}
		addresses = append(addresses, servers...)
	}
	return uniqueStrings(addresses), nil
}

func dnsmasqSelfIPv4ListenAddresses(spec api.IPv4DHCPScopeSpec, staticIPv4 map[string]netip.Prefix) []string {
	addrPrefix := staticIPv4[spec.Interface]
	if !addrPrefix.IsValid() {
		return nil
	}
	return []string{addrPrefix.Addr().String()}
}

func dnsmasqDNSServers(spec api.IPv4DHCPScopeSpec, aliases map[string]string, staticIPv4 map[string]netip.Prefix, runtime DnsmasqRuntime) ([]string, error) {
	switch defaultString(spec.DNSSource, "self") {
	case "dhcp4":
		ifname := aliases[spec.DNSInterface]
		servers := filterIPv4Strings(runtime.DHCPv4DNSServersByInterface[ifname])
		if len(servers) == 0 {
			return nil, fmt.Errorf("no DHCPv4 DNS servers observed on %s", ifname)
		}
		return servers, nil
	case "static":
		return spec.DNSServers, nil
	case "self":
		prefix := staticIPv4[spec.Interface]
		if !prefix.IsValid() {
			return nil, fmt.Errorf("self DNS needs an IPv4StaticAddress on %s", spec.Interface)
		}
		return []string{prefix.Addr().String()}, nil
	case "none":
		return nil, nil
	default:
		return nil, fmt.Errorf("unsupported dnsSource %q", spec.DNSSource)
	}
}

func dnsmasqIPv6DNSServers(spec api.IPv6DHCPScopeSpec, delegated delegatedIPv6Address, policy api.SelfAddressPolicySpec, aliases map[string]string, delegatedAddresses map[string]delegatedIPv6Address, runtime DnsmasqRuntime) ([]string, error) {
	switch defaultString(spec.DNSSource, "self") {
	case "self":
		return selectIPv6SelfAddress(defaultIPv6SelfAddressPolicy(spec, delegated, policy), delegatedAddresses, aliases, runtime)
	case "static":
		return spec.DNSServers, nil
	case "none":
		return nil, nil
	default:
		return nil, fmt.Errorf("unsupported dnsSource %q", spec.DNSSource)
	}
}

func defaultIPv6SelfAddressPolicy(spec api.IPv6DHCPScopeSpec, delegated delegatedIPv6Address, policy api.SelfAddressPolicySpec) api.SelfAddressPolicySpec {
	if spec.SelfAddressPolicy != "" {
		return policy
	}
	return api.SelfAddressPolicySpec{
		AddressFamily: "ipv6",
		Candidates: []api.SelfAddressPolicyCandidate{
			{Source: "delegatedAddress", DelegatedAddress: spec.DelegatedAddress, AddressSuffix: delegated.AddressSuffix},
			{Source: "interfaceAddress", Interface: delegated.Interface, MatchSuffix: delegated.AddressSuffix},
			{Source: "interfaceAddress", Interface: delegated.Interface, Ordinal: 1},
		},
	}
}

func selectIPv6SelfAddress(policy api.SelfAddressPolicySpec, delegatedAddresses map[string]delegatedIPv6Address, aliases map[string]string, runtime DnsmasqRuntime) ([]string, error) {
	var errs []string
	for _, candidate := range policy.Candidates {
		address, err := selectIPv6SelfAddressCandidate(candidate, delegatedAddresses, aliases, runtime)
		if err == nil {
			return []string{address}, nil
		}
		errs = append(errs, err.Error())
	}
	return nil, fmt.Errorf("no IPv6 self address selected: %s", strings.Join(errs, "; "))
}

func selectIPv6SelfAddressCandidate(candidate api.SelfAddressPolicyCandidate, delegatedAddresses map[string]delegatedIPv6Address, aliases map[string]string, runtime DnsmasqRuntime) (string, error) {
	switch candidate.Source {
	case "delegatedAddress":
		delegated := delegatedAddresses[candidate.DelegatedAddress]
		if delegated.IfName == "" {
			return "", fmt.Errorf("delegated address %q is not available", candidate.DelegatedAddress)
		}
		suffix := defaultString(candidate.AddressSuffix, delegated.AddressSuffix)
		address, err := deriveIPv6Address(runtime.IPv6PrefixesByInterface[delegated.IfName], suffix)
		if err != nil {
			return "", fmt.Errorf("derive %s%s: %w", candidate.DelegatedAddress, suffix, err)
		}
		return address, nil
	case "interfaceAddress":
		ifname := aliases[candidate.Interface]
		if ifname == "" {
			return "", fmt.Errorf("interface %q is not available", candidate.Interface)
		}
		servers := filterGlobalIPv6Strings(runtime.IPv6AddressesByInterface[ifname])
		if candidate.MatchSuffix != "" {
			for _, server := range servers {
				if ipv6AddressMatchesSuffix(server, candidate.MatchSuffix) {
					return server, nil
				}
			}
			return "", fmt.Errorf("no IPv6 address on %s matches suffix %s", ifname, candidate.MatchSuffix)
		}
		ordinal := candidate.Ordinal
		if ordinal == 0 {
			ordinal = 1
		}
		if ordinal < 1 || ordinal > len(servers) {
			return "", fmt.Errorf("IPv6 address ordinal %d is outside available address count %d on %s", ordinal, len(servers), ifname)
		}
		return servers[ordinal-1], nil
	case "static":
		return candidate.Address, nil
	default:
		return "", fmt.Errorf("unsupported self address source %q", candidate.Source)
	}
}

func ipv6AddressMatchesSuffix(address, suffix string) bool {
	addr, addrErr := netip.ParseAddr(address)
	suffixAddr, suffixErr := netip.ParseAddr(suffix)
	if addrErr != nil || suffixErr != nil || !addr.Is6() || !suffixAddr.Is6() {
		return false
	}
	addrBytes := addr.As16()
	suffixBytes := suffixAddr.As16()
	for i := range suffixBytes {
		if suffixBytes[i] != 0 && addrBytes[i] != suffixBytes[i] {
			return false
		}
	}
	return true
}

func ipv4Netmask(bits int) (string, error) {
	if bits < 0 || bits > 32 {
		return "", fmt.Errorf("%d", bits)
	}
	mask := uint32(0xffffffff) << uint(32-bits)
	if bits == 0 {
		mask = 0
	}
	return fmt.Sprintf("%d.%d.%d.%d", byte(mask>>24), byte(mask>>16), byte(mask>>8), byte(mask)), nil
}

func filterGlobalIPv6Strings(values []string) []string {
	var out []string
	for _, value := range values {
		addr, err := netip.ParseAddr(value)
		if err == nil && addr.Is6() && !addr.IsLinkLocalUnicast() {
			out = append(out, addr.String())
		}
	}
	return uniqueStrings(out)
}

func deriveIPv6Address(prefixes []string, suffix string) (string, error) {
	suffixAddr, err := netip.ParseAddr(suffix)
	if err != nil || !suffixAddr.Is6() {
		return "", fmt.Errorf("invalid suffix %q", suffix)
	}
	suffixBytes := suffixAddr.As16()
	for _, value := range prefixes {
		prefix, err := netip.ParsePrefix(value)
		if err != nil || !prefix.Addr().Is6() {
			continue
		}
		addrBytes := prefix.Masked().Addr().As16()
		for i := range addrBytes {
			addrBytes[i] |= suffixBytes[i]
		}
		return netip.AddrFrom16(addrBytes).String(), nil
	}
	return "", fmt.Errorf("no IPv6 prefix available")
}

func filterIPv4Strings(values []string) []string {
	var out []string
	for _, value := range values {
		addr, err := netip.ParseAddr(value)
		if err == nil && addr.Is4() {
			out = append(out, addr.String())
		}
	}
	return uniqueStrings(out)
}

func wrapIPv6Servers(values []string) []string {
	out := make([]string, 0, len(values))
	for _, value := range values {
		out = append(out, "["+value+"]")
	}
	return out
}

func uniqueStrings(values []string) []string {
	seen := map[string]bool{}
	var out []string
	for _, value := range values {
		if value == "" || seen[value] {
			continue
		}
		seen[value] = true
		out = append(out, value)
	}
	sort.Strings(out)
	return out
}

func sanitizeDnsmasqTag(value string) string {
	var b strings.Builder
	for _, r := range value {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_' || r == '-' {
			b.WriteRune(r)
		} else {
			b.WriteByte('-')
		}
	}
	if b.Len() == 0 {
		return "scope"
	}
	return b.String()
}
