// SPDX-License-Identifier: BSD-3-Clause

package render

import (
	"bytes"
	"errors"
	"fmt"
	"net/netip"
	"sort"
	"strings"

	"github.com/imksoo/routerd/pkg/api"
	"github.com/imksoo/routerd/pkg/resourcequery"
)

type DnsmasqRuntime struct {
	DHCPv4DNSServersByInterface map[string][]string
	DHCPv6DNSServersByInterface map[string][]string
	IPv6AddressesByInterface    map[string][]string
	IPv6PrefixesByInterface     map[string][]string
	StickyHosts                 []DHCPStickyHost
	RuntimeDir                  string
	LeaseFile                   string
}

type DHCPStickyHost struct {
	MACAddress string
	IPAddress  string
	Hostname   string
	Family     string
	LeaseTime  string
}

func DnsmasqConfig(router *api.Router, runtime DnsmasqRuntime) ([]byte, []string, error) {
	var warnings []string
	aliases, staticIPv4, delegatedIPv6, selfPolicies, err := dnsmasqInputs(router)
	if err != nil {
		return nil, nil, err
	}
	raMTUByScope, err := pathMTURAByScope(router)
	if err != nil {
		return nil, nil, err
	}

	var v4Pools []api.Resource
	var v6Delegated []api.Resource
	v4Servers := map[string]api.DHCPv4ServerSpec{}
	v6Servers := map[string]api.DHCPv6ServerSpec{}
	v4ReservationsByServer := map[string][]api.Resource{}
	for _, res := range router.Spec.Resources {
		switch res.Kind {
		case "DHCPv4Server":
			spec, err := res.DHCPv4ServerSpec()
			if err != nil {
				return nil, warnings, err
			}
			v4Servers[res.Metadata.Name] = spec
		case "DHCPv6Server":
			spec, err := res.DHCPv6ServerSpec()
			if err != nil {
				return nil, warnings, err
			}
			v6Servers[res.Metadata.Name] = spec
		}
	}
	for _, res := range router.Spec.Resources {
		switch res.Kind {
		case "DHCPv4Server":
			spec, err := res.DHCPv4ServerSpec()
			if err != nil {
				return nil, warnings, err
			}
			if dnsmasqUsesScopeStyleDHCPv4(spec) && defaultString(spec.Server, "dnsmasq") == "dnsmasq" && defaultString(spec.Role, "server") != "transit" {
				v4Pools = append(v4Pools, res)
			}
		case "DHCPv4Reservation":
			spec, err := res.DHCPv4ReservationSpec()
			if err != nil {
				return nil, warnings, err
			}
			server := defaultString(spec.Server, spec.Scope)
			v4ReservationsByServer[server] = append(v4ReservationsByServer[server], res)
		case "DHCPv6Server":
			spec, err := res.DHCPv6ServerSpec()
			if err != nil {
				return nil, warnings, err
			}
			if strings.TrimSpace(spec.DelegatedAddress) != "" && defaultString(spec.Server, "dnsmasq") == "dnsmasq" && defaultString(spec.Role, "server") != "transit" {
				v6Delegated = append(v6Delegated, res)
			}
		}
	}
	hasDirect := hasDirectDnsmasqLANService(router)
	if len(v4Pools) == 0 && len(v6Delegated) == 0 && !hasDirect {
		return nil, nil, nil
	}
	sort.Slice(v4Pools, func(i, j int) bool { return v4Pools[i].Metadata.Name < v4Pools[j].Metadata.Name })
	sort.Slice(v6Delegated, func(i, j int) bool { return v6Delegated[i].Metadata.Name < v6Delegated[j].Metadata.Name })
	for server := range v4ReservationsByServer {
		sort.Slice(v4ReservationsByServer[server], func(i, j int) bool {
			return v4ReservationsByServer[server][i].Metadata.Name < v4ReservationsByServer[server][j].Metadata.Name
		})
	}
	v6Delegated, err = activeDnsmasqIPv6Scopes(v6Delegated, delegatedIPv6, runtime)
	if err != nil {
		return nil, warnings, err
	}

	var buf bytes.Buffer
	leaseFile := strings.TrimSpace(runtime.LeaseFile)
	if leaseFile == "" {
		leaseFile = "/var/lib/routerd/dnsmasq/dnsmasq.leases"
	}
	buf.WriteString("# Generated by routerd. Do not edit by hand.\n")
	buf.WriteString("dhcp-leasefile=" + leaseFile + "\n")
	if dnsmasqLogDHCPEnabled(v4Servers, v6Servers) {
		buf.WriteString("log-dhcp\n")
	}
	buf.WriteString("port=0\n")
	buf.WriteString("no-resolv\n")
	var renderedScopes []string
	for _, res := range v4Pools {
		spec, err := res.DHCPv4ServerSpec()
		if err != nil {
			return nil, warnings, err
		}
		if len(spec.ListenInterfaces) > 0 && !serverListensOn(spec.ListenInterfaces, spec.Interface) {
			return nil, warnings, fmt.Errorf("%s interface %q is not listed in spec.listenInterfaces", res.ID(), spec.Interface)
		}
		ifname := aliases[spec.Interface]
		if ifname == "" {
			return nil, warnings, fmt.Errorf("%s references interface with empty ifname", res.ID())
		}
		renderedScopes = append(renderedScopes, ifname)
	}
	for _, res := range v6Delegated {
		spec, err := res.DHCPv6ServerSpec()
		if err != nil {
			return nil, warnings, err
		}
		delegated := delegatedIPv6[spec.DelegatedAddress]
		if len(spec.ListenInterfaces) > 0 && !serverListensOn(spec.ListenInterfaces, delegated.Interface) {
			return nil, warnings, fmt.Errorf("%s delegatedAddress interface %q is not listed in spec.listenInterfaces", res.ID(), delegated.Interface)
		}
		if delegated.IfName == "" {
			return nil, warnings, fmt.Errorf("%s references delegated address with empty ifname", res.ID())
		}
		renderedScopes = append(renderedScopes, delegated.IfName)
	}
	renderedScopes = append(renderedScopes, directDnsmasqIfnames(router, aliases)...)
	buf.WriteString("bind-dynamic\n")
	for _, ifname := range uniqueStrings(renderedScopes) {
		buf.WriteString("interface=" + ifname + "\n")
	}
	for _, ifname := range dnsmasqExcludedInterfaces(aliases, renderedScopes) {
		buf.WriteString("except-interface=" + ifname + "\n")
	}
	if len(v6Delegated) > 0 {
		buf.WriteString("enable-ra\n")
	}
	if err := writeDirectDnsmasqLANService(&buf, router, aliases, staticIPv4, delegatedIPv6, runtime); err != nil {
		return nil, warnings, err
	}

	for _, res := range v4Pools {
		spec, err := res.DHCPv4ServerSpec()
		if err != nil {
			return nil, warnings, err
		}
		ifname := aliases[spec.Interface]
		addrPrefix := staticIPv4[spec.Interface]
		if !addrPrefix.IsValid() {
			return nil, warnings, fmt.Errorf("%s needs an IPv4StaticAddress on %s to derive DHCP netmask/options", res.ID(), spec.Interface)
		}
		netmask, err := ipv4Netmask(addrPrefix.Bits())
		if err != nil {
			return nil, warnings, fmt.Errorf("%s has invalid IPv4 prefix length: %w", res.ID(), err)
		}
		leaseTime := defaultString(dhcpv4LeaseTime(spec), "12h")
		tag := sanitizeDnsmasqTag(res.Metadata.Name)

		buf.WriteString("\n")
		if spec.Authoritative {
			buf.WriteString("dhcp-authoritative\n")
		}
		buf.WriteString(fmt.Sprintf("dhcp-range=set:%s,%s,%s,%s,%s\n", tag, dhcpv4PoolStart(spec), dhcpv4PoolEnd(spec), netmask, leaseTime))

		switch defaultString(spec.RouterSource, "interfaceAddress") {
		case "interfaceAddress":
			buf.WriteString(fmt.Sprintf("dhcp-option=tag:%s,option:router,%s\n", tag, addrPrefix.Addr()))
		case "static":
			buf.WriteString(fmt.Sprintf("dhcp-option=tag:%s,option:router,%s\n", tag, spec.Router))
		case "none":
			buf.WriteString(fmt.Sprintf("dhcp-option=tag:%s,option:router\n", tag))
		}

		dnsServers, err := dnsmasqDNSServers(spec, aliases, staticIPv4, runtime)
		if err != nil {
			if errors.Is(err, errObservedDataNotReady) {
				warnings = append(warnings, fmt.Sprintf("%s: %v; emitting empty DHCP dns-server option until observed", res.ID(), err))
				buf.WriteString(fmt.Sprintf("dhcp-option=tag:%s,option:dns-server\n", tag))
			} else {
				return nil, warnings, fmt.Errorf("%s: %w", res.ID(), err)
			}
		} else if len(dnsServers) == 0 {
			buf.WriteString(fmt.Sprintf("dhcp-option=tag:%s,option:dns-server\n", tag))
		} else {
			buf.WriteString(fmt.Sprintf("dhcp-option=tag:%s,option:dns-server,%s\n", tag, strings.Join(dnsServers, ",")))
		}
		for _, reservation := range v4ReservationsByServer[res.Metadata.Name] {
			reservationSpec, err := reservation.DHCPv4ReservationSpec()
			if err != nil {
				return nil, warnings, err
			}
			buf.WriteString("dhcp-host=" + dnsmasqHostReservation(reservationSpec, leaseTime) + "\n")
		}
		for _, host := range stickyHostsForIPv4Scope(runtime.StickyHosts, dhcpv4PoolStart(spec), dhcpv4PoolEnd(spec), leaseTime) {
			buf.WriteString("dhcp-host=" + dnsmasqStickyHost(host) + "\n")
		}
		_ = ifname
	}
	for _, res := range v6Delegated {
		spec, err := res.DHCPv6ServerSpec()
		if err != nil {
			return nil, warnings, err
		}
		delegated := delegatedIPv6[spec.DelegatedAddress]
		leaseTime := defaultString(spec.LeaseTime, "12h")
		tag := sanitizeDnsmasqTag(res.Metadata.Name)
		mode := defaultString(spec.Mode, "stateless")
		raMode := "ra-stateless"
		if mode == "ra-only" {
			raMode = "ra-only"
		}
		buf.WriteString("\n")
		buf.WriteString(fmt.Sprintf("dhcp-range=set:%s,::,constructor:%s,%s,64,%s\n", tag, delegated.IfName, raMode, leaseTime))
		raMTU := raMTUByScope[res.Metadata.Name]
		switch {
		case raMTU != 0 && !spec.DefaultRoute:
			buf.WriteString(fmt.Sprintf("ra-param=%s,%d\n", delegated.IfName, raMTU))
			buf.WriteString(fmt.Sprintf("ra-param=%s,0,0\n", delegated.IfName))
		case raMTU != 0:
			buf.WriteString(fmt.Sprintf("ra-param=%s,%d\n", delegated.IfName, raMTU))
		case !spec.DefaultRoute:
			buf.WriteString(fmt.Sprintf("ra-param=%s,0,0\n", delegated.IfName))
		}
		dnsServers, err := dnsmasqIPv6DNSServers(spec, delegated, selfPolicies[spec.SelfAddressPolicy], aliases, delegatedIPv6, runtime)
		if err != nil {
			return nil, warnings, fmt.Errorf("%s: %w", res.ID(), err)
		}
		if len(dnsServers) == 0 {
			buf.WriteString(fmt.Sprintf("dhcp-option=tag:%s,option6:dns-server\n", tag))
		} else {
			buf.WriteString(fmt.Sprintf("dhcp-option=tag:%s,option6:dns-server,%s\n", tag, strings.Join(wrapIPv6Servers(dnsServers), ",")))
		}
		for _, host := range stickyHostsForFamily(runtime.StickyHosts, "ipv6", leaseTime) {
			buf.WriteString("dhcp-host=" + dnsmasqStickyHost(host) + "\n")
		}
	}

	return buf.Bytes(), warnings, nil
}

func dnsmasqLogDHCPEnabled(v4Servers map[string]api.DHCPv4ServerSpec, v6Servers map[string]api.DHCPv6ServerSpec) bool {
	for _, spec := range v4Servers {
		if defaultString(spec.Server, "dnsmasq") == "dnsmasq" && spec.LogDHCP {
			return true
		}
	}
	for _, spec := range v6Servers {
		if defaultString(spec.Server, "dnsmasq") == "dnsmasq" && spec.LogDHCP {
			return true
		}
	}
	return false
}

func dnsmasqUsesScopeStyleDHCPv4(spec api.DHCPv4ServerSpec) bool {
	return strings.TrimSpace(spec.RouterSource) != "" ||
		strings.TrimSpace(spec.Router) != "" ||
		strings.TrimSpace(spec.DNSSource) != "" ||
		strings.TrimSpace(spec.DNSInterface) != "" ||
		strings.TrimSpace(spec.RangeStart) != "" ||
		strings.TrimSpace(spec.RangeEnd) != "" ||
		spec.Authoritative
}

func dhcpv4PoolStart(spec api.DHCPv4ServerSpec) string {
	return defaultString(spec.AddressPool.Start, spec.RangeStart)
}

func dhcpv4PoolEnd(spec api.DHCPv4ServerSpec) string {
	return defaultString(spec.AddressPool.End, spec.RangeEnd)
}

func dhcpv4LeaseTime(spec api.DHCPv4ServerSpec) string {
	return defaultString(spec.AddressPool.LeaseTime, spec.LeaseTime)
}

func hasDirectDnsmasqLANService(router *api.Router) bool {
	for _, res := range router.Spec.Resources {
		switch res.Kind {
		case "DHCPv4Server":
			spec, err := res.DHCPv4ServerSpec()
			if err == nil && spec.Interface != "" && !dnsmasqUsesScopeStyleDHCPv4(spec) {
				return true
			}
		case "DHCPv6Server":
			spec, err := res.DHCPv6ServerSpec()
			if err == nil && spec.Interface != "" {
				return true
			}
		case "IPv6RouterAdvertisement", "DHCPv4Relay":
			return true
		}
	}
	return false
}

func directDnsmasqIfnames(router *api.Router, aliases map[string]string) []string {
	var ifnames []string
	for _, res := range router.Spec.Resources {
		switch res.Kind {
		case "DHCPv4Server":
			spec, err := res.DHCPv4ServerSpec()
			if err == nil && spec.Interface != "" && !dnsmasqUsesScopeStyleDHCPv4(spec) && aliases[spec.Interface] != "" {
				ifnames = append(ifnames, aliases[spec.Interface])
			}
		case "DHCPv6Server", "IPv6RouterAdvertisement":
			var iface string
			if res.Kind == "DHCPv6Server" {
				spec, err := res.DHCPv6ServerSpec()
				if err == nil && spec.Interface != "" {
					iface = spec.Interface
				}
			} else {
				spec, err := res.IPv6RouterAdvertisementSpec()
				if err == nil {
					iface = spec.Interface
				}
			}
			if aliases[iface] != "" {
				ifnames = append(ifnames, aliases[iface])
			}
		case "DHCPv4Relay":
			spec, err := res.DHCPv4RelaySpec()
			if err == nil {
				for _, iface := range spec.Interfaces {
					if aliases[iface] != "" {
						ifnames = append(ifnames, aliases[iface])
					}
				}
			}
		}
	}
	return uniqueStrings(ifnames)
}

func writeDirectDnsmasqLANService(buf *bytes.Buffer, router *api.Router, aliases map[string]string, staticIPv4 map[string]netip.Prefix, delegatedIPv6 map[string]delegatedIPv6Address, runtime DnsmasqRuntime) error {
	raMTUByScope, err := pathMTURAByScope(router)
	if err != nil {
		return err
	}
	for _, res := range router.Spec.Resources {
		if res.Kind != "DHCPv4Server" {
			continue
		}
		spec, err := res.DHCPv4ServerSpec()
		if err != nil || spec.Interface == "" || dnsmasqUsesScopeStyleDHCPv4(spec) {
			continue
		}
		ifname := aliases[spec.Interface]
		if ifname == "" {
			continue
		}
		tag := sanitizeDnsmasqTag(res.Metadata.Name)
		buf.WriteString("\n")
		buf.WriteString("interface=" + ifname + "\n")
		leaseTime := defaultString(dhcpv4LeaseTime(spec), "12h")
		buf.WriteString(fmt.Sprintf("dhcp-range=set:%s,%s,%s,%s\n", tag, dhcpv4PoolStart(spec), dhcpv4PoolEnd(spec), leaseTime))
		gateway := strings.TrimSpace(spec.Gateway)
		if strings.TrimSpace(spec.GatewayFrom.Resource) != "" {
			resolved, err := renderAddressFromResource(router, spec.GatewayFrom)
			if err != nil {
				return err
			}
			gateway = resolved
		}
		if gateway != "" {
			buf.WriteString(fmt.Sprintf("dhcp-option=tag:%s,option:router,%s\n", tag, gateway))
		}
		dnsServers, err := dnsmasqExpandIPv4Servers(router, append([]string(nil), spec.DNSServers...), spec.DNSServerFrom, aliases, staticIPv4, delegatedIPv6, runtime)
		if err != nil {
			return err
		}
		if len(dnsServers) > 0 {
			buf.WriteString(fmt.Sprintf("dhcp-option=tag:%s,option:dns-server,%s\n", tag, strings.Join(dnsServers, ",")))
		}
		ntpServers, err := dnsmasqExpandIPv4Servers(router, append([]string(nil), spec.NTPServers...), spec.NTPServerFrom, aliases, staticIPv4, delegatedIPv6, runtime)
		if err != nil {
			return err
		}
		if len(ntpServers) > 0 {
			buf.WriteString(fmt.Sprintf("dhcp-option=tag:%s,option:ntp-server,%s\n", tag, strings.Join(ntpServers, ",")))
		}
		domains := dnsmasqExpandDomainValues(router, []string{spec.Domain}, []api.StatusValueSourceSpec{spec.DomainFrom})
		if len(domains) > 0 {
			buf.WriteString(fmt.Sprintf("dhcp-option=tag:%s,option:domain-name,%s\n", tag, domains[0]))
			if !dnsmasqHasDHCPv4Option(spec.Options, "domain-search", 119) {
				buf.WriteString(fmt.Sprintf("dhcp-option=tag:%s,option:domain-search,%s\n", tag, domains[0]))
			}
		}
		for _, option := range spec.Options {
			buf.WriteString("dhcp-option=tag:" + tag + "," + dnsmasqDHCPv4Option(option) + "\n")
		}
		for _, reservation := range router.Spec.Resources {
			if reservation.Kind != "DHCPv4Reservation" {
				continue
			}
			reservationSpec, err := reservation.DHCPv4ReservationSpec()
			if err != nil || reservationSpec.Scope != "" || (reservationSpec.Server != "" && reservationSpec.Server != res.Metadata.Name) {
				continue
			}
			reservationTag := sanitizeDnsmasqTag(reservation.Metadata.Name)
			buf.WriteString("dhcp-host=" + dnsmasqIPv4Reservation(reservationSpec, reservationTag) + "\n")
			for _, option := range reservationSpec.Options {
				buf.WriteString("dhcp-option=tag:" + reservationTag + "," + dnsmasqDHCPv4Option(option) + "\n")
			}
		}
		for _, host := range stickyHostsForIPv4Scope(runtime.StickyHosts, dhcpv4PoolStart(spec), dhcpv4PoolEnd(spec), leaseTime) {
			buf.WriteString("dhcp-host=" + dnsmasqStickyHost(host) + "\n")
		}
	}
	for _, res := range router.Spec.Resources {
		if res.Kind != "DHCPv6Server" {
			continue
		}
		spec, err := res.DHCPv6ServerSpec()
		if err != nil || spec.Interface == "" || strings.TrimSpace(spec.DelegatedAddress) != "" {
			continue
		}
		ifname := defaultString(aliases[spec.Interface], spec.Interface)
		tag := sanitizeDnsmasqTag(res.Metadata.Name)
		buf.WriteString("\n")
		buf.WriteString("interface=" + ifname + "\n")
		buf.WriteString("enable-ra\n")
		leaseTime := defaultString(defaultString(spec.AddressPool.LeaseTime, spec.LeaseTime), "12h")
		switch defaultString(spec.Mode, "stateless") {
		case "stateful":
			buf.WriteString(fmt.Sprintf("dhcp-range=set:%s,%s,%s,constructor:%s,64,%s\n", tag, spec.AddressPool.Start, spec.AddressPool.End, ifname, leaseTime))
		case "both":
			buf.WriteString(fmt.Sprintf("dhcp-range=set:%s,%s,%s,constructor:%s,slaac,64,%s\n", tag, spec.AddressPool.Start, spec.AddressPool.End, ifname, leaseTime))
		default:
			buf.WriteString(fmt.Sprintf("dhcp-range=set:%s,::,constructor:%s,ra-stateless,64,%s\n", tag, ifname, leaseTime))
		}
		dnsServers, err := dnsmasqExpandIPv6Servers(router, append([]string(nil), spec.DNSServers...), spec.DNSServerFrom, aliases, delegatedIPv6, runtime)
		if err != nil {
			return err
		}
		for _, server := range dnsServers {
			buf.WriteString(fmt.Sprintf("dhcp-option=tag:%s,option6:dns-server,[%s]\n", tag, strings.Trim(server, "[]")))
		}
		searchDomains := dnsmasqExpandDomainValues(router, spec.DomainSearch, spec.DomainSearchFrom)
		if len(searchDomains) > 0 {
			buf.WriteString(fmt.Sprintf("dhcp-option=tag:%s,option6:domain-search,%s\n", tag, strings.Join(searchDomains, ",")))
		}
		sntpServers, err := dnsmasqExpandIPv6Servers(router, append([]string(nil), spec.SNTPServers...), spec.SNTPServerFrom, aliases, delegatedIPv6, runtime)
		if err != nil {
			return err
		}
		for _, server := range sntpServers {
			buf.WriteString(fmt.Sprintf("dhcp-option=tag:%s,option6:sntp-server,[%s]\n", tag, strings.Trim(server, "[]")))
		}
		for _, host := range stickyHostsForFamily(runtime.StickyHosts, "ipv6", leaseTime) {
			buf.WriteString("dhcp-host=" + dnsmasqStickyHost(host) + "\n")
		}
	}
	for _, res := range router.Spec.Resources {
		if res.Kind != "IPv6RouterAdvertisement" {
			continue
		}
		spec, err := res.IPv6RouterAdvertisementSpec()
		if err != nil {
			continue
		}
		ifname := aliases[spec.Interface]
		if ifname == "" {
			ifname = spec.Interface
		}
		buf.WriteString("interface=" + ifname + "\n")
		buf.WriteString("enable-ra\n")
		var params []string
		mtu := firstNonZero(raMTUByScope[res.Metadata.Name], spec.MTU)
		if mtu != 0 {
			params = append(params, fmt.Sprintf("mtu:%d", mtu))
		}
		switch spec.PRFPreference {
		case "high", "low":
			params = append(params, spec.PRFPreference)
		}
		if spec.ValidLifetime != "" {
			params = append(params, "0", spec.ValidLifetime)
		} else if mtu != 0 && (spec.PRFPreference == "high" || spec.PRFPreference == "low") {
			params = append(params, "0")
		}
		if len(params) > 0 {
			buf.WriteString(fmt.Sprintf("ra-param=%s,%s\n", ifname, strings.Join(params, ",")))
		}
		rdnss, err := dnsmasqExpandIPv6Servers(router, append([]string(nil), spec.RDNSS...), spec.RDNSSFrom, aliases, delegatedIPv6, runtime)
		if err != nil {
			return err
		}
		for _, server := range rdnss {
			buf.WriteString(fmt.Sprintf("dhcp-option=option6:dns-server,[%s]\n", strings.Trim(server, "[]")))
		}
		dnssl := dnsmasqExpandDomainValues(router, spec.DNSSL, spec.DNSSLFrom)
		if len(dnssl) > 0 {
			buf.WriteString("dhcp-option=option6:domain-search," + strings.Join(dnssl, ",") + "\n")
		}
	}
	for _, res := range router.Spec.Resources {
		if res.Kind == "DHCPv4Relay" {
			spec, err := res.DHCPv4RelaySpec()
			if err == nil {
				for _, iface := range spec.Interfaces {
					if ifname := aliases[iface]; ifname != "" {
						buf.WriteString(fmt.Sprintf("dhcp-relay=0.0.0.0,%s,%s\n", spec.Upstream, ifname))
					}
				}
			}
		}
	}
	return nil
}

func dnsmasqExpandDomainValues(router *api.Router, base []string, sources []api.StatusValueSourceSpec) []string {
	var out []string
	for _, value := range base {
		value = strings.TrimSpace(value)
		if value != "" {
			out = append(out, value)
		}
	}
	for _, source := range sources {
		if strings.TrimSpace(source.Resource) == "" {
			continue
		}
		out = append(out, resourcequery.ValuesFromRouter(router, source)...)
	}
	return uniqueStrings(out)
}

func dnsmasqHasDHCPv4Option(options []api.DHCPv4OptionSpec, name string, code int) bool {
	for _, option := range options {
		if option.Code == code || strings.EqualFold(strings.TrimSpace(option.Name), name) {
			return true
		}
	}
	return false
}

func dnsmasqExpandIPv4Servers(router *api.Router, base []string, sources []api.StatusValueSourceSpec, aliases map[string]string, staticIPv4 map[string]netip.Prefix, delegatedIPv6 map[string]delegatedIPv6Address, runtime DnsmasqRuntime) ([]string, error) {
	values, err := dnsmasqExpandStatusSources(router, sources, aliases, staticIPv4, delegatedIPv6, runtime)
	if err != nil {
		return nil, err
	}
	return filterIPv4Strings(append(base, values...)), nil
}

func dnsmasqExpandIPv6Servers(router *api.Router, base []string, sources []api.StatusValueSourceSpec, aliases map[string]string, delegatedIPv6 map[string]delegatedIPv6Address, runtime DnsmasqRuntime) ([]string, error) {
	values, err := dnsmasqExpandStatusSources(router, sources, aliases, nil, delegatedIPv6, runtime)
	if err != nil {
		return nil, err
	}
	return filterGlobalIPv6Strings(append(base, values...)), nil
}

func dnsmasqExpandStatusSources(router *api.Router, sources []api.StatusValueSourceSpec, aliases map[string]string, staticIPv4 map[string]netip.Prefix, delegatedIPv6 map[string]delegatedIPv6Address, runtime DnsmasqRuntime) ([]string, error) {
	var out []string
	for _, source := range sources {
		values, err := dnsmasqResolveStatusSource(router, source, aliases, staticIPv4, delegatedIPv6, runtime)
		if err != nil {
			if source.Optional {
				continue
			}
			return nil, err
		}
		out = append(out, values...)
	}
	return uniqueStrings(out), nil
}

func dnsmasqResolveStatusSource(router *api.Router, source api.StatusValueSourceSpec, aliases map[string]string, staticIPv4 map[string]netip.Prefix, delegatedIPv6 map[string]delegatedIPv6Address, runtime DnsmasqRuntime) ([]string, error) {
	kind, name, ok := strings.Cut(source.Resource, "/")
	if !ok {
		return nil, fmt.Errorf("unsupported status source %q", source.Resource)
	}
	switch kind {
	case "VirtualAddress":
		switch defaultString(source.Field, "address") {
		case "address", "ipv4", "ipv4Address", "ipv6", "ipv6Address":
			address, err := renderAddressFromResource(router, source)
			if err != nil {
				return nil, err
			}
			if address == "" {
				return nil, nil
			}
			return []string{address}, nil
		default:
			return nil, fmt.Errorf("unsupported VirtualAddress field %q", source.Field)
		}
	case "IPv4StaticAddress":
		prefix := staticIPv4[name]
		if !prefix.IsValid() {
			return nil, fmt.Errorf("IPv4StaticAddress/%s is not available", name)
		}
		switch defaultString(source.Field, "address") {
		case "address", "ipv4", "ipv4Address":
			return []string{prefix.Addr().String()}, nil
		default:
			return nil, fmt.Errorf("unsupported IPv4StaticAddress field %q", source.Field)
		}
	case "IPv6DelegatedAddress":
		delegated := delegatedIPv6[name]
		if delegated.IfName == "" {
			return nil, fmt.Errorf("IPv6DelegatedAddress/%s is not available", name)
		}
		switch defaultString(source.Field, "address") {
		case "address", "ipv6", "ipv6Address":
			address, err := deriveIPv6Address(runtime.IPv6PrefixesByInterface[delegated.IfName], delegated.AddressSuffix)
			if err == nil {
				return []string{address}, nil
			}
			for _, candidate := range filterGlobalIPv6Strings(runtime.IPv6AddressesByInterface[delegated.IfName]) {
				if ipv6AddressMatchesSuffix(candidate, delegated.AddressSuffix) {
					return []string{candidate}, nil
				}
			}
			return nil, fmt.Errorf("derive IPv6DelegatedAddress/%s: %w", name, err)
		default:
			return nil, fmt.Errorf("unsupported IPv6DelegatedAddress field %q", source.Field)
		}
	case "Interface":
		ifname := aliases[name]
		if ifname == "" {
			return nil, fmt.Errorf("Interface/%s is not available", name)
		}
		switch defaultString(source.Field, "ipv4Addresses") {
		case "ipv4Addresses":
			return filterIPv4Strings(runtime.DHCPv4DNSServersByInterface[ifname]), nil
		case "ipv6Addresses":
			return filterGlobalIPv6Strings(runtime.IPv6AddressesByInterface[ifname]), nil
		default:
			return nil, fmt.Errorf("unsupported Interface field %q", source.Field)
		}
	case "DHCPv6Information":
		switch defaultString(source.Field, "dnsServers") {
		case "dnsServers":
			var values []string
			for _, servers := range runtime.DHCPv6DNSServersByInterface {
				values = append(values, servers...)
			}
			return uniqueStrings(filterGlobalIPv6Strings(values)), nil
		case "sntpServers", "domainSearch", "aftrName":
			return nil, nil
		default:
			return nil, fmt.Errorf("unsupported DHCPv6Information field %q", source.Field)
		}
	default:
		return nil, fmt.Errorf("unsupported status source kind %q", kind)
	}
}

var errObservedDataNotReady = errors.New("observed runtime data not yet available")

func DnsmasqServiceUnit(configPath, dnsmasqPath string) []byte {
	return DnsmasqServiceUnitWithPID(configPath, "/run/routerd/dnsmasq.pid", dnsmasqPath)
}

func DnsmasqServiceUnitWithPID(configPath, pidFile, dnsmasqPath string) []byte {
	return []byte(`[Unit]
Description=routerd managed dnsmasq DHCP service
After=network-online.target
Wants=network-online.target
ConditionPathExists=` + configPath + `

[Service]
Type=simple
ExecStart=` + dnsmasqPath + ` --keep-in-foreground --conf-file=` + configPath + ` --pid-file=` + pidFile + `
Restart=on-failure
RestartSec=2s

[Install]
WantedBy=multi-user.target
`)
}

func DnsmasqRCScript(configPath, runtimeDir, leaseDir, dnsmasqPath string) []byte {
	if runtimeDir == "" {
		runtimeDir = "/var/run/routerd"
	}
	if leaseDir == "" {
		leaseDir = "/var/db/routerd/dnsmasq"
	}
	if dnsmasqPath == "" {
		dnsmasqPath = "/usr/local/sbin/dnsmasq"
	}
	return []byte(`#!/bin/sh

# PROVIDE: routerd_dnsmasq
# REQUIRE: NETWORKING mpd5
# KEYWORD: shutdown

. /etc/rc.subr

name="routerd_dnsmasq"
rcvar="routerd_dnsmasq_enable"
command="` + dnsmasqPath + `"
pidfile="` + strings.TrimRight(runtimeDir, "/") + `/dnsmasq.pid"
command_args="--conf-file=` + configPath + ` --pid-file=${pidfile}"
start_precmd="${name}_prestart"

routerd_dnsmasq_prestart()
{
	mkdir -p "` + strings.TrimRight(runtimeDir, "/") + `"
	mkdir -p "` + strings.TrimRight(leaseDir, "/") + `"
}

load_rc_config ${name}
: ${routerd_dnsmasq_enable:="NO"}

run_rc_command "$1"
`)
}

func activeDnsmasqIPv6Scopes(scopes []api.Resource, delegatedIPv6 map[string]delegatedIPv6Address, runtime DnsmasqRuntime) ([]api.Resource, error) {
	var active []api.Resource
	for _, res := range scopes {
		spec, err := res.DHCPv6ServerSpec()
		if err != nil {
			return nil, err
		}
		delegated := delegatedIPv6[spec.DelegatedAddress]
		if delegated.IfName == "" || hasUsableIPv6Prefix(runtime.IPv6PrefixesByInterface[delegated.IfName]) {
			active = append(active, res)
		}
	}
	return active, nil
}

type delegatedIPv6Address struct {
	Interface     string
	IfName        string
	AddressSuffix string
}

func dnsmasqInputs(router *api.Router) (map[string]string, map[string]netip.Prefix, map[string]delegatedIPv6Address, map[string]api.SelfAddressPolicySpec, error) {
	aliases := map[string]string{}
	staticIPv4 := map[string]netip.Prefix{}
	delegatedIPv6 := map[string]delegatedIPv6Address{}
	selfPolicies := map[string]api.SelfAddressPolicySpec{}
	for _, res := range router.Spec.Resources {
		switch res.Kind {
		case "Interface":
			spec, err := res.InterfaceSpec()
			if err != nil {
				return nil, nil, nil, nil, err
			}
			aliases[res.Metadata.Name] = spec.IfName
		}
	}
	for _, res := range router.Spec.Resources {
		switch res.Kind {
		case "IPv4StaticAddress":
			spec, err := res.IPv4StaticAddressSpec()
			if err != nil {
				return nil, nil, nil, nil, err
			}
			prefix, err := netip.ParsePrefix(spec.Address)
			if err != nil {
				return nil, nil, nil, nil, err
			}
			staticIPv4[spec.Interface] = prefix
			staticIPv4[res.Metadata.Name] = prefix
		case "IPv6DelegatedAddress":
			spec, err := res.IPv6DelegatedAddressSpec()
			if err != nil {
				return nil, nil, nil, nil, err
			}
			delegatedIPv6[res.Metadata.Name] = delegatedIPv6Address{Interface: spec.Interface, IfName: aliases[spec.Interface], AddressSuffix: spec.AddressSuffix}
		case "SelfAddressPolicy":
			spec, err := res.SelfAddressPolicySpec()
			if err != nil {
				return nil, nil, nil, nil, err
			}
			selfPolicies[res.Metadata.Name] = spec
		}
	}
	return aliases, staticIPv4, delegatedIPv6, selfPolicies, nil
}

func dnsmasqExcludedInterfaces(aliases map[string]string, renderedScopes []string) []string {
	served := map[string]bool{}
	for _, ifname := range renderedScopes {
		if ifname != "" {
			served[ifname] = true
		}
	}
	var excluded []string
	for _, ifname := range aliases {
		if ifname != "" && !served[ifname] {
			excluded = append(excluded, ifname)
		}
	}
	return uniqueStrings(excluded)
}

func serverListensOn(listenInterfaces []string, iface string) bool {
	for _, candidate := range listenInterfaces {
		if candidate == iface {
			return true
		}
	}
	return false
}

func dnsmasqDNSServers(spec api.DHCPv4ServerSpec, aliases map[string]string, staticIPv4 map[string]netip.Prefix, runtime DnsmasqRuntime) ([]string, error) {
	switch defaultString(spec.DNSSource, "self") {
	case "dhcpv4":
		ifname := aliases[spec.DNSInterface]
		servers := filterIPv4Strings(runtime.DHCPv4DNSServersByInterface[ifname])
		if len(servers) == 0 {
			return nil, fmt.Errorf("no DHCPv4 DNS servers observed on %s: %w", ifname, errObservedDataNotReady)
		}
		return servers, nil
	case "static":
		return spec.DNSServers, nil
	case "self":
		prefix := staticIPv4[spec.Interface]
		if !prefix.IsValid() {
			return nil, fmt.Errorf("self DNS needs an IPv4StaticAddress on %s", spec.Interface)
		}
		return []string{prefix.Addr().String()}, nil
	case "none":
		return nil, nil
	default:
		return nil, fmt.Errorf("unsupported dnsSource %q", spec.DNSSource)
	}
}

func dnsmasqHostReservation(spec api.DHCPv4ReservationSpec, scopeLeaseTime string) string {
	parts := []string{strings.ToLower(spec.MACAddress), spec.IPAddress}
	if spec.Hostname != "" {
		parts = append(parts, spec.Hostname)
	}
	if leaseTime := defaultString(spec.LeaseTime, scopeLeaseTime); leaseTime != "" {
		parts = append(parts, leaseTime)
	}
	return strings.Join(parts, ",")
}

func dnsmasqStickyHost(host DHCPStickyHost) string {
	parts := []string{strings.ToLower(strings.TrimSpace(host.MACAddress)), strings.TrimSpace(host.IPAddress)}
	if hostname := strings.TrimSpace(host.Hostname); hostname != "" {
		parts = append(parts, hostname)
	}
	if leaseTime := strings.TrimSpace(host.LeaseTime); leaseTime != "" {
		parts = append(parts, leaseTime)
	}
	return strings.Join(parts, ",")
}

func stickyHostsForFamily(hosts []DHCPStickyHost, family, leaseTime string) []DHCPStickyHost {
	var out []DHCPStickyHost
	for _, host := range hosts {
		if strings.TrimSpace(host.MACAddress) == "" || strings.TrimSpace(host.IPAddress) == "" {
			continue
		}
		hostFamily := strings.ToLower(strings.TrimSpace(host.Family))
		if hostFamily == "" {
			if strings.Contains(host.IPAddress, ":") {
				hostFamily = "ipv6"
			} else {
				hostFamily = "ipv4"
			}
		}
		if hostFamily != family {
			continue
		}
		if strings.TrimSpace(host.LeaseTime) == "" {
			host.LeaseTime = leaseTime
		}
		out = append(out, host)
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].IPAddress != out[j].IPAddress {
			return out[i].IPAddress < out[j].IPAddress
		}
		return out[i].MACAddress < out[j].MACAddress
	})
	return out
}

func stickyHostsForIPv4Scope(hosts []DHCPStickyHost, start, end, leaseTime string) []DHCPStickyHost {
	var out []DHCPStickyHost
	startAddr, startErr := netip.ParseAddr(strings.TrimSpace(start))
	endAddr, endErr := netip.ParseAddr(strings.TrimSpace(end))
	for _, host := range stickyHostsForFamily(hosts, "ipv4", leaseTime) {
		addr, err := netip.ParseAddr(strings.TrimSpace(host.IPAddress))
		if err != nil || !addr.Is4() {
			continue
		}
		if startErr == nil && endErr == nil && startAddr.Is4() && endAddr.Is4() && !addrInRange(addr, startAddr, endAddr) {
			continue
		}
		out = append(out, host)
	}
	return out
}

func addrInRange(addr, start, end netip.Addr) bool {
	a := addr.As4()
	s := start.As4()
	e := end.As4()
	for i := 0; i < len(a); i++ {
		if a[i] < s[i] {
			return false
		}
		if a[i] > s[i] {
			break
		}
	}
	for i := 0; i < len(a); i++ {
		if a[i] > e[i] {
			return false
		}
		if a[i] < e[i] {
			break
		}
	}
	return true
}

func dnsmasqIPv4Reservation(spec api.DHCPv4ReservationSpec, tag string) string {
	parts := []string{strings.ToLower(spec.MACAddress)}
	if tag != "" {
		parts = append(parts, "set:"+tag)
	}
	if spec.Hostname != "" {
		parts = append(parts, spec.Hostname)
	}
	parts = append(parts, spec.IPAddress)
	return strings.Join(parts, ",")
}

func dnsmasqDHCPv4Option(option api.DHCPv4OptionSpec) string {
	key := option.Name
	if key == "" {
		key = fmt.Sprintf("%d", option.Code)
	} else {
		key = "option:" + key
	}
	return key + "," + option.Value
}

func dnsmasqIPv6DNSServers(spec api.DHCPv6ServerSpec, delegated delegatedIPv6Address, policy api.SelfAddressPolicySpec, aliases map[string]string, delegatedAddresses map[string]delegatedIPv6Address, runtime DnsmasqRuntime) ([]string, error) {
	switch defaultString(spec.DNSSource, "self") {
	case "self":
		return selectIPv6SelfAddress(defaultIPv6SelfAddressPolicy(spec, delegated, policy), delegatedAddresses, aliases, runtime)
	case "static":
		return spec.DNSServers, nil
	case "none":
		return nil, nil
	default:
		return nil, fmt.Errorf("unsupported dnsSource %q", spec.DNSSource)
	}
}

func defaultIPv6SelfAddressPolicy(spec api.DHCPv6ServerSpec, delegated delegatedIPv6Address, policy api.SelfAddressPolicySpec) api.SelfAddressPolicySpec {
	if spec.SelfAddressPolicy != "" {
		return policy
	}
	return api.SelfAddressPolicySpec{
		AddressFamily: "ipv6",
		Candidates: []api.SelfAddressPolicyCandidate{
			{Source: "delegatedAddress", DelegatedAddress: spec.DelegatedAddress, AddressSuffix: delegated.AddressSuffix},
			{Source: "interfaceAddress", Interface: delegated.Interface, MatchSuffix: delegated.AddressSuffix},
			{Source: "interfaceAddress", Interface: delegated.Interface, Ordinal: 1},
		},
	}
}

func selectIPv6SelfAddress(policy api.SelfAddressPolicySpec, delegatedAddresses map[string]delegatedIPv6Address, aliases map[string]string, runtime DnsmasqRuntime) ([]string, error) {
	var errs []string
	for _, candidate := range policy.Candidates {
		address, err := selectIPv6SelfAddressCandidate(candidate, delegatedAddresses, aliases, runtime)
		if err == nil {
			return []string{address}, nil
		}
		errs = append(errs, err.Error())
	}
	return nil, fmt.Errorf("no IPv6 self address selected: %s", strings.Join(errs, "; "))
}

func selectIPv6SelfAddressCandidate(candidate api.SelfAddressPolicyCandidate, delegatedAddresses map[string]delegatedIPv6Address, aliases map[string]string, runtime DnsmasqRuntime) (string, error) {
	switch candidate.Source {
	case "delegatedAddress":
		delegated := delegatedAddresses[candidate.DelegatedAddress]
		if delegated.IfName == "" {
			return "", fmt.Errorf("delegated address %q is not available", candidate.DelegatedAddress)
		}
		suffix := defaultString(candidate.AddressSuffix, delegated.AddressSuffix)
		address, err := deriveIPv6Address(runtime.IPv6PrefixesByInterface[delegated.IfName], suffix)
		if err != nil {
			return "", fmt.Errorf("derive %s%s: %w", candidate.DelegatedAddress, suffix, err)
		}
		return address, nil
	case "interfaceAddress":
		ifname := aliases[candidate.Interface]
		if ifname == "" {
			return "", fmt.Errorf("interface %q is not available", candidate.Interface)
		}
		servers := filterGlobalIPv6Strings(runtime.IPv6AddressesByInterface[ifname])
		if candidate.MatchSuffix != "" {
			for _, server := range servers {
				if ipv6AddressMatchesSuffix(server, candidate.MatchSuffix) {
					return server, nil
				}
			}
			return "", fmt.Errorf("no IPv6 address on %s matches suffix %s", ifname, candidate.MatchSuffix)
		}
		ordinal := candidate.Ordinal
		if ordinal == 0 {
			ordinal = 1
		}
		if ordinal < 1 || ordinal > len(servers) {
			return "", fmt.Errorf("IPv6 address ordinal %d is outside available address count %d on %s", ordinal, len(servers), ifname)
		}
		return servers[ordinal-1], nil
	case "static":
		return candidate.Address, nil
	default:
		return "", fmt.Errorf("unsupported self address source %q", candidate.Source)
	}
}

func ipv6AddressMatchesSuffix(address, suffix string) bool {
	addr, addrErr := netip.ParseAddr(address)
	suffixAddr, suffixErr := netip.ParseAddr(suffix)
	if addrErr != nil || suffixErr != nil || !addr.Is6() || !suffixAddr.Is6() {
		return false
	}
	addrBytes := addr.As16()
	suffixBytes := suffixAddr.As16()
	for i := range suffixBytes {
		if suffixBytes[i] != 0 && addrBytes[i] != suffixBytes[i] {
			return false
		}
	}
	return true
}

func ipv4Netmask(bits int) (string, error) {
	if bits < 0 || bits > 32 {
		return "", fmt.Errorf("%d", bits)
	}
	mask := uint32(0xffffffff) << uint(32-bits)
	if bits == 0 {
		mask = 0
	}
	return fmt.Sprintf("%d.%d.%d.%d", byte(mask>>24), byte(mask>>16), byte(mask>>8), byte(mask)), nil
}

func filterGlobalIPv6Strings(values []string) []string {
	var out []string
	for _, value := range values {
		addr, err := netip.ParseAddr(value)
		if err == nil && addr.Is6() && !addr.IsLinkLocalUnicast() {
			out = append(out, addr.String())
		}
	}
	return uniqueStrings(out)
}

func deriveIPv6Address(prefixes []string, suffix string) (string, error) {
	suffixAddr, err := netip.ParseAddr(suffix)
	if err != nil || !suffixAddr.Is6() {
		return "", fmt.Errorf("invalid suffix %q", suffix)
	}
	suffixBytes := suffixAddr.As16()
	for _, value := range prefixes {
		prefix, err := netip.ParsePrefix(value)
		if err != nil || !prefix.Addr().Is6() || prefix.Addr().IsLinkLocalUnicast() {
			continue
		}
		addrBytes := prefix.Masked().Addr().As16()
		for i := range addrBytes {
			addrBytes[i] |= suffixBytes[i]
		}
		return netip.AddrFrom16(addrBytes).String(), nil
	}
	return "", fmt.Errorf("no IPv6 prefix available")
}

func hasUsableIPv6Prefix(prefixes []string) bool {
	for _, value := range prefixes {
		prefix, err := netip.ParsePrefix(value)
		if err == nil && prefix.Addr().Is6() && !prefix.Addr().IsLinkLocalUnicast() {
			return true
		}
	}
	return false
}

func filterIPv4Strings(values []string) []string {
	var out []string
	for _, value := range values {
		addr, err := netip.ParseAddr(value)
		if err == nil && addr.Is4() {
			out = append(out, addr.String())
		}
	}
	return uniqueStrings(out)
}

func wrapIPv6Servers(values []string) []string {
	out := make([]string, 0, len(values))
	for _, value := range values {
		out = append(out, "["+value+"]")
	}
	return out
}

func uniqueStrings(values []string) []string {
	seen := map[string]bool{}
	var out []string
	for _, value := range values {
		if value == "" || seen[value] {
			continue
		}
		seen[value] = true
		out = append(out, value)
	}
	sort.Strings(out)
	return out
}

func sanitizeDnsmasqTag(value string) string {
	var b strings.Builder
	for _, r := range value {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_' || r == '-' {
			b.WriteRune(r)
		} else {
			b.WriteByte('-')
		}
	}
	if b.Len() == 0 {
		return "scope"
	}
	return b.String()
}
