package render

import (
	"bytes"
	"fmt"
	"net/netip"
	"sort"
	"strconv"
	"strings"

	"routerd/pkg/api"
)

type FreeBSDConfig struct {
	RCConf     []byte
	DHCPClient []byte
	MPD5       []byte
	PF         []byte
	Warnings   []string
}

func FreeBSD(router *api.Router) (FreeBSDConfig, error) {
	return FreeBSDWithPPPoEPasswords(router, func(_ api.Resource, spec api.PPPoEInterfaceSpec) (string, error) {
		if spec.Password != "" {
			return spec.Password, nil
		}
		return "CHANGEME-read-" + spec.PasswordFile, nil
	})
}

func FreeBSDWithPPPoEPasswords(router *api.Router, passwordFor func(api.Resource, api.PPPoEInterfaceSpec) (string, error)) (FreeBSDConfig, error) {
	aliases := map[string]string{}
	managed := map[string]bool{}
	for _, res := range router.Spec.Resources {
		if res.Kind != "Interface" {
			continue
		}
		spec, err := res.InterfaceSpec()
		if err != nil {
			return FreeBSDConfig{}, err
		}
		aliases[res.Metadata.Name] = spec.IfName
		managed[res.Metadata.Name] = spec.Managed && spec.Owner != "external"
	}
	for _, res := range router.Spec.Resources {
		if res.Kind != "Bridge" {
			continue
		}
		spec, err := res.BridgeSpec()
		if err != nil {
			return FreeBSDConfig{}, err
		}
		aliases[res.Metadata.Name] = defaultString(spec.IfName, res.Metadata.Name)
		managed[res.Metadata.Name] = true
	}
	for _, res := range router.Spec.Resources {
		if res.Kind != "VXLANSegment" {
			continue
		}
		spec, err := res.VXLANSegmentSpec()
		if err != nil {
			return FreeBSDConfig{}, err
		}
		aliases[res.Metadata.Name] = defaultString(spec.IfName, res.Metadata.Name)
		managed[res.Metadata.Name] = true
	}

	var rc bytes.Buffer
	rc.WriteString("# Generated by routerd. Do not edit by hand.\n")
	rc.WriteString("gateway_enable=\"YES\"\n")
	rc.WriteString("ipv6_gateway_enable=\"YES\"\n")

	dhclientOptions := map[string]api.DHCPv4AddressSpec{}
	var staticV4Routes []freeBSDStaticRoute
	var staticV6Routes []freeBSDStaticRoute
	staticBridgeV4 := map[string][]string{}
	var pppoes []freeBSDPPPoE
	bridges, err := bridgeConfigs(router, aliases)
	if err != nil {
		return FreeBSDConfig{}, err
	}
	vxlans, err := vxlanConfigs(router, aliases)
	if err != nil {
		return FreeBSDConfig{}, err
	}
	var warnings []string
	for _, vxlan := range vxlans {
		if len(vxlan.Remotes) > 1 {
			warnings = append(warnings, fmt.Sprintf("VXLANSegment %s: FreeBSD vxlan(4) supports a single unicast remote; using %s as the seed and ignoring %v. Reach the other peers via a Linux relay or a multicast underlay.", vxlan.Name, vxlan.Remotes[0], vxlan.Remotes[1:]))
		}
	}
	for _, res := range router.Spec.Resources {
		switch res.Kind {
		case "DHCPv4Address":
			spec, err := res.DHCPv4AddressSpec()
			if err != nil {
				return FreeBSDConfig{}, err
			}
			if managed[spec.Interface] {
				rc.WriteString(fmt.Sprintf("ifconfig_%s=\"DHCP\"\n", aliases[spec.Interface]))
				if spec.UseRoutes != nil || spec.UseDNS != nil || spec.RouteMetric != 0 {
					dhclientOptions[aliases[spec.Interface]] = spec
				}
			}
		case "IPv6RAAddress":
			spec, err := res.IPv6RAAddressSpec()
			if err != nil {
				return FreeBSDConfig{}, err
			}
			if api.BoolDefault(spec.Managed, true) {
				rc.WriteString(fmt.Sprintf("ifconfig_%s_ipv6=\"inet6 accept_rtadv\"\n", aliases[spec.Interface]))
				rc.WriteString(fmt.Sprintf("rtsold_flags=\"%s\"\n", aliases[spec.Interface]))
				rc.WriteString("rtsold_enable=\"YES\"\n")
			}
		case "IPv4StaticAddress":
			spec, err := res.IPv4StaticAddressSpec()
			if err != nil {
				return FreeBSDConfig{}, err
			}
			if managed[spec.Interface] {
				address, err := freeBSDIPv4CIDR(spec.Address)
				if err != nil {
					return FreeBSDConfig{}, fmt.Errorf("%s: %w", res.ID(), err)
				}
				if resourceKind(router, spec.Interface) == "Bridge" {
					staticBridgeV4[aliases[spec.Interface]] = append(staticBridgeV4[aliases[spec.Interface]], address)
				} else {
					rc.WriteString(fmt.Sprintf("ifconfig_%s=\"inet %s\"\n", aliases[spec.Interface], address))
				}
			}
		case "IPv4StaticRoute":
			spec, err := res.IPv4StaticRouteSpec()
			if err != nil {
				return FreeBSDConfig{}, err
			}
			staticV4Routes = append(staticV4Routes, freeBSDStaticRoute{Name: res.Metadata.Name, IfName: aliases[spec.Interface], Destination: spec.Destination, Via: spec.Via})
		case "IPv6StaticRoute":
			spec, err := res.IPv6StaticRouteSpec()
			if err != nil {
				return FreeBSDConfig{}, err
			}
			staticV6Routes = append(staticV6Routes, freeBSDStaticRoute{Name: res.Metadata.Name, IfName: aliases[spec.Interface], Destination: spec.Destination, Via: spec.Via})
		case "PPPoEInterface":
			spec, err := res.PPPoEInterfaceSpec()
			if err != nil {
				return FreeBSDConfig{}, err
			}
			lowerIfName := aliases[spec.Interface]
			if lowerIfName == "" {
				return FreeBSDConfig{}, fmt.Errorf("%s references interface with empty ifname", res.ID())
			}
			password, err := passwordFor(res, spec)
			if err != nil {
				return FreeBSDConfig{}, err
			}
			pppoes = append(pppoes, freeBSDPPPoE{Name: res.Metadata.Name, IfName: defaultString(spec.IfName, "ppp-"+res.Metadata.Name), LowerIfName: lowerIfName, Password: password, Spec: spec})
		}
	}

	if hasManagedFreeBSDPPPoE(pppoes) {
		rc.WriteString("mpd_enable=\"YES\"\n")
		rc.WriteString("mpd_flags=\"-b\"\n")
	}
	pf, err := PF(router, nil)
	if err != nil {
		return FreeBSDConfig{}, err
	}
	if len(pf) > 0 {
		rc.WriteString("pf_enable=\"YES\"\n")
		rc.WriteString("pflog_enable=\"YES\"\n")
		warnings = append(warnings, "FreeBSD pf.conf was generated, but live pf apply is not wired yet. Install the generated pf.conf and validate with pfctl -nf before enabling.")
	}
	writeFreeBSDClonedInterfaces(&rc, bridges, vxlans)
	writeFreeBSDVXLANS(&rc, vxlans)
	writeFreeBSDBridges(&rc, bridges)
	writeFreeBSDBridgeAliases(&rc, staticBridgeV4)
	writeFreeBSDStaticRoutes(&rc, staticV4Routes, false)
	writeFreeBSDStaticRoutes(&rc, staticV6Routes, true)

	dhclient := freeBSDDHClient(dhclientOptions)
	mpd5, err := freeBSDMPD5(pppoes)
	if err != nil {
		return FreeBSDConfig{}, err
	}
	return FreeBSDConfig{RCConf: rc.Bytes(), DHCPClient: dhclient, MPD5: mpd5, PF: pf, Warnings: warnings}, nil
}

type freeBSDPPPoE struct {
	Name        string
	IfName      string
	LowerIfName string
	Password    string
	Spec        api.PPPoEInterfaceSpec
}

type freeBSDStaticRoute struct {
	Name        string
	IfName      string
	Destination string
	Via         string
}

func writeFreeBSDBridges(buf *bytes.Buffer, bridges []bridgeConfig) {
	if len(bridges) == 0 {
		return
	}
	for _, bridge := range bridges {
		var args []string
		for _, member := range bridge.Members {
			args = append(args, "addm "+member)
			if bridge.STP {
				args = append(args, "stp "+member)
			}
		}
		if bridge.MTU != 0 {
			args = append(args, fmt.Sprintf("mtu %d", bridge.MTU))
		}
		if bridge.MACAddress != "" {
			args = append(args, "ether "+bridge.MACAddress)
		}
		args = append(args, "up")
		buf.WriteString(fmt.Sprintf("ifconfig_%s=\"%s\"\n", bridge.IfName, strings.Join(args, " ")))
	}
}

func writeFreeBSDBridgeAliases(buf *bytes.Buffer, addresses map[string][]string) {
	var ifnames []string
	for ifname := range addresses {
		ifnames = append(ifnames, ifname)
	}
	sort.Strings(ifnames)
	for _, ifname := range ifnames {
		sort.Strings(addresses[ifname])
		for i, address := range addresses[ifname] {
			buf.WriteString(fmt.Sprintf("ifconfig_%s_alias%d=\"inet %s\"\n", ifname, i, address))
		}
	}
}

func writeFreeBSDVXLANS(buf *bytes.Buffer, vxlans []vxlanConfig) {
	if len(vxlans) == 0 {
		return
	}
	for _, vxlan := range vxlans {
		var args []string
		args = append(args, "vxlanid "+strconv.Itoa(vxlan.VNI))
		args = append(args, "vxlanlocal "+vxlan.LocalAddress)
		if vxlan.MulticastGroup != "" {
			args = append(args, "vxlangroup "+vxlan.MulticastGroup)
		} else if len(vxlan.Remotes) > 0 {
			args = append(args, "vxlanremote "+vxlan.Remotes[0])
		}
		if vxlan.UnderlayIfName != "" {
			args = append(args, "vxlandev "+vxlan.UnderlayIfName)
		}
		args = append(args, "vxlanport "+strconv.Itoa(vxlan.UDPPort))
		if vxlan.MTU != 0 {
			args = append(args, "mtu "+strconv.Itoa(vxlan.MTU))
		}
		args = append(args, "up")
		buf.WriteString(fmt.Sprintf("ifconfig_%s=\"%s\"\n", vxlan.IfName, strings.Join(args, " ")))
	}
}

func resourceKind(router *api.Router, name string) string {
	for _, res := range router.Spec.Resources {
		if res.Metadata.Name == name {
			return res.Kind
		}
	}
	return ""
}

func writeFreeBSDClonedInterfaces(buf *bytes.Buffer, bridges []bridgeConfig, vxlans []vxlanConfig) {
	var names []string
	for _, vxlan := range vxlans {
		names = append(names, vxlan.IfName)
	}
	for _, bridge := range bridges {
		names = append(names, bridge.IfName)
	}
	if len(names) > 0 {
		buf.WriteString("cloned_interfaces=\"" + strings.Join(names, " ") + "\"\n")
	}
}

func writeFreeBSDStaticRoutes(buf *bytes.Buffer, routes []freeBSDStaticRoute, ipv6 bool) {
	if len(routes) == 0 {
		return
	}
	sort.Slice(routes, func(i, j int) bool { return routes[i].Name < routes[j].Name })
	var names []string
	for _, route := range routes {
		names = append(names, freeBSDRouteLabel(route.Name))
	}
	if ipv6 {
		buf.WriteString("ipv6_static_routes=\"" + strings.Join(names, " ") + "\"\n")
	} else {
		buf.WriteString("static_routes=\"" + strings.Join(names, " ") + "\"\n")
	}
	for _, route := range routes {
		label := freeBSDRouteLabel(route.Name)
		via := route.Via
		if ipv6 && strings.HasPrefix(strings.ToLower(via), "fe80:") && route.IfName != "" && !strings.Contains(via, "%") {
			via += "%" + route.IfName
		}
		if ipv6 {
			buf.WriteString(fmt.Sprintf("ipv6_route_%s=\"%s %s\"\n", label, route.Destination, via))
		} else {
			buf.WriteString(fmt.Sprintf("route_%s=\"-net %s %s\"\n", label, route.Destination, via))
		}
	}
}

func freeBSDRouteLabel(name string) string {
	label := strings.Map(func(r rune) rune {
		switch {
		case r >= 'a' && r <= 'z':
			return r
		case r >= 'A' && r <= 'Z':
			return r
		case r >= '0' && r <= '9':
			return r
		case r == '_' || r == '-':
			return r
		default:
			return '_'
		}
	}, name)
	label = strings.ReplaceAll(label, "-", "_")
	if label == "" {
		return "route"
	}
	return label
}

func hasManagedFreeBSDPPPoE(pppoes []freeBSDPPPoE) bool {
	for _, pppoe := range pppoes {
		if pppoe.Spec.Managed {
			return true
		}
	}
	return false
}

func freeBSDMPD5(pppoes []freeBSDPPPoE) ([]byte, error) {
	if len(pppoes) == 0 {
		return nil, nil
	}
	sort.Slice(pppoes, func(i, j int) bool { return pppoes[i].Name < pppoes[j].Name })
	var buf bytes.Buffer
	buf.WriteString("# Generated by routerd. Do not edit by hand.\n")
	buf.WriteString("# This file uses FreeBSD mpd5 for PPPoE client sessions.\n\n")
	buf.WriteString("startup:\n\n")
	buf.WriteString("default:\n")
	managed := false
	for _, pppoe := range pppoes {
		if !pppoe.Spec.Managed {
			continue
		}
		managed = true
		buf.WriteString("  load " + freeBSDMPDLabel(pppoe.Name) + "\n")
	}
	if !managed {
		buf.WriteString("  # No managed PPPoE sessions are enabled.\n")
	}
	buf.WriteString("\n")

	for _, pppoe := range pppoes {
		spec := pppoe.Spec
		mtu := spec.MTU
		if mtu == 0 {
			mtu = 1492
		}
		mru := spec.MRU
		if mru == 0 {
			mru = 1492
		}
		lcpInterval := spec.LCPInterval
		if lcpInterval == 0 {
			lcpInterval = 20
		}
		lcpFailure := spec.LCPFailure
		if lcpFailure == 0 {
			lcpFailure = 3
		}
		label := freeBSDMPDLabel(pppoe.Name)
		bundle := freeBSDMPDName("B", pppoe.Name)
		link := freeBSDMPDName("L", pppoe.Name)

		buf.WriteString(label + ":\n")
		buf.WriteString("  create bundle static " + bundle + "\n")
		buf.WriteString("  set iface name " + pppoe.IfName + "\n")
		if spec.DefaultRoute {
			buf.WriteString("  set iface route default\n")
		}
		buf.WriteString("  set iface enable tcpmssfix\n")
		buf.WriteString("  set ipcp ranges 0.0.0.0/0 0.0.0.0/0\n")
		buf.WriteString("  create link static " + link + " pppoe\n")
		buf.WriteString("  set link action bundle " + bundle + "\n")
		buf.WriteString("  set auth authname " + strconv.Quote(spec.Username) + "\n")
		buf.WriteString("  set auth password " + strconv.Quote(pppoe.Password) + "\n")
		buf.WriteString("  set link max-redial 0\n")
		buf.WriteString(fmt.Sprintf("  set link mtu %d\n", mtu))
		buf.WriteString(fmt.Sprintf("  set link mru %d\n", mru))
		buf.WriteString(fmt.Sprintf("  set link keep-alive %d %d\n", lcpInterval, lcpInterval*lcpFailure))
		buf.WriteString("  set pppoe iface " + pppoe.LowerIfName + "\n")
		if spec.ServiceName != "" {
			buf.WriteString("  set pppoe service " + strconv.Quote(spec.ServiceName) + "\n")
		}
		if spec.ACName != "" {
			buf.WriteString("  set pppoe acname " + strconv.Quote(spec.ACName) + "\n")
		}
		buf.WriteString("  open\n\n")
	}
	return buf.Bytes(), nil
}

func freeBSDDHClient(options map[string]api.DHCPv4AddressSpec) []byte {
	if len(options) == 0 {
		return nil
	}
	var buf bytes.Buffer
	buf.WriteString("# Generated by routerd. Do not edit by hand.\n")
	for _, ifname := range sortedFreeBSDMapKeysSpec(options) {
		spec := options[ifname]
		buf.WriteString(fmt.Sprintf("interface \"%s\" {\n", ifname))
		var ignored []string
		if spec.UseRoutes != nil && !*spec.UseRoutes {
			ignored = append(ignored, "routers")
		}
		if spec.UseDNS != nil && !*spec.UseDNS {
			ignored = append(ignored, "domain-name", "domain-name-servers", "domain-search")
		}
		if len(ignored) > 0 {
			buf.WriteString("  ignore " + strings.Join(ignored, ", ") + ";\n")
		}
		buf.WriteString("}\n\n")
	}
	return buf.Bytes()
}

func freeBSDIPv4CIDR(value string) (string, error) {
	prefix, err := netip.ParsePrefix(value)
	if err != nil {
		return "", err
	}
	return prefix.Addr().String() + "/" + fmt.Sprintf("%d", prefix.Bits()), nil
}

func sortedFreeBSDMapKeys(values map[string]bool) []string {
	var keys []string
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func sortedFreeBSDMapKeysSpec(values map[string]api.DHCPv4AddressSpec) []string {
	var keys []string
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func freeBSDMPDLabel(name string) string {
	return "routerd_" + freeBSDMPDName("", name)
}

func freeBSDMPDName(prefix, name string) string {
	var b strings.Builder
	b.WriteString(prefix)
	for _, r := range name {
		switch {
		case r >= 'a' && r <= 'z':
			b.WriteRune(r)
		case r >= 'A' && r <= 'Z':
			b.WriteRune(r)
		case r >= '0' && r <= '9':
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
	}
	if b.Len() == len(prefix) {
		b.WriteString("unnamed")
	}
	return b.String()
}
