// SPDX-License-Identifier: BSD-3-Clause

package render

import (
	"bytes"
	"fmt"
	"net/netip"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/imksoo/routerd/pkg/api"
	"github.com/imksoo/routerd/pkg/hostdeps"
)

type FreeBSDConfig struct {
	RCConf         []byte
	NTP            []byte
	DHCPClient     []byte
	MPD5           []byte
	PF             []byte
	PackageInstall []byte
	RCDScripts     map[string][]byte
	Warnings       []string
}

func FreeBSD(router *api.Router) (FreeBSDConfig, error) {
	return FreeBSDWithPPPoEPasswords(router, func(_ api.Resource, spec api.PPPoESessionSpec) (string, error) {
		if spec.Password != "" {
			return spec.Password, nil
		}
		return "CHANGEME-read-" + spec.PasswordFile, nil
	})
}

func FreeBSDWithPPPoEPasswords(router *api.Router, passwordFor func(api.Resource, api.PPPoESessionSpec) (string, error)) (FreeBSDConfig, error) {
	router = api.ExpandClusterNetworkRoutes(router)
	aliases := map[string]string{}
	managed := map[string]bool{}
	for _, res := range router.Spec.Resources {
		if res.Kind != "Interface" {
			continue
		}
		spec, err := res.InterfaceSpec()
		if err != nil {
			return FreeBSDConfig{}, err
		}
		aliases[res.Metadata.Name] = spec.IfName
		managed[res.Metadata.Name] = spec.Managed && spec.Owner != "external"
	}
	for _, res := range router.Spec.Resources {
		if res.Kind != "Bridge" {
			continue
		}
		spec, err := res.BridgeSpec()
		if err != nil {
			return FreeBSDConfig{}, err
		}
		aliases[res.Metadata.Name] = defaultString(spec.IfName, res.Metadata.Name)
		managed[res.Metadata.Name] = true
	}
	for _, res := range router.Spec.Resources {
		if res.Kind != "VXLANSegment" {
			continue
		}
		spec, err := res.VXLANSegmentSpec()
		if err != nil {
			return FreeBSDConfig{}, err
		}
		aliases[res.Metadata.Name] = defaultString(spec.IfName, res.Metadata.Name)
		managed[res.Metadata.Name] = true
	}
	for _, res := range router.Spec.Resources {
		if res.Kind != "WireGuardInterface" {
			continue
		}
		aliases[res.Metadata.Name] = res.Metadata.Name
		managed[res.Metadata.Name] = true
	}

	var rc bytes.Buffer
	rc.WriteString("# Generated by routerd. Do not edit by hand.\n")
	rc.WriteString("gateway_enable=\"YES\"\n")
	rc.WriteString("ipv6_gateway_enable=\"YES\"\n")

	adminUpIfaces := map[string]string{}
	hasPrimaryIfconfig := map[string]bool{}
	for _, res := range router.Spec.Resources {
		if res.Kind != "Interface" {
			continue
		}
		spec, err := res.InterfaceSpec()
		if err != nil {
			return FreeBSDConfig{}, err
		}
		if spec.AdminUp && spec.IfName != "" && spec.Managed && spec.Owner != "external" {
			adminUpIfaces[res.Metadata.Name] = spec.IfName
		}
	}
	for _, res := range router.Spec.Resources {
		if res.Kind != "IPv4StaticAddress" {
			continue
		}
		spec, err := res.IPv4StaticAddressSpec()
		if err != nil {
			return FreeBSDConfig{}, err
		}
		if managed[spec.Interface] && resourceKind(router, spec.Interface) != "Bridge" && resourceKind(router, spec.Interface) != "WireGuardInterface" {
			hasPrimaryIfconfig[spec.Interface] = true
		}
	}
	adminNames := make([]string, 0, len(adminUpIfaces))
	for name := range adminUpIfaces {
		adminNames = append(adminNames, name)
	}
	sort.Strings(adminNames)
	for _, name := range adminNames {
		if !hasPrimaryIfconfig[name] {
			rc.WriteString(fmt.Sprintf("ifconfig_%s=\"up\"\n", adminUpIfaces[name]))
		}
	}

	var staticV4Routes []freeBSDStaticRoute
	var staticV6Routes []freeBSDStaticRoute
	staticBridgeV4 := map[string][]string{}
	var ntpConfig []byte
	var pppoes []freeBSDPPPoE
	var dslites []freeBSDDSLite
	bridges, err := bridgeConfigs(router, aliases)
	if err != nil {
		return FreeBSDConfig{}, err
	}
	vxlans, err := vxlanConfigs(router, aliases)
	if err != nil {
		return FreeBSDConfig{}, err
	}
	var warnings []string
	for _, vxlan := range vxlans {
		if len(vxlan.Remotes) > 1 {
			warnings = append(warnings, fmt.Sprintf("VXLANSegment %s: FreeBSD vxlan(4) supports a single unicast remote; using %s as the seed and ignoring %v. Reach the other peers via a Linux relay or a multicast underlay.", vxlan.Name, vxlan.Remotes[0], vxlan.Remotes[1:]))
		}
	}
	for _, res := range router.Spec.Resources {
		switch res.Kind {
		case "IPv6RAAddress":
			spec, err := res.IPv6RAAddressSpec()
			if err != nil {
				return FreeBSDConfig{}, err
			}
			if api.BoolDefault(spec.Managed, true) {
				rc.WriteString(fmt.Sprintf("ifconfig_%s_ipv6=\"inet6 accept_rtadv\"\n", aliases[spec.Interface]))
				rc.WriteString(fmt.Sprintf("rtsold_flags=\"%s\"\n", aliases[spec.Interface]))
				rc.WriteString("rtsold_enable=\"YES\"\n")
			}
		case "IPv4StaticAddress":
			spec, err := res.IPv4StaticAddressSpec()
			if err != nil {
				return FreeBSDConfig{}, err
			}
			if managed[spec.Interface] {
				address, err := freeBSDIPv4CIDR(spec.Address)
				if err != nil {
					return FreeBSDConfig{}, fmt.Errorf("%s: %w", res.ID(), err)
				}
				if resourceKind(router, spec.Interface) == "Bridge" {
					staticBridgeV4[aliases[spec.Interface]] = append(staticBridgeV4[aliases[spec.Interface]], address)
				} else if resourceKind(router, spec.Interface) == "WireGuardInterface" {
					// WireGuard interfaces are created by their rc.d service; that
					// service applies static addresses after the interface exists.
				} else {
					rc.WriteString(fmt.Sprintf("ifconfig_%s=\"inet %s\"\n", aliases[spec.Interface], address))
				}
			}
		case "IPv4StaticRoute":
			spec, err := res.IPv4StaticRouteSpec()
			if err != nil {
				return FreeBSDConfig{}, err
			}
			staticV4Routes = append(staticV4Routes, freeBSDStaticRoute{Name: res.Metadata.Name, IfName: aliases[spec.Interface], Destination: spec.Destination, Via: spec.Via})
		case "IPv6StaticRoute":
			spec, err := res.IPv6StaticRouteSpec()
			if err != nil {
				return FreeBSDConfig{}, err
			}
			staticV6Routes = append(staticV6Routes, freeBSDStaticRoute{Name: res.Metadata.Name, IfName: aliases[spec.Interface], Destination: spec.Destination, Via: spec.Via})
		case "PPPoESession":
			spec, err := res.PPPoESessionSpec()
			if err != nil {
				return FreeBSDConfig{}, err
			}
			lowerIfName := aliases[spec.Interface]
			if lowerIfName == "" {
				return FreeBSDConfig{}, fmt.Errorf("%s references interface with empty ifname", res.ID())
			}
			password, err := passwordFor(res, spec)
			if err != nil {
				return FreeBSDConfig{}, err
			}
			pppoes = append(pppoes, freeBSDPPPoE{Name: res.Metadata.Name, IfName: defaultString(spec.IfName, "ppp-"+res.Metadata.Name), LowerIfName: lowerIfName, Password: password, Spec: spec})
		case "DSLiteTunnel":
			spec, err := res.DSLiteTunnelSpec()
			if err != nil {
				return FreeBSDConfig{}, err
			}
			if !api.BoolDefault(spec.Enabled, true) {
				continue
			}
			local := strings.TrimSpace(spec.LocalAddress)
			remote := defaultString(spec.RemoteAddress, spec.AFTRIPv6)
			if local == "" || remote == "" {
				// Dynamic DS-Lite is applied by routerd at runtime, after PD,
				// AFTR resolution, and IPv4StaticAddress references converge.
				// The rc.conf renderer intentionally leaves it out instead of
				// emitting noisy warnings for the normal declarative path.
				continue
			}
			ifname := freeBSDGifIfName(spec.TunnelName, len(dslites))
			innerLocal, err := freeBSDDSLiteInnerLocalIPv4(spec)
			if err != nil {
				return FreeBSDConfig{}, fmt.Errorf("%s: %w", res.ID(), err)
			}
			dslites = append(dslites, freeBSDDSLite{Name: res.Metadata.Name, IfName: ifname, LocalAddress: local, RemoteAddress: remote, InnerLocalAddress: innerLocal, MTU: spec.MTU, DefaultRoute: spec.DefaultRoute})
			if spec.DefaultRoute {
				staticV4Routes = append(staticV4Routes, freeBSDStaticRoute{Name: res.Metadata.Name + "-default", IfName: ifname, Destination: "default", Via: dsliteInnerRemoteIPv4})
			}
		case "NTPClient":
			if freeBSDHasManagedNTPServer(router) {
				continue
			}
			spec, err := res.NTPClientSpec()
			if err != nil {
				return FreeBSDConfig{}, err
			}
			if !spec.Managed {
				continue
			}
			if provider := defaultString(spec.Provider, "ntpd"); provider != "ntpd" {
				return FreeBSDConfig{}, fmt.Errorf("%s has unsupported FreeBSD provider %q", res.ID(), provider)
			}
			servers := freeBSDNTPServers(spec)
			if len(servers) == 0 {
				warnings = append(warnings, fmt.Sprintf("%s: no static or fallback NTP servers available for boot-time ntpd; runtime controller may still derive servers from status.", res.ID()))
				continue
			}
			rc.WriteString("ntpd_enable=\"YES\"\n")
			rc.WriteString("ntpd_sync_on_start=\"YES\"\n")
			rc.WriteString("ntpd_config=\"/usr/local/etc/routerd/ntp.conf\"\n")
			ntpConfig = freeBSDNTPConfig(servers)
		case "NTPServer":
			spec, err := res.NTPServerSpec()
			if err != nil {
				return FreeBSDConfig{}, err
			}
			if !spec.Managed {
				continue
			}
			if provider := defaultString(spec.Provider, "ntpd"); provider != "ntpd" {
				return FreeBSDConfig{}, fmt.Errorf("%s has unsupported FreeBSD provider %q", res.ID(), provider)
			}
			servers := freeBSDNTPServerServers(spec)
			if len(servers) == 0 {
				warnings = append(warnings, fmt.Sprintf("%s: no static or fallback NTP servers available for boot-time ntpd; runtime controller may still derive servers from status.", res.ID()))
				continue
			}
			rc.WriteString("ntpd_enable=\"YES\"\n")
			rc.WriteString("ntpd_sync_on_start=\"YES\"\n")
			rc.WriteString("ntpd_config=\"/usr/local/etc/routerd/ntp.conf\"\n")
			ntpConfig = freeBSDNTPServerConfig(servers, spec.ListenAddresses, len(spec.ListenAddressFrom) > 0)
		}
	}

	if hasManagedFreeBSDPPPoE(pppoes) {
		rc.WriteString("mpd_enable=\"YES\"\n")
		rc.WriteString("mpd_flags=\"-b\"\n")
	}
	pf, err := PF(router, InternalFirewallHoles(router))
	if err != nil {
		return FreeBSDConfig{}, err
	}
	if len(pf) > 0 {
		rc.WriteString("pf_enable=\"YES\"\n")
		rc.WriteString("pflog_enable=\"YES\"\n")
	}
	if hasManagedFreeBSDTailscale(router) {
		rc.WriteString("tailscaled_enable=\"YES\"\n")
	}
	packageInstall, err := freeBSDPackageInstallScript(router)
	if err != nil {
		return FreeBSDConfig{}, err
	}
	rcdScripts, err := freeBSDRCDScripts(router)
	if err != nil {
		return FreeBSDConfig{}, err
	}
	for _, name := range sortedByteMapKeys(rcdScripts) {
		rc.WriteString(name + "_enable=\"YES\"\n")
	}
	writeFreeBSDClonedInterfaces(&rc, bridges, vxlans, dslites)
	writeFreeBSDDSLites(&rc, dslites)
	writeFreeBSDVXLANS(&rc, vxlans)
	writeFreeBSDBridges(&rc, bridges)
	writeFreeBSDBridgeAliases(&rc, staticBridgeV4)
	writeFreeBSDStaticRoutes(&rc, staticV4Routes, false)
	writeFreeBSDStaticRoutes(&rc, staticV6Routes, true)

	mpd5, err := freeBSDMPD5(pppoes)
	if err != nil {
		return FreeBSDConfig{}, err
	}
	return FreeBSDConfig{RCConf: rc.Bytes(), NTP: ntpConfig, MPD5: mpd5, PF: pf, PackageInstall: packageInstall, RCDScripts: rcdScripts, Warnings: warnings}, nil
}

const (
	dsliteDefaultInnerLocalIPv4 = "192.0.0.2"
	dsliteInnerRemoteIPv4       = "192.0.0.1"
)

type freeBSDPPPoE struct {
	Name        string
	IfName      string
	LowerIfName string
	Password    string
	Spec        api.PPPoESessionSpec
}

type freeBSDStaticRoute struct {
	Name        string
	IfName      string
	Destination string
	Via         string
}

type freeBSDDSLite struct {
	Name              string
	IfName            string
	LocalAddress      string
	RemoteAddress     string
	InnerLocalAddress string
	MTU               int
	DefaultRoute      bool
}

func freeBSDDSLiteInnerLocalIPv4(spec api.DSLiteTunnelSpec) (string, error) {
	value := ""
	if strings.TrimSpace(spec.LocalAddressFrom.Resource) != "" {
		return "", fmt.Errorf("localAddressFrom is resolved by the runtime controller")
	}
	if value == "" {
		value = dsliteDefaultInnerLocalIPv4
	}
	addr, err := netip.ParseAddr(value)
	if err != nil || !addr.Is4() {
		return "", fmt.Errorf("innerLocalAddress %q is not an IPv4 address", value)
	}
	if addr.IsUnspecified() || addr.IsMulticast() || addr.IsLoopback() {
		return "", fmt.Errorf("innerLocalAddress %q must be a usable unicast IPv4 address", value)
	}
	return addr.String(), nil
}

func freeBSDNTPServers(spec api.NTPClientSpec) []string {
	source := defaultString(spec.Source, "static")
	servers := compactRenderNTPServers(spec.Servers)
	if source != "static" && len(servers) == 0 {
		servers = compactRenderNTPServers(spec.FallbackServers)
	}
	return servers
}

func freeBSDNTPConfig(servers []string) []byte {
	var buf bytes.Buffer
	buf.WriteString("# Generated by routerd. Do not edit by hand.\n")
	buf.WriteString("driftfile /var/db/ntpd.drift\n")
	for _, server := range compactRenderNTPServers(servers) {
		buf.WriteString("server " + server + " iburst\n")
	}
	return buf.Bytes()
}

func freeBSDNTPServerConfig(servers, listenAddresses []string, hasDynamicListenAddresses bool) []byte {
	var buf bytes.Buffer
	buf.WriteString("# Generated by routerd. Do not edit by hand.\n")
	if len(listenAddresses) > 0 || hasDynamicListenAddresses {
		buf.WriteString("interface ignore all\n")
		buf.WriteString("interface listen 127.0.0.1\n")
		buf.WriteString("interface listen ::1\n")
		for _, address := range freeBSDNTPListenAddresses(listenAddresses) {
			buf.WriteString("interface listen " + address + "\n")
		}
	}
	buf.WriteString("driftfile /var/db/ntpd.drift\n")
	for _, server := range compactRenderNTPServers(servers) {
		buf.WriteString("server " + server + " iburst\n")
	}
	return buf.Bytes()
}

func freeBSDNTPServerServers(spec api.NTPServerSpec) []string {
	source := defaultString(spec.Source, "static")
	servers := compactRenderNTPServers(spec.Servers)
	if source != "static" && len(servers) == 0 {
		servers = compactRenderNTPServers(spec.FallbackServers)
	}
	return servers
}

func freeBSDHasManagedNTPServer(router *api.Router) bool {
	if router == nil {
		return false
	}
	for _, resource := range router.Spec.Resources {
		if resource.Kind != "NTPServer" {
			continue
		}
		spec, err := resource.NTPServerSpec()
		if err != nil || !spec.Managed {
			continue
		}
		if defaultString(spec.Provider, "ntpd") == "ntpd" {
			return true
		}
	}
	return false
}

func freeBSDNTPListenAddresses(values []string) []string {
	out := make([]string, 0, len(values))
	seen := map[string]bool{}
	for _, value := range compactRenderNTPServers(values) {
		if strings.Contains(value, "/") {
			if prefix, err := netip.ParsePrefix(value); err == nil {
				value = prefix.Addr().String()
			}
		}
		if value == "" || seen[value] {
			continue
		}
		seen[value] = true
		out = append(out, value)
	}
	return out
}

func compactRenderNTPServers(values []string) []string {
	out := make([]string, 0, len(values))
	seen := map[string]bool{}
	for _, value := range values {
		for _, part := range strings.FieldsFunc(value, func(r rune) bool {
			return r == ',' || r == ';' || r == ' ' || r == '\t' || r == '\n' || r == '\r'
		}) {
			part = strings.Trim(part, "[] ")
			if part == "" || seen[part] {
				continue
			}
			seen[part] = true
			out = append(out, part)
		}
	}
	return out
}

func writeFreeBSDDSLites(buf *bytes.Buffer, dslites []freeBSDDSLite) {
	for _, tunnel := range dslites {
		args := []string{
			"inet6 tunnel " + tunnel.LocalAddress + " " + tunnel.RemoteAddress,
			"inet " + tunnel.InnerLocalAddress + " " + dsliteInnerRemoteIPv4 + " netmask 255.255.255.255",
		}
		if tunnel.MTU != 0 {
			args = append(args, "mtu "+strconv.Itoa(tunnel.MTU))
		}
		args = append(args, "up")
		buf.WriteString(fmt.Sprintf("ifconfig_%s=\"%s\"\n", tunnel.IfName, strings.Join(args, " ")))
	}
}

func writeFreeBSDBridges(buf *bytes.Buffer, bridges []bridgeConfig) {
	if len(bridges) == 0 {
		return
	}
	for _, bridge := range bridges {
		var args []string
		for _, member := range bridge.Members {
			args = append(args, "addm "+member)
			if bridge.STP {
				args = append(args, "stp "+member)
			}
		}
		if bridge.MTU != 0 {
			args = append(args, fmt.Sprintf("mtu %d", bridge.MTU))
		}
		if bridge.MACAddress != "" {
			args = append(args, "ether "+bridge.MACAddress)
		}
		args = append(args, "up")
		buf.WriteString(fmt.Sprintf("ifconfig_%s=\"%s\"\n", bridge.IfName, strings.Join(args, " ")))
	}
}

func writeFreeBSDBridgeAliases(buf *bytes.Buffer, addresses map[string][]string) {
	var ifnames []string
	for ifname := range addresses {
		ifnames = append(ifnames, ifname)
	}
	sort.Strings(ifnames)
	for _, ifname := range ifnames {
		sort.Strings(addresses[ifname])
		for i, address := range addresses[ifname] {
			buf.WriteString(fmt.Sprintf("ifconfig_%s_alias%d=\"inet %s\"\n", ifname, i, address))
		}
	}
}

func writeFreeBSDVXLANS(buf *bytes.Buffer, vxlans []vxlanConfig) {
	if len(vxlans) == 0 {
		return
	}
	for _, vxlan := range vxlans {
		var args []string
		args = append(args, "vxlanid "+strconv.Itoa(vxlan.VNI))
		args = append(args, "vxlanlocal "+vxlan.LocalAddress)
		if vxlan.MulticastGroup != "" {
			args = append(args, "vxlangroup "+vxlan.MulticastGroup)
		} else if len(vxlan.Remotes) > 0 {
			args = append(args, "vxlanremote "+vxlan.Remotes[0])
		}
		if vxlan.UnderlayIfName != "" {
			args = append(args, "vxlandev "+vxlan.UnderlayIfName)
		}
		args = append(args, "vxlanport "+strconv.Itoa(vxlan.UDPPort))
		if vxlan.MTU != 0 {
			args = append(args, "mtu "+strconv.Itoa(vxlan.MTU))
		}
		args = append(args, "up")
		buf.WriteString(fmt.Sprintf("ifconfig_%s=\"%s\"\n", vxlan.IfName, strings.Join(args, " ")))
	}
}

func resourceKind(router *api.Router, name string) string {
	for _, res := range router.Spec.Resources {
		if res.Metadata.Name == name {
			return res.Kind
		}
	}
	return ""
}

func writeFreeBSDClonedInterfaces(buf *bytes.Buffer, bridges []bridgeConfig, vxlans []vxlanConfig, dslites []freeBSDDSLite) {
	var names []string
	for _, vxlan := range vxlans {
		names = append(names, vxlan.IfName)
	}
	for _, tunnel := range dslites {
		names = append(names, tunnel.IfName)
	}
	for _, bridge := range bridges {
		names = append(names, bridge.IfName)
	}
	if len(names) > 0 {
		buf.WriteString("cloned_interfaces=\"" + strings.Join(names, " ") + "\"\n")
	}
}

func writeFreeBSDStaticRoutes(buf *bytes.Buffer, routes []freeBSDStaticRoute, ipv6 bool) {
	if len(routes) == 0 {
		return
	}
	sort.Slice(routes, func(i, j int) bool { return routes[i].Name < routes[j].Name })
	var names []string
	for _, route := range routes {
		names = append(names, freeBSDRouteLabel(route.Name))
	}
	if ipv6 {
		buf.WriteString("ipv6_static_routes=\"" + strings.Join(names, " ") + "\"\n")
	} else {
		buf.WriteString("static_routes=\"" + strings.Join(names, " ") + "\"\n")
	}
	for _, route := range routes {
		label := freeBSDRouteLabel(route.Name)
		via := route.Via
		if ipv6 && strings.HasPrefix(strings.ToLower(via), "fe80:") && route.IfName != "" && !strings.Contains(via, "%") {
			via += "%" + route.IfName
		}
		if ipv6 {
			buf.WriteString(fmt.Sprintf("ipv6_route_%s=\"%s %s\"\n", label, route.Destination, via))
		} else if route.Destination == "default" {
			buf.WriteString(fmt.Sprintf("route_%s=\"default %s\"\n", label, via))
		} else {
			buf.WriteString(fmt.Sprintf("route_%s=\"-net %s %s\"\n", label, route.Destination, via))
		}
	}
}

var freeBSDGIFNamePattern = regexp.MustCompile(`^gif[0-9]+$`)

func freeBSDGifIfName(value string, index int) string {
	if freeBSDGIFNamePattern.MatchString(value) {
		return value
	}
	return "gif" + strconv.Itoa(index)
}

func freeBSDRouteLabel(name string) string {
	label := strings.Map(func(r rune) rune {
		switch {
		case r >= 'a' && r <= 'z':
			return r
		case r >= 'A' && r <= 'Z':
			return r
		case r >= '0' && r <= '9':
			return r
		case r == '_' || r == '-':
			return r
		default:
			return '_'
		}
	}, name)
	label = strings.ReplaceAll(label, "-", "_")
	if label == "" {
		return "route"
	}
	return label
}

func hasManagedFreeBSDPPPoE(pppoes []freeBSDPPPoE) bool {
	for _, pppoe := range pppoes {
		if pppoe.Spec.Managed && api.BoolDefault(pppoe.Spec.Enabled, true) {
			return true
		}
	}
	return false
}

func hasManagedFreeBSDTailscale(router *api.Router) bool {
	for _, res := range router.Spec.Resources {
		if res.Kind != "TailscaleNode" {
			continue
		}
		spec, err := res.TailscaleNodeSpec()
		if err != nil {
			continue
		}
		if firstNonEmpty(spec.State, "present") != "absent" {
			return true
		}
	}
	return false
}

func freeBSDPackageInstallScript(router *api.Router) ([]byte, error) {
	var packages []string
	seen := map[string]bool{}
	for _, resource := range hostdeps.PackageResources(router) {
		spec, err := resource.PackageSpec()
		if err != nil {
			return nil, err
		}
		for _, set := range spec.Packages {
			if set.OS != "freebsd" {
				continue
			}
			for _, name := range set.Names {
				name = strings.TrimSpace(name)
				if name == "" || seen[name] {
					continue
				}
				seen[name] = true
				packages = append(packages, name)
			}
		}
	}
	sort.Strings(packages)
	if len(packages) == 0 {
		return nil, nil
	}
	var buf bytes.Buffer
	buf.WriteString("#!/bin/sh\n")
	buf.WriteString("set -eu\n")
	buf.WriteString("# Generated by routerd. Installs missing FreeBSD packages required by declared router resources.\n")
	buf.WriteString("missing=\"\"\n")
	buf.WriteString("for pkg in")
	for _, name := range packages {
		buf.WriteString(" " + shellSingleQuote(name))
	}
	buf.WriteString("; do\n")
	buf.WriteString("  if ! pkg info -e \"${pkg}\"; then\n")
	buf.WriteString("    missing=\"${missing} ${pkg}\"\n")
	buf.WriteString("  fi\n")
	buf.WriteString("done\n")
	buf.WriteString("if [ -n \"${missing}\" ]; then\n")
	buf.WriteString("  pkg install -y ${missing}\n")
	buf.WriteString("fi\n")
	return buf.Bytes(), nil
}

func freeBSDMPD5(pppoes []freeBSDPPPoE) ([]byte, error) {
	if len(pppoes) == 0 {
		return nil, nil
	}
	sort.Slice(pppoes, func(i, j int) bool { return pppoes[i].Name < pppoes[j].Name })
	var buf bytes.Buffer
	buf.WriteString("# Generated by routerd. Do not edit by hand.\n")
	buf.WriteString("# This file uses FreeBSD mpd5 for PPPoE client sessions.\n\n")
	buf.WriteString("startup:\n\n")
	buf.WriteString("default:\n")
	managed := false
	for _, pppoe := range pppoes {
		if !pppoe.Spec.Managed || !api.BoolDefault(pppoe.Spec.Enabled, true) {
			continue
		}
		managed = true
		buf.WriteString("  load " + freeBSDMPDLabel(pppoe.Name) + "\n")
	}
	if !managed {
		buf.WriteString("  # No managed PPPoE sessions are enabled.\n")
	}
	buf.WriteString("\n")

	for _, pppoe := range pppoes {
		spec := pppoe.Spec
		mtu := spec.MTU
		if mtu == 0 {
			mtu = 1492
		}
		mru := spec.MRU
		if mru == 0 {
			mru = 1492
		}
		lcpInterval := spec.LCPInterval
		if lcpInterval == 0 {
			lcpInterval = 20
		}
		lcpFailure := spec.LCPFailure
		if lcpFailure == 0 {
			lcpFailure = 3
		}
		label := freeBSDMPDLabel(pppoe.Name)
		bundle := freeBSDMPDName("B", pppoe.Name)
		link := freeBSDMPDName("L", pppoe.Name)

		buf.WriteString(label + ":\n")
		buf.WriteString("  create bundle static " + bundle + "\n")
		buf.WriteString("  set iface name " + pppoe.IfName + "\n")
		if spec.DefaultRoute {
			buf.WriteString("  set iface route default\n")
		}
		buf.WriteString("  set iface enable tcpmssfix\n")
		buf.WriteString("  set ipcp ranges 0.0.0.0/0 0.0.0.0/0\n")
		buf.WriteString("  create link static " + link + " pppoe\n")
		buf.WriteString("  set link action bundle " + bundle + "\n")
		buf.WriteString("  set auth authname " + strconv.Quote(spec.Username) + "\n")
		buf.WriteString("  set auth password " + strconv.Quote(pppoe.Password) + "\n")
		buf.WriteString("  set link max-redial 0\n")
		buf.WriteString(fmt.Sprintf("  set link mtu %d\n", mtu))
		buf.WriteString(fmt.Sprintf("  set link mru %d\n", mru))
		buf.WriteString(fmt.Sprintf("  set link keep-alive %d %d\n", lcpInterval, lcpInterval*lcpFailure))
		buf.WriteString("  set pppoe iface " + pppoe.LowerIfName + "\n")
		if spec.ServiceName != "" {
			buf.WriteString("  set pppoe service " + strconv.Quote(spec.ServiceName) + "\n")
		}
		if spec.ACName != "" {
			buf.WriteString("  set pppoe acname " + strconv.Quote(spec.ACName) + "\n")
		}
		buf.WriteString("  open\n\n")
	}
	return buf.Bytes(), nil
}

func freeBSDIPv4CIDR(value string) (string, error) {
	prefix, err := netip.ParsePrefix(value)
	if err != nil {
		return "", err
	}
	return prefix.Addr().String() + "/" + fmt.Sprintf("%d", prefix.Bits()), nil
}

func sortedFreeBSDMapKeys(values map[string]bool) []string {
	var keys []string
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func freeBSDMPDLabel(name string) string {
	return "routerd_" + freeBSDMPDName("", name)
}

func freeBSDMPDName(prefix, name string) string {
	var b strings.Builder
	b.WriteString(prefix)
	for _, r := range name {
		switch {
		case r >= 'a' && r <= 'z':
			b.WriteRune(r)
		case r >= 'A' && r <= 'Z':
			b.WriteRune(r)
		case r >= '0' && r <= '9':
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
	}
	if b.Len() == len(prefix) {
		b.WriteString("unnamed")
	}
	return b.String()
}
