package render

import (
	"bytes"
	"fmt"
	"net/netip"
	"sort"
	"strconv"
	"strings"

	"routerd/pkg/api"
	routerstate "routerd/pkg/state"
)

type FreeBSDConfig struct {
	RCConf     []byte
	DHCP6C     []byte
	DHCPClient []byte
	MPD5       []byte
}

func FreeBSD(router *api.Router) (FreeBSDConfig, error) {
	return FreeBSDWithPPPoEPasswords(router, func(_ api.Resource, spec api.PPPoEInterfaceSpec) (string, error) {
		if spec.Password != "" {
			return spec.Password, nil
		}
		return "CHANGEME-read-" + spec.PasswordFile, nil
	})
}

func FreeBSDWithPPPoEPasswords(router *api.Router, passwordFor func(api.Resource, api.PPPoEInterfaceSpec) (string, error)) (FreeBSDConfig, error) {
	aliases := map[string]string{}
	managed := map[string]bool{}
	for _, res := range router.Spec.Resources {
		if res.Kind != "Interface" {
			continue
		}
		spec, err := res.InterfaceSpec()
		if err != nil {
			return FreeBSDConfig{}, err
		}
		aliases[res.Metadata.Name] = spec.IfName
		managed[res.Metadata.Name] = spec.Managed && spec.Owner != "external"
	}
	for _, res := range router.Spec.Resources {
		if res.Kind != "Bridge" {
			continue
		}
		spec, err := res.BridgeSpec()
		if err != nil {
			return FreeBSDConfig{}, err
		}
		aliases[res.Metadata.Name] = defaultString(spec.IfName, res.Metadata.Name)
		managed[res.Metadata.Name] = true
	}

	var rc bytes.Buffer
	rc.WriteString("# Generated by routerd. Do not edit by hand.\n")
	rc.WriteString("gateway_enable=\"YES\"\n")
	rc.WriteString("ipv6_gateway_enable=\"YES\"\n")

	dhcp6cIfaces := map[string]bool{}
	dhcpcdPDIfaces := map[string]bool{}
	dhclientOptions := map[string]api.IPv4DHCPAddressSpec{}
	var staticV4Routes []freeBSDStaticRoute
	var staticV6Routes []freeBSDStaticRoute
	var pds []freeBSDPD
	var pppoes []freeBSDPPPoE
	bridges, err := bridgeConfigs(router, aliases)
	if err != nil {
		return FreeBSDConfig{}, err
	}
	for _, res := range router.Spec.Resources {
		switch res.Kind {
		case "IPv4DHCPAddress":
			spec, err := res.IPv4DHCPAddressSpec()
			if err != nil {
				return FreeBSDConfig{}, err
			}
			if managed[spec.Interface] {
				rc.WriteString(fmt.Sprintf("ifconfig_%s=\"DHCP\"\n", aliases[spec.Interface]))
				if spec.UseRoutes != nil || spec.UseDNS != nil || spec.RouteMetric != 0 {
					dhclientOptions[aliases[spec.Interface]] = spec
				}
			}
		case "IPv6DHCPAddress":
			spec, err := res.IPv6DHCPAddressSpec()
			if err != nil {
				return FreeBSDConfig{}, err
			}
			if managed[spec.Interface] {
				rc.WriteString(fmt.Sprintf("ifconfig_%s_ipv6=\"inet6 accept_rtadv\"\n", aliases[spec.Interface]))
				rc.WriteString(fmt.Sprintf("rtsold_flags=\"%s\"\n", aliases[spec.Interface]))
				rc.WriteString("rtsold_enable=\"YES\"\n")
			}
		case "IPv6RAAddress":
			spec, err := res.IPv6RAAddressSpec()
			if err != nil {
				return FreeBSDConfig{}, err
			}
			if api.BoolDefault(spec.Managed, true) {
				rc.WriteString(fmt.Sprintf("ifconfig_%s_ipv6=\"inet6 accept_rtadv\"\n", aliases[spec.Interface]))
				rc.WriteString(fmt.Sprintf("rtsold_flags=\"%s\"\n", aliases[spec.Interface]))
				rc.WriteString("rtsold_enable=\"YES\"\n")
			}
		case "IPv4StaticAddress":
			spec, err := res.IPv4StaticAddressSpec()
			if err != nil {
				return FreeBSDConfig{}, err
			}
			if managed[spec.Interface] {
				address, err := freeBSDIPv4CIDR(spec.Address)
				if err != nil {
					return FreeBSDConfig{}, fmt.Errorf("%s: %w", res.ID(), err)
				}
				rc.WriteString(fmt.Sprintf("ifconfig_%s=\"inet %s\"\n", aliases[spec.Interface], address))
			}
		case "IPv4StaticRoute":
			spec, err := res.IPv4StaticRouteSpec()
			if err != nil {
				return FreeBSDConfig{}, err
			}
			staticV4Routes = append(staticV4Routes, freeBSDStaticRoute{Name: res.Metadata.Name, IfName: aliases[spec.Interface], Destination: spec.Destination, Via: spec.Via})
		case "IPv6StaticRoute":
			spec, err := res.IPv6StaticRouteSpec()
			if err != nil {
				return FreeBSDConfig{}, err
			}
			staticV6Routes = append(staticV6Routes, freeBSDStaticRoute{Name: res.Metadata.Name, IfName: aliases[spec.Interface], Destination: spec.Destination, Via: spec.Via})
		case "IPv6PrefixDelegation":
			spec, err := res.IPv6PrefixDelegationSpec()
			if err != nil {
				return FreeBSDConfig{}, err
			}
			ifname := aliases[spec.Interface]
			if ifname == "" {
				return FreeBSDConfig{}, fmt.Errorf("%s references interface with empty ifname", res.ID())
			}
			if defaultString(spec.Client, "dhcp6c") != "dhcp6c" {
				dhcpcdPDIfaces[ifname] = true
				continue
			}
			dhcp6cIfaces[ifname] = true
			profile := defaultString(spec.Profile, api.IPv6PDProfileDefault)
			pds = append(pds, freeBSDPD{
				Name:                res.Metadata.Name,
				IfName:              ifname,
				Profile:             profile,
				PrefixLength:        api.EffectiveIPv6PDPrefixLength(profile, spec.PrefixLength),
				IAID:                strings.TrimSpace(spec.IAID),
				ServerID:            strings.TrimSpace(spec.ServerID),
				PriorPrefix:         strings.TrimSpace(spec.PriorPrefix),
				AcquisitionStrategy: strings.TrimSpace(spec.AcquisitionStrategy),
			})
		case "PPPoEInterface":
			spec, err := res.PPPoEInterfaceSpec()
			if err != nil {
				return FreeBSDConfig{}, err
			}
			lowerIfName := aliases[spec.Interface]
			if lowerIfName == "" {
				return FreeBSDConfig{}, fmt.Errorf("%s references interface with empty ifname", res.ID())
			}
			password, err := passwordFor(res, spec)
			if err != nil {
				return FreeBSDConfig{}, err
			}
			pppoes = append(pppoes, freeBSDPPPoE{Name: res.Metadata.Name, IfName: defaultString(spec.IfName, "ppp-"+res.Metadata.Name), LowerIfName: lowerIfName, Password: password, Spec: spec})
		}
	}

	if len(dhcp6cIfaces) > 0 {
		rc.WriteString("dhcp6c_enable=\"YES\"\n")
		rc.WriteString("dhcp6c_interfaces=\"" + strings.Join(sortedFreeBSDMapKeys(dhcp6cIfaces), " ") + "\"\n")
		rc.WriteString("dhcp6c_flags=\"" + freeBSDDHCP6CFlags(pds) + "\"\n")
	} else if len(dhcpcdPDIfaces) > 0 {
		rc.WriteString("dhcp6c_enable=\"NO\"\n")
	}
	if hasManagedFreeBSDPPPoE(pppoes) {
		rc.WriteString("mpd_enable=\"YES\"\n")
		rc.WriteString("mpd_flags=\"-b\"\n")
	}
	writeFreeBSDBridges(&rc, bridges)
	writeFreeBSDStaticRoutes(&rc, staticV4Routes, false)
	writeFreeBSDStaticRoutes(&rc, staticV6Routes, true)

	dhcp6c, err := freeBSDDHCP6C(router, aliases, pds)
	if err != nil {
		return FreeBSDConfig{}, err
	}
	dhclient := freeBSDDHClient(dhclientOptions)
	mpd5, err := freeBSDMPD5(pppoes)
	if err != nil {
		return FreeBSDConfig{}, err
	}
	return FreeBSDConfig{RCConf: rc.Bytes(), DHCP6C: dhcp6c, DHCPClient: dhclient, MPD5: mpd5}, nil
}

type freeBSDPD struct {
	Name                string
	IfName              string
	Profile             string
	PrefixLength        int
	IAID                string
	ServerID            string
	PriorPrefix         string
	AcquisitionStrategy string
	Lease               routerstate.PDLease
}

type freeBSDPPPoE struct {
	Name        string
	IfName      string
	LowerIfName string
	Password    string
	Spec        api.PPPoEInterfaceSpec
}

type freeBSDStaticRoute struct {
	Name        string
	IfName      string
	Destination string
	Via         string
}

func writeFreeBSDBridges(buf *bytes.Buffer, bridges []bridgeConfig) {
	if len(bridges) == 0 {
		return
	}
	var names []string
	for _, bridge := range bridges {
		names = append(names, bridge.IfName)
	}
	buf.WriteString("cloned_interfaces=\"" + strings.Join(names, " ") + "\"\n")
	for _, bridge := range bridges {
		var args []string
		for _, member := range bridge.Members {
			args = append(args, "addm "+member)
			if bridge.STP {
				if bridge.RSTP {
					args = append(args, "rstp "+member)
				} else {
					args = append(args, "stp "+member)
				}
			}
		}
		if bridge.MTU != 0 {
			args = append(args, fmt.Sprintf("mtu %d", bridge.MTU))
		}
		if bridge.MACAddress != "" {
			args = append(args, "ether "+bridge.MACAddress)
		}
		args = append(args, "up")
		buf.WriteString(fmt.Sprintf("ifconfig_%s=\"%s\"\n", bridge.IfName, strings.Join(args, " ")))
	}
}

func writeFreeBSDStaticRoutes(buf *bytes.Buffer, routes []freeBSDStaticRoute, ipv6 bool) {
	if len(routes) == 0 {
		return
	}
	sort.Slice(routes, func(i, j int) bool { return routes[i].Name < routes[j].Name })
	var names []string
	for _, route := range routes {
		names = append(names, freeBSDRouteLabel(route.Name))
	}
	if ipv6 {
		buf.WriteString("ipv6_static_routes=\"" + strings.Join(names, " ") + "\"\n")
	} else {
		buf.WriteString("static_routes=\"" + strings.Join(names, " ") + "\"\n")
	}
	for _, route := range routes {
		label := freeBSDRouteLabel(route.Name)
		via := route.Via
		if ipv6 && strings.HasPrefix(strings.ToLower(via), "fe80:") && route.IfName != "" && !strings.Contains(via, "%") {
			via += "%" + route.IfName
		}
		if ipv6 {
			buf.WriteString(fmt.Sprintf("ipv6_route_%s=\"%s %s\"\n", label, route.Destination, via))
		} else {
			buf.WriteString(fmt.Sprintf("route_%s=\"-net %s %s\"\n", label, route.Destination, via))
		}
	}
}

func freeBSDRouteLabel(name string) string {
	label := strings.Map(func(r rune) rune {
		switch {
		case r >= 'a' && r <= 'z':
			return r
		case r >= 'A' && r <= 'Z':
			return r
		case r >= '0' && r <= '9':
			return r
		case r == '_' || r == '-':
			return r
		default:
			return '_'
		}
	}, name)
	label = strings.ReplaceAll(label, "-", "_")
	if label == "" {
		return "route"
	}
	return label
}

func hasManagedFreeBSDPPPoE(pppoes []freeBSDPPPoE) bool {
	for _, pppoe := range pppoes {
		if pppoe.Spec.Managed {
			return true
		}
	}
	return false
}

func freeBSDMPD5(pppoes []freeBSDPPPoE) ([]byte, error) {
	if len(pppoes) == 0 {
		return nil, nil
	}
	sort.Slice(pppoes, func(i, j int) bool { return pppoes[i].Name < pppoes[j].Name })
	var buf bytes.Buffer
	buf.WriteString("# Generated by routerd. Do not edit by hand.\n")
	buf.WriteString("# This file uses FreeBSD mpd5 for PPPoE client sessions.\n\n")
	buf.WriteString("startup:\n\n")
	buf.WriteString("default:\n")
	managed := false
	for _, pppoe := range pppoes {
		if !pppoe.Spec.Managed {
			continue
		}
		managed = true
		buf.WriteString("  load " + freeBSDMPDLabel(pppoe.Name) + "\n")
	}
	if !managed {
		buf.WriteString("  # No managed PPPoE sessions are enabled.\n")
	}
	buf.WriteString("\n")

	for _, pppoe := range pppoes {
		spec := pppoe.Spec
		mtu := spec.MTU
		if mtu == 0 {
			mtu = 1492
		}
		mru := spec.MRU
		if mru == 0 {
			mru = 1492
		}
		lcpInterval := spec.LCPInterval
		if lcpInterval == 0 {
			lcpInterval = 20
		}
		lcpFailure := spec.LCPFailure
		if lcpFailure == 0 {
			lcpFailure = 3
		}
		label := freeBSDMPDLabel(pppoe.Name)
		bundle := freeBSDMPDName("B", pppoe.Name)
		link := freeBSDMPDName("L", pppoe.Name)

		buf.WriteString(label + ":\n")
		buf.WriteString("  create bundle static " + bundle + "\n")
		buf.WriteString("  set iface name " + pppoe.IfName + "\n")
		if spec.DefaultRoute {
			buf.WriteString("  set iface route default\n")
		}
		buf.WriteString("  set iface enable tcpmssfix\n")
		buf.WriteString("  set ipcp ranges 0.0.0.0/0 0.0.0.0/0\n")
		buf.WriteString("  create link static " + link + " pppoe\n")
		buf.WriteString("  set link action bundle " + bundle + "\n")
		buf.WriteString("  set auth authname " + strconv.Quote(spec.Username) + "\n")
		buf.WriteString("  set auth password " + strconv.Quote(pppoe.Password) + "\n")
		buf.WriteString("  set link max-redial 0\n")
		buf.WriteString(fmt.Sprintf("  set link mtu %d\n", mtu))
		buf.WriteString(fmt.Sprintf("  set link mru %d\n", mru))
		buf.WriteString(fmt.Sprintf("  set link keep-alive %d %d\n", lcpInterval, lcpInterval*lcpFailure))
		buf.WriteString("  set pppoe iface " + pppoe.LowerIfName + "\n")
		if spec.ServiceName != "" {
			buf.WriteString("  set pppoe service " + strconv.Quote(spec.ServiceName) + "\n")
		}
		if spec.ACName != "" {
			buf.WriteString("  set pppoe acname " + strconv.Quote(spec.ACName) + "\n")
		}
		buf.WriteString("  open\n\n")
	}
	return buf.Bytes(), nil
}

func freeBSDDHCP6C(router *api.Router, aliases map[string]string, pds []freeBSDPD) ([]byte, error) {
	if len(pds) == 0 {
		return nil, nil
	}
	sort.Slice(pds, func(i, j int) bool { return pds[i].Name < pds[j].Name })
	var buf bytes.Buffer
	buf.WriteString("# Generated by routerd. Do not edit by hand.\n")
	for i, pd := range pds {
		iaid := i
		if parsed, ok := parseIAID(pd.IAID); ok {
			iaid = int(parsed)
		}
		buf.WriteString(fmt.Sprintf("interface %s {\n", pd.IfName))
		buf.WriteString(fmt.Sprintf("  send ia-pd %d;\n", iaid))
		buf.WriteString("  request domain-name-servers;\n")
		buf.WriteString("};\n\n")
		buf.WriteString(fmt.Sprintf("id-assoc pd %d {\n", iaid))
		writeDHCP6CObservedLeaseComments(&buf, pd)
		for _, res := range router.Spec.Resources {
			if res.Kind != "IPv6DelegatedAddress" {
				continue
			}
			spec, err := res.IPv6DelegatedAddressSpec()
			if err != nil {
				return nil, err
			}
			if spec.PrefixDelegation != pd.Name {
				continue
			}
			ifname := aliases[spec.Interface]
			if ifname == "" {
				return nil, fmt.Errorf("%s references interface with empty ifname", res.ID())
			}
			buf.WriteString(fmt.Sprintf("  prefix-interface %s {\n", ifname))
			buf.WriteString(fmt.Sprintf("    sla-id %s;\n", defaultString(spec.SubnetID, "0")))
			if pd.PrefixLength > 0 && pd.PrefixLength <= 64 {
				buf.WriteString(fmt.Sprintf("    sla-len %d;\n", 64-pd.PrefixLength))
			}
			buf.WriteString("  };\n")
		}
		buf.WriteString("};\n\n")
	}
	return buf.Bytes(), nil
}

func writeDHCP6CObservedLeaseComments(buf *bytes.Buffer, pd freeBSDPD) {
	serverID := firstNonEmpty(pd.ServerID, pd.Lease.ServerID)
	priorPrefix := firstNonEmpty(pd.PriorPrefix, pd.Lease.PriorPrefix, pd.Lease.CurrentPrefix, pd.Lease.LastPrefix)
	strategy := firstNonEmpty(pd.AcquisitionStrategy, "hybrid")
	if serverID == "" && priorPrefix == "" && strategy == "hybrid" {
		return
	}
	buf.WriteString("  # routerd acquisition-strategy " + strategy + "\n")
	if serverID != "" {
		buf.WriteString("  # routerd observed-server-id " + colonHex(serverID) + "\n")
	}
	if priorPrefix != "" {
		buf.WriteString("  # routerd prior-prefix " + priorPrefix + "\n")
	}
}

func colonHex(value string) string {
	cleaned := strings.NewReplacer(":", "", "-", "", " ", "").Replace(value)
	if len(cleaned)%2 != 0 {
		return value
	}
	var parts []string
	for i := 0; i < len(cleaned); i += 2 {
		parts = append(parts, strings.ToLower(cleaned[i:i+2]))
	}
	return strings.Join(parts, ":")
}

func freeBSDDHCP6CFlags(pds []freeBSDPD) string {
	for _, pd := range pds {
		switch pd.Profile {
		case api.IPv6PDProfileNTTNGNDirectHikariDenwa, api.IPv6PDProfileNTTHGWLANPD:
			return "-n"
		}
	}
	return ""
}

func firstNonEmpty(values ...string) string {
	for _, value := range values {
		if strings.TrimSpace(value) != "" {
			return strings.TrimSpace(value)
		}
	}
	return ""
}

func freeBSDDHClient(options map[string]api.IPv4DHCPAddressSpec) []byte {
	if len(options) == 0 {
		return nil
	}
	var buf bytes.Buffer
	buf.WriteString("# Generated by routerd. Do not edit by hand.\n")
	for _, ifname := range sortedFreeBSDMapKeysSpec(options) {
		spec := options[ifname]
		buf.WriteString(fmt.Sprintf("interface \"%s\" {\n", ifname))
		var ignored []string
		if spec.UseRoutes != nil && !*spec.UseRoutes {
			ignored = append(ignored, "routers")
		}
		if spec.UseDNS != nil && !*spec.UseDNS {
			ignored = append(ignored, "domain-name", "domain-name-servers", "domain-search")
		}
		if len(ignored) > 0 {
			buf.WriteString("  ignore " + strings.Join(ignored, ", ") + ";\n")
		}
		buf.WriteString("}\n\n")
	}
	return buf.Bytes()
}

func freeBSDIPv4CIDR(value string) (string, error) {
	prefix, err := netip.ParsePrefix(value)
	if err != nil {
		return "", err
	}
	return prefix.Addr().String() + "/" + fmt.Sprintf("%d", prefix.Bits()), nil
}

func sortedFreeBSDMapKeys(values map[string]bool) []string {
	var keys []string
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func sortedFreeBSDMapKeysSpec(values map[string]api.IPv4DHCPAddressSpec) []string {
	var keys []string
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func freeBSDMPDLabel(name string) string {
	return "routerd_" + freeBSDMPDName("", name)
}

func freeBSDMPDName(prefix, name string) string {
	var b strings.Builder
	b.WriteString(prefix)
	for _, r := range name {
		switch {
		case r >= 'a' && r <= 'z':
			b.WriteRune(r)
		case r >= 'A' && r <= 'Z':
			b.WriteRune(r)
		case r >= '0' && r <= '9':
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
	}
	if b.Len() == len(prefix) {
		b.WriteString("unnamed")
	}
	return b.String()
}
