package render

import (
	"bytes"
	"fmt"
	"sort"

	"gopkg.in/yaml.v3"

	"routerd/pkg/api"
)

type netplanDocument struct {
	Network netplanNetwork `yaml:"network"`
}

type netplanNetwork struct {
	Version   int                        `yaml:"version"`
	Renderer  string                     `yaml:"renderer,omitempty"`
	Ethernets map[string]netplanEthernet `yaml:"ethernets"`
}

type netplanEthernet struct {
	Optional       bool                  `yaml:"optional,omitempty"`
	DHCP4          bool                  `yaml:"dhcp4"`
	DHCP4Overrides *netplanDHCPOverrides `yaml:"dhcp4-overrides,omitempty"`
	DHCP6          bool                  `yaml:"dhcp6"`
	AcceptRA       bool                  `yaml:"accept-ra"`
	LinkLocal      []string              `yaml:"link-local"`
	Addresses      []string              `yaml:"addresses,omitempty"`
}

type netplanDHCPOverrides struct {
	UseRoutes   *bool `yaml:"use-routes,omitempty"`
	UseDNS      *bool `yaml:"use-dns,omitempty"`
	RouteMetric int   `yaml:"route-metric,omitempty"`
}

type netplanInterface struct {
	Name             string
	IfName           string
	AdminUp          bool
	Addresses        []string
	DHCP4            bool
	DHCP4UseRoutes   *bool
	DHCP4UseDNS      *bool
	DHCP4RouteMetric int
	DHCP6            bool
	AcceptRA         bool
	IPv6LinkLocal    bool
}

func Netplan(router *api.Router) ([]byte, error) {
	interfaces := map[string]*netplanInterface{}
	var names []string

	for _, res := range router.Spec.Resources {
		if res.APIVersion != api.NetAPIVersion || res.Kind != "Interface" {
			continue
		}
		spec, err := res.InterfaceSpec()
		if err != nil {
			return nil, err
		}
		owner := spec.Owner
		if owner == "" && spec.Managed {
			owner = "routerd"
		}
		if !spec.Managed || owner == "external" {
			continue
		}
		interfaces[res.Metadata.Name] = &netplanInterface{
			Name:    res.Metadata.Name,
			IfName:  spec.IfName,
			AdminUp: spec.AdminUp,
		}
		names = append(names, res.Metadata.Name)
	}

	for _, res := range router.Spec.Resources {
		switch res.Kind {
		case "IPv4StaticAddress":
			spec, err := res.IPv4StaticAddressSpec()
			if err != nil {
				return nil, err
			}
			if iface := interfaces[spec.Interface]; iface != nil {
				iface.Addresses = append(iface.Addresses, spec.Address)
			}
		case "IPv4DHCPAddress":
			spec, err := res.IPv4DHCPAddressSpec()
			if err != nil {
				return nil, err
			}
			if iface := interfaces[spec.Interface]; iface != nil {
				iface.DHCP4 = true
				iface.DHCP4UseRoutes = spec.UseRoutes
				iface.DHCP4UseDNS = spec.UseDNS
				iface.DHCP4RouteMetric = spec.RouteMetric
			}
		case "IPv6DHCPAddress":
			spec, err := res.IPv6DHCPAddressSpec()
			if err != nil {
				return nil, err
			}
			if iface := interfaces[spec.Interface]; iface != nil {
				iface.DHCP6 = true
				iface.IPv6LinkLocal = true
			}
		case "IPv6RAAddress":
			spec, err := res.IPv6RAAddressSpec()
			if err != nil {
				return nil, err
			}
			if iface := interfaces[spec.Interface]; iface != nil && api.BoolDefault(spec.Managed, true) {
				iface.AcceptRA = true
				iface.IPv6LinkLocal = true
			}
		case "IPv6DelegatedAddress":
			spec, err := res.IPv6DelegatedAddressSpec()
			if err != nil {
				return nil, err
			}
			if iface := interfaces[spec.Interface]; iface != nil {
				iface.IPv6LinkLocal = true
			}
		}
	}

	sort.Strings(names)
	if len(names) == 0 {
		return nil, nil
	}
	ethernets := map[string]netplanEthernet{}
	for _, name := range names {
		iface := interfaces[name]
		if iface.IfName == "" {
			return nil, fmt.Errorf("Interface %q has empty ifname", name)
		}
		linkLocal := []string{}
		if iface.IPv6LinkLocal {
			linkLocal = []string{"ipv6"}
		}
		var dhcp4Overrides *netplanDHCPOverrides
		if iface.DHCP4UseRoutes != nil || iface.DHCP4UseDNS != nil || iface.DHCP4RouteMetric != 0 {
			dhcp4Overrides = &netplanDHCPOverrides{
				UseRoutes:   iface.DHCP4UseRoutes,
				UseDNS:      iface.DHCP4UseDNS,
				RouteMetric: iface.DHCP4RouteMetric,
			}
		}
		ethernets[iface.IfName] = netplanEthernet{
			Optional:       true,
			DHCP4:          iface.DHCP4,
			DHCP4Overrides: dhcp4Overrides,
			DHCP6:          iface.DHCP6,
			AcceptRA:       iface.DHCP6 || iface.AcceptRA,
			LinkLocal:      linkLocal,
			Addresses:      iface.Addresses,
		}
	}

	doc := netplanDocument{
		Network: netplanNetwork{
			Version:   2,
			Renderer:  "networkd",
			Ethernets: ethernets,
		},
	}
	var buf bytes.Buffer
	buf.WriteString("# Generated by routerd. Do not edit by hand.\n")
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(doc); err != nil {
		return nil, err
	}
	if err := enc.Close(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
