package render

import (
	"bytes"
	"fmt"
	"sort"

	"gopkg.in/yaml.v3"

	"routerd/pkg/api"
)

type netplanDocument struct {
	Network netplanNetwork `yaml:"network"`
}

type netplanNetwork struct {
	Version   int                        `yaml:"version"`
	Renderer  string                     `yaml:"renderer,omitempty"`
	Ethernets map[string]netplanEthernet `yaml:"ethernets"`
}

type netplanEthernet struct {
	Optional        bool                  `yaml:"optional,omitempty"`
	DHCPv4          bool                  `yaml:"dhcp4"`
	DHCPv4Overrides *netplanDHCPOverrides `yaml:"dhcp4-overrides,omitempty"`
	DHCPv6          bool                  `yaml:"dhcp6"`
	AcceptRA        bool                  `yaml:"accept-ra"`
	LinkLocal       []string              `yaml:"link-local"`
	Addresses       []string              `yaml:"addresses,omitempty"`
}

type netplanDHCPOverrides struct {
	UseRoutes   *bool `yaml:"use-routes,omitempty"`
	UseDNS      *bool `yaml:"use-dns,omitempty"`
	RouteMetric int   `yaml:"route-metric,omitempty"`
}

type netplanInterface struct {
	Name              string
	IfName            string
	AdminUp           bool
	Addresses         []string
	DHCPv4            bool
	DHCPv4UseRoutes   *bool
	DHCPv4UseDNS      *bool
	DHCPv4RouteMetric int
	DHCPv6            bool
	AcceptRA          bool
	IPv6LinkLocal     bool
}

func Netplan(router *api.Router) ([]byte, error) {
	interfaces := map[string]*netplanInterface{}
	var names []string

	for _, res := range router.Spec.Resources {
		if res.APIVersion != api.NetAPIVersion || res.Kind != "Interface" {
			continue
		}
		spec, err := res.InterfaceSpec()
		if err != nil {
			return nil, err
		}
		owner := spec.Owner
		if owner == "" && spec.Managed {
			owner = "routerd"
		}
		if !spec.Managed || owner == "external" {
			continue
		}
		interfaces[res.Metadata.Name] = &netplanInterface{
			Name:    res.Metadata.Name,
			IfName:  spec.IfName,
			AdminUp: spec.AdminUp,
		}
		names = append(names, res.Metadata.Name)
	}

	for _, res := range router.Spec.Resources {
		switch res.Kind {
		case "IPv4StaticAddress":
			spec, err := res.IPv4StaticAddressSpec()
			if err != nil {
				return nil, err
			}
			if iface := interfaces[spec.Interface]; iface != nil {
				iface.Addresses = append(iface.Addresses, spec.Address)
			}
		case "DHCPv4Address":
			spec, err := res.DHCPv4AddressSpec()
			if err != nil {
				return nil, err
			}
			if iface := interfaces[spec.Interface]; iface != nil {
				iface.DHCPv4 = true
				iface.DHCPv4UseRoutes = spec.UseRoutes
				iface.DHCPv4UseDNS = spec.UseDNS
				iface.DHCPv4RouteMetric = spec.RouteMetric
			}
		case "DHCPv6Address":
			spec, err := res.DHCPv6AddressSpec()
			if err != nil {
				return nil, err
			}
			if iface := interfaces[spec.Interface]; iface != nil {
				iface.DHCPv6 = true
				iface.IPv6LinkLocal = true
			}
		case "IPv6RAAddress":
			spec, err := res.IPv6RAAddressSpec()
			if err != nil {
				return nil, err
			}
			if iface := interfaces[spec.Interface]; iface != nil && api.BoolDefault(spec.Managed, true) {
				iface.AcceptRA = true
				iface.IPv6LinkLocal = true
			}
		case "IPv6DelegatedAddress":
			spec, err := res.IPv6DelegatedAddressSpec()
			if err != nil {
				return nil, err
			}
			if iface := interfaces[spec.Interface]; iface != nil {
				iface.IPv6LinkLocal = true
			}
		}
	}

	sort.Strings(names)
	if len(names) == 0 {
		return nil, nil
	}
	ethernets := map[string]netplanEthernet{}
	for _, name := range names {
		iface := interfaces[name]
		if iface.IfName == "" {
			return nil, fmt.Errorf("Interface %q has empty ifname", name)
		}
		linkLocal := []string{}
		if iface.IPv6LinkLocal {
			linkLocal = []string{"ipv6"}
		}
		var dhcp4Overrides *netplanDHCPOverrides
		if iface.DHCPv4UseRoutes != nil || iface.DHCPv4UseDNS != nil || iface.DHCPv4RouteMetric != 0 {
			dhcp4Overrides = &netplanDHCPOverrides{
				UseRoutes:   iface.DHCPv4UseRoutes,
				UseDNS:      iface.DHCPv4UseDNS,
				RouteMetric: iface.DHCPv4RouteMetric,
			}
		}
		ethernets[iface.IfName] = netplanEthernet{
			Optional:        true,
			DHCPv4:          iface.DHCPv4,
			DHCPv4Overrides: dhcp4Overrides,
			DHCPv6:          iface.DHCPv6,
			AcceptRA:        iface.DHCPv6 || iface.AcceptRA,
			LinkLocal:       linkLocal,
			Addresses:       iface.Addresses,
		}
	}

	doc := netplanDocument{
		Network: netplanNetwork{
			Version:   2,
			Renderer:  "networkd",
			Ethernets: ethernets,
		},
	}
	var buf bytes.Buffer
	buf.WriteString("# Generated by routerd. Do not edit by hand.\n")
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(doc); err != nil {
		return nil, err
	}
	if err := enc.Close(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
