package render

import (
	"bytes"
	"fmt"
	"sort"

	"gopkg.in/yaml.v3"

	"routerd/pkg/api"
)

type netplanDocument struct {
	Network netplanNetwork `yaml:"network"`
}

type netplanNetwork struct {
	Version   int                        `yaml:"version"`
	Renderer  string                     `yaml:"renderer,omitempty"`
	Ethernets map[string]netplanEthernet `yaml:"ethernets"`
}

type netplanEthernet struct {
	Optional  bool     `yaml:"optional,omitempty"`
	DHCP4     bool     `yaml:"dhcp4"`
	DHCP6     bool     `yaml:"dhcp6"`
	AcceptRA  bool     `yaml:"accept-ra"`
	LinkLocal []string `yaml:"link-local"`
	Addresses []string `yaml:"addresses,omitempty"`
}

type netplanInterface struct {
	Name          string
	IfName        string
	AdminUp       bool
	Addresses     []string
	DHCP4         bool
	DHCP6         bool
	IPv6LinkLocal bool
}

func Netplan(router *api.Router) ([]byte, error) {
	interfaces := map[string]*netplanInterface{}
	var names []string

	for _, res := range router.Spec.Resources {
		if res.APIVersion != api.NetAPIVersion || res.Kind != "Interface" {
			continue
		}
		spec, err := res.InterfaceSpec()
		if err != nil {
			return nil, err
		}
		owner := spec.Owner
		if owner == "" && spec.Managed {
			owner = "routerd"
		}
		if !spec.Managed || owner == "external" {
			continue
		}
		interfaces[res.Metadata.Name] = &netplanInterface{
			Name:    res.Metadata.Name,
			IfName:  spec.IfName,
			AdminUp: spec.AdminUp,
		}
		names = append(names, res.Metadata.Name)
	}

	for _, res := range router.Spec.Resources {
		switch res.Kind {
		case "IPv4StaticAddress":
			spec, err := res.IPv4StaticAddressSpec()
			if err != nil {
				return nil, err
			}
			if iface := interfaces[spec.Interface]; iface != nil {
				iface.Addresses = append(iface.Addresses, spec.Address)
			}
		case "IPv4DHCPAddress":
			spec, err := res.IPv4DHCPAddressSpec()
			if err != nil {
				return nil, err
			}
			if iface := interfaces[spec.Interface]; iface != nil {
				iface.DHCP4 = true
			}
		case "IPv6DHCPAddress":
			spec, err := res.IPv6DHCPAddressSpec()
			if err != nil {
				return nil, err
			}
			if iface := interfaces[spec.Interface]; iface != nil {
				iface.DHCP6 = true
				iface.IPv6LinkLocal = true
			}
		case "IPv6DelegatedAddress":
			spec, err := res.IPv6DelegatedAddressSpec()
			if err != nil {
				return nil, err
			}
			if iface := interfaces[spec.Interface]; iface != nil {
				iface.IPv6LinkLocal = true
			}
		}
	}

	sort.Strings(names)
	if len(names) == 0 {
		return nil, nil
	}
	ethernets := map[string]netplanEthernet{}
	for _, name := range names {
		iface := interfaces[name]
		if iface.IfName == "" {
			return nil, fmt.Errorf("Interface %q has empty ifname", name)
		}
		linkLocal := []string{}
		if iface.IPv6LinkLocal {
			linkLocal = []string{"ipv6"}
		}
		ethernets[iface.IfName] = netplanEthernet{
			Optional:  true,
			DHCP4:     iface.DHCP4,
			DHCP6:     iface.DHCP6,
			AcceptRA:  iface.DHCP6,
			LinkLocal: linkLocal,
			Addresses: iface.Addresses,
		}
	}

	doc := netplanDocument{
		Network: netplanNetwork{
			Version:   2,
			Renderer:  "networkd",
			Ethernets: ethernets,
		},
	}
	var buf bytes.Buffer
	buf.WriteString("# Generated by routerd. Do not edit by hand.\n")
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(doc); err != nil {
		return nil, err
	}
	if err := enc.Close(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
