package render

import (
	"bytes"
	"fmt"
	"net/netip"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"routerd/pkg/api"
)

type File struct {
	Path string
	Data []byte
}

type pdSource struct {
	Name         string
	IfName       string
	Client       string
	Profile      string
	PrefixLength int
	IAID         string
	DUIDType     string
	DUIDRawData  string
}

func NetworkdDropins(router *api.Router) ([]File, error) {
	aliases := linkAliases(router)

	pds := map[string]pdSource{}
	raIfaces := map[string]bool{}
	externalPDIfaces := map[string]bool{}
	for _, res := range router.Spec.Resources {
		switch res.Kind {
		case "IPv6RAAddress":
			spec, err := res.IPv6RAAddressSpec()
			if err != nil {
				return nil, err
			}
			if ifname := aliases[spec.Interface]; ifname != "" {
				raIfaces[ifname] = api.BoolDefault(spec.Managed, true)
			}
			continue
		case "IPv6PrefixDelegation":
		default:
			continue
		}
		spec, err := res.IPv6PrefixDelegationSpec()
		if err != nil {
			return nil, err
		}
		profile := defaultString(spec.Profile, api.IPv6PDProfileDefault)
		client := effectiveNetworkdIPv6PDClient(profile, spec.Client)
		pds[res.Metadata.Name] = pdSource{
			Name:         res.Metadata.Name,
			IfName:       aliases[spec.Interface],
			Client:       client,
			Profile:      profile,
			PrefixLength: api.EffectiveIPv6PDPrefixLength(profile, spec.PrefixLength),
			IAID:         strings.TrimSpace(spec.IAID),
			DUIDType:     api.EffectiveIPv6PDDUIDType(profile, spec.DUIDType),
			DUIDRawData:  spec.DUIDRawData,
		}
		if isExternalIPv6PDClient(client) {
			if ifname := aliases[spec.Interface]; ifname != "" {
				externalPDIfaces[ifname] = true
			}
		}
	}

	var files []File
	bridges, err := bridgeConfigs(router, aliases)
	if err != nil {
		return nil, err
	}
	for _, bridge := range bridges {
		var netdev bytes.Buffer
		netdev.WriteString("# Generated by routerd. Do not edit by hand.\n")
		netdev.WriteString("[NetDev]\n")
		netdev.WriteString("Name=" + bridge.IfName + "\n")
		netdev.WriteString("Kind=bridge\n")
		if bridge.MACAddress != "" {
			netdev.WriteString("MACAddress=" + bridge.MACAddress + "\n")
		}
		if bridge.MTU != 0 {
			netdev.WriteString(fmt.Sprintf("MTUBytes=%d\n", bridge.MTU))
		}
		netdev.WriteString("\n[Bridge]\n")
		netdev.WriteString("STP=" + boolString(bridge.STP) + "\n")
		netdev.WriteString("MulticastSnooping=" + boolString(bridge.MulticastSnooping) + "\n")
		netdev.WriteString(fmt.Sprintf("ForwardDelaySec=%ds\n", bridge.ForwardDelay))
		netdev.WriteString(fmt.Sprintf("HelloTimeSec=%ds\n", bridge.HelloTime))
		files = append(files, File{
			Path: filepath.Join("/etc/systemd/network", "30-routerd-"+bridge.IfName+".netdev"),
			Data: netdev.Bytes(),
		})
		var network bytes.Buffer
		network.WriteString("# Generated by routerd. Do not edit by hand.\n")
		network.WriteString("[Match]\n")
		network.WriteString("Name=" + bridge.IfName + "\n\n")
		network.WriteString("[Network]\n")
		network.WriteString("ConfigureWithoutCarrier=yes\n")
		for _, address := range networkdStaticIPv4Addresses(router, aliases, bridge.IfName) {
			network.WriteString("Address=" + address + "\n")
		}
		files = append(files, File{
			Path: filepath.Join("/etc/systemd/network", "30-routerd-"+bridge.IfName+".network"),
			Data: network.Bytes(),
		})
		for _, member := range bridge.Members {
			var memberDropin bytes.Buffer
			memberDropin.WriteString("# Generated by routerd. Do not edit by hand.\n")
			memberDropin.WriteString("[Network]\n")
			memberDropin.WriteString("Bridge=" + bridge.IfName + "\n")
			files = append(files, File{
				Path: filepath.Join(networkdDropinDir(member), "88-routerd-bridge.conf"),
				Data: memberDropin.Bytes(),
			})
		}
	}
	vxlans, err := vxlanConfigs(router, aliases)
	if err != nil {
		return nil, err
	}
	for _, vxlan := range vxlans {
		var netdev bytes.Buffer
		netdev.WriteString("# Generated by routerd. Do not edit by hand.\n")
		netdev.WriteString("[NetDev]\n")
		netdev.WriteString("Name=" + vxlan.IfName + "\n")
		netdev.WriteString("Kind=vxlan\n")
		if vxlan.MTU != 0 {
			netdev.WriteString(fmt.Sprintf("MTUBytes=%d\n", vxlan.MTU))
		}
		netdev.WriteString("\n[VXLAN]\n")
		netdev.WriteString(fmt.Sprintf("VNI=%d\n", vxlan.VNI))
		netdev.WriteString("Local=" + vxlan.LocalAddress + "\n")
		netdev.WriteString("Independent=yes\n")
		netdev.WriteString("UDPChecksum=yes\n")
		netdev.WriteString(fmt.Sprintf("PortRange=%d-%d\n", vxlan.UDPPort, vxlan.UDPPort))
		if vxlan.MulticastGroup != "" {
			netdev.WriteString("Group=" + vxlan.MulticastGroup + "\n")
		} else if len(vxlan.Remotes) > 0 {
			netdev.WriteString("Remote=" + vxlan.Remotes[0] + "\n")
		}
		netdev.WriteString(fmt.Sprintf("DestinationPort=%d\n", vxlan.UDPPort))
		files = append(files, File{
			Path: filepath.Join("/etc/systemd/network", "31-routerd-"+vxlan.IfName+".netdev"),
			Data: netdev.Bytes(),
		})
		var network bytes.Buffer
		network.WriteString("# Generated by routerd. Do not edit by hand.\n")
		network.WriteString("[Match]\n")
		network.WriteString("Name=" + vxlan.IfName + "\n\n")
		network.WriteString("[Network]\n")
		for _, address := range networkdStaticIPv4Addresses(router, aliases, vxlan.IfName) {
			network.WriteString("Address=" + address + "\n")
		}
		if vxlan.BridgeIfName != "" {
			network.WriteString("Bridge=" + vxlan.BridgeIfName + "\n")
		}
		if len(vxlan.Remotes) > 1 {
			for _, remote := range vxlan.Remotes {
				network.WriteString("\n[BridgeFDB]\n")
				network.WriteString("MACAddress=00:00:00:00:00:00\n")
				network.WriteString("Destination=" + remote + "\n")
			}
		}
		files = append(files, File{
			Path: filepath.Join("/etc/systemd/network", "31-routerd-"+vxlan.IfName+".network"),
			Data: network.Bytes(),
		})
	}
	var raNames []string
	for ifname, managed := range raIfaces {
		if managed {
			raNames = append(raNames, ifname)
		}
	}
	sort.Strings(raNames)
	for _, ifname := range raNames {
		var buf bytes.Buffer
		buf.WriteString("[Network]\nIPv6AcceptRA=yes\n")
		if externalPDIfaces[ifname] {
			buf.WriteString("\n[IPv6AcceptRA]\nDHCPv6Client=no\nUseDNS=no\nUseDomains=no\n")
		}
		files = append(files, File{
			Path: filepath.Join(networkdDropinDir(ifname), "89-routerd-ipv6-ra.conf"),
			Data: buf.Bytes(),
		})
	}
	var names []string
	for name := range pds {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		source := pds[name]
		if source.Client != "networkd" {
			if source.IfName == "" {
				return nil, fmt.Errorf("IPv6PrefixDelegation %q has empty ifname", name)
			}
			files = append(files, File{
				Path: filepath.Join(networkdDropinDir(source.IfName), "90-routerd-dhcp6-pd.conf"),
				Data: networkdPDDisabledDropin("external DHCPv6-PD client " + source.Client + " owns this resource"),
			})
			continue
		}
		ifname := source.IfName
		if ifname == "" {
			return nil, fmt.Errorf("IPv6PrefixDelegation %q has empty ifname", name)
		}
		var buf bytes.Buffer
		writeDHCPv6PD(&buf, source)
		files = append(files, File{
			Path: filepath.Join(networkdDropinDir(ifname), "90-routerd-dhcp6-pd.conf"),
			Data: buf.Bytes(),
		})
	}

	for _, res := range router.Spec.Resources {
		if res.Kind != "IPv6DelegatedAddress" {
			continue
		}
		spec, err := res.IPv6DelegatedAddressSpec()
		if err != nil {
			return nil, err
		}
		ifname := aliases[spec.Interface]
		source := pds[spec.PrefixDelegation]
		if source.Client != "networkd" {
			if ifname != "" {
				files = append(files, File{
					Path: filepath.Join(networkdDropinDir(ifname), "90-routerd-dhcp6-pd.conf"),
					Data: networkdPDDisabledDropin("delegated prefix is managed outside systemd-networkd"),
				})
			}
			continue
		}
		if ifname == "" || source.IfName == "" {
			return nil, fmt.Errorf("%s references interface with empty ifname", res.ID())
		}
		var buf bytes.Buffer
		buf.WriteString("[Network]\n")
		if spec.SendRA {
			buf.WriteString("IPv6SendRA=yes\n")
		}
		buf.WriteString("DHCPPrefixDelegation=yes\n\n[DHCPPrefixDelegation]\n")
		buf.WriteString("UplinkInterface=" + source.IfName + "\n")
		buf.WriteString("SubnetId=" + defaultString(spec.SubnetID, "0") + "\n")
		buf.WriteString("Assign=yes\n")
		buf.WriteString("Token=" + spec.AddressSuffix + "\n")
		buf.WriteString("Announce=" + boolString(spec.Announce || spec.SendRA) + "\n")
		files = append(files, File{
			Path: filepath.Join(networkdDropinDir(ifname), "90-routerd-dhcp6-pd.conf"),
			Data: buf.Bytes(),
		})
	}
	for _, res := range router.Spec.Resources {
		if res.Kind != "NTPClient" {
			continue
		}
		spec, err := res.NTPClientSpec()
		if err != nil {
			return nil, err
		}
		if !spec.Managed || spec.Interface == "" {
			continue
		}
		ifname := aliases[spec.Interface]
		if ifname == "" {
			return nil, fmt.Errorf("%s references interface with empty ifname", res.ID())
		}
		var servers []string
		for _, server := range spec.Servers {
			server = strings.TrimSpace(server)
			if server != "" {
				servers = append(servers, server)
			}
		}
		if len(servers) == 0 {
			return nil, fmt.Errorf("%s spec.servers is required", res.ID())
		}
		var buf bytes.Buffer
		buf.WriteString("[Network]\n")
		buf.WriteString("NTP=" + strings.Join(servers, " ") + "\n")
		files = append(files, File{
			Path: filepath.Join(networkdDropinDir(ifname), "91-routerd-ntp.conf"),
			Data: buf.Bytes(),
		})
	}
	staticRoutes, err := networkdStaticRoutes(router, aliases)
	if err != nil {
		return nil, err
	}
	for ifname, routes := range staticRoutes {
		var buf bytes.Buffer
		buf.WriteString("# Generated by routerd. Do not edit by hand.\n")
		for _, route := range routes {
			buf.WriteString("\n[Route]\n")
			buf.WriteString("Destination=" + route.Destination + "\n")
			buf.WriteString("Gateway=" + route.Via + "\n")
			if route.Metric != 0 {
				buf.WriteString(fmt.Sprintf("Metric=%d\n", route.Metric))
			}
			if route.GatewayOnLink {
				buf.WriteString("GatewayOnLink=yes\n")
			}
		}
		files = append(files, File{
			Path: filepath.Join(networkdDropinDir(ifname), "92-routerd-static-routes.conf"),
			Data: buf.Bytes(),
		})
	}
	sort.Slice(files, func(i, j int) bool { return files[i].Path < files[j].Path })
	return files, nil
}

type networkdStaticRoute struct {
	Destination   string
	Via           string
	Metric        int
	GatewayOnLink bool
}

func networkdStaticRoutes(router *api.Router, aliases map[string]string) (map[string][]networkdStaticRoute, error) {
	out := map[string][]networkdStaticRoute{}
	for _, res := range router.Spec.Resources {
		switch res.Kind {
		case "IPv4StaticRoute":
			spec, err := res.IPv4StaticRouteSpec()
			if err != nil {
				return nil, err
			}
			ifname := aliases[spec.Interface]
			if ifname == "" {
				return nil, fmt.Errorf("%s references interface with empty ifname", res.ID())
			}
			out[ifname] = append(out[ifname], networkdStaticRoute{
				Destination: spec.Destination,
				Via:         spec.Via,
				Metric:      spec.Metric,
			})
		case "IPv6StaticRoute":
			spec, err := res.IPv6StaticRouteSpec()
			if err != nil {
				return nil, err
			}
			ifname := aliases[spec.Interface]
			if ifname == "" {
				return nil, fmt.Errorf("%s references interface with empty ifname", res.ID())
			}
			via, err := netip.ParseAddr(spec.Via)
			if err != nil {
				return nil, fmt.Errorf("%s spec.via is invalid: %w", res.ID(), err)
			}
			out[ifname] = append(out[ifname], networkdStaticRoute{
				Destination:   spec.Destination,
				Via:           spec.Via,
				Metric:        spec.Metric,
				GatewayOnLink: via.IsLinkLocalUnicast(),
			})
		}
	}
	for ifname := range out {
		sort.Slice(out[ifname], func(i, j int) bool {
			if out[ifname][i].Destination == out[ifname][j].Destination {
				return out[ifname][i].Via < out[ifname][j].Via
			}
			return out[ifname][i].Destination < out[ifname][j].Destination
		})
	}
	return out, nil
}

func networkdStaticIPv4Addresses(router *api.Router, aliases map[string]string, ifname string) []string {
	var addresses []string
	for _, res := range router.Spec.Resources {
		if res.Kind != "IPv4StaticAddress" {
			continue
		}
		spec, err := res.IPv4StaticAddressSpec()
		if err != nil {
			continue
		}
		if aliases[spec.Interface] == ifname {
			addresses = append(addresses, spec.Address)
		}
	}
	sort.Strings(addresses)
	return addresses
}

func networkdPDDisabledDropin(reason string) []byte {
	var buf bytes.Buffer
	buf.WriteString("# Generated by routerd. Do not edit by hand.\n")
	buf.WriteString("# " + reason + ".\n")
	buf.WriteString("[Network]\nIPv6AcceptRA=yes\n\n")
	buf.WriteString("[IPv6AcceptRA]\nDHCPv6Client=no\nUseDNS=no\nUseDomains=no\n")
	return buf.Bytes()
}

func isExternalIPv6PDClient(client string) bool {
	switch client {
	case "dhcp6c", "dhcpcd":
		return true
	default:
		return false
	}
}

func effectiveNetworkdIPv6PDClient(profile, configured string) string {
	return api.EffectiveIPv6PDClient("linux", false, profile, configured)
}

func writeDHCPv6PD(buf *bytes.Buffer, source pdSource) {
	buf.WriteString("[Network]\nDHCP=yes\nIPv6AcceptRA=yes\n\n[DHCPv6]\n")
	if source.IAID != "" {
		buf.WriteString("IAID=" + normalizeIAIDForRender(source.IAID) + "\n")
	}
	if source.DUIDType != "" {
		buf.WriteString("DUIDType=" + source.DUIDType + "\n")
	}
	if source.DUIDRawData != "" {
		buf.WriteString("DUIDRawData=" + formatColonHex(source.DUIDRawData) + "\n")
	}
	switch source.Profile {
	case api.IPv6PDProfileNTTNGNDirectHikariDenwa, api.IPv6PDProfileNTTHGWLANPD:
		buf.WriteString("UseAddress=no\n")
		buf.WriteString("UseDelegatedPrefix=yes\n")
		buf.WriteString("WithoutRA=solicit\n")
		buf.WriteString("RapidCommit=no\n")
	default:
		buf.WriteString("UseDelegatedPrefix=yes\n")
		buf.WriteString("WithoutRA=solicit\n")
	}
	if source.PrefixLength != 0 && !api.IsNTTIPv6PDProfile(source.Profile) {
		buf.WriteString(fmt.Sprintf("PrefixDelegationHint=::/%d\n", source.PrefixLength))
	}
}

func normalizeIAIDForRender(value string) string {
	parsed, ok := parseIAID(value)
	if !ok {
		return value
	}
	return fmt.Sprintf("%d", parsed)
}

func parseIAID(value string) (uint32, bool) {
	value = strings.TrimSpace(value)
	if value == "" {
		return 0, false
	}
	if strings.HasPrefix(value, "0x") || strings.HasPrefix(value, "0X") {
		parsed, err := strconv.ParseUint(value[2:], 16, 32)
		return uint32(parsed), err == nil
	}
	if len(value) == 8 && isHexString(value) {
		parsed, err := strconv.ParseUint(value, 16, 32)
		return uint32(parsed), err == nil
	}
	parsed, err := strconv.ParseUint(value, 10, 32)
	return uint32(parsed), err == nil
}

func formatColonHex(value string) string {
	value = strings.ToLower(strings.TrimSpace(value))
	value = strings.ReplaceAll(value, ":", "")
	if len(value)%2 != 0 || !isHexString(value) {
		return strings.TrimSpace(value)
	}
	var parts []string
	for i := 0; i < len(value); i += 2 {
		parts = append(parts, value[i:i+2])
	}
	return strings.Join(parts, ":")
}

func isHexString(value string) bool {
	if value == "" {
		return false
	}
	for _, r := range strings.ToLower(value) {
		if (r < '0' || r > '9') && (r < 'a' || r > 'f') {
			return false
		}
	}
	return true
}

func networkdDropinDir(ifname string) string {
	return "/etc/systemd/network/10-netplan-" + sanitizeNetworkdName(ifname) + ".network.d"
}

func sanitizeNetworkdName(name string) string {
	return strings.NewReplacer("/", "-", "\x00", "").Replace(name)
}

func boolString(value bool) string {
	if value {
		return "yes"
	}
	return "no"
}

func defaultString(value, fallback string) string {
	if value == "" {
		return fallback
	}
	return value
}
