package render

import (
	"bytes"
	"fmt"
	"net/netip"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"routerd/pkg/api"
)

type File struct {
	Path string
	Data []byte
}

func NetworkdDropins(router *api.Router) ([]File, error) {
	aliases := linkAliases(router)

	var files []File
	bridges, err := bridgeConfigs(router, aliases)
	if err != nil {
		return nil, err
	}
	for _, bridge := range bridges {
		var netdev bytes.Buffer
		netdev.WriteString("# Generated by routerd. Do not edit by hand.\n")
		netdev.WriteString("[NetDev]\n")
		netdev.WriteString("Name=" + bridge.IfName + "\n")
		netdev.WriteString("Kind=bridge\n")
		if bridge.MACAddress != "" {
			netdev.WriteString("MACAddress=" + bridge.MACAddress + "\n")
		}
		if bridge.MTU != 0 {
			netdev.WriteString(fmt.Sprintf("MTUBytes=%d\n", bridge.MTU))
		}
		netdev.WriteString("\n[Bridge]\n")
		netdev.WriteString("STP=" + boolString(bridge.STP) + "\n")
		netdev.WriteString("MulticastSnooping=" + boolString(bridge.MulticastSnooping) + "\n")
		netdev.WriteString(fmt.Sprintf("ForwardDelaySec=%ds\n", bridge.ForwardDelay))
		netdev.WriteString(fmt.Sprintf("HelloTimeSec=%ds\n", bridge.HelloTime))
		files = append(files, File{
			Path: filepath.Join("/etc/systemd/network", "30-routerd-"+bridge.IfName+".netdev"),
			Data: netdev.Bytes(),
		})
		var network bytes.Buffer
		network.WriteString("# Generated by routerd. Do not edit by hand.\n")
		network.WriteString("[Match]\n")
		network.WriteString("Name=" + bridge.IfName + "\n\n")
		network.WriteString("[Network]\n")
		network.WriteString("ConfigureWithoutCarrier=yes\n")
		for _, address := range networkdStaticIPv4Addresses(router, aliases, bridge.IfName) {
			network.WriteString("Address=" + address + "\n")
		}
		files = append(files, File{
			Path: filepath.Join("/etc/systemd/network", "30-routerd-"+bridge.IfName+".network"),
			Data: network.Bytes(),
		})
		for _, member := range bridge.Members {
			var memberDropin bytes.Buffer
			memberDropin.WriteString("# Generated by routerd. Do not edit by hand.\n")
			memberDropin.WriteString("[Network]\n")
			memberDropin.WriteString("Bridge=" + bridge.IfName + "\n")
			files = append(files, File{
				Path: filepath.Join(networkdDropinDir(member), "88-routerd-bridge.conf"),
				Data: memberDropin.Bytes(),
			})
		}
	}
	vxlans, err := vxlanConfigs(router, aliases)
	if err != nil {
		return nil, err
	}
	for _, vxlan := range vxlans {
		var netdev bytes.Buffer
		netdev.WriteString("# Generated by routerd. Do not edit by hand.\n")
		netdev.WriteString("[NetDev]\n")
		netdev.WriteString("Name=" + vxlan.IfName + "\n")
		netdev.WriteString("Kind=vxlan\n")
		if vxlan.MTU != 0 {
			netdev.WriteString(fmt.Sprintf("MTUBytes=%d\n", vxlan.MTU))
		}
		netdev.WriteString("\n[VXLAN]\n")
		netdev.WriteString(fmt.Sprintf("VNI=%d\n", vxlan.VNI))
		netdev.WriteString("Local=" + vxlan.LocalAddress + "\n")
		netdev.WriteString("Independent=yes\n")
		netdev.WriteString("UDPChecksum=yes\n")
		netdev.WriteString(fmt.Sprintf("PortRange=%d-%d\n", vxlan.UDPPort, vxlan.UDPPort))
		if vxlan.MulticastGroup != "" {
			netdev.WriteString("Group=" + vxlan.MulticastGroup + "\n")
		} else if len(vxlan.Remotes) > 0 {
			netdev.WriteString("Remote=" + vxlan.Remotes[0] + "\n")
		}
		netdev.WriteString(fmt.Sprintf("DestinationPort=%d\n", vxlan.UDPPort))
		files = append(files, File{
			Path: filepath.Join("/etc/systemd/network", "31-routerd-"+vxlan.IfName+".netdev"),
			Data: netdev.Bytes(),
		})
		var network bytes.Buffer
		network.WriteString("# Generated by routerd. Do not edit by hand.\n")
		network.WriteString("[Match]\n")
		network.WriteString("Name=" + vxlan.IfName + "\n\n")
		network.WriteString("[Network]\n")
		for _, address := range networkdStaticIPv4Addresses(router, aliases, vxlan.IfName) {
			network.WriteString("Address=" + address + "\n")
		}
		if vxlan.BridgeIfName != "" {
			network.WriteString("Bridge=" + vxlan.BridgeIfName + "\n")
		}
		if len(vxlan.Remotes) > 1 {
			for _, remote := range vxlan.Remotes {
				network.WriteString("\n[BridgeFDB]\n")
				network.WriteString("MACAddress=00:00:00:00:00:00\n")
				network.WriteString("Destination=" + remote + "\n")
			}
		}
		files = append(files, File{
			Path: filepath.Join("/etc/systemd/network", "31-routerd-"+vxlan.IfName+".network"),
			Data: network.Bytes(),
		})
	}
	for _, res := range router.Spec.Resources {
		if res.Kind != "NTPClient" {
			continue
		}
		spec, err := res.NTPClientSpec()
		if err != nil {
			return nil, err
		}
		if !spec.Managed || spec.Interface == "" {
			continue
		}
		ifname := aliases[spec.Interface]
		if ifname == "" {
			return nil, fmt.Errorf("%s references interface with empty ifname", res.ID())
		}
		var servers []string
		for _, server := range spec.Servers {
			server = strings.TrimSpace(server)
			if server != "" {
				servers = append(servers, server)
			}
		}
		if len(servers) == 0 {
			return nil, fmt.Errorf("%s spec.servers is required", res.ID())
		}
		var buf bytes.Buffer
		buf.WriteString("[Network]\n")
		buf.WriteString("NTP=" + strings.Join(servers, " ") + "\n")
		files = append(files, File{
			Path: filepath.Join(networkdDropinDir(ifname), "91-routerd-ntp.conf"),
			Data: buf.Bytes(),
		})
	}
	staticRoutes, err := networkdStaticRoutes(router, aliases)
	if err != nil {
		return nil, err
	}
	for ifname, routes := range staticRoutes {
		var buf bytes.Buffer
		buf.WriteString("# Generated by routerd. Do not edit by hand.\n")
		for _, route := range routes {
			buf.WriteString("\n[Route]\n")
			buf.WriteString("Destination=" + route.Destination + "\n")
			buf.WriteString("Gateway=" + route.Via + "\n")
			if route.Metric != 0 {
				buf.WriteString(fmt.Sprintf("Metric=%d\n", route.Metric))
			}
			if route.GatewayOnLink {
				buf.WriteString("GatewayOnLink=yes\n")
			}
		}
		files = append(files, File{
			Path: filepath.Join(networkdDropinDir(ifname), "92-routerd-static-routes.conf"),
			Data: buf.Bytes(),
		})
	}
	sort.Slice(files, func(i, j int) bool { return files[i].Path < files[j].Path })
	return files, nil
}

type networkdStaticRoute struct {
	Destination   string
	Via           string
	Metric        int
	GatewayOnLink bool
}

func networkdStaticRoutes(router *api.Router, aliases map[string]string) (map[string][]networkdStaticRoute, error) {
	out := map[string][]networkdStaticRoute{}
	for _, res := range router.Spec.Resources {
		switch res.Kind {
		case "IPv4StaticRoute":
			spec, err := res.IPv4StaticRouteSpec()
			if err != nil {
				return nil, err
			}
			ifname := aliases[spec.Interface]
			if ifname == "" {
				return nil, fmt.Errorf("%s references interface with empty ifname", res.ID())
			}
			out[ifname] = append(out[ifname], networkdStaticRoute{
				Destination: spec.Destination,
				Via:         spec.Via,
				Metric:      spec.Metric,
			})
		case "IPv6StaticRoute":
			spec, err := res.IPv6StaticRouteSpec()
			if err != nil {
				return nil, err
			}
			ifname := aliases[spec.Interface]
			if ifname == "" {
				return nil, fmt.Errorf("%s references interface with empty ifname", res.ID())
			}
			via, err := netip.ParseAddr(spec.Via)
			if err != nil {
				return nil, fmt.Errorf("%s spec.via is invalid: %w", res.ID(), err)
			}
			out[ifname] = append(out[ifname], networkdStaticRoute{
				Destination:   spec.Destination,
				Via:           spec.Via,
				Metric:        spec.Metric,
				GatewayOnLink: via.IsLinkLocalUnicast(),
			})
		}
	}
	for ifname := range out {
		sort.Slice(out[ifname], func(i, j int) bool {
			if out[ifname][i].Destination == out[ifname][j].Destination {
				return out[ifname][i].Via < out[ifname][j].Via
			}
			return out[ifname][i].Destination < out[ifname][j].Destination
		})
	}
	return out, nil
}

func networkdStaticIPv4Addresses(router *api.Router, aliases map[string]string, ifname string) []string {
	var addresses []string
	for _, res := range router.Spec.Resources {
		if res.Kind != "IPv4StaticAddress" {
			continue
		}
		spec, err := res.IPv4StaticAddressSpec()
		if err != nil {
			continue
		}
		if aliases[spec.Interface] == ifname {
			addresses = append(addresses, spec.Address)
		}
	}
	sort.Strings(addresses)
	return addresses
}

func parseIAID(value string) (uint32, bool) {
	value = strings.TrimSpace(value)
	if value == "" {
		return 0, false
	}
	if strings.HasPrefix(value, "0x") || strings.HasPrefix(value, "0X") {
		parsed, err := strconv.ParseUint(value[2:], 16, 32)
		return uint32(parsed), err == nil
	}
	if len(value) == 8 && isHexString(value) {
		parsed, err := strconv.ParseUint(value, 16, 32)
		return uint32(parsed), err == nil
	}
	parsed, err := strconv.ParseUint(value, 10, 32)
	return uint32(parsed), err == nil
}

func isHexString(value string) bool {
	if value == "" {
		return false
	}
	for _, r := range strings.ToLower(value) {
		if (r < '0' || r > '9') && (r < 'a' || r > 'f') {
			return false
		}
	}
	return true
}

func networkdDropinDir(ifname string) string {
	return "/etc/systemd/network/10-netplan-" + sanitizeNetworkdName(ifname) + ".network.d"
}

func sanitizeNetworkdName(name string) string {
	return strings.NewReplacer("/", "-", "\x00", "").Replace(name)
}

func boolString(value bool) string {
	if value {
		return "yes"
	}
	return "no"
}

func defaultString(value, fallback string) string {
	if value == "" {
		return fallback
	}
	return value
}
