package render

import (
	"bytes"
	"fmt"
	"net/netip"
	"sort"
	"strconv"
	"strings"

	"routerd/pkg/api"
)

func NftablesIPv4SourceNAT(router *api.Router) ([]byte, error) {
	aliases, err := nftOutboundAliases(router)
	if err != nil {
		return nil, err
	}

	var nats []api.Resource
	var policies []api.Resource
	var policySets []api.Resource
	var zones []api.Resource
	var firewallPolicies []api.Resource
	var exposeServices []api.Resource
	var mssPolicies []pathMTUPolicy
	for _, res := range router.Spec.Resources {
		if res.Kind == "IPv4SourceNAT" {
			nats = append(nats, res)
		}
		if res.Kind == "IPv4PolicyRoute" {
			policies = append(policies, res)
		}
		if res.Kind == "IPv4PolicyRouteSet" {
			policySets = append(policySets, res)
		}
		if res.APIVersion == api.FirewallAPIVersion && res.Kind == "Zone" {
			zones = append(zones, res)
		}
		if res.APIVersion == api.FirewallAPIVersion && res.Kind == "FirewallPolicy" {
			firewallPolicies = append(firewallPolicies, res)
		}
		if res.APIVersion == api.FirewallAPIVersion && res.Kind == "ExposeService" {
			exposeServices = append(exposeServices, res)
		}
	}
	mssPolicies, err = pathMTUMSSPolicies(router)
	if err != nil {
		return nil, err
	}
	if len(nats) == 0 && len(policies) == 0 && len(policySets) == 0 && len(firewallPolicies) == 0 && len(exposeServices) == 0 && len(mssPolicies) == 0 {
		return nil, nil
	}
	sort.Slice(nats, func(i, j int) bool { return nats[i].Metadata.Name < nats[j].Metadata.Name })
	sort.Slice(policies, func(i, j int) bool { return policies[i].Metadata.Name < policies[j].Metadata.Name })
	sort.Slice(policySets, func(i, j int) bool { return policySets[i].Metadata.Name < policySets[j].Metadata.Name })
	sort.Slice(zones, func(i, j int) bool { return zones[i].Metadata.Name < zones[j].Metadata.Name })
	sort.Slice(firewallPolicies, func(i, j int) bool { return firewallPolicies[i].Metadata.Name < firewallPolicies[j].Metadata.Name })
	sort.Slice(exposeServices, func(i, j int) bool { return exposeServices[i].Metadata.Name < exposeServices[j].Metadata.Name })

	var buf bytes.Buffer
	buf.WriteString("# Generated by routerd. Do not edit by hand.\n")
	if len(firewallPolicies) > 0 {
		if err := writeFirewallFilterTable(&buf, aliases, zones, firewallPolicies, exposeServices, router.Spec.Apply.ProtectedZones); err != nil {
			return nil, err
		}
	}
	if len(mssPolicies) > 0 {
		if err := writeTCPMSSClampTable(&buf, aliases, mssPolicies); err != nil {
			return nil, err
		}
	}
	if len(exposeServices) > 0 {
		if err := writeExposeServiceDNATTable(&buf, aliases, zones, exposeServices); err != nil {
			return nil, err
		}
	}
	if len(policies) > 0 || len(policySets) > 0 {
		if err := writeIPv4PolicyRouteTable(&buf, policies, policySets); err != nil {
			return nil, err
		}
	}
	if len(nats) > 0 {
		if err := writeIPv4SourceNATTable(&buf, aliases, nats); err != nil {
			return nil, err
		}
	}
	return buf.Bytes(), nil
}

func nftOutboundAliases(router *api.Router) (map[string]string, error) {
	aliases := map[string]string{}
	for _, res := range router.Spec.Resources {
		switch res.Kind {
		case "Interface":
			spec, err := res.InterfaceSpec()
			if err != nil {
				return nil, err
			}
			aliases[res.Metadata.Name] = spec.IfName
		case "PPPoEInterface":
			spec, err := res.PPPoEInterfaceSpec()
			if err != nil {
				return nil, err
			}
			aliases[res.Metadata.Name] = defaultString(spec.IfName, "ppp-"+res.Metadata.Name)
		case "DSLiteTunnel":
			spec, err := res.DSLiteTunnelSpec()
			if err != nil {
				return nil, err
			}
			aliases[res.Metadata.Name] = defaultString(spec.TunnelName, res.Metadata.Name)
		}
	}
	return aliases, nil
}

func writeFirewallFilterTable(buf *bytes.Buffer, aliases map[string]string, zones []api.Resource, policies []api.Resource, exposes []api.Resource, protectedZones []string) error {
	zoneIfnames, err := nftZoneIfnames(aliases, zones)
	if err != nil {
		return err
	}
	inputPolicy := "drop"
	forwardPolicy := "drop"
	for _, res := range policies {
		spec, err := res.FirewallPolicySpec()
		if err != nil {
			return err
		}
		inputPolicy = defaultString(spec.Input.Default, inputPolicy)
		forwardPolicy = defaultString(spec.Forward.Default, forwardPolicy)
	}
	buf.WriteString("table inet routerd_filter {\n")
	buf.WriteString("  chain input {\n")
	buf.WriteString("    type filter hook input priority filter; policy " + inputPolicy + ";\n")
	buf.WriteString("    ct state invalid drop\n")
	buf.WriteString("    ct state { established, related } accept\n")
	buf.WriteString("    iifname \"lo\" accept\n")
	buf.WriteString("    meta l4proto ipv6-icmp accept\n")
	if wan := zoneIfnames["wan"]; len(wan) > 0 {
		buf.WriteString("    " + nftIfnameMatch("iifname", wan) + " udp dport 546 accept\n")
	}
	for _, zone := range protectedZones {
		ifnames := zoneIfnames[zone]
		if len(ifnames) == 0 {
			return fmt.Errorf("protected zone %q has no resolved interfaces", zone)
		}
		buf.WriteString("    " + nftIfnameMatch("iifname", ifnames) + " tcp dport 22 accept\n")
	}
	for _, res := range policies {
		spec, err := res.FirewallPolicySpec()
		if err != nil {
			return err
		}
		if err := writeRouterAccessRules(buf, zoneIfnames, spec); err != nil {
			return fmt.Errorf("%s: %w", res.ID(), err)
		}
	}
	buf.WriteString("  }\n")
	buf.WriteString("  chain forward {\n")
	buf.WriteString("    type filter hook forward priority filter; policy " + forwardPolicy + ";\n")
	buf.WriteString("    ct state invalid drop\n")
	buf.WriteString("    ct state { established, related } accept\n")
	if lan := zoneIfnames["lan"]; len(lan) > 0 {
		if wan := zoneIfnames["wan"]; len(wan) > 0 {
			buf.WriteString("    " + nftIfnameMatch("iifname", lan) + " " + nftIfnameMatch("oifname", wan) + " accept\n")
		}
	}
	for _, res := range exposes {
		spec, err := res.ExposeServiceSpec()
		if err != nil {
			return err
		}
		if defaultString(spec.Family, "ipv4") != "ipv4" {
			continue
		}
		ifnames, err := nftExposeIngressIfnames(aliases, zoneIfnames, spec)
		if err != nil {
			return fmt.Errorf("%s: %w", res.ID(), err)
		}
		sourceMatch, err := nftIPv4SourcesMatch(res.ID(), spec.Sources)
		if err != nil {
			return err
		}
		buf.WriteString("    " + nftIfnameMatch("iifname", ifnames) + sourceMatch + " ip daddr " + spec.InternalAddress + " " + spec.Protocol + " dport " + strconv.Itoa(spec.InternalPort) + " accept\n")
	}
	buf.WriteString("  }\n")
	buf.WriteString("}\n")
	return nil
}

func writeRouterAccessRules(buf *bytes.Buffer, zoneIfnames map[string][]string, spec api.FirewallPolicySpec) error {
	ssh := spec.RouterAccess.SSH
	if len(ssh.FromZones) == 0 && zoneIfnames["lan"] != nil {
		ssh.FromZones = []string{"lan"}
	}
	if err := writeRouterServiceRule(buf, zoneIfnames, ssh, "tcp dport 22"); err != nil {
		return err
	}
	dns := spec.RouterAccess.DNS
	if len(dns.FromZones) == 0 && zoneIfnames["lan"] != nil {
		dns.FromZones = []string{"lan"}
	}
	if err := writeRouterServiceRule(buf, zoneIfnames, dns, "udp dport 53"); err != nil {
		return err
	}
	if err := writeRouterServiceRule(buf, zoneIfnames, dns, "tcp dport 53"); err != nil {
		return err
	}
	dhcp := spec.RouterAccess.DHCP
	if len(dhcp.FromZones) == 0 && zoneIfnames["lan"] != nil {
		dhcp.FromZones = []string{"lan"}
	}
	if err := writeRouterServiceRule(buf, zoneIfnames, dhcp, "udp dport 67"); err != nil {
		return err
	}
	return writeRouterServiceRule(buf, zoneIfnames, dhcp, "udp dport 547")
}

func writeRouterServiceRule(buf *bytes.Buffer, zoneIfnames map[string][]string, service api.FirewallRouterServiceSpec, expr string) error {
	for _, zone := range service.FromZones {
		ifnames := zoneIfnames[zone]
		if len(ifnames) == 0 {
			return fmt.Errorf("zone %q has no resolved interfaces", zone)
		}
		buf.WriteString("    " + nftIfnameMatch("iifname", ifnames) + " " + expr + " accept\n")
	}
	if service.WAN.Enabled {
		ifnames := zoneIfnames["wan"]
		if len(ifnames) == 0 {
			return fmt.Errorf("wan.enabled requires a wan zone")
		}
		buf.WriteString("    " + nftIfnameMatch("iifname", ifnames) + " " + expr + " accept\n")
	}
	return nil
}

func writeExposeServiceDNATTable(buf *bytes.Buffer, aliases map[string]string, zones []api.Resource, exposes []api.Resource) error {
	zoneIfnames, err := nftZoneIfnames(aliases, zones)
	if err != nil {
		return err
	}
	buf.WriteString("table ip routerd_dnat {\n")
	buf.WriteString("  chain prerouting {\n")
	buf.WriteString("    type nat hook prerouting priority dstnat; policy accept;\n")
	for _, res := range exposes {
		spec, err := res.ExposeServiceSpec()
		if err != nil {
			return err
		}
		if defaultString(spec.Family, "ipv4") != "ipv4" {
			continue
		}
		ifnames, err := nftExposeIngressIfnames(aliases, zoneIfnames, spec)
		if err != nil {
			return fmt.Errorf("%s: %w", res.ID(), err)
		}
		sourceMatch, err := nftIPv4SourcesMatch(res.ID(), spec.Sources)
		if err != nil {
			return err
		}
		buf.WriteString("    " + nftIfnameMatch("iifname", ifnames) + sourceMatch + " " + spec.Protocol + " dport " + strconv.Itoa(spec.ExternalPort) + " dnat to " + spec.InternalAddress + ":" + strconv.Itoa(spec.InternalPort) + "\n")
	}
	buf.WriteString("  }\n")
	buf.WriteString("}\n")
	return nil
}

func nftZoneIfnames(aliases map[string]string, zones []api.Resource) (map[string][]string, error) {
	result := map[string][]string{}
	for _, res := range zones {
		spec, err := res.ZoneSpec()
		if err != nil {
			return nil, err
		}
		var ifnames []string
		for _, iface := range spec.Interfaces {
			ifname := aliases[iface]
			if ifname == "" {
				return nil, fmt.Errorf("%s references interface with empty ifname %q", res.ID(), iface)
			}
			ifnames = append(ifnames, ifname)
		}
		sort.Strings(ifnames)
		result[res.Metadata.Name] = compactStrings(ifnames)
	}
	return result, nil
}

func nftExposeIngressIfnames(aliases map[string]string, zones map[string][]string, spec api.ExposeServiceSpec) ([]string, error) {
	if spec.ViaInterface != "" {
		ifname := aliases[spec.ViaInterface]
		if ifname == "" {
			return nil, fmt.Errorf("spec.viaInterface has empty ifname")
		}
		return []string{ifname}, nil
	}
	ifnames := zones[spec.FromZone]
	if len(ifnames) == 0 {
		return nil, fmt.Errorf("spec.fromZone %q has no resolved interfaces", spec.FromZone)
	}
	return ifnames, nil
}

func nftIPv4SourcesMatch(resourceID string, sources []string) (string, error) {
	if len(sources) == 0 {
		return "", nil
	}
	var values []string
	for _, source := range sources {
		prefix, err := netip.ParsePrefix(source)
		if err != nil || !prefix.Addr().Is4() {
			return "", fmt.Errorf("%s has invalid IPv4 source CIDR %q", resourceID, source)
		}
		values = append(values, prefix.Masked().String())
	}
	sort.Strings(values)
	if len(values) == 1 {
		return " ip saddr " + values[0], nil
	}
	return " ip saddr { " + strings.Join(values, ", ") + " }", nil
}

func writeIPv4SourceNATTable(buf *bytes.Buffer, aliases map[string]string, nats []api.Resource) error {
	buf.WriteString("table ip routerd_nat {\n")
	buf.WriteString("  chain postrouting {\n")
	buf.WriteString("    type nat hook postrouting priority srcnat; policy accept;\n")
	for _, res := range nats {
		spec, err := res.IPv4SourceNATSpec()
		if err != nil {
			return err
		}
		ifname := aliases[spec.OutboundInterface]
		if ifname == "" {
			return fmt.Errorf("%s references outbound interface with empty ifname", res.ID())
		}
		for _, cidr := range spec.SourceCIDRs {
			prefix, err := netip.ParsePrefix(cidr)
			if err != nil || !prefix.Addr().Is4() {
				return fmt.Errorf("%s has invalid IPv4 source CIDR %q", res.ID(), cidr)
			}
			rules, err := nftSourceNATRules(ifname, prefix.Masked().String(), spec.Translation)
			if err != nil {
				return fmt.Errorf("%s: %w", res.ID(), err)
			}
			for _, rule := range rules {
				buf.WriteString("    " + rule + "\n")
			}
		}
	}
	buf.WriteString("  }\n")
	buf.WriteString("}\n")
	return nil
}

func writeTCPMSSClampTable(buf *bytes.Buffer, aliases map[string]string, policies []pathMTUPolicy) error {
	buf.WriteString("table inet routerd_mss {\n")
	buf.WriteString("  chain forward {\n")
	buf.WriteString("    type filter hook forward priority mangle; policy accept;\n")
	for _, policy := range policies {
		fromIfname := aliases[policy.Spec.FromInterface]
		if fromIfname == "" {
			return fmt.Errorf("%s references fromInterface with empty ifname", policy.Resource.ID())
		}
		var toIfnames []string
		for _, name := range policy.Spec.ToInterfaces {
			ifname := aliases[name]
			if ifname == "" {
				return fmt.Errorf("%s references toInterface with empty ifname %q", policy.Resource.ID(), name)
			}
			toIfnames = append(toIfnames, ifname)
		}
		sort.Strings(toIfnames)
		toIfnames = compactStrings(toIfnames)
		match := nftIfnameMatch("iifname", []string{fromIfname}) + " " + nftIfnameMatch("oifname", toIfnames)
		if pathMTUFamilyEnabled(policy.Spec.TCPMSSClamp.Families, "ipv4") {
			mss := policy.MTU - 40
			if mss < 536 {
				return fmt.Errorf("%s computed IPv4 MSS %d is too small", policy.Resource.ID(), mss)
			}
			buf.WriteString("    " + match + " ip protocol tcp tcp flags syn / syn,rst tcp option maxseg size set " + strconv.Itoa(mss) + "\n")
		}
		if pathMTUFamilyEnabled(policy.Spec.TCPMSSClamp.Families, "ipv6") {
			mss := policy.MTU - 60
			if mss < 1220 {
				return fmt.Errorf("%s computed IPv6 MSS %d is too small", policy.Resource.ID(), mss)
			}
			buf.WriteString("    " + match + " meta nfproto ipv6 tcp flags syn / syn,rst tcp option maxseg size set " + strconv.Itoa(mss) + "\n")
		}
	}
	buf.WriteString("  }\n")
	buf.WriteString("}\n")
	return nil
}

func writeIPv4PolicyRouteTable(buf *bytes.Buffer, policies []api.Resource, policySets []api.Resource) error {
	buf.WriteString("table ip routerd_policy {\n")
	buf.WriteString("  chain prerouting {\n")
	buf.WriteString("    type filter hook prerouting priority mangle; policy accept;\n")
	for _, res := range policies {
		spec, err := res.IPv4PolicyRouteSpec()
		if err != nil {
			return err
		}
		matches, err := nftIPv4PolicyRouteMatches(res.ID(), spec)
		if err != nil {
			return err
		}
		for _, match := range matches {
			buf.WriteString("    " + match + " meta mark set " + nftMark(spec.Mark) + "\n")
		}
	}
	for _, res := range policySets {
		spec, err := res.IPv4PolicyRouteSetSpec()
		if err != nil {
			return err
		}
		matches, err := nftIPv4PolicyRouteSetMatches(res.ID(), spec)
		if err != nil {
			return err
		}
		hashExpr, err := nftIPv4PolicyRouteSetHash(res.ID(), spec)
		if err != nil {
			return err
		}
		markMap := nftPolicyRouteSetMarkMap(spec.Targets)
		for _, match := range matches {
			buf.WriteString("    " + match + " ct mark != 0x0 meta mark set ct mark\n")
			prefix := strings.TrimSpace(match + " ct mark 0x0")
			buf.WriteString("    " + prefix + " meta mark set " + hashExpr + " mod " + strconv.Itoa(len(spec.Targets)) + " map { " + markMap + " }\n")
			buf.WriteString("    " + prefix + " ct mark set meta mark\n")
		}
	}
	buf.WriteString("  }\n")
	buf.WriteString("}\n")
	return nil
}

func nftIPv4PolicyRouteMatches(resourceID string, spec api.IPv4PolicyRouteSpec) ([]string, error) {
	var sources []string
	if len(spec.SourceCIDRs) == 0 {
		sources = []string{""}
	} else {
		for _, cidr := range spec.SourceCIDRs {
			prefix, err := netip.ParsePrefix(cidr)
			if err != nil || !prefix.Addr().Is4() {
				return nil, fmt.Errorf("%s has invalid IPv4 source CIDR %q", resourceID, cidr)
			}
			sources = append(sources, "ip saddr "+prefix.Masked().String())
		}
	}
	var destinations []string
	if len(spec.DestinationCIDRs) == 0 {
		destinations = []string{""}
	} else {
		for _, cidr := range spec.DestinationCIDRs {
			prefix, err := netip.ParsePrefix(cidr)
			if err != nil || !prefix.Addr().Is4() {
				return nil, fmt.Errorf("%s has invalid IPv4 destination CIDR %q", resourceID, cidr)
			}
			destinations = append(destinations, "ip daddr "+prefix.Masked().String())
		}
	}
	var matches []string
	for _, source := range sources {
		for _, destination := range destinations {
			matches = append(matches, strings.TrimSpace(strings.Join([]string{source, destination}, " ")))
		}
	}
	return matches, nil
}

func nftIPv4PolicyRouteSetMatches(resourceID string, spec api.IPv4PolicyRouteSetSpec) ([]string, error) {
	return nftIPv4CIDRMatches(resourceID, spec.SourceCIDRs, spec.DestinationCIDRs)
}

func nftIPv4CIDRMatches(resourceID string, sourceCIDRs, destinationCIDRs []string) ([]string, error) {
	var sources []string
	if len(sourceCIDRs) == 0 {
		sources = []string{""}
	} else {
		for _, cidr := range sourceCIDRs {
			prefix, err := netip.ParsePrefix(cidr)
			if err != nil || !prefix.Addr().Is4() {
				return nil, fmt.Errorf("%s has invalid IPv4 source CIDR %q", resourceID, cidr)
			}
			sources = append(sources, "ip saddr "+prefix.Masked().String())
		}
	}
	var destinations []string
	if len(destinationCIDRs) == 0 {
		destinations = []string{""}
	} else {
		for _, cidr := range destinationCIDRs {
			prefix, err := netip.ParsePrefix(cidr)
			if err != nil || !prefix.Addr().Is4() {
				return nil, fmt.Errorf("%s has invalid IPv4 destination CIDR %q", resourceID, cidr)
			}
			destinations = append(destinations, "ip daddr "+prefix.Masked().String())
		}
	}
	var matches []string
	for _, source := range sources {
		for _, destination := range destinations {
			matches = append(matches, strings.TrimSpace(strings.Join([]string{source, destination}, " ")))
		}
	}
	return matches, nil
}

func nftIPv4PolicyRouteSetHash(resourceID string, spec api.IPv4PolicyRouteSetSpec) (string, error) {
	var fields []string
	for _, field := range spec.HashFields {
		switch field {
		case "sourceAddress":
			fields = append(fields, "ip saddr")
		case "destinationAddress":
			fields = append(fields, "ip daddr")
		default:
			return "", fmt.Errorf("%s has unsupported hash field %q", resourceID, field)
		}
	}
	if len(fields) == 0 {
		return "", fmt.Errorf("%s requires at least one hash field", resourceID)
	}
	return "jhash " + strings.Join(fields, " . "), nil
}

func nftPolicyRouteSetMarkMap(targets []api.IPv4PolicyRouteTarget) string {
	parts := make([]string, 0, len(targets))
	for i, target := range targets {
		parts = append(parts, strconv.Itoa(i)+" : "+nftMark(target.Mark))
	}
	return strings.Join(parts, ", ")
}

func nftSourceNATRules(ifname, cidr string, translation api.IPv4NATTranslationSpec) ([]string, error) {
	match := "oifname " + nftQuote(ifname) + " ip saddr " + cidr + " "
	expr, err := nftNATExpression(translation)
	if err != nil {
		return nil, err
	}
	if defaultString(translation.PortMapping.Type, "auto") == "range" {
		return []string{
			match + "meta l4proto { tcp, udp } " + nftNATExpressionWithPortRange(expr, translation.PortMapping),
			match + expr,
		}, nil
	}
	portSuffix, err := nftPortMapping(translation.PortMapping)
	if err != nil {
		return nil, err
	}
	return []string{match + expr + portSuffix}, nil
}

func nftNATExpressionWithPortRange(expr string, portMapping api.IPv4NATPortMappingSpec) string {
	portRange := strconv.Itoa(portMapping.Start) + "-" + strconv.Itoa(portMapping.End)
	if strings.HasPrefix(expr, "snat to ") {
		return expr + ":" + portRange
	}
	return expr + " to :" + portRange
}

func nftNATExpression(translation api.IPv4NATTranslationSpec) (string, error) {
	switch translation.Type {
	case "interfaceAddress":
		return "masquerade", nil
	case "address":
		if translation.Address == "" {
			return "", fmt.Errorf("translation.address is required")
		}
		return "snat to " + translation.Address, nil
	case "pool":
		if len(translation.Addresses) == 0 {
			return "", fmt.Errorf("translation.addresses is required")
		}
		addresses := append([]string(nil), translation.Addresses...)
		sort.Strings(addresses)
		return "snat to " + strings.Join(addresses, "-"), nil
	default:
		return "", fmt.Errorf("unsupported translation.type %q", translation.Type)
	}
}

func nftPortMapping(portMapping api.IPv4NATPortMappingSpec) (string, error) {
	switch defaultString(portMapping.Type, "auto") {
	case "auto":
		return "", nil
	case "range":
		return "", nil
	case "preserve":
		return " persistent", nil
	default:
		return "", fmt.Errorf("unsupported portMapping.type %q", portMapping.Type)
	}
}

func nftQuote(value string) string {
	return strconv.Quote(value)
}

func nftMark(value int) string {
	return fmt.Sprintf("0x%x", value)
}

func nftIfnameMatch(key string, ifnames []string) string {
	if len(ifnames) == 1 {
		return key + " " + nftQuote(ifnames[0])
	}
	quoted := make([]string, 0, len(ifnames))
	for _, ifname := range ifnames {
		quoted = append(quoted, nftQuote(ifname))
	}
	return key + " { " + strings.Join(quoted, ", ") + " }"
}

func compactStrings(values []string) []string {
	var result []string
	for _, value := range values {
		if len(result) == 0 || result[len(result)-1] != value {
			result = append(result, value)
		}
	}
	return result
}
