// SPDX-License-Identifier: BSD-3-Clause

package render

import (
	"bytes"
	"fmt"
	"net"
	"net/netip"
	"sort"
	"strconv"
	"strings"

	"routerd/pkg/api"
)

func NftablesNAT44(router *api.Router) ([]byte, error) {
	aliases, err := nftOutboundAliases(router)
	if err != nil {
		return nil, err
	}

	var nat44Rules []api.Resource
	var egressPolicies []api.Resource
	var zones []api.Resource
	var firewallPolicies []api.Resource
	var firewallLogs []api.Resource
	var firewallRules []api.Resource
	var clientPolicies []api.Resource
	var ingressRules []ingressNATRule
	var redirectRules []localServiceRedirectRule
	var addressSets map[string]nftIPAddressSet
	var referencedAddressSets []nftIPAddressSet
	var mssPolicies []pathMTUPolicy
	var l2FilterVXLANS []vxlanConfig
	for _, res := range router.Spec.Resources {
		if res.Kind == "NAT44Rule" {
			nat44Rules = append(nat44Rules, res)
		}
		if res.Kind == "EgressRoutePolicy" {
			spec, err := res.EgressRoutePolicySpec()
			if err == nil && egressPolicyRendersPolicyMarks(spec) {
				egressPolicies = append(egressPolicies, res)
			}
		}
		if res.APIVersion == api.FirewallAPIVersion && res.Kind == "FirewallZone" {
			zones = append(zones, res)
		}
		if res.APIVersion == api.FirewallAPIVersion && res.Kind == "FirewallPolicy" {
			firewallPolicies = append(firewallPolicies, res)
		}
		if res.APIVersion == api.FirewallAPIVersion && res.Kind == "FirewallEventLog" {
			firewallLogs = append(firewallLogs, res)
		}
		if res.APIVersion == api.FirewallAPIVersion && res.Kind == "FirewallRule" {
			firewallRules = append(firewallRules, res)
		}
		if res.APIVersion == api.FirewallAPIVersion && res.Kind == "ClientPolicy" {
			clientPolicies = append(clientPolicies, res)
		}
	}
	ingressRules, err = ingressNATRules(router, aliases)
	if err != nil {
		return nil, err
	}
	addressSets, err = nftIPAddressSets(router)
	if err != nil {
		return nil, err
	}
	redirectRules, err = localServiceRedirectRules(router, aliases, addressSets)
	if err != nil {
		return nil, err
	}
	if len(nat44Rules) == 0 {
		nat44Rules = derivedDefaultNAT44Rules(router)
	}
	referencedAddressSets = mergeIPAddressSets(
		referencedIPAddressSets(redirectRules, addressSets),
		referencedNAT44ResourceIPAddressSets(nat44Rules, addressSets),
	)
	mssPolicies, err = pathMTUMSSPolicies(router)
	if err != nil {
		return nil, err
	}
	vxlans, err := vxlanConfigs(router, aliases)
	if err != nil {
		return nil, err
	}
	for _, vxlan := range vxlans {
		if vxlan.L2Filter != "none" {
			l2FilterVXLANS = append(l2FilterVXLANS, vxlan)
		}
	}
	if len(nat44Rules) == 0 && len(ingressRules) == 0 && len(redirectRules) == 0 && len(egressPolicies) == 0 && len(zones) == 0 && len(firewallPolicies) == 0 && len(firewallLogs) == 0 && len(firewallRules) == 0 && len(clientPolicies) == 0 && len(mssPolicies) == 0 && len(l2FilterVXLANS) == 0 {
		return nil, nil
	}
	sort.Slice(nat44Rules, func(i, j int) bool { return nat44Rules[i].Metadata.Name < nat44Rules[j].Metadata.Name })
	sort.Slice(egressPolicies, func(i, j int) bool { return egressPolicies[i].Metadata.Name < egressPolicies[j].Metadata.Name })
	sort.Slice(zones, func(i, j int) bool { return zones[i].Metadata.Name < zones[j].Metadata.Name })
	sort.Slice(firewallPolicies, func(i, j int) bool { return firewallPolicies[i].Metadata.Name < firewallPolicies[j].Metadata.Name })
	sort.Slice(firewallLogs, func(i, j int) bool { return firewallLogs[i].Metadata.Name < firewallLogs[j].Metadata.Name })
	sort.Slice(firewallRules, func(i, j int) bool { return firewallRules[i].Metadata.Name < firewallRules[j].Metadata.Name })
	sort.Slice(clientPolicies, func(i, j int) bool { return clientPolicies[i].Metadata.Name < clientPolicies[j].Metadata.Name })

	var buf bytes.Buffer
	buf.WriteString("# Generated by routerd. Do not edit by hand.\n")
	if len(l2FilterVXLANS) > 0 {
		writeBridgeL2FilterTable(&buf, l2FilterVXLANS)
	}
	if len(zones) > 0 || len(firewallPolicies) > 0 || len(firewallLogs) > 0 || len(firewallRules) > 0 || len(clientPolicies) > 0 {
		if err := writeFirewallFilterTable(&buf, aliases, zones, firewallPolicies, firewallLogs, firewallRules, clientPolicies, InternalFirewallHoles(router), ingressRules, addressSets); err != nil {
			return nil, err
		}
	}
	if len(mssPolicies) > 0 {
		if err := writeTCPMSSClampTable(&buf, aliases, mssPolicies); err != nil {
			return nil, err
		}
	}
	if len(egressPolicies) > 0 {
		if err := writeIPv4PolicyRouteTable(&buf, egressPolicies, addressSets); err != nil {
			return nil, err
		}
	}
	if len(nat44Rules) > 0 || len(ingressRules) > 0 || hasIPv4LocalServiceRedirectRules(redirectRules) {
		if err := writeNAT44Table(&buf, router, aliases, nat44Rules, ingressRules, redirectRules, referencedAddressSets, addressSets); err != nil {
			return nil, err
		}
	}
	if hasIPv6LocalServiceRedirectRules(redirectRules) {
		writeIPv6LocalServiceRedirectTable(&buf, redirectRules, referencedAddressSets)
	}
	return buf.Bytes(), nil
}

func NftablesNAT44Rule(router *api.Router) ([]byte, error) {
	return NftablesNAT44(router)
}

func derivedDefaultNAT44Rules(router *api.Router) []api.Resource {
	if router == nil {
		return nil
	}
	trustIfaces := map[string]bool{}
	var untrustIfaces []string
	seenUntrust := map[string]bool{}
	for _, res := range router.Spec.Resources {
		if res.APIVersion != api.FirewallAPIVersion || res.Kind != "FirewallZone" {
			continue
		}
		spec, err := res.FirewallZoneSpec()
		if err != nil {
			continue
		}
		for _, ref := range spec.Interfaces {
			name := refName(ref)
			if name == "" {
				continue
			}
			switch spec.Role {
			case "trust":
				trustIfaces[name] = true
			case "untrust":
				if !seenUntrust[name] {
					seenUntrust[name] = true
					untrustIfaces = append(untrustIfaces, name)
				}
			}
		}
	}
	if len(trustIfaces) == 0 || len(untrustIfaces) == 0 {
		return nil
	}
	sourceSet := map[string]bool{}
	for _, res := range router.Spec.Resources {
		if res.APIVersion != api.NetAPIVersion || res.Kind != "IPv4StaticAddress" {
			continue
		}
		spec, err := res.IPv4StaticAddressSpec()
		if err != nil || !trustIfaces[spec.Interface] {
			continue
		}
		prefix, err := netip.ParsePrefix(spec.Address)
		if err != nil || !prefix.Addr().Is4() {
			continue
		}
		sourceSet[prefix.Masked().String()] = true
	}
	if len(sourceSet) == 0 {
		return nil
	}
	sources := make([]string, 0, len(sourceSet))
	for source := range sourceSet {
		sources = append(sources, source)
	}
	sort.Strings(sources)
	sort.Strings(untrustIfaces)
	rules := make([]api.Resource, 0, len(untrustIfaces))
	for _, ifname := range untrustIfaces {
		rules = append(rules, api.Resource{
			TypeMeta: api.TypeMeta{APIVersion: api.NetAPIVersion, Kind: "NAT44Rule"},
			Metadata: api.ObjectMeta{Name: "derived-lan-to-" + strings.NewReplacer("/", "-", ".", "-").Replace(ifname)},
			Spec: api.NAT44RuleSpec{
				Type:                    "masquerade",
				EgressInterface:         ifname,
				SourceRanges:            sources,
				ExcludeDestinationCIDRs: privateIPv4CIDRs(),
			},
		})
	}
	return rules
}

func refName(ref string) string {
	ref = strings.TrimSpace(ref)
	if ref == "" {
		return ""
	}
	if _, name, ok := strings.Cut(ref, "/"); ok {
		return strings.TrimSpace(name)
	}
	return ref
}

func privateIPv4CIDRs() []string {
	return []string{"10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"}
}

func NftablesTCPMSSClamp(router *api.Router) ([]byte, error) {
	aliases, err := nftOutboundAliases(router)
	if err != nil {
		return nil, err
	}
	policies, err := pathMTUMSSPolicies(router)
	if err != nil {
		return nil, err
	}
	if len(policies) == 0 {
		return nil, nil
	}
	var buf bytes.Buffer
	buf.WriteString("# Generated by routerd. Do not edit by hand.\n")
	if err := writeTCPMSSClampTable(&buf, aliases, policies); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func NftablesIPv4PolicyRoutes(router *api.Router) ([]byte, error) {
	var policies []api.Resource
	addressSets, err := nftIPAddressSets(router)
	if err != nil {
		return nil, err
	}
	for _, res := range router.Spec.Resources {
		if res.Kind != "EgressRoutePolicy" {
			continue
		}
		spec, err := res.EgressRoutePolicySpec()
		if err == nil && egressPolicyRendersPolicyMarks(spec) {
			policies = append(policies, res)
		}
	}
	if len(policies) == 0 {
		return nil, nil
	}
	sort.Slice(policies, func(i, j int) bool { return policies[i].Metadata.Name < policies[j].Metadata.Name })
	var buf bytes.Buffer
	if err := writeIPv4PolicyRouteTable(&buf, policies, addressSets); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func NftablesEgressRoutePolicyDefaultMarks(resourceID string, spec api.EgressRoutePolicySpec, active api.EgressRoutePolicyCandidate, healthy []api.EgressRoutePolicyCandidate) ([]byte, error) {
	matches, err := nftIPv4CIDRMatches(resourceID, spec.SourceCIDRs, spec.DestinationCIDRs, spec.ExcludeDestinationCIDRs)
	if err != nil {
		return nil, err
	}
	healthyMarks := make([]string, 0, len(healthy))
	for _, candidate := range healthy {
		if len(candidate.Targets) > 0 {
			for _, target := range candidate.Targets {
				healthyMarks = append(healthyMarks, nftMark(target.Mark))
			}
			continue
		}
		healthyMarks = append(healthyMarks, nftMark(candidate.Mark))
	}
	sort.Strings(healthyMarks)
	var buf bytes.Buffer
	writeNftTablePreamble(&buf, "ip", "routerd_default_route")
	buf.WriteString("table ip routerd_default_route {\n")
	buf.WriteString("  chain prerouting {\n")
	buf.WriteString("    type filter hook prerouting priority -151; policy accept;\n")
	activeTargetCandidate := len(active.Targets) > 0
	activeMark := nftMark(active.Mark)
	for _, match := range matches {
		prefix := strings.TrimSpace(match)
		if prefix != "" {
			prefix += " "
		}
		if len(healthyMarks) > 0 {
			set := "{ " + strings.Join(healthyMarks, ", ") + " }"
			buf.WriteString("    " + prefix + "ct mark " + set + " meta mark set ct mark\n")
			if activeTargetCandidate {
				buf.WriteString("    " + prefix + "ct mark != 0x0 ct mark != " + set + " meta mark set 0x0 ct mark set meta mark\n")
			} else {
				buf.WriteString("    " + prefix + "ct mark != 0x0 ct mark != " + set + " meta mark set " + activeMark + " ct mark set meta mark\n")
			}
		}
		if !activeTargetCandidate {
			buf.WriteString("    " + prefix + "ct mark 0x0 meta mark set " + activeMark + " ct mark set meta mark\n")
		}
	}
	buf.WriteString("  }\n")
	buf.WriteString("}\n")
	return buf.Bytes(), nil
}

type NAT44RenderRule struct {
	Name                      string
	Type                      string
	EgressInterface           string
	SourceRanges              []string
	DestinationCIDRs          []string
	DestinationSetRefs        []string
	ExcludeDestinationCIDRs   []string
	ExcludeDestinationSetRefs []string
	SNATAddress               string
}

func writeNftTablePreamble(buf *bytes.Buffer, family, name string) {
	buf.WriteString("add table " + family + " " + name + "\n")
	buf.WriteString("flush table " + family + " " + name + "\n")
}

func writeNftSetReset(buf *bytes.Buffer, family, table, name string) {
	buf.WriteString("destroy set " + family + " " + table + " " + name + "\n")
}

func NftablesNAT44Rules(rules []NAT44RenderRule) ([]byte, error) {
	return NftablesNAT44RulesForRouter(nil, rules)
}

func NftablesNAT44RulesForRouter(router *api.Router, rules []NAT44RenderRule) ([]byte, error) {
	var ingressRules []ingressNATRule
	var redirectRules []localServiceRedirectRule
	var addressSets []nftIPAddressSet
	var sets map[string]nftIPAddressSet
	if router != nil {
		aliases, err := nftOutboundAliases(router)
		if err != nil {
			return nil, err
		}
		sets, err = nftIPAddressSets(router)
		if err != nil {
			return nil, err
		}
		redirectRules, err = localServiceRedirectRules(router, aliases, sets)
		if err != nil {
			return nil, err
		}
		addressSets = mergeIPAddressSets(referencedIPAddressSets(redirectRules, sets), referencedNAT44IPAddressSets(rules, sets))
		ingressRules, err = ingressNATRules(router, aliases)
		if err != nil {
			return nil, err
		}
	}
	if len(rules) == 0 && len(ingressRules) == 0 && !hasIPv4LocalServiceRedirectRules(redirectRules) && !hasIPv6LocalServiceRedirectRules(redirectRules) {
		return nil, nil
	}
	rules = append([]NAT44RenderRule(nil), rules...)
	sort.Slice(rules, func(i, j int) bool { return rules[i].Name < rules[j].Name })
	var buf bytes.Buffer
	buf.WriteString("# Generated by routerd. Do not edit by hand.\n")
	if len(rules) > 0 || len(ingressRules) > 0 || hasIPv4LocalServiceRedirectRules(redirectRules) {
		writeNftTablePreamble(&buf, "ip", "routerd_nat")
		buf.WriteString("table ip routerd_nat {\n")
		writeIPv4AddressSets(&buf, addressSets)
		if len(ingressRules) > 0 || hasIPv4LocalServiceRedirectRules(redirectRules) {
			writeIngressDNATChains(&buf, ingressRules)
			buf.WriteString("  chain prerouting {\n")
			buf.WriteString("    type nat hook prerouting priority dstnat; policy accept;\n")
			writeLocalServiceRedirectRules(&buf, redirectRules, "ip")
			for _, rule := range ingressRules {
				writeIngressDNATRule(&buf, rule, rule.ListenInterface, "")
				for _, ifname := range rule.HairpinInterfaces {
					if ifname == rule.ListenInterface {
						continue
					}
					writeIngressDNATRule(&buf, rule, ifname, " hairpin")
				}
			}
			buf.WriteString("  }\n")
		}
		buf.WriteString("  chain postrouting {\n")
		buf.WriteString("    type nat hook postrouting priority srcnat; policy accept;\n")
		writeIngressHairpinSNATRules(&buf, ingressRules)
		for _, rule := range rules {
			if err := writeNAT44RenderRule(&buf, rule, sets); err != nil {
				return nil, err
			}
		}
		buf.WriteString("  }\n")
		buf.WriteString("}\n")
	}
	if hasIPv6LocalServiceRedirectRules(redirectRules) {
		writeIPv6LocalServiceRedirectTable(&buf, redirectRules, addressSets)
	}
	return buf.Bytes(), nil
}

func writeIPv6LocalServiceRedirectTable(buf *bytes.Buffer, redirectRules []localServiceRedirectRule, addressSets []nftIPAddressSet) {
	writeNftTablePreamble(buf, "ip6", "routerd_nat")
	buf.WriteString("table ip6 routerd_nat {\n")
	writeIPv6AddressSets(buf, addressSets)
	buf.WriteString("  chain prerouting {\n")
	buf.WriteString("    type nat hook prerouting priority dstnat; policy accept;\n")
	writeLocalServiceRedirectRules(buf, redirectRules, "ip6")
	buf.WriteString("  }\n")
	buf.WriteString("}\n")
}

func nftOutboundAliases(router *api.Router) (map[string]string, error) {
	aliases := map[string]string{}
	for _, res := range router.Spec.Resources {
		switch res.Kind {
		case "Interface":
			spec, err := res.InterfaceSpec()
			if err != nil {
				return nil, err
			}
			aliases[res.Metadata.Name] = spec.IfName
		case "PPPoESession":
			spec, err := res.PPPoESessionSpec()
			if err != nil {
				return nil, err
			}
			aliases[res.Metadata.Name] = defaultString(spec.IfName, "ppp-"+res.Metadata.Name)
		case "DSLiteTunnel":
			spec, err := res.DSLiteTunnelSpec()
			if err != nil {
				return nil, err
			}
			aliases[res.Metadata.Name] = defaultString(spec.TunnelName, res.Metadata.Name)
		case "Bridge":
			spec, err := res.BridgeSpec()
			if err != nil {
				return nil, err
			}
			aliases[res.Metadata.Name] = defaultString(spec.IfName, res.Metadata.Name)
		case "VXLANSegment":
			spec, err := res.VXLANSegmentSpec()
			if err != nil {
				return nil, err
			}
			aliases[res.Metadata.Name] = defaultString(spec.IfName, res.Metadata.Name)
		case "WireGuardInterface":
			aliases[res.Metadata.Name] = res.Metadata.Name
		}
	}
	return aliases, nil
}

type vxlanUnderlayPort struct {
	IfName  string
	UDPPort int
}

func vxlanUnderlayPorts(vxlans []vxlanConfig) []vxlanUnderlayPort {
	seen := map[string]bool{}
	var out []vxlanUnderlayPort
	for _, v := range vxlans {
		if v.UnderlayIfName == "" {
			continue
		}
		key := v.UnderlayIfName + ":" + strconv.Itoa(v.UDPPort)
		if seen[key] {
			continue
		}
		seen[key] = true
		out = append(out, vxlanUnderlayPort{IfName: v.UnderlayIfName, UDPPort: v.UDPPort})
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].IfName != out[j].IfName {
			return out[i].IfName < out[j].IfName
		}
		return out[i].UDPPort < out[j].UDPPort
	})
	return out
}

func writeBridgeL2FilterTable(buf *bytes.Buffer, vxlans []vxlanConfig) {
	sort.Slice(vxlans, func(i, j int) bool { return vxlans[i].IfName < vxlans[j].IfName })
	writeNftTablePreamble(buf, "bridge", "routerd_l2_filter")
	buf.WriteString("table bridge routerd_l2_filter {\n")
	buf.WriteString("  chain forward {\n")
	buf.WriteString("    type filter hook forward priority filter; policy accept;\n")
	for _, vxlan := range vxlans {
		ifname := nftQuote(vxlan.IfName)
		for _, direction := range []string{"iifname", "oifname"} {
			buf.WriteString("    " + direction + " " + ifname + " ether type ip udp sport { 67, 68 } counter drop\n")
			buf.WriteString("    " + direction + " " + ifname + " ether type ip udp dport { 67, 68 } counter drop\n")
			buf.WriteString("    " + direction + " " + ifname + " ether type ip6 udp sport { 546, 547 } counter drop\n")
			buf.WriteString("    " + direction + " " + ifname + " ether type ip6 udp dport { 546, 547 } counter drop\n")
			buf.WriteString("    " + direction + " " + ifname + " ether type ip6 icmpv6 type { nd-router-solicit, nd-router-advert, nd-neighbor-solicit, nd-neighbor-advert } counter drop\n")
		}
	}
	buf.WriteString("  }\n")
	buf.WriteString("}\n")
}

type FirewallHole struct {
	Name      string
	FromZone  string
	ToZone    string
	IfNames   []string
	Protocol  string
	Port      int
	Action    string
	Direction string
	Comment   string
}

func NftablesFirewall(router *api.Router, holes []FirewallHole) ([]byte, error) {
	aliases, err := nftOutboundAliases(router)
	if err != nil {
		return nil, err
	}
	var zones []api.Resource
	var policies []api.Resource
	var logs []api.Resource
	var rules []api.Resource
	var clientPolicies []api.Resource
	for _, res := range router.Spec.Resources {
		if res.APIVersion != api.FirewallAPIVersion {
			continue
		}
		switch res.Kind {
		case "FirewallZone":
			zones = append(zones, res)
		case "FirewallPolicy":
			policies = append(policies, res)
		case "FirewallEventLog":
			logs = append(logs, res)
		case "FirewallRule":
			rules = append(rules, res)
		case "ClientPolicy":
			clientPolicies = append(clientPolicies, res)
		}
	}
	ingressRules, err := ingressNATRules(router, aliases)
	if err != nil {
		return nil, err
	}
	addressSets, err := nftIPAddressSets(router)
	if err != nil {
		return nil, err
	}
	if len(zones) == 0 && len(rules) == 0 && len(clientPolicies) == 0 && len(holes) == 0 {
		return nil, nil
	}
	sort.Slice(zones, func(i, j int) bool { return zones[i].Metadata.Name < zones[j].Metadata.Name })
	sort.Slice(policies, func(i, j int) bool { return policies[i].Metadata.Name < policies[j].Metadata.Name })
	sort.Slice(logs, func(i, j int) bool { return logs[i].Metadata.Name < logs[j].Metadata.Name })
	sort.Slice(rules, func(i, j int) bool { return rules[i].Metadata.Name < rules[j].Metadata.Name })
	sort.Slice(clientPolicies, func(i, j int) bool { return clientPolicies[i].Metadata.Name < clientPolicies[j].Metadata.Name })
	var buf bytes.Buffer
	buf.WriteString("# Generated by routerd. Do not edit by hand.\n")
	if err := writeFirewallFilterTable(&buf, aliases, zones, policies, logs, rules, clientPolicies, holes, ingressRules, addressSets); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func writeFirewallFilterTable(buf *bytes.Buffer, aliases map[string]string, zones []api.Resource, policies []api.Resource, logs []api.Resource, rules []api.Resource, clientPolicyResources []api.Resource, holes []FirewallHole, ingressRules []ingressNATRule, addressSetMap map[string]nftIPAddressSet) error {
	zoneMap, err := nftFirewallZones(aliases, zones)
	if err != nil {
		return err
	}
	clientPolicies, err := nftClientPolicies(aliases, zoneMap, clientPolicyResources)
	if err != nil {
		return err
	}
	policy := firewallPolicyOptions(policies)
	logging := firewallLogOptions(logs)
	sortedZones := sortedFirewallZones(zoneMap)
	firewallAddressSets := referencedFirewallIPAddressSets(rules, addressSetMap)
	writeNftTablePreamble(buf, "inet", "routerd_filter")
	for _, zone := range sortedZones {
		if len(zone.IfNames) > 0 {
			writeNftSetReset(buf, "inet", "routerd_filter", nftSetName("if_"+zone.Name))
		}
	}
	writeFirewallAddressSetResets(buf, firewallAddressSets)
	for _, policy := range clientPolicies {
		if len(policy.MACs) > 0 {
			writeNftSetReset(buf, "inet", "routerd_filter", policy.SetName)
		}
	}
	buf.WriteString("table inet routerd_filter {\n")
	for _, zone := range sortedZones {
		if len(zone.IfNames) > 0 {
			buf.WriteString("  set " + nftSetName("if_"+zone.Name) + " { type ifname; elements = { " + nftQuotedList(zone.IfNames) + " } }\n")
		}
	}
	for _, policy := range clientPolicies {
		if len(policy.MACs) > 0 {
			buf.WriteString("  set " + policy.SetName + " { type ether_addr; elements = { " + strings.Join(policy.MACs, ", ") + " } }\n")
		}
	}
	writeFirewallAddressSets(buf, firewallAddressSets)
	buf.WriteString("  chain input {\n")
	buf.WriteString("    type filter hook input priority filter; policy drop;\n")
	buf.WriteString("    ct state invalid counter drop\n")
	buf.WriteString("    ct state { established, related } counter accept\n")
	buf.WriteString("    iifname \"lo\" counter accept\n")
	buf.WriteString("    meta l4proto ipv6-icmp counter accept\n")
	writeClientPolicyInputRules(buf, clientPolicies)
	for _, zone := range sortedZones {
		if len(zone.IfNames) == 0 {
			continue
		}
		buf.WriteString("    iifname @if_" + nftIdent(zone.Name) + " jump " + nftChainName(zone.Name+"-to-self") + "\n")
	}
	if policy.LogDeny {
		buf.WriteString("    counter " + nftSampledLogExpr("routerd firewall input deny ", logging.DropSampleRate, logging) + " drop\n")
	} else {
		buf.WriteString("    counter drop\n")
	}
	buf.WriteString("  }\n")
	buf.WriteString("  chain forward {\n")
	buf.WriteString("    type filter hook forward priority filter; policy drop;\n")
	buf.WriteString("    ct state invalid counter drop\n")
	if logging.Enabled && logging.AcceptSampleRate > 0 {
		buf.WriteString("    ct state { new, established } " + nftSampledLogExpr("routerd firewall forward accept ", logging.AcceptSampleRate, logging) + "\n")
	}
	buf.WriteString("    ct state { established, related } counter accept\n")
	buf.WriteString("    meta l4proto ipv6-icmp counter accept\n")
	writeIngressForwardAcceptRules(buf, ingressRules)
	writeClientPolicyForwardRules(buf, clientPolicies, logging)
	for _, from := range sortedZones {
		for _, to := range sortedZones {
			if len(from.IfNames) == 0 || len(to.IfNames) == 0 {
				continue
			}
			buf.WriteString("    iifname @if_" + nftIdent(from.Name) + " oifname @if_" + nftIdent(to.Name) + " jump " + nftChainName(from.Name+"-to-"+to.Name) + "\n")
		}
	}
	if policy.LogDeny {
		buf.WriteString("    counter " + nftSampledLogExpr("routerd firewall forward deny ", logging.DropSampleRate, logging) + " drop\n")
	} else {
		buf.WriteString("    counter drop\n")
	}
	buf.WriteString("  }\n")
	for _, from := range sortedZones {
		if err := writeFirewallPairChain(buf, from, firewallZone{Name: "self", Role: "self"}, rules, holes, policy, logging, addressSetMap); err != nil {
			return err
		}
		for _, to := range sortedZones {
			if err := writeFirewallPairChain(buf, from, to, rules, holes, policy, logging, addressSetMap); err != nil {
				return err
			}
		}
	}
	buf.WriteString("}\n")
	return nil
}

type firewallPolicy struct {
	LogDeny        bool
	SameRoleAccept bool
}

type firewallLogging struct {
	Enabled          bool
	Group            int
	AcceptSampleRate int
	DropSampleRate   int
	CopyRange        int
}

type firewallZone struct {
	Name    string
	Role    string
	IfNames []string
}

type clientPolicy struct {
	Name           string
	Mode           string
	IfNames        []string
	MACs           []string
	SetName        string
	GuestServices  []string
	EgressDeny     []string
	EgressAllow    []string
	BlockDiscovery bool
}

func nftClientPolicies(aliases map[string]string, zoneMap map[string]firewallZone, resources []api.Resource) ([]clientPolicy, error) {
	var out []clientPolicy
	for _, res := range resources {
		spec, err := res.ClientPolicySpec()
		if err != nil {
			return nil, err
		}
		ifnames, err := clientPolicyIfNames(res, spec, aliases, zoneMap)
		if err != nil {
			return nil, err
		}
		sort.Strings(ifnames)
		policy := clientPolicy{
			Name:           res.Metadata.Name,
			Mode:           spec.Mode,
			IfNames:        compactStrings(ifnames),
			SetName:        nftSetName("client_policy_" + res.Metadata.Name),
			GuestServices:  clientPolicyGuestServices(spec.GuestServices),
			EgressDeny:     clientPolicyEgressCIDRs(spec.GuestEgressDeny, clientPolicyDefaultEgressDeny(spec.Isolation)),
			EgressAllow:    clientPolicyEgressCIDRs(spec.GuestEgressAllow, nil),
			BlockDiscovery: spec.Isolation.MDNSBroadcast == "deny",
		}
		if spec.Isolation.LANInternet == "deny" && len(spec.GuestEgressDeny) == 0 {
			policy.EgressDeny = clientPolicyEgressCIDRs([]string{"0.0.0.0/0", "::/0"}, nil)
		}
		for _, value := range spec.MACs {
			parsedMAC, err := net.ParseMAC(value)
			if err != nil {
				return nil, fmt.Errorf("%s has invalid client MAC %q: %w", res.ID(), value, err)
			}
			policy.MACs = append(policy.MACs, strings.ToLower(parsedMAC.String()))
		}
		for _, entry := range spec.Classification {
			for _, value := range entry.Match.MACs {
				parsedMAC, err := net.ParseMAC(value)
				if err != nil {
					return nil, fmt.Errorf("%s has invalid client MAC %q: %w", res.ID(), value, err)
				}
				mac := strings.ToLower(parsedMAC.String())
				switch spec.Mode {
				case "include":
					if entry.Mode == "guest" || entry.Mode == "isolated" {
						policy.MACs = append(policy.MACs, mac)
					}
				case "exclude":
					if entry.Mode == "trusted" {
						policy.MACs = append(policy.MACs, mac)
					}
				}
			}
		}
		sort.Strings(policy.MACs)
		policy.MACs = compactStrings(policy.MACs)
		out = append(out, policy)
	}
	return out, nil
}

func clientPolicyIfNames(res api.Resource, spec api.ClientPolicySpec, aliases map[string]string, zoneMap map[string]firewallZone) ([]string, error) {
	var ifnames []string
	if len(spec.Interfaces) == 0 {
		for _, zone := range zoneMap {
			if zone.Role == "trust" {
				ifnames = append(ifnames, zone.IfNames...)
			}
		}
		if len(ifnames) == 0 {
			return nil, fmt.Errorf("%s spec.interfaces is required when no trust FirewallZone interfaces are available", res.ID())
		}
		return ifnames, nil
	}
	for _, iface := range spec.Interfaces {
		ref := iface
		if kind, name, ok := strings.Cut(iface, "/"); ok {
			if kind != "Interface" {
				return nil, fmt.Errorf("%s references unsupported client policy interface %q", res.ID(), iface)
			}
			ref = name
		}
		ifname := aliases[ref]
		if ifname == "" {
			return nil, fmt.Errorf("%s references interface with empty ifname %q", res.ID(), iface)
		}
		ifnames = append(ifnames, ifname)
	}
	return ifnames, nil
}

func clientPolicyDefaultEgressDeny(isolation api.ClientPolicyIsolationSpec) []string {
	if isolation.LANLAN == "allow" && isolation.LANMgmt == "allow" {
		return nil
	}
	return []string{"10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16", "fc00::/7"}
}

func clientPolicyGuestServices(values []string) []string {
	if len(values) == 0 {
		return []string{"dhcp", "dns", "ntp"}
	}
	out := append([]string(nil), values...)
	sort.Strings(out)
	return compactStrings(out)
}

func clientPolicyEgressCIDRs(values, defaults []string) []string {
	if len(values) == 0 {
		values = defaults
	}
	out := append([]string(nil), values...)
	sort.Strings(out)
	return compactStrings(out)
}

func writeClientPolicyInputRules(buf *bytes.Buffer, policies []clientPolicy) {
	for _, policy := range policies {
		match := nftClientPolicyMatch(policy)
		if match == "" {
			continue
		}
		if stringInSlice("dns", policy.GuestServices) {
			buf.WriteString("    " + match + " udp dport 53 counter accept comment " + nftQuote("routerd client policy "+policy.Name+" guest DNS") + "\n")
			buf.WriteString("    " + match + " tcp dport 53 counter accept comment " + nftQuote("routerd client policy "+policy.Name+" guest DNS") + "\n")
		}
		if stringInSlice("dhcp", policy.GuestServices) {
			buf.WriteString("    " + match + " udp dport { 67, 547 } counter accept comment " + nftQuote("routerd client policy "+policy.Name+" guest DHCP") + "\n")
		}
		if stringInSlice("ntp", policy.GuestServices) {
			buf.WriteString("    " + match + " udp dport 123 counter accept comment " + nftQuote("routerd client policy "+policy.Name+" guest NTP") + "\n")
		}
		if stringInSlice("mdns", policy.GuestServices) {
			buf.WriteString("    " + match + " udp dport 5353 counter accept comment " + nftQuote("routerd client policy "+policy.Name+" guest mDNS") + "\n")
		}
		if stringInSlice("ssdp", policy.GuestServices) {
			buf.WriteString("    " + match + " udp dport 1900 counter accept comment " + nftQuote("routerd client policy "+policy.Name+" guest SSDP") + "\n")
		}
		buf.WriteString("    " + match + " counter drop comment " + nftQuote("routerd client policy "+policy.Name+" guest self isolation") + "\n")
	}
}

func writeClientPolicyForwardRules(buf *bytes.Buffer, policies []clientPolicy, logging firewallLogging) {
	for _, policy := range policies {
		match := nftClientPolicyMatch(policy)
		if match == "" {
			continue
		}
		for _, cidr := range policy.EgressAllow {
			if dst := nftClientPolicyDestinationMatch(cidr); dst != "" {
				buf.WriteString("    " + match + " " + dst + " counter accept comment " + nftQuote("routerd client policy "+policy.Name+" guest allow") + "\n")
			}
		}
		if policy.BlockDiscovery {
			buf.WriteString("    " + match + " ip daddr 224.0.0.251 udp dport 5353 counter " + nftLogExpr("routerd client-policy "+policy.Name+" discovery deny ", logging) + " drop\n")
			buf.WriteString("    " + match + " ip6 daddr ff02::fb udp dport 5353 counter " + nftLogExpr("routerd client-policy "+policy.Name+" discovery deny ", logging) + " drop\n")
			buf.WriteString("    " + match + " ip daddr 239.255.255.250 udp dport 1900 counter " + nftLogExpr("routerd client-policy "+policy.Name+" discovery deny ", logging) + " drop\n")
			buf.WriteString("    " + match + " ip6 daddr ff02::c udp dport 1900 counter " + nftLogExpr("routerd client-policy "+policy.Name+" discovery deny ", logging) + " drop\n")
			buf.WriteString("    " + match + " udp dport { 137, 138 } counter " + nftLogExpr("routerd client-policy "+policy.Name+" netbios deny ", logging) + " drop\n")
		}
		for _, cidr := range policy.EgressDeny {
			if dst := nftClientPolicyDestinationMatch(cidr); dst != "" {
				buf.WriteString("    " + match + " " + dst + " counter " + nftLogExpr("routerd client-policy "+policy.Name+" deny ", logging) + " drop\n")
			}
		}
	}
}

func nftClientPolicyMatch(policy clientPolicy) string {
	if len(policy.IfNames) == 0 {
		return ""
	}
	parts := []string{nftIfNameMatch("iifname", policy.IfNames)}
	switch policy.Mode {
	case "include":
		if len(policy.MACs) == 0 {
			return ""
		}
		parts = append(parts, "ether saddr @"+policy.SetName)
	case "exclude":
		if len(policy.MACs) > 0 {
			parts = append(parts, "ether saddr != @"+policy.SetName)
		}
	default:
		return ""
	}
	return strings.Join(parts, " ")
}

func nftClientPolicyDestinationMatch(cidr string) string {
	prefix, err := netip.ParsePrefix(cidr)
	if err != nil {
		return ""
	}
	if prefix.Addr().Is4() {
		return "ip daddr " + prefix.Masked().String()
	}
	return "ip6 daddr " + prefix.Masked().String()
}

func firewallPolicyOptions(resources []api.Resource) firewallPolicy {
	out := firewallPolicy{SameRoleAccept: true}
	for _, res := range resources {
		spec, err := res.FirewallPolicySpec()
		if err != nil {
			continue
		}
		out.LogDeny = out.LogDeny || spec.LogDeny
		if spec.SameRoleAccept {
			out.SameRoleAccept = true
		}
	}
	return out
}

func firewallLogOptions(resources []api.Resource) firewallLogging {
	for _, res := range resources {
		spec, err := res.FirewallEventLogSpec()
		if err != nil || !spec.Enabled {
			continue
		}
		group := spec.NFLogGroup
		if group == 0 {
			group = 1
		}
		return firewallLogging{Enabled: true, Group: group, AcceptSampleRate: spec.Log.AcceptSampleRate, DropSampleRate: spec.Log.DropSampleRate, CopyRange: spec.Log.CopyRange}
	}
	return firewallLogging{}
}

func nftLogExpr(prefix string, logging firewallLogging) string {
	expr := "log prefix " + nftQuote(prefix)
	if logging.Enabled {
		expr += " group " + strconv.Itoa(logging.Group)
		if logging.CopyRange > 0 {
			expr += " snaplen " + strconv.Itoa(logging.CopyRange)
		}
	}
	return expr
}

func nftSampledLogExpr(prefix string, sampleRate int, logging firewallLogging) string {
	if sampleRate <= 1 {
		return nftLogExpr(prefix, logging)
	}
	return "numgen random mod " + strconv.Itoa(sampleRate) + " == 0 " + nftLogExpr(prefix, logging)
}

func writeFirewallPairChain(buf *bytes.Buffer, from firewallZone, to firewallZone, rules []api.Resource, holes []FirewallHole, policy firewallPolicy, logging firewallLogging, addressSetMap map[string]nftIPAddressSet) error {
	chain := nftChainName(from.Name + "-to-" + to.Name)
	buf.WriteString("  chain " + chain + " {\n")
	for _, hole := range holes {
		if hole.FromZone == from.Name && hole.ToZone == to.Name {
			if to.Name == "self" && implicitFirewallAction(from.Role, to.Role, policy) == "accept" {
				continue
			}
			buf.WriteString("    " + nftFirewallHoleExpr(hole) + "\n")
		}
	}
	for _, res := range rules {
		spec, err := res.FirewallRuleSpec()
		if err != nil {
			return err
		}
		if spec.FromZone != from.Name || spec.ToZone != to.Name {
			continue
		}
		exprs, err := nftFirewallRuleExprs(res.Metadata.Name, spec, logging, addressSetMap)
		if err != nil {
			return err
		}
		for _, expr := range exprs {
			buf.WriteString("    " + expr + "\n")
		}
	}
	action := implicitFirewallAction(from.Role, to.Role, policy)
	if policy.LogDeny && (action == "drop" || action == "reject") {
		buf.WriteString("    counter " + nftSampledLogExpr("routerd firewall "+from.Name+"-to-"+to.Name+" deny ", logging.DropSampleRate, logging) + " " + action + "\n")
	} else if action == "accept" && logging.Enabled && logging.AcceptSampleRate > 0 {
		buf.WriteString("    ct state new " + nftSampledLogExpr("routerd firewall "+from.Name+"-to-"+to.Name+" accept ", logging.AcceptSampleRate, logging) + " counter accept\n")
		buf.WriteString("    counter accept\n")
	} else {
		buf.WriteString("    counter " + action + "\n")
	}
	buf.WriteString("  }\n")
	return nil
}

func implicitFirewallAction(fromRole, toRole string, policy firewallPolicy) string {
	if toRole == "self" {
		switch fromRole {
		case "mgmt", "trust":
			return "accept"
		default:
			return "drop"
		}
	}
	if policy.SameRoleAccept && fromRole == toRole {
		return "accept"
	}
	switch fromRole {
	case "mgmt":
		return "accept"
	case "trust":
		if toRole == "mgmt" {
			return "drop"
		}
		return "accept"
	default:
		return "drop"
	}
}

func nftFirewallRuleExpr(name string, spec api.FirewallRuleSpec, logging firewallLogging) (string, error) {
	exprs, err := nftFirewallRuleExprs(name, spec, logging, nil)
	if err != nil {
		return "", err
	}
	if len(exprs) == 0 {
		return "", nil
	}
	return exprs[0], nil
}

func nftFirewallRuleExprs(name string, spec api.FirewallRuleSpec, logging firewallLogging, addressSets map[string]nftIPAddressSet) ([]string, error) {
	matches, err := nftFirewallMatchAlternatives(name, spec, addressSets)
	if err != nil {
		return nil, err
	}
	var common []string
	srcPorts := firewallSourcePorts(spec)
	dstPorts := firewallDestinationPorts(spec)
	if proto := nftFirewallProtocol(spec.Protocol); proto != "" && len(srcPorts) == 0 && len(dstPorts) == 0 {
		common = append(common, proto)
	}
	if len(srcPorts) > 0 {
		common = append(common, nftPortMatch(spec.Protocol, "sport", srcPorts))
	}
	if len(dstPorts) > 0 {
		common = append(common, nftPortMatch(spec.Protocol, "dport", dstPorts))
	}
	if icmp := nftICMPTypeMatch(spec); icmp != "" {
		common = append(common, icmp)
	}
	rateLimit := nftFirewallRateLimitExpr(spec.RateLimit)
	suffix := append([]string{}, common...)
	if limit := nftFirewallRateLimitExpr(spec.RateLimit); limit != "" {
		suffix = append(suffix, limit)
		if spec.RateLimit.Log {
			suffix = append(suffix, nftLogExpr("routerd firewall "+name+" rate-limit ", logging))
		}
	}
	if spec.Log {
		suffix = append(suffix, nftLogExpr("routerd firewall "+name+" ", logging))
	}
	suffix = append(suffix, "counter", spec.Action)
	connSuffix := append([]string{}, common...)
	if spec.Log {
		connSuffix = append(connSuffix, nftLogExpr("routerd firewall "+name+" ", logging))
	}
	connSuffix = append(connSuffix, "counter", spec.Action)
	var out []string
	for _, match := range matches {
		if spec.ConnLimit.MaxPerSource > 0 {
			for _, connLimit := range nftFirewallConnLimitExprs(name, spec.ConnLimit, match.Family, logging) {
				out = append(out, strings.Join(strings.Fields(strings.Join([]string{match.Expr, connLimit, strings.Join(connSuffix, " ")}, " ")), " "))
			}
		}
		if rateLimit != "" || spec.ConnLimit.MaxPerSource <= 0 {
			out = append(out, strings.Join(strings.Fields(strings.Join([]string{match.Expr, strings.Join(suffix, " ")}, " ")), " "))
		}
	}
	return out, nil
}

func nftFirewallHoleExpr(hole FirewallHole) string {
	var parts []string
	if len(hole.IfNames) > 0 {
		parts = append(parts, nftIfNameMatch("iifname", hole.IfNames))
	}
	if proto := nftFirewallProtocol(hole.Protocol); proto != "" {
		parts = append(parts, proto)
	}
	if hole.Port != 0 {
		parts = append(parts, "dport "+strconv.Itoa(hole.Port))
	}
	parts = append(parts, "counter", defaultString(hole.Action, "accept"))
	if hole.Comment != "" {
		parts = append(parts, "comment "+nftQuote(hole.Comment))
	}
	return strings.Join(parts, " ")
}

func writeIngressForwardAcceptRules(buf *bytes.Buffer, rules []ingressNATRule) {
	for _, rule := range rules {
		writeIngressForwardAcceptRule(buf, rule, rule.ListenInterface, "")
		for _, ifname := range rule.HairpinInterfaces {
			if ifname == rule.ListenInterface {
				continue
			}
			writeIngressForwardAcceptRule(buf, rule, ifname, " hairpin")
		}
	}
}

func writeIngressForwardAcceptRule(buf *bytes.Buffer, rule ingressNATRule, ifname string, commentSuffix string) {
	for _, target := range ingressRuleTargets(rule) {
		var parts []string
		parts = append(parts, "iifname "+nftQuote(ifname))
		parts = append(parts, "ip daddr "+target.Address)
		parts = append(parts, rule.Protocol)
		parts = append(parts, "dport "+strconv.Itoa(target.Port))
		parts = append(parts, "counter accept")
		parts = append(parts, "comment "+nftQuote("routerd "+rule.ResourceKind+" "+rule.Name+commentSuffix))
		buf.WriteString("    " + strings.Join(parts, " ") + "\n")
	}
}

func nftIfNameMatch(key string, ifnames []string) string {
	values := compactStrings(ifnames)
	sort.Strings(values)
	if len(values) == 1 {
		return key + " " + nftQuote(values[0])
	}
	return key + " { " + nftQuotedList(values) + " }"
}

func nftFirewallProtocol(protocol string) string {
	switch protocol {
	case "tcp", "udp":
		return protocol
	case "icmp":
		return "ip protocol icmp"
	case "icmpv6", "ipv6-icmp":
		return "meta l4proto ipv6-icmp"
	case "ipip":
		return "meta nfproto ipv6 meta l4proto 4"
	case "vrrp":
		return "ip protocol 112"
	case "vrrp6":
		return "ip6 nexthdr 112"
	default:
		return ""
	}
}

func nftFirewallProtocolFamily(protocol string) string {
	switch protocol {
	case "icmp", "vrrp":
		return "ip"
	case "icmpv6", "ipv6-icmp", "ipip", "vrrp6":
		return "ip6"
	default:
		return ""
	}
}

func firewallSourcePorts(spec api.FirewallRuleSpec) []api.FirewallPort {
	return spec.SourcePorts
}

func firewallDestinationPorts(spec api.FirewallRuleSpec) []api.FirewallPort {
	if len(spec.DestinationPorts) > 0 {
		return spec.DestinationPorts
	}
	if spec.Port != 0 {
		return []api.FirewallPort{api.FirewallPort(strconv.Itoa(spec.Port))}
	}
	return nil
}

func nftPortMatch(protocol, direction string, ports []api.FirewallPort) string {
	values := make([]string, 0, len(ports))
	for _, port := range ports {
		value := strings.TrimSpace(string(port))
		if value != "" {
			values = append(values, value)
		}
	}
	if len(values) == 0 {
		return ""
	}
	prefix := protocol
	if prefix != "tcp" && prefix != "udp" {
		prefix = "th"
	}
	if len(values) == 1 {
		return prefix + " " + direction + " " + values[0]
	}
	return prefix + " " + direction + " { " + strings.Join(values, ", ") + " }"
}

func nftICMPTypeMatch(spec api.FirewallRuleSpec) string {
	switch spec.Protocol {
	case "icmp":
		if icmpType := firewallRuleICMPType(spec); icmpType != "" {
			return "icmp type " + nftICMPTypeName(icmpType)
		}
	case "icmpv6", "ipv6-icmp":
		if icmpType := firewallRuleICMPv6Type(spec); icmpType != "" {
			return "icmpv6 type " + nftICMPv6TypeName(icmpType)
		}
	}
	return ""
}

func firewallRuleICMPType(spec api.FirewallRuleSpec) string {
	if strings.TrimSpace(spec.ICMPType) != "" {
		return strings.TrimSpace(spec.ICMPType)
	}
	return strings.TrimSpace(spec.ICMPTypeKebab)
}

func firewallRuleICMPv6Type(spec api.FirewallRuleSpec) string {
	if strings.TrimSpace(spec.ICMPv6Type) != "" {
		return strings.TrimSpace(spec.ICMPv6Type)
	}
	return strings.TrimSpace(spec.ICMPv6TypeKebab)
}

func nftICMPTypeName(value string) string {
	value = strings.TrimSpace(value)
	if normalized, ok := nftICMPTypeAliases[value]; ok {
		return normalized
	}
	return value
}

func nftICMPv6TypeName(value string) string {
	value = strings.TrimSpace(value)
	if normalized, ok := nftICMPv6TypeAliases[value]; ok {
		return normalized
	}
	return value
}

var nftICMPTypeAliases = map[string]string{
	"echo-reply":              "echo-reply",
	"destination-unreachable": "destination-unreachable",
	"source-quench":           "source-quench",
	"redirect":                "redirect",
	"echo-request":            "echo-request",
	"router-advertisement":    "router-advertisement",
	"router-solicitation":     "router-solicitation",
	"time-exceeded":           "time-exceeded",
	"parameter-problem":       "parameter-problem",
	"timestamp-request":       "timestamp-request",
	"timestamp-reply":         "timestamp-reply",
}

var nftICMPv6TypeAliases = map[string]string{
	"destination-unreachable": "destination-unreachable",
	"packet-too-big":          "packet-too-big",
	"time-exceeded":           "time-exceeded",
	"parameter-problem":       "parameter-problem",
	"echo-request":            "echo-request",
	"echo-reply":              "echo-reply",
	"router-solicit":          "nd-router-solicit",
	"router-advert":           "nd-router-advert",
	"neighbor-solicit":        "nd-neighbor-solicit",
	"neighbor-advert":         "nd-neighbor-advert",
	"nd-router-solicit":       "nd-router-solicit",
	"nd-router-advert":        "nd-router-advert",
	"nd-neighbor-solicit":     "nd-neighbor-solicit",
	"nd-neighbor-advert":      "nd-neighbor-advert",
}

func nftFirewallRateLimitExpr(limit api.FirewallRateLimitSpec) string {
	rate := limit.Rate
	unit := strings.TrimSpace(limit.Unit)
	per := strings.TrimSpace(limit.Per)
	if rate == 0 && limit.PacketsPerSecond > 0 {
		rate = limit.PacketsPerSecond
	}
	if unit == "" && rate > 0 {
		unit = "packet"
	}
	if per == "" && rate > 0 {
		per = "second"
	}
	if rate <= 0 {
		return ""
	}
	value := strconv.Itoa(rate)
	burstUnit := "packets"
	switch unit {
	case "byte":
		value += " bytes"
		burstUnit = "bytes"
	case "kilobyte":
		value += " kbytes"
		burstUnit = "kbytes"
	case "megabyte":
		value += " mbytes"
		burstUnit = "mbytes"
	}
	expr := "limit rate over " + value + "/" + per
	if limit.Burst > 0 {
		expr += " burst " + strconv.Itoa(limit.Burst) + " " + burstUnit
	}
	return expr
}

func nftFirewallConnLimitExprs(name string, limit api.FirewallConnLimitSpec, family string, logging firewallLogging) []string {
	if limit.MaxPerSource <= 0 {
		return []string{""}
	}
	safeName := nftSetName("routerd_conn_" + name)
	logExpr := ""
	if limit.Log {
		logExpr = nftLogExpr("routerd firewall "+name+" conn-limit ", logging)
	}
	if family == "ip" {
		return []string{strings.TrimSpace("meter " + safeName + "_v4 { ip saddr ct count over " + strconv.Itoa(limit.MaxPerSource) + " } " + logExpr)}
	}
	if family == "ip6" {
		return []string{strings.TrimSpace("meter " + safeName + "_v6 { ip6 saddr ct count over " + strconv.Itoa(limit.MaxPerSource) + " } " + logExpr)}
	}
	return []string{
		strings.TrimSpace("meta nfproto ipv4 meter " + safeName + "_v4 { ip saddr ct count over " + strconv.Itoa(limit.MaxPerSource) + " } " + logExpr),
		strings.TrimSpace("meta nfproto ipv6 meter " + safeName + "_v6 { ip6 saddr ct count over " + strconv.Itoa(limit.MaxPerSource) + " } " + logExpr),
	}
}

func nftFirewallCIDRMatch(resourceID, direction string, cidrs []string) (string, error) {
	var v4, v6 []string
	for _, cidr := range cidrs {
		prefix, err := netip.ParsePrefix(cidr)
		if err != nil {
			return "", fmt.Errorf("%s has invalid %s CIDR %q", resourceID, direction, cidr)
		}
		if prefix.Addr().Is4() {
			v4 = append(v4, prefix.Masked().String())
		} else {
			v6 = append(v6, prefix.Masked().String())
		}
	}
	var out []string
	if len(v4) > 0 {
		sort.Strings(v4)
		if len(v4) == 1 {
			out = append(out, "ip "+direction+" "+v4[0])
		} else {
			out = append(out, "ip "+direction+" { "+strings.Join(v4, ", ")+" }")
		}
	}
	if len(v6) > 0 {
		sort.Strings(v6)
		if len(v6) == 1 {
			out = append(out, "ip6 "+direction+" "+v6[0])
		} else {
			out = append(out, "ip6 "+direction+" { "+strings.Join(v6, ", ")+" }")
		}
	}
	return strings.Join(out, " "), nil
}

type nftFirewallMatch struct {
	Family string
	Expr   string
}

func nftFirewallMatches(resourceID string, spec api.FirewallRuleSpec, addressSets map[string]nftIPAddressSet) ([]string, error) {
	matches, err := nftFirewallMatchAlternatives(resourceID, spec, addressSets)
	if err != nil {
		return nil, err
	}
	out := make([]string, 0, len(matches))
	for _, match := range matches {
		out = append(out, match.Expr)
	}
	return out, nil
}

func nftFirewallMatchAlternatives(resourceID string, spec api.FirewallRuleSpec, addressSets map[string]nftIPAddressSet) ([]nftFirewallMatch, error) {
	sources, err := nftFirewallCIDRMatchAlternatives(resourceID, "saddr", spec.SourceCIDRs)
	if err != nil {
		return nil, err
	}
	destinations, err := nftFirewallDestinationAlternatives(resourceID, spec, addressSets)
	if err != nil {
		return nil, err
	}
	excludes, err := nftFirewallExcludedDestinationMatches(resourceID, spec.ExcludeDestinationSetRefs, addressSets)
	if err != nil {
		return nil, err
	}
	if len(sources) == 0 {
		sources = []nftFirewallMatch{{}}
	}
	if len(destinations) == 0 {
		destinations = []nftFirewallMatch{{}}
	}
	var out []nftFirewallMatch
	for _, source := range sources {
		for _, destination := range destinations {
			family, ok := mergeNftMatchFamilies(source.Family, destination.Family)
			if !ok {
				continue
			}
			if protoFamily := nftFirewallProtocolFamily(spec.Protocol); protoFamily != "" {
				var protoOK bool
				family, protoOK = mergeNftMatchFamilies(family, protoFamily)
				if !protoOK {
					continue
				}
			}
			parts := []string{source.Expr, destination.Expr}
			for _, exclude := range excludes {
				if exclude.Family == "" || family == "" || exclude.Family == family {
					parts = append(parts, exclude.Expr)
				}
			}
			out = append(out, nftFirewallMatch{Family: family, Expr: strings.Join(strings.Fields(strings.Join(parts, " ")), " ")})
		}
	}
	if len(out) == 0 {
		return nil, fmt.Errorf("%s has no compatible firewall match alternatives", resourceID)
	}
	return out, nil
}

func nftFirewallCIDRMatchAlternatives(resourceID, direction string, cidrs []string) ([]nftFirewallMatch, error) {
	var out []nftFirewallMatch
	for _, cidr := range cidrs {
		prefix, err := netip.ParsePrefix(cidr)
		if err != nil {
			return nil, fmt.Errorf("%s has invalid %s CIDR %q", resourceID, direction, cidr)
		}
		prefix = prefix.Masked()
		if prefix.Addr().Is4() {
			out = append(out, nftFirewallMatch{Family: "ip", Expr: "ip " + direction + " " + prefix.String()})
		} else {
			out = append(out, nftFirewallMatch{Family: "ip6", Expr: "ip6 " + direction + " " + prefix.String()})
		}
	}
	return out, nil
}

func nftFirewallDestinationAlternatives(resourceID string, spec api.FirewallRuleSpec, addressSets map[string]nftIPAddressSet) ([]nftFirewallMatch, error) {
	out, err := nftFirewallCIDRMatchAlternatives(resourceID, "daddr", spec.DestinationCIDRs)
	if err != nil {
		return nil, err
	}
	for _, ref := range spec.DestinationSetRefs {
		set, err := nftIPAddressSetRef(resourceID, ref, addressSets)
		if err != nil {
			return nil, err
		}
		if set.IPv4Enabled {
			out = append(out, nftFirewallMatch{Family: "ip", Expr: "ip daddr @" + NftFirewallIPAddressSetName(set.Name, "ip")})
		}
		if set.IPv6Enabled {
			out = append(out, nftFirewallMatch{Family: "ip6", Expr: "ip6 daddr @" + NftFirewallIPAddressSetName(set.Name, "ip6")})
		}
	}
	return out, nil
}

func nftFirewallExcludedDestinationMatches(resourceID string, refs []string, addressSets map[string]nftIPAddressSet) ([]nftFirewallMatch, error) {
	var out []nftFirewallMatch
	for _, ref := range refs {
		set, err := nftIPAddressSetRef(resourceID, ref, addressSets)
		if err != nil {
			return nil, err
		}
		if set.IPv4Enabled {
			out = append(out, nftFirewallMatch{Family: "ip", Expr: "ip daddr != @" + NftFirewallIPAddressSetName(set.Name, "ip")})
		}
		if set.IPv6Enabled {
			out = append(out, nftFirewallMatch{Family: "ip6", Expr: "ip6 daddr != @" + NftFirewallIPAddressSetName(set.Name, "ip6")})
		}
	}
	return out, nil
}

func mergeNftMatchFamilies(a, b string) (string, bool) {
	if a == "" {
		return b, true
	}
	if b == "" || a == b {
		return a, true
	}
	return "", false
}

func nftFirewallZones(aliases map[string]string, zones []api.Resource) (map[string]firewallZone, error) {
	result := map[string]firewallZone{}
	for _, res := range zones {
		spec, err := res.FirewallZoneSpec()
		if err != nil {
			return nil, err
		}
		var ifnames []string
		for _, iface := range spec.Interfaces {
			ref := iface
			if _, name, ok := strings.Cut(iface, "/"); ok {
				ref = name
			}
			ifname := aliases[ref]
			if ifname == "" {
				return nil, fmt.Errorf("%s references interface with empty ifname %q", res.ID(), iface)
			}
			ifnames = append(ifnames, ifname)
		}
		sort.Strings(ifnames)
		result[res.Metadata.Name] = firewallZone{Name: res.Metadata.Name, Role: spec.Role, IfNames: compactStrings(ifnames)}
	}
	return result, nil
}

func sortedFirewallZones(zones map[string]firewallZone) []firewallZone {
	out := make([]firewallZone, 0, len(zones))
	for _, zone := range zones {
		out = append(out, zone)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

func nftIdent(name string) string {
	replacer := strings.NewReplacer("-", "_", ".", "_", "/", "_")
	return replacer.Replace(name)
}

func nftSetName(name string) string {
	return nftIdent(name)
}

func nftChainName(name string) string {
	return nftIdent(name)
}

func nftQuotedList(values []string) string {
	quoted := make([]string, 0, len(values))
	for _, value := range values {
		quoted = append(quoted, nftQuote(value))
	}
	return strings.Join(quoted, ", ")
}

func nftIPv4SourcesMatch(resourceID string, sources []string) (string, error) {
	if len(sources) == 0 {
		return "", nil
	}
	var values []string
	for _, source := range sources {
		prefix, err := netip.ParsePrefix(source)
		if err != nil || !prefix.Addr().Is4() {
			return "", fmt.Errorf("%s has invalid IPv4 source CIDR %q", resourceID, source)
		}
		values = append(values, prefix.Masked().String())
	}
	sort.Strings(values)
	if len(values) == 1 {
		return " ip saddr " + values[0], nil
	}
	return " ip saddr { " + strings.Join(values, ", ") + " }", nil
}

func writeNAT44Table(buf *bytes.Buffer, router *api.Router, aliases map[string]string, nat44Rules []api.Resource, ingressRules []ingressNATRule, redirectRules []localServiceRedirectRule, addressSets []nftIPAddressSet, addressSetMap map[string]nftIPAddressSet) error {
	writeNftTablePreamble(buf, "ip", "routerd_nat")
	buf.WriteString("table ip routerd_nat {\n")
	writeIPv4AddressSets(buf, addressSets)
	if len(ingressRules) > 0 || hasIPv4LocalServiceRedirectRules(redirectRules) {
		writeIngressDNATChains(buf, ingressRules)
		buf.WriteString("  chain prerouting {\n")
		buf.WriteString("    type nat hook prerouting priority dstnat; policy accept;\n")
		writeLocalServiceRedirectRules(buf, redirectRules, "ip")
		for _, rule := range ingressRules {
			writeIngressDNATRule(buf, rule, rule.ListenInterface, "")
			for _, ifname := range rule.HairpinInterfaces {
				if ifname == rule.ListenInterface {
					continue
				}
				writeIngressDNATRule(buf, rule, ifname, " hairpin")
			}
		}
		buf.WriteString("  }\n")
	}
	buf.WriteString("  chain postrouting {\n")
	buf.WriteString("    type nat hook postrouting priority srcnat; policy accept;\n")
	writeIngressHairpinSNATRules(buf, ingressRules)
	for _, res := range nat44Rules {
		spec, err := res.NAT44RuleSpec()
		if err != nil {
			return err
		}
		if spec.OutboundInterface != "" || len(spec.SourceCIDRs) > 0 || spec.Translation.Type != "" {
			ifname := aliases[spec.OutboundInterface]
			if ifname == "" {
				return fmt.Errorf("%s references outbound interface with empty ifname", res.ID())
			}
			for _, cidr := range spec.SourceCIDRs {
				prefix, err := netip.ParsePrefix(cidr)
				if err != nil || !prefix.Addr().Is4() {
					return fmt.Errorf("%s has invalid IPv4 source CIDR %q", res.ID(), cidr)
				}
				rules, err := nftSourceNATRules(ifname, prefix.Masked().String(), spec.Translation)
				if err != nil {
					return fmt.Errorf("%s: %w", res.ID(), err)
				}
				for _, rule := range rules {
					buf.WriteString("    " + rule + "\n")
				}
			}
			continue
		}
		if spec.EgressInterface == "" {
			if spec.EgressPolicyRef != "" {
				buf.WriteString("    # " + res.ID() + " skipped: egressInterface is resolved by " + spec.EgressPolicyRef + " at runtime\n")
				continue
			}
			return fmt.Errorf("%s needs resolved egressInterface for static nftables render", res.ID())
		}
		ifname := aliases[spec.EgressInterface]
		if ifname == "" {
			return fmt.Errorf("%s references egress interface with empty ifname", res.ID())
		}
		snatAddress := spec.SNATAddress
		if snatAddress == "" && spec.SNATAddressFrom.Resource != "" {
			var err error
			snatAddress, err = renderAddressFromResource(router, spec.SNATAddressFrom)
			if err != nil {
				return fmt.Errorf("%s spec.snatAddressFrom: %w", res.ID(), err)
			}
		}
		if err := writeNAT44RenderRule(buf, NAT44RenderRule{
			Name:                      res.Metadata.Name,
			Type:                      spec.Type,
			EgressInterface:           ifname,
			SourceRanges:              spec.SourceRanges,
			DestinationCIDRs:          spec.DestinationCIDRs,
			DestinationSetRefs:        spec.DestinationSetRefs,
			ExcludeDestinationCIDRs:   spec.ExcludeDestinationCIDRs,
			ExcludeDestinationSetRefs: spec.ExcludeDestinationSetRefs,
			SNATAddress:               snatAddress,
		}, addressSetMap); err != nil {
			return err
		}
	}
	buf.WriteString("  }\n")
	buf.WriteString("}\n")
	return nil
}

func writeIngressDNATChains(buf *bytes.Buffer, rules []ingressNATRule) {
	for _, rule := range rules {
		if !ingressUsesDistribution(rule) {
			continue
		}
		for i, target := range rule.Targets {
			buf.WriteString("  chain " + ingressDNATChainName(rule, i) + " {\n")
			buf.WriteString("    " + rule.Protocol + " dport " + strconv.Itoa(rule.ListenPort) + " counter dnat to " + target.Address + ":" + strconv.Itoa(target.Port) + " comment " + nftQuote("routerd "+rule.ResourceKind+" "+rule.Name+" "+target.Name) + "\n")
			buf.WriteString("  }\n")
		}
	}
}

func writeIngressDNATRule(buf *bytes.Buffer, rule ingressNATRule, ifname string, commentSuffix string) {
	var parts []string
	parts = append(parts, "iifname "+nftQuote(ifname))
	if rule.ListenAddress != "" {
		parts = append(parts, "ip daddr "+rule.ListenAddress)
	}
	parts = append(parts, rule.Protocol)
	parts = append(parts, "dport "+strconv.Itoa(rule.ListenPort))
	if ingressUsesDistribution(rule) {
		parts = append(parts, ingressSelectionExpression(rule)+" vmap { "+ingressDNATVerdictMap(rule)+" }")
	} else {
		parts = append(parts, "counter dnat to "+rule.TargetAddress+":"+strconv.Itoa(rule.TargetPort))
	}
	parts = append(parts, "comment "+nftQuote("routerd "+rule.ResourceKind+" "+rule.Name+commentSuffix))
	buf.WriteString("    " + strings.Join(parts, " ") + "\n")
}

func writeIngressHairpinSNATRules(buf *bytes.Buffer, rules []ingressNATRule) {
	for _, rule := range rules {
		if rule.ListenAddress == "" {
			continue
		}
		for _, ifname := range rule.HairpinInterfaces {
			for _, target := range ingressRuleTargets(rule) {
				var parts []string
				parts = append(parts, "iifname "+nftQuote(ifname))
				parts = append(parts, "ip daddr "+target.Address)
				parts = append(parts, rule.Protocol)
				parts = append(parts, "dport "+strconv.Itoa(target.Port))
				parts = append(parts, "ct original ip daddr "+rule.ListenAddress)
				parts = append(parts, "ct original proto-dst "+strconv.Itoa(rule.ListenPort))
				parts = append(parts, "counter masquerade")
				parts = append(parts, "comment "+nftQuote("routerd "+rule.ResourceKind+" "+rule.Name+" hairpin"))
				buf.WriteString("    " + strings.Join(parts, " ") + "\n")
			}
		}
	}
}

func ingressUsesDistribution(rule ingressNATRule) bool {
	return len(rule.Targets) > 1 && (rule.Selection == "sourceHash" || rule.Selection == "random")
}

func ingressSelectionExpression(rule ingressNATRule) string {
	switch rule.Selection {
	case "random":
		return "numgen random mod " + strconv.Itoa(len(rule.Targets))
	default:
		return "jhash ip saddr mod " + strconv.Itoa(len(rule.Targets))
	}
}

func ingressDNATVerdictMap(rule ingressNATRule) string {
	parts := make([]string, 0, len(rule.Targets))
	for i := range rule.Targets {
		parts = append(parts, strconv.Itoa(i)+" : jump "+ingressDNATChainName(rule, i))
	}
	return strings.Join(parts, ", ")
}

func ingressDNATChainName(rule ingressNATRule, index int) string {
	return "ingress_" + sanitizeNftIdentifier(rule.ResourceKind) + "_" + sanitizeNftIdentifier(rule.Name) + "_" + strconv.Itoa(index)
}

func sanitizeNftIdentifier(value string) string {
	value = strings.TrimSpace(strings.ToLower(value))
	var b strings.Builder
	for _, r := range value {
		switch {
		case r >= 'a' && r <= 'z':
			b.WriteRune(r)
		case r >= '0' && r <= '9':
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
	}
	out := strings.Trim(b.String(), "_")
	if out == "" {
		return "resource"
	}
	return out
}

func ingressRuleTargets(rule ingressNATRule) []ingressNATTarget {
	if len(rule.Targets) > 0 {
		return rule.Targets
	}
	return []ingressNATTarget{{Address: rule.TargetAddress, Port: rule.TargetPort}}
}

func writeNAT44RenderRule(buf *bytes.Buffer, rule NAT44RenderRule, addressSets map[string]nftIPAddressSet) error {
	if rule.EgressInterface == "" {
		return fmt.Errorf("nat44 rule %q has empty egress interface", rule.Name)
	}
	matches, err := nftIPv4Matches("nat44 rule "+rule.Name, nftIPv4MatchSpec{
		SourceCIDRs:               rule.SourceRanges,
		DestinationCIDRs:          rule.DestinationCIDRs,
		DestinationSetRefs:        rule.DestinationSetRefs,
		ExcludeDestinationCIDRs:   rule.ExcludeDestinationCIDRs,
		ExcludeDestinationSetRefs: rule.ExcludeDestinationSetRefs,
	}, addressSets)
	if err != nil {
		return err
	}
	for _, match := range matches {
		expr := "masquerade"
		switch rule.Type {
		case "masquerade":
		case "snat":
			if rule.SNATAddress == "" {
				return fmt.Errorf("nat44 rule %q needs snat address", rule.Name)
			}
			expr = "snat to " + rule.SNATAddress
		default:
			return fmt.Errorf("nat44 rule %q has unsupported type %q", rule.Name, rule.Type)
		}
		buf.WriteString("    oifname " + nftQuote(rule.EgressInterface) + " " + match + " " + expr + "\n")
	}
	return nil
}

func writeTCPMSSClampTable(buf *bytes.Buffer, aliases map[string]string, policies []pathMTUPolicy) error {
	writeNftTablePreamble(buf, "inet", "routerd_mss")
	buf.WriteString("table inet routerd_mss {\n")
	buf.WriteString("  chain forward {\n")
	buf.WriteString("    type filter hook forward priority mangle; policy accept;\n")
	for _, policy := range policies {
		fromIfname := aliases[policy.Spec.FromInterface]
		if fromIfname == "" {
			return fmt.Errorf("%s references fromInterface with empty ifname", policy.ResourceID)
		}
		var toIfnames []string
		for _, name := range policy.Spec.ToInterfaces {
			ifname := aliases[name]
			if ifname == "" {
				return fmt.Errorf("%s references toInterface with empty ifname %q", policy.ResourceID, name)
			}
			toIfnames = append(toIfnames, ifname)
		}
		sort.Strings(toIfnames)
		toIfnames = compactStrings(toIfnames)
		match := nftIfnameMatch("iifname", []string{fromIfname}) + " " + nftIfnameMatch("oifname", toIfnames)
		if pathMTUFamilyEnabled(policy.Spec.TCPMSSClamp.Families, "ipv4") {
			mss := policy.MTU - 40
			if mss < 536 {
				return fmt.Errorf("%s computed IPv4 MSS %d is too small", policy.ResourceID, mss)
			}
			mssValue := strconv.Itoa(mss)
			buf.WriteString("    " + match + " ip protocol tcp tcp flags syn / syn,rst tcp option maxseg size > " + mssValue + " tcp option maxseg size set " + mssValue + "\n")
		}
		if pathMTUFamilyEnabled(policy.Spec.TCPMSSClamp.Families, "ipv6") {
			mss := policy.MTU - 60
			if mss < 1220 {
				return fmt.Errorf("%s computed IPv6 MSS %d is too small", policy.ResourceID, mss)
			}
			mssValue := strconv.Itoa(mss)
			buf.WriteString("    " + match + " meta nfproto ipv6 tcp flags syn / syn,rst tcp option maxseg size > " + mssValue + " tcp option maxseg size set " + mssValue + "\n")
		}
	}
	buf.WriteString("  }\n")
	buf.WriteString("}\n")
	return nil
}

func writeIPv4PolicyRouteTable(buf *bytes.Buffer, policies []api.Resource, addressSets map[string]nftIPAddressSet) error {
	writeNftTablePreamble(buf, "ip", "routerd_policy")
	buf.WriteString("table ip routerd_policy {\n")
	writeIPv4AddressSets(buf, referencedIPv4PolicyIPAddressSets(policies, addressSets))
	buf.WriteString("  chain prerouting {\n")
	buf.WriteString("    type filter hook prerouting priority mangle; policy accept;\n")
	for _, res := range policies {
		spec, err := res.EgressRoutePolicySpec()
		if err != nil {
			return err
		}
		matches, err := nftEgressRoutePolicyMatches(res.ID(), spec, addressSets)
		if err != nil {
			return err
		}
		for _, candidate := range spec.Candidates {
			if len(candidate.Targets) > 0 {
				hashExpr, err := nftEgressRoutePolicyHash(res.ID(), spec)
				if err != nil {
					return err
				}
				markMap := nftEgressRoutePolicyTargetMarkMap(candidate.Targets)
				for _, match := range matches {
					buf.WriteString("    " + match + " ct mark != 0x0 meta mark set ct mark\n")
					prefix := strings.TrimSpace(match + " ct mark 0x0")
					buf.WriteString("    " + prefix + " meta mark set " + hashExpr + " mod " + strconv.Itoa(len(candidate.Targets)) + " map { " + markMap + " }\n")
					buf.WriteString("    " + prefix + " ct mark set meta mark\n")
				}
				continue
			}
			if spec.Mode == "priority" {
				continue
			}
			if candidate.Mark == 0 {
				continue
			}
			for _, match := range matches {
				buf.WriteString("    " + match + " meta mark set " + nftMark(candidate.Mark) + "\n")
			}
		}
	}
	buf.WriteString("  }\n")
	buf.WriteString("}\n")
	return nil
}

func nftEgressRoutePolicyMatches(resourceID string, spec api.EgressRoutePolicySpec, addressSets map[string]nftIPAddressSet) ([]string, error) {
	return nftIPv4Matches(resourceID, nftIPv4MatchSpec{
		SourceCIDRs:               spec.SourceCIDRs,
		DestinationCIDRs:          spec.DestinationCIDRs,
		DestinationSetRefs:        spec.DestinationSetRefs,
		ExcludeDestinationCIDRs:   spec.ExcludeDestinationCIDRs,
		ExcludeDestinationSetRefs: spec.ExcludeDestinationSetRefs,
	}, addressSets)
}

func nftIPv4CIDRMatches(resourceID string, sourceCIDRs, destinationCIDRs, excludeDestinationCIDRs []string) ([]string, error) {
	return nftIPv4Matches(resourceID, nftIPv4MatchSpec{
		SourceCIDRs:             sourceCIDRs,
		DestinationCIDRs:        destinationCIDRs,
		ExcludeDestinationCIDRs: excludeDestinationCIDRs,
	}, nil)
}

type nftIPv4MatchSpec struct {
	SourceCIDRs               []string
	DestinationCIDRs          []string
	DestinationSetRefs        []string
	ExcludeDestinationCIDRs   []string
	ExcludeDestinationSetRefs []string
}

func nftIPv4Matches(resourceID string, spec nftIPv4MatchSpec, addressSets map[string]nftIPAddressSet) ([]string, error) {
	var sources []string
	if len(spec.SourceCIDRs) == 0 {
		sources = []string{""}
	} else {
		for _, cidr := range spec.SourceCIDRs {
			prefix, err := netip.ParsePrefix(cidr)
			if err != nil || !prefix.Addr().Is4() {
				return nil, fmt.Errorf("%s has invalid IPv4 source CIDR %q", resourceID, cidr)
			}
			sources = append(sources, "ip saddr "+prefix.Masked().String())
		}
	}
	var destinations []string
	if len(spec.DestinationCIDRs) == 0 && len(spec.DestinationSetRefs) == 0 {
		destinations = []string{""}
	} else {
		for _, cidr := range spec.DestinationCIDRs {
			prefix, err := netip.ParsePrefix(cidr)
			if err != nil || !prefix.Addr().Is4() {
				return nil, fmt.Errorf("%s has invalid IPv4 destination CIDR %q", resourceID, cidr)
			}
			destinations = append(destinations, "ip daddr "+prefix.Masked().String())
		}
		for _, ref := range spec.DestinationSetRefs {
			setName, err := nftIPAddressSetRefName(resourceID, ref, addressSets)
			if err != nil {
				return nil, err
			}
			destinations = append(destinations, "ip daddr @"+setName)
		}
	}
	excludes, err := nftIPv4ExcludedDestinationMatch(resourceID, spec.ExcludeDestinationCIDRs, spec.ExcludeDestinationSetRefs, addressSets)
	if err != nil {
		return nil, err
	}
	var matches []string
	for _, source := range sources {
		for _, destination := range destinations {
			matches = append(matches, strings.Join(strings.Fields(strings.Join([]string{source, destination, excludes}, " ")), " "))
		}
	}
	return matches, nil
}

func nftIPv4ExcludedDestinationMatch(resourceID string, cidrs, setRefs []string, addressSets map[string]nftIPAddressSet) (string, error) {
	var out []string
	for _, cidr := range cidrs {
		prefix, err := netip.ParsePrefix(cidr)
		if err != nil || !prefix.Addr().Is4() {
			return "", fmt.Errorf("%s has invalid IPv4 excluded destination CIDR %q", resourceID, cidr)
		}
		out = append(out, "ip daddr !="+prefix.Masked().String())
	}
	for _, ref := range setRefs {
		setName, err := nftIPAddressSetRefName(resourceID, ref, addressSets)
		if err != nil {
			return "", err
		}
		out = append(out, "ip daddr != @"+setName)
	}
	return strings.Join(out, " "), nil
}

func nftIPAddressSetRefName(resourceID, ref string, sets map[string]nftIPAddressSet) (string, error) {
	set, err := nftIPAddressSetRef(resourceID, ref, sets)
	if err != nil {
		return "", err
	}
	return set.SetName, nil
}

func nftIPAddressSetRef(resourceID, ref string, sets map[string]nftIPAddressSet) (nftIPAddressSet, error) {
	ref = strings.TrimSpace(ref)
	if ref == "" {
		return nftIPAddressSet{}, fmt.Errorf("%s has empty IPAddressSet reference", resourceID)
	}
	if sets == nil {
		return nftIPAddressSet{}, fmt.Errorf("%s cannot resolve IPAddressSet reference %q without router context", resourceID, ref)
	}
	set, ok := sets[ref]
	if !ok {
		return nftIPAddressSet{}, fmt.Errorf("%s references missing IPAddressSet %q", resourceID, ref)
	}
	return set, nil
}

func nftEgressRoutePolicyHash(resourceID string, spec api.EgressRoutePolicySpec) (string, error) {
	var fields []string
	for _, field := range spec.HashFields {
		switch field {
		case "sourceAddress":
			fields = append(fields, "ip saddr")
		case "destinationAddress":
			fields = append(fields, "ip daddr")
		default:
			return "", fmt.Errorf("%s has unsupported hash field %q", resourceID, field)
		}
	}
	if len(fields) == 0 {
		return "", fmt.Errorf("%s requires at least one hash field", resourceID)
	}
	return "jhash " + strings.Join(fields, " . "), nil
}

func nftEgressRoutePolicyTargetMarkMap(targets []api.EgressRoutePolicyTarget) string {
	parts := make([]string, 0, len(targets))
	for i, target := range targets {
		parts = append(parts, strconv.Itoa(i)+" : "+nftMark(target.Mark))
	}
	return strings.Join(parts, ", ")
}

func egressPolicyRendersPolicyMarks(spec api.EgressRoutePolicySpec) bool {
	mode := defaultString(spec.Mode, "")
	if mode == "mark" || mode == "hash" {
		return true
	}
	for _, candidate := range spec.Candidates {
		if len(candidate.Targets) > 0 {
			return true
		}
		if candidate.Mark != 0 {
			return mode != "priority"
		}
	}
	return false
}

func nftSourceNATRules(ifname, cidr string, translation api.IPv4NATTranslationSpec) ([]string, error) {
	match := "oifname " + nftQuote(ifname) + " ip saddr " + cidr + " "
	expr, err := nftNATExpression(translation)
	if err != nil {
		return nil, err
	}
	if defaultString(translation.PortMapping.Type, "auto") == "range" {
		return []string{
			match + "meta l4proto { tcp, udp } " + nftNATExpressionWithPortRange(expr, translation.PortMapping),
			match + expr,
		}, nil
	}
	portSuffix, err := nftPortMapping(translation.PortMapping)
	if err != nil {
		return nil, err
	}
	return []string{match + expr + portSuffix}, nil
}

func nftNATExpressionWithPortRange(expr string, portMapping api.IPv4NATPortMappingSpec) string {
	portRange := strconv.Itoa(portMapping.Start) + "-" + strconv.Itoa(portMapping.End)
	if strings.HasPrefix(expr, "snat to ") {
		return expr + ":" + portRange
	}
	return expr + " to :" + portRange
}

func nftNATExpression(translation api.IPv4NATTranslationSpec) (string, error) {
	switch translation.Type {
	case "interfaceAddress":
		return "masquerade", nil
	case "address":
		if translation.Address == "" {
			return "", fmt.Errorf("translation.address is required")
		}
		return "snat to " + translation.Address, nil
	case "pool":
		if len(translation.Addresses) == 0 {
			return "", fmt.Errorf("translation.addresses is required")
		}
		addresses := append([]string(nil), translation.Addresses...)
		sort.Strings(addresses)
		return "snat to " + strings.Join(addresses, "-"), nil
	default:
		return "", fmt.Errorf("unsupported translation.type %q", translation.Type)
	}
}

func nftPortMapping(portMapping api.IPv4NATPortMappingSpec) (string, error) {
	switch defaultString(portMapping.Type, "auto") {
	case "auto":
		return "", nil
	case "range":
		return "", nil
	case "preserve":
		return " persistent", nil
	default:
		return "", fmt.Errorf("unsupported portMapping.type %q", portMapping.Type)
	}
}

func nftQuote(value string) string {
	return strconv.Quote(value)
}

func nftMark(value int) string {
	return fmt.Sprintf("0x%x", value)
}

func nftIfnameMatch(key string, ifnames []string) string {
	if len(ifnames) == 1 {
		return key + " " + nftQuote(ifnames[0])
	}
	quoted := make([]string, 0, len(ifnames))
	for _, ifname := range ifnames {
		quoted = append(quoted, nftQuote(ifname))
	}
	return key + " { " + strings.Join(quoted, ", ") + " }"
}

func compactStrings(values []string) []string {
	var result []string
	for _, value := range values {
		if len(result) == 0 || result[len(result)-1] != value {
			result = append(result, value)
		}
	}
	return result
}

func stringInSlice(needle string, values []string) bool {
	for _, value := range values {
		if value == needle {
			return true
		}
	}
	return false
}
