package render

import (
	"bytes"
	"fmt"
	"net/netip"
	"sort"
	"strconv"
	"strings"

	"routerd/pkg/api"
)

func NftablesIPv4SourceNAT(router *api.Router) ([]byte, error) {
	aliases, err := nftOutboundAliases(router)
	if err != nil {
		return nil, err
	}

	var nats []api.Resource
	var policies []api.Resource
	var policySets []api.Resource
	for _, res := range router.Spec.Resources {
		if res.Kind == "IPv4SourceNAT" {
			nats = append(nats, res)
		}
		if res.Kind == "IPv4PolicyRoute" {
			policies = append(policies, res)
		}
		if res.Kind == "IPv4PolicyRouteSet" {
			policySets = append(policySets, res)
		}
	}
	if len(nats) == 0 && len(policies) == 0 && len(policySets) == 0 {
		return nil, nil
	}
	sort.Slice(nats, func(i, j int) bool { return nats[i].Metadata.Name < nats[j].Metadata.Name })
	sort.Slice(policies, func(i, j int) bool { return policies[i].Metadata.Name < policies[j].Metadata.Name })
	sort.Slice(policySets, func(i, j int) bool { return policySets[i].Metadata.Name < policySets[j].Metadata.Name })

	var buf bytes.Buffer
	buf.WriteString("# Generated by routerd. Do not edit by hand.\n")
	if len(policies) > 0 || len(policySets) > 0 {
		if err := writeIPv4PolicyRouteTable(&buf, policies, policySets); err != nil {
			return nil, err
		}
	}
	if len(nats) > 0 {
		if err := writeIPv4SourceNATTable(&buf, aliases, nats); err != nil {
			return nil, err
		}
	}
	return buf.Bytes(), nil
}

func nftOutboundAliases(router *api.Router) (map[string]string, error) {
	aliases := map[string]string{}
	for _, res := range router.Spec.Resources {
		switch res.Kind {
		case "Interface":
			spec, err := res.InterfaceSpec()
			if err != nil {
				return nil, err
			}
			aliases[res.Metadata.Name] = spec.IfName
		case "PPPoEInterface":
			spec, err := res.PPPoEInterfaceSpec()
			if err != nil {
				return nil, err
			}
			aliases[res.Metadata.Name] = defaultString(spec.IfName, "ppp-"+res.Metadata.Name)
		case "DSLiteTunnel":
			spec, err := res.DSLiteTunnelSpec()
			if err != nil {
				return nil, err
			}
			aliases[res.Metadata.Name] = defaultString(spec.TunnelName, res.Metadata.Name)
		}
	}
	return aliases, nil
}

func writeIPv4SourceNATTable(buf *bytes.Buffer, aliases map[string]string, nats []api.Resource) error {
	buf.WriteString("table ip routerd_nat {\n")
	buf.WriteString("  chain postrouting {\n")
	buf.WriteString("    type nat hook postrouting priority srcnat; policy accept;\n")
	for _, res := range nats {
		spec, err := res.IPv4SourceNATSpec()
		if err != nil {
			return err
		}
		ifname := aliases[spec.OutboundInterface]
		if ifname == "" {
			return fmt.Errorf("%s references outbound interface with empty ifname", res.ID())
		}
		for _, cidr := range spec.SourceCIDRs {
			prefix, err := netip.ParsePrefix(cidr)
			if err != nil || !prefix.Addr().Is4() {
				return fmt.Errorf("%s has invalid IPv4 source CIDR %q", res.ID(), cidr)
			}
			rules, err := nftSourceNATRules(ifname, prefix.Masked().String(), spec.Translation)
			if err != nil {
				return fmt.Errorf("%s: %w", res.ID(), err)
			}
			for _, rule := range rules {
				buf.WriteString("    " + rule + "\n")
			}
		}
	}
	buf.WriteString("  }\n")
	buf.WriteString("}\n")
	return nil
}

func writeIPv4PolicyRouteTable(buf *bytes.Buffer, policies []api.Resource, policySets []api.Resource) error {
	buf.WriteString("table ip routerd_policy {\n")
	buf.WriteString("  chain prerouting {\n")
	buf.WriteString("    type filter hook prerouting priority mangle; policy accept;\n")
	for _, res := range policies {
		spec, err := res.IPv4PolicyRouteSpec()
		if err != nil {
			return err
		}
		matches, err := nftIPv4PolicyRouteMatches(res.ID(), spec)
		if err != nil {
			return err
		}
		for _, match := range matches {
			buf.WriteString("    " + match + " meta mark set " + nftMark(spec.Mark) + "\n")
		}
	}
	for _, res := range policySets {
		spec, err := res.IPv4PolicyRouteSetSpec()
		if err != nil {
			return err
		}
		matches, err := nftIPv4PolicyRouteSetMatches(res.ID(), spec)
		if err != nil {
			return err
		}
		hashExpr, err := nftIPv4PolicyRouteSetHash(res.ID(), spec)
		if err != nil {
			return err
		}
		markMap := nftPolicyRouteSetMarkMap(spec.Targets)
		for _, match := range matches {
			buf.WriteString("    " + match + " ct mark != 0x0 meta mark set ct mark\n")
			prefix := strings.TrimSpace(match + " ct mark 0x0")
			buf.WriteString("    " + prefix + " meta mark set " + hashExpr + " mod " + strconv.Itoa(len(spec.Targets)) + " map { " + markMap + " }\n")
			buf.WriteString("    " + prefix + " ct mark set meta mark\n")
		}
	}
	buf.WriteString("  }\n")
	buf.WriteString("}\n")
	return nil
}

func nftIPv4PolicyRouteMatches(resourceID string, spec api.IPv4PolicyRouteSpec) ([]string, error) {
	var sources []string
	if len(spec.SourceCIDRs) == 0 {
		sources = []string{""}
	} else {
		for _, cidr := range spec.SourceCIDRs {
			prefix, err := netip.ParsePrefix(cidr)
			if err != nil || !prefix.Addr().Is4() {
				return nil, fmt.Errorf("%s has invalid IPv4 source CIDR %q", resourceID, cidr)
			}
			sources = append(sources, "ip saddr "+prefix.Masked().String())
		}
	}
	var destinations []string
	if len(spec.DestinationCIDRs) == 0 {
		destinations = []string{""}
	} else {
		for _, cidr := range spec.DestinationCIDRs {
			prefix, err := netip.ParsePrefix(cidr)
			if err != nil || !prefix.Addr().Is4() {
				return nil, fmt.Errorf("%s has invalid IPv4 destination CIDR %q", resourceID, cidr)
			}
			destinations = append(destinations, "ip daddr "+prefix.Masked().String())
		}
	}
	var matches []string
	for _, source := range sources {
		for _, destination := range destinations {
			matches = append(matches, strings.TrimSpace(strings.Join([]string{source, destination}, " ")))
		}
	}
	return matches, nil
}

func nftIPv4PolicyRouteSetMatches(resourceID string, spec api.IPv4PolicyRouteSetSpec) ([]string, error) {
	return nftIPv4CIDRMatches(resourceID, spec.SourceCIDRs, spec.DestinationCIDRs)
}

func nftIPv4CIDRMatches(resourceID string, sourceCIDRs, destinationCIDRs []string) ([]string, error) {
	var sources []string
	if len(sourceCIDRs) == 0 {
		sources = []string{""}
	} else {
		for _, cidr := range sourceCIDRs {
			prefix, err := netip.ParsePrefix(cidr)
			if err != nil || !prefix.Addr().Is4() {
				return nil, fmt.Errorf("%s has invalid IPv4 source CIDR %q", resourceID, cidr)
			}
			sources = append(sources, "ip saddr "+prefix.Masked().String())
		}
	}
	var destinations []string
	if len(destinationCIDRs) == 0 {
		destinations = []string{""}
	} else {
		for _, cidr := range destinationCIDRs {
			prefix, err := netip.ParsePrefix(cidr)
			if err != nil || !prefix.Addr().Is4() {
				return nil, fmt.Errorf("%s has invalid IPv4 destination CIDR %q", resourceID, cidr)
			}
			destinations = append(destinations, "ip daddr "+prefix.Masked().String())
		}
	}
	var matches []string
	for _, source := range sources {
		for _, destination := range destinations {
			matches = append(matches, strings.TrimSpace(strings.Join([]string{source, destination}, " ")))
		}
	}
	return matches, nil
}

func nftIPv4PolicyRouteSetHash(resourceID string, spec api.IPv4PolicyRouteSetSpec) (string, error) {
	var fields []string
	for _, field := range spec.HashFields {
		switch field {
		case "sourceAddress":
			fields = append(fields, "ip saddr")
		case "destinationAddress":
			fields = append(fields, "ip daddr")
		default:
			return "", fmt.Errorf("%s has unsupported hash field %q", resourceID, field)
		}
	}
	if len(fields) == 0 {
		return "", fmt.Errorf("%s requires at least one hash field", resourceID)
	}
	return "jhash " + strings.Join(fields, " . "), nil
}

func nftPolicyRouteSetMarkMap(targets []api.IPv4PolicyRouteTarget) string {
	parts := make([]string, 0, len(targets))
	for i, target := range targets {
		parts = append(parts, strconv.Itoa(i)+" : "+nftMark(target.Mark))
	}
	return strings.Join(parts, ", ")
}

func nftSourceNATRules(ifname, cidr string, translation api.IPv4NATTranslationSpec) ([]string, error) {
	match := "oifname " + nftQuote(ifname) + " ip saddr " + cidr + " "
	expr, err := nftNATExpression(translation)
	if err != nil {
		return nil, err
	}
	if defaultString(translation.PortMapping.Type, "auto") == "range" {
		return []string{
			match + "meta l4proto { tcp, udp } " + nftNATExpressionWithPortRange(expr, translation.PortMapping),
			match + expr,
		}, nil
	}
	portSuffix, err := nftPortMapping(translation.PortMapping)
	if err != nil {
		return nil, err
	}
	return []string{match + expr + portSuffix}, nil
}

func nftNATExpressionWithPortRange(expr string, portMapping api.IPv4NATPortMappingSpec) string {
	portRange := strconv.Itoa(portMapping.Start) + "-" + strconv.Itoa(portMapping.End)
	if strings.HasPrefix(expr, "snat to ") {
		return expr + ":" + portRange
	}
	return expr + " to :" + portRange
}

func nftNATExpression(translation api.IPv4NATTranslationSpec) (string, error) {
	switch translation.Type {
	case "interfaceAddress":
		return "masquerade", nil
	case "address":
		if translation.Address == "" {
			return "", fmt.Errorf("translation.address is required")
		}
		return "snat to " + translation.Address, nil
	case "pool":
		if len(translation.Addresses) == 0 {
			return "", fmt.Errorf("translation.addresses is required")
		}
		addresses := append([]string(nil), translation.Addresses...)
		sort.Strings(addresses)
		return "snat to " + strings.Join(addresses, "-"), nil
	default:
		return "", fmt.Errorf("unsupported translation.type %q", translation.Type)
	}
}

func nftPortMapping(portMapping api.IPv4NATPortMappingSpec) (string, error) {
	switch defaultString(portMapping.Type, "auto") {
	case "auto":
		return "", nil
	case "range":
		return "", nil
	case "preserve":
		return " persistent", nil
	default:
		return "", fmt.Errorf("unsupported portMapping.type %q", portMapping.Type)
	}
}

func nftQuote(value string) string {
	return strconv.Quote(value)
}

func nftMark(value int) string {
	return fmt.Sprintf("0x%x", value)
}
