// SPDX-License-Identifier: BSD-3-Clause

package render

import (
	"bytes"
	"fmt"
	"sort"
	"strconv"
	"strings"

	"github.com/imksoo/routerd/pkg/api"
	"github.com/imksoo/routerd/pkg/hostdeps"
	"github.com/imksoo/routerd/pkg/platform"
	"github.com/imksoo/routerd/pkg/sysctlprofile"
)

type nixOSInterface struct {
	Name              string
	IfName            string
	AdminUp           bool
	Bridge            string
	VRF               string
	DHCPv4            bool
	DHCPv4UseRoutes   *bool
	DHCPv4UseDNS      *bool
	DHCPv4RouteMetric int
	AcceptRA          bool
	DisableDHCPv4     bool
	DisableDHCPv6     bool
	DisableIPv6RA     bool
	Addresses         []string
	Routes            []nixOSRoute
	MTU               int
}

type nixOSRoute struct {
	Destination string
	Gateway     string
	Metric      int
}

type nixOSBridge struct {
	Name              string
	IfName            string
	STP               bool
	RSTP              bool
	ForwardDelay      int
	HelloTime         int
	MACAddress        string
	MTU               int
	MulticastSnooping bool
}

type nixOSVXLAN struct {
	Name           string
	IfName         string
	VNI            int
	LocalAddress   string
	Remotes        []string
	MulticastGroup string
	UDPPort        int
	MTU            int
	Bridge         string
}

type nixOSVRF struct {
	Name       string
	IfName     string
	RouteTable int
	Members    []string
}

type nixOSDHCPv6Client struct {
	Name       string
	IFName     string
	Interface  string
	ClientDUID string
}

type nixOSSystemdUnit struct {
	Name string
	Spec api.SystemdUnitSpec
	Path []string
}

type nixOSChronyConfig struct {
	Enabled         bool
	Servers         []string
	AllowCIDRs      []string
	ListenAddresses []string
}

func NixOSModule(router *api.Router) ([]byte, error) {
	router = api.ExpandClusterNetworkRoutes(router)
	host, err := nixOSHost(router)
	if err != nil {
		return nil, err
	}
	interfaces, err := nixOSInterfaces(router)
	if err != nil {
		return nil, err
	}
	bridges, err := nixOSBridges(router)
	if err != nil {
		return nil, err
	}
	vxlans, err := nixOSVXLANS(router)
	if err != nil {
		return nil, err
	}
	vrfs, err := nixOSVRFS(router, interfaces)
	if err != nil {
		return nil, err
	}
	dhcpv6Clients, err := nixOSDHCPv6Clients(router, interfaces)
	if err != nil {
		return nil, err
	}
	ntpServers, err := nixOSNTPServers(router)
	if err != nil {
		return nil, err
	}
	chrony, err := nixOSChronyConfigForRouter(router)
	if err != nil {
		return nil, err
	}
	sysctls, err := nixOSSysctls(router)
	if err != nil {
		return nil, err
	}
	packages, servicePackages, err := nixOSPackages(router, host)
	if err != nil {
		return nil, err
	}
	resolvedStubDisabled := nixOSResolvedStubDisabled(router)
	systemdUnits, err := nixOSSystemdUnits(router)
	if err != nil {
		return nil, err
	}
	telemetryEnv, err := TelemetryEnvironment(router)
	if err != nil {
		return nil, err
	}

	var buf bytes.Buffer
	buf.WriteString("# Generated by routerd. Do not edit by hand.\n")
	buf.WriteString("{ config, lib, pkgs, ... }:\n\n")
	buf.WriteString("{\n")
	if host.Hostname != "" {
		buf.WriteString("  networking.hostName = " + nixString(host.Hostname) + ";\n")
	}
	if host.Domain != "" {
		buf.WriteString("  networking.domain = " + nixString(host.Domain) + ";\n")
	}
	if host.Boot.Loader == "grub" || host.Boot.GrubDevice != "" {
		buf.WriteString("  boot.loader.grub.enable = true;\n")
		if host.Boot.GrubDevice != "" {
			buf.WriteString("  boot.loader.grub.device = " + nixString(host.Boot.GrubDevice) + ";\n")
		}
	}
	if len(interfaces) > 0 {
		buf.WriteString("  networking.useDHCP = false;\n")
		buf.WriteString("  networking.useNetworkd = true;\n")
		buf.WriteString("  networking.firewall.checkReversePath = false;\n")
		if udpPorts := nixOSFirewallAllowedUDPPorts(vxlans); len(udpPorts) > 0 {
			buf.WriteString("  networking.firewall.allowedUDPPorts = [ " + nixIntListSpaced(udpPorts) + " ];\n")
		}
		if trusted := nixOSFirewallTrustedInterfaces(vxlans); len(trusted) > 0 {
			buf.WriteString("  networking.firewall.trustedInterfaces = " + nixStringList(trusted) + ";\n")
		}
		if nixOSNeedsNftables(router) {
			buf.WriteString("  networking.nftables.enable = true;\n")
		}
		buf.WriteString("  systemd.network.enable = true;\n")
		for _, bridge := range bridges {
			writeNixOSBridge(&buf, bridge)
		}
		for _, vxlan := range vxlans {
			writeNixOSVXLAN(&buf, vxlan)
			writeNixOSVXLANFDBService(&buf, vxlan)
		}
		for _, vrf := range vrfs {
			writeNixOSVRF(&buf, vrf)
		}
		for _, iface := range interfaces {
			writeNixOSNetwork(&buf, iface)
		}
	}
	if api.BoolDefault(host.SSH.Enabled, len(host.Users) > 0) {
		buf.WriteString("  services.openssh = {\n")
		buf.WriteString("    enable = true;\n")
		if host.SSH.PasswordAuthentication != nil || host.SSH.PermitRootLogin != "" {
			buf.WriteString("    settings = {\n")
			if host.SSH.PasswordAuthentication != nil {
				buf.WriteString("      PasswordAuthentication = " + nixBool(*host.SSH.PasswordAuthentication) + ";\n")
			}
			if host.SSH.PermitRootLogin != "" {
				buf.WriteString("      PermitRootLogin = " + nixString(host.SSH.PermitRootLogin) + ";\n")
			}
			buf.WriteString("    };\n")
		}
		buf.WriteString("  };\n")
	}
	for _, user := range host.Users {
		writeNixOSUser(&buf, user)
	}
	if host.Sudo.WheelNeedsPassword != nil {
		buf.WriteString("  security.sudo.wheelNeedsPassword = " + nixBool(*host.Sudo.WheelNeedsPassword) + ";\n")
	}
	if chrony.Enabled {
		buf.WriteString("  services.timesyncd.enable = false;\n")
		buf.WriteString("  services.chrony.enable = true;\n")
		if len(chrony.Servers) > 0 {
			buf.WriteString("  services.chrony.servers = " + nixStringList(chrony.Servers) + ";\n")
		}
		if len(chrony.AllowCIDRs) > 0 || len(chrony.ListenAddresses) > 0 {
			buf.WriteString("  services.chrony.extraConfig = ''\n")
			for _, cidr := range chrony.AllowCIDRs {
				buf.WriteString("    allow " + cidr + "\n")
			}
			for _, address := range chrony.ListenAddresses {
				buf.WriteString("    bindaddress " + address + "\n")
			}
			buf.WriteString("    cmdallow 127.0.0.1\n")
			buf.WriteString("    cmdallow ::1\n")
			buf.WriteString("  '';\n")
		}
	} else if len(ntpServers) > 0 {
		buf.WriteString("  services.timesyncd.enable = true;\n")
		buf.WriteString("  services.timesyncd.servers = " + nixStringList(ntpServers) + ";\n")
	}
	if resolvedStubDisabled {
		buf.WriteString("  services.resolved.enable = true;\n")
		buf.WriteString("  services.resolved.extraConfig = ''\n")
		buf.WriteString("    DNSStubListener=no\n")
		buf.WriteString("  '';\n")
	}
	if nixOSTailscaleEnabled(router) {
		buf.WriteString("  services.tailscale.enable = true;\n")
	}
	if len(sysctls) > 0 {
		buf.WriteString("  boot.kernel.sysctl = {\n")
		for _, key := range sortedMapKeysString(sysctls) {
			buf.WriteString("    " + nixString(key) + " = " + nixSysctlValue(sysctls[key]) + ";\n")
		}
		buf.WriteString("  };\n")
	}
	if len(packages) > 0 {
		buf.WriteString("  environment.systemPackages = with pkgs; [\n")
		for _, pkg := range packages {
			buf.WriteString("    " + pkg + "\n")
		}
		buf.WriteString("  ];\n")
	}
	if !nixOSRouterdSupervisesClientDaemons(host.RouterdService) {
		for _, client := range dhcpv6Clients {
			writeNixOSDHCPv6ClientService(&buf, client)
		}
	}
	for _, unit := range systemdUnits {
		writeNixOSSystemdUnit(&buf, unit)
	}
	if api.BoolDefault(host.RouterdService.Enabled, false) {
		writeNixOSRouterdService(&buf, host.RouterdService, servicePackages, telemetryEnv)
	}
	if host.StateVersion != "" {
		buf.WriteString("  system.stateVersion = " + nixString(host.StateVersion) + ";\n")
	}
	buf.WriteString("}\n")
	return buf.Bytes(), nil
}

func nixOSRouterdSupervisesClientDaemons(spec api.NixOSRouterdServiceSpec) bool {
	if !api.BoolDefault(spec.Enabled, false) {
		return false
	}
	return true
}

func nixOSDHCPv6Clients(router *api.Router, interfaces []nixOSInterface) ([]nixOSDHCPv6Client, error) {
	aliases := map[string]string{}
	for _, iface := range interfaces {
		aliases[iface.Name] = iface.IfName
	}
	var out []nixOSDHCPv6Client
	for _, res := range router.Spec.Resources {
		if res.Kind != "DHCPv6PrefixDelegation" {
			continue
		}
		spec, err := res.DHCPv6PrefixDelegationSpec()
		if err != nil {
			return nil, err
		}
		ifname := aliases[spec.Interface]
		if ifname == "" {
			ifname = spec.Interface
		}
		if ifname == "" {
			return nil, fmt.Errorf("%s needs spec.interface", res.ID())
		}
		out = append(out, nixOSDHCPv6Client{Name: res.Metadata.Name, Interface: spec.Interface, IFName: ifname, ClientDUID: spec.ClientDUID})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out, nil
}

func nixOSHost(router *api.Router) (api.NixOSHostSpec, error) {
	var out api.NixOSHostSpec
	seen := false
	for _, res := range router.Spec.Resources {
		switch res.Kind {
		case "NixOSHost":
			if seen {
				return out, fmt.Errorf("multiple NixOSHost resources are not supported")
			}
			spec, err := res.NixOSHostSpec()
			if err != nil {
				return out, err
			}
			out = spec
			seen = true
		case "Hostname":
			spec, err := res.HostnameSpec()
			if err != nil {
				return out, err
			}
			if out.Hostname == "" && spec.Managed {
				host, domain := splitHostname(spec.Hostname)
				out.Hostname = host
				out.Domain = domain
			}
		}
	}
	return out, nil
}

func nixOSNTPServers(router *api.Router) ([]string, error) {
	var servers []string
	for _, res := range router.Spec.Resources {
		if res.Kind != "NTPClient" {
			continue
		}
		spec, err := res.NTPClientSpec()
		if err != nil {
			return nil, err
		}
		if !spec.Managed {
			continue
		}
		if provider := defaultString(spec.Provider, "systemd-timesyncd"); provider == "chrony" {
			continue
		} else if provider != "systemd-timesyncd" {
			return nil, fmt.Errorf("%s has unsupported provider %q", res.ID(), provider)
		}
		source := defaultString(spec.Source, "static")
		switch source {
		case "static", "auto", "dhcp", "dhcpv6":
		default:
			return nil, fmt.Errorf("%s has unsupported source %q", res.ID(), source)
		}
		for _, server := range spec.Servers {
			server = strings.TrimSpace(server)
			if server != "" {
				servers = append(servers, server)
			}
		}
		if source != "static" && len(spec.Servers) == 0 {
			for _, server := range spec.FallbackServers {
				server = strings.TrimSpace(server)
				if server != "" {
					servers = append(servers, server)
				}
			}
		}
	}
	sort.Strings(servers)
	return servers, nil
}

func nixOSChronyConfigForRouter(router *api.Router) (nixOSChronyConfig, error) {
	var cfg nixOSChronyConfig
	for _, res := range router.Spec.Resources {
		switch res.Kind {
		case "NTPClient":
			spec, err := res.NTPClientSpec()
			if err != nil {
				return cfg, err
			}
			if !spec.Managed {
				continue
			}
			if provider := defaultString(spec.Provider, "systemd-timesyncd"); provider != "chrony" {
				continue
			}
			cfg.Enabled = true
			cfg.Servers = append(cfg.Servers, nixOSRenderNTPServers(spec.Source, spec.Servers, spec.FallbackServers)...)
		case "NTPServer":
			spec, err := res.NTPServerSpec()
			if err != nil {
				return cfg, err
			}
			if !spec.Managed {
				continue
			}
			if provider := defaultString(spec.Provider, "chrony"); provider != "chrony" {
				return cfg, fmt.Errorf("%s has unsupported NixOS provider %q", res.ID(), provider)
			}
			cfg.Enabled = true
			cfg.Servers = append(cfg.Servers, nixOSRenderNTPServers(spec.Source, spec.Servers, spec.FallbackServers)...)
			cfg.AllowCIDRs = append(cfg.AllowCIDRs, spec.AllowCIDRs...)
			cfg.ListenAddresses = append(cfg.ListenAddresses, spec.ListenAddresses...)
		}
	}
	cfg.Servers = compactSortedStrings(cfg.Servers)
	cfg.AllowCIDRs = compactSortedStrings(cfg.AllowCIDRs)
	cfg.ListenAddresses = compactSortedStrings(cfg.ListenAddresses)
	return cfg, nil
}

func nixOSRenderNTPServers(source string, servers, fallback []string) []string {
	source = defaultString(source, "static")
	out := compactRenderNTPServers(servers)
	if source != "static" && len(out) == 0 {
		out = compactRenderNTPServers(fallback)
	}
	return out
}

func compactSortedStrings(values []string) []string {
	seen := map[string]bool{}
	out := make([]string, 0, len(values))
	for _, value := range values {
		value = strings.TrimSpace(value)
		if value == "" || seen[value] {
			continue
		}
		seen[value] = true
		out = append(out, value)
	}
	sort.Strings(out)
	return out
}

func nixOSSysctls(router *api.Router) (map[string]string, error) {
	values := map[string]string{}
	for _, res := range hostdeps.SysctlResources(router) {
		switch res.Kind {
		case "Sysctl":
			spec, err := res.SysctlSpec()
			if err != nil {
				return nil, err
			}
			if spec.Persistent {
				values[spec.Key] = spec.Value
			}
		case "SysctlProfile":
			spec, err := res.SysctlProfileSpec()
			if err != nil {
				return nil, err
			}
			if !spec.Persistent {
				continue
			}
			entries, err := sysctlprofile.Entries(spec.Profile, spec.Overrides)
			if err != nil {
				return nil, err
			}
			for _, entry := range entries {
				if entry.Optional {
					continue
				}
				values[entry.Key] = entry.Value
			}
		}
	}
	return values, nil
}

func nixOSInterfaces(router *api.Router) ([]nixOSInterface, error) {
	interfaces := map[string]*nixOSInterface{}
	var names []string
	for _, res := range router.Spec.Resources {
		if res.Kind != "Interface" {
			continue
		}
		spec, err := res.InterfaceSpec()
		if err != nil {
			return nil, err
		}
		if spec.IfName == "" {
			return nil, fmt.Errorf("%s has empty ifname", res.ID())
		}
		interfaces[res.Metadata.Name] = &nixOSInterface{
			Name:    res.Metadata.Name,
			IfName:  spec.IfName,
			AdminUp: spec.AdminUp,
			MTU:     spec.MTU,
		}
		names = append(names, res.Metadata.Name)
	}
	for _, res := range router.Spec.Resources {
		if res.Kind != "Bridge" {
			continue
		}
		spec, err := res.BridgeSpec()
		if err != nil {
			return nil, err
		}
		interfaces[res.Metadata.Name] = &nixOSInterface{
			Name:    res.Metadata.Name,
			IfName:  defaultString(spec.IfName, res.Metadata.Name),
			AdminUp: true,
		}
		names = append(names, res.Metadata.Name)
	}
	for _, res := range router.Spec.Resources {
		if res.Kind != "VXLANSegment" {
			continue
		}
		spec, err := res.VXLANSegmentSpec()
		if err != nil {
			return nil, err
		}
		interfaces[res.Metadata.Name] = &nixOSInterface{
			Name:    res.Metadata.Name,
			IfName:  defaultString(spec.IfName, res.Metadata.Name),
			AdminUp: true,
		}
		names = append(names, res.Metadata.Name)
	}
	aliases := linkAliases(router)
	bridges, err := bridgeConfigs(router, aliases)
	if err != nil {
		return nil, err
	}
	for _, bridge := range bridges {
		for _, member := range bridge.Members {
			for _, iface := range interfaces {
				if iface.IfName == member {
					iface.Bridge = bridge.IfName
				}
			}
		}
	}
	for _, res := range router.Spec.Resources {
		if res.Kind != "VRF" {
			continue
		}
		spec, err := res.VRFSpec()
		if err != nil {
			return nil, err
		}
		vrfIfName := defaultString(spec.IfName, res.Metadata.Name)
		for _, member := range spec.Members {
			if iface := interfaces[member]; iface != nil {
				iface.VRF = vrfIfName
			}
		}
	}
	for _, res := range hostdeps.NetworkAdoptionResources(router) {
		spec, err := res.NetworkAdoptionSpec()
		if err != nil {
			return nil, err
		}
		if defaultString(spec.State, "present") == "absent" {
			continue
		}
		ifname := strings.TrimSpace(spec.IfName)
		name := spec.Interface
		if ifname == "" && name != "" {
			if iface := interfaces[name]; iface != nil {
				ifname = iface.IfName
			}
		}
		if ifname == "" {
			continue
		}
		if name == "" {
			name = "adopt-" + ifname
		}
		if interfaces[name] == nil {
			interfaces[name] = &nixOSInterface{Name: name, IfName: ifname, AdminUp: true}
			names = append(names, name)
		}
		iface := interfaces[name]
		if spec.SystemdNetworkd.DisableDHCPv4 {
			iface.DisableDHCPv4 = true
		}
		if spec.SystemdNetworkd.DisableDHCPv6 {
			iface.DisableDHCPv6 = true
		}
		if spec.SystemdNetworkd.DisableIPv6RA {
			iface.DisableIPv6RA = true
		}
		if spec.SystemdNetworkd.DHCPv4UseRoutes != nil {
			iface.DHCPv4UseRoutes = spec.SystemdNetworkd.DHCPv4UseRoutes
		}
		if spec.SystemdNetworkd.DHCPv4UseDNS != nil {
			iface.DHCPv4UseDNS = spec.SystemdNetworkd.DHCPv4UseDNS
		}
		if spec.SystemdNetworkd.DHCPv4RouteMetric != 0 {
			iface.DHCPv4RouteMetric = spec.SystemdNetworkd.DHCPv4RouteMetric
		}
	}
	for _, res := range router.Spec.Resources {
		switch res.Kind {
		case "IPv4StaticAddress":
			spec, err := res.IPv4StaticAddressSpec()
			if err != nil {
				return nil, err
			}
			if iface := interfaces[spec.Interface]; iface != nil {
				iface.Addresses = append(iface.Addresses, spec.Address)
			}
		case "IPv4StaticRoute":
			spec, err := res.IPv4StaticRouteSpec()
			if err != nil {
				return nil, err
			}
			if iface := interfaces[spec.Interface]; iface != nil {
				iface.Routes = append(iface.Routes, nixOSRoute{Destination: spec.Destination, Gateway: spec.Via, Metric: spec.Metric})
			}
		case "IPv6StaticRoute":
			spec, err := res.IPv6StaticRouteSpec()
			if err != nil {
				return nil, err
			}
			if iface := interfaces[spec.Interface]; iface != nil {
				iface.Routes = append(iface.Routes, nixOSRoute{Destination: spec.Destination, Gateway: spec.Via, Metric: spec.Metric})
			}
		case "IPv6RAAddress":
			spec, err := res.IPv6RAAddressSpec()
			if err != nil {
				return nil, err
			}
			if iface := interfaces[spec.Interface]; iface != nil && api.BoolDefault(spec.Managed, true) {
				iface.AcceptRA = true
			}
		}
	}
	sort.Strings(names)
	out := make([]nixOSInterface, 0, len(names))
	for _, name := range names {
		out = append(out, *interfaces[name])
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].IfName == out[j].IfName {
			return out[i].Name < out[j].Name
		}
		return out[i].IfName < out[j].IfName
	})
	return out, nil
}

func nixOSBridges(router *api.Router) ([]nixOSBridge, error) {
	bridges, err := bridgeConfigs(router, linkAliases(router))
	if err != nil {
		return nil, err
	}
	out := make([]nixOSBridge, 0, len(bridges))
	for _, bridge := range bridges {
		out = append(out, nixOSBridge{
			Name:              bridge.Name,
			IfName:            bridge.IfName,
			STP:               bridge.STP,
			RSTP:              bridge.RSTP,
			ForwardDelay:      bridge.ForwardDelay,
			HelloTime:         bridge.HelloTime,
			MACAddress:        bridge.MACAddress,
			MTU:               bridge.MTU,
			MulticastSnooping: bridge.MulticastSnooping,
		})
	}
	return out, nil
}

func nixOSVXLANS(router *api.Router) ([]nixOSVXLAN, error) {
	vxlans, err := vxlanConfigs(router, linkAliases(router))
	if err != nil {
		return nil, err
	}
	out := make([]nixOSVXLAN, 0, len(vxlans))
	for _, vxlan := range vxlans {
		out = append(out, nixOSVXLAN{
			Name:           vxlan.Name,
			IfName:         vxlan.IfName,
			VNI:            vxlan.VNI,
			LocalAddress:   vxlan.LocalAddress,
			Remotes:        vxlan.Remotes,
			MulticastGroup: vxlan.MulticastGroup,
			UDPPort:        vxlan.UDPPort,
			MTU:            vxlan.MTU,
			Bridge:         vxlan.BridgeIfName,
		})
	}
	return out, nil
}

func nixOSVRFS(router *api.Router, interfaces []nixOSInterface) ([]nixOSVRF, error) {
	ifnames := map[string]string{}
	for _, iface := range interfaces {
		ifnames[iface.Name] = iface.IfName
	}
	var out []nixOSVRF
	for _, res := range router.Spec.Resources {
		if res.Kind != "VRF" {
			continue
		}
		spec, err := res.VRFSpec()
		if err != nil {
			return nil, err
		}
		var members []string
		for _, member := range spec.Members {
			if ifname := ifnames[member]; ifname != "" {
				members = append(members, ifname)
			}
		}
		out = append(out, nixOSVRF{
			Name:       res.Metadata.Name,
			IfName:     defaultString(spec.IfName, res.Metadata.Name),
			RouteTable: spec.RouteTable,
			Members:    members,
		})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].IfName < out[j].IfName })
	return out, nil
}

func writeNixOSBridge(buf *bytes.Buffer, bridge nixOSBridge) {
	buf.WriteString("  systemd.network.netdevs." + nixString("30-routerd-"+bridge.IfName) + " = {\n")
	buf.WriteString("    netdevConfig = {\n")
	buf.WriteString("      Name = " + nixString(bridge.IfName) + ";\n")
	buf.WriteString("      Kind = \"bridge\";\n")
	if bridge.MACAddress != "" {
		buf.WriteString("      MACAddress = " + nixString(bridge.MACAddress) + ";\n")
	}
	if bridge.MTU != 0 {
		buf.WriteString("      MTUBytes = " + strconv.Itoa(bridge.MTU) + ";\n")
	}
	buf.WriteString("    };\n")
	buf.WriteString("    bridgeConfig = {\n")
	buf.WriteString("      STP = " + nixBool(bridge.STP) + ";\n")
	buf.WriteString("      MulticastSnooping = " + nixBool(bridge.MulticastSnooping) + ";\n")
	buf.WriteString("      ForwardDelaySec = " + strconv.Itoa(bridge.ForwardDelay) + ";\n")
	buf.WriteString("      HelloTimeSec = " + strconv.Itoa(bridge.HelloTime) + ";\n")
	buf.WriteString("    };\n")
	buf.WriteString("  };\n")
}

func writeNixOSVXLAN(buf *bytes.Buffer, vxlan nixOSVXLAN) {
	buf.WriteString("  systemd.network.netdevs." + nixString("31-routerd-"+vxlan.IfName) + " = {\n")
	buf.WriteString("    netdevConfig = {\n")
	buf.WriteString("      Name = " + nixString(vxlan.IfName) + ";\n")
	buf.WriteString("      Kind = \"vxlan\";\n")
	if vxlan.MTU != 0 {
		buf.WriteString("      MTUBytes = " + strconv.Itoa(vxlan.MTU) + ";\n")
	}
	buf.WriteString("    };\n")
	buf.WriteString("    vxlanConfig = {\n")
	buf.WriteString("      VNI = " + strconv.Itoa(vxlan.VNI) + ";\n")
	buf.WriteString("      Local = " + nixString(vxlan.LocalAddress) + ";\n")
	buf.WriteString("      Independent = true;\n")
	if vxlan.MulticastGroup != "" {
		buf.WriteString("      Group = " + nixString(vxlan.MulticastGroup) + ";\n")
	} else if len(vxlan.Remotes) > 0 {
		buf.WriteString("      Remote = " + nixString(vxlan.Remotes[0]) + ";\n")
	}
	buf.WriteString("      DestinationPort = " + strconv.Itoa(vxlan.UDPPort) + ";\n")
	buf.WriteString("    };\n")
	buf.WriteString("  };\n")
	if vxlan.Bridge != "" || len(vxlan.Remotes) > 1 {
		buf.WriteString("  systemd.network.networks." + nixString("31-routerd-"+vxlan.IfName) + " = {\n")
		buf.WriteString("    matchConfig.Name = " + nixString(vxlan.IfName) + ";\n")
		buf.WriteString("    networkConfig = {\n")
		if vxlan.Bridge != "" {
			buf.WriteString("      Bridge = " + nixString(vxlan.Bridge) + ";\n")
		}
		buf.WriteString("    };\n")
		if len(vxlan.Remotes) > 1 {
			buf.WriteString("    bridgeFDBs = [\n")
			for _, remote := range vxlan.Remotes {
				buf.WriteString("      { MACAddress = \"00:00:00:00:00:00\"; Destination = " + nixString(remote) + "; }\n")
			}
			buf.WriteString("    ];\n")
		}
		buf.WriteString("  };\n")
	}
}

func writeNixOSVXLANFDBService(buf *bytes.Buffer, vxlan nixOSVXLAN) {
	if vxlan.MulticastGroup != "" || len(vxlan.Remotes) < 2 {
		return
	}
	buf.WriteString("  systemd.services." + nixString("routerd-"+vxlan.IfName+"-fdb") + " = {\n")
	buf.WriteString("    description = " + nixString("routerd VXLAN flood FDB entries for "+vxlan.IfName) + ";\n")
	buf.WriteString("    after = [ \"systemd-networkd.service\" ];\n")
	buf.WriteString("    wants = [ \"systemd-networkd.service\" ];\n")
	buf.WriteString("    wantedBy = [ \"multi-user.target\" ];\n")
	buf.WriteString("    path = [ pkgs.iproute2 ];\n")
	buf.WriteString("    serviceConfig = {\n")
	buf.WriteString("      Type = \"oneshot\";\n")
	buf.WriteString("      RemainAfterExit = true;\n")
	buf.WriteString("    };\n")
	buf.WriteString("    script = ''\n")
	buf.WriteString("      set -eu\n")
	buf.WriteString("      for remote in")
	for _, remote := range vxlan.Remotes {
		buf.WriteString(" " + shellSingleQuote(remote))
	}
	buf.WriteString("; do\n")
	buf.WriteString("        bridge fdb show dev " + shellSingleQuote(vxlan.IfName) + " | grep -F \"00:00:00:00:00:00 dst $remote\" >/dev/null || \\\n")
	buf.WriteString("          bridge fdb append 00:00:00:00:00:00 dev " + shellSingleQuote(vxlan.IfName) + " dst \"$remote\" || true\n")
	buf.WriteString("      done\n")
	buf.WriteString("    '';\n")
	buf.WriteString("  };\n")
}

func writeNixOSVRF(buf *bytes.Buffer, vrf nixOSVRF) {
	buf.WriteString("  systemd.network.netdevs." + nixString("32-routerd-"+vrf.IfName) + " = {\n")
	buf.WriteString("    netdevConfig = {\n")
	buf.WriteString("      Name = " + nixString(vrf.IfName) + ";\n")
	buf.WriteString("      Kind = \"vrf\";\n")
	buf.WriteString("    };\n")
	buf.WriteString("    vrfConfig = {\n")
	buf.WriteString("      Table = " + strconv.Itoa(vrf.RouteTable) + ";\n")
	buf.WriteString("    };\n")
	buf.WriteString("  };\n")
}

func writeNixOSNetwork(buf *bytes.Buffer, iface nixOSInterface) {
	buf.WriteString("  systemd.network.networks." + nixString("10-netplan-"+iface.IfName) + " = {\n")
	buf.WriteString("    matchConfig.Name = " + nixString(iface.IfName) + ";\n")
	if iface.DHCPv4 || iface.AcceptRA || iface.Bridge != "" || iface.VRF != "" || len(iface.Addresses) == 0 || iface.DisableDHCPv4 || iface.DisableDHCPv6 || iface.DisableIPv6RA {
		buf.WriteString("    networkConfig = {\n")
		dhcpv4 := iface.DHCPv4 && !iface.DisableDHCPv4
		dhcpv6 := false
		if dhcpv4 && dhcpv6 {
			buf.WriteString("      DHCP = \"yes\";\n")
		} else if dhcpv4 {
			buf.WriteString("      DHCP = \"ipv4\";\n")
		} else if dhcpv6 {
			buf.WriteString("      DHCP = \"ipv6\";\n")
		} else if iface.DHCPv4 || iface.DisableDHCPv4 || iface.DisableDHCPv6 {
			buf.WriteString("      DHCP = \"no\";\n")
		}
		if iface.DisableIPv6RA {
			buf.WriteString("      IPv6AcceptRA = false;\n")
		} else if iface.AcceptRA {
			buf.WriteString("      IPv6AcceptRA = true;\n")
		}
		if len(iface.Addresses) == 0 && !iface.DHCPv4 && !iface.AcceptRA {
			buf.WriteString("      LinkLocalAddressing = \"no\";\n")
		}
		if iface.Bridge != "" {
			buf.WriteString("      Bridge = " + nixString(iface.Bridge) + ";\n")
		}
		if iface.VRF != "" {
			buf.WriteString("      VRF = " + nixString(iface.VRF) + ";\n")
		}
		buf.WriteString("    };\n")
	}
	if len(iface.Addresses) > 0 {
		buf.WriteString("    address = [\n")
		for _, address := range iface.Addresses {
			buf.WriteString("      " + nixString(address) + "\n")
		}
		buf.WriteString("    ];\n")
	}
	if iface.DHCPv4UseRoutes != nil || iface.DHCPv4UseDNS != nil || iface.DHCPv4RouteMetric != 0 {
		buf.WriteString("    dhcpV4Config = {\n")
		if iface.DHCPv4UseRoutes != nil {
			buf.WriteString("      UseRoutes = " + nixBool(*iface.DHCPv4UseRoutes) + ";\n")
		}
		if iface.DHCPv4UseDNS != nil {
			buf.WriteString("      UseDNS = " + nixBool(*iface.DHCPv4UseDNS) + ";\n")
		}
		if iface.DHCPv4RouteMetric != 0 {
			buf.WriteString("      RouteMetric = " + strconv.Itoa(iface.DHCPv4RouteMetric) + ";\n")
		}
		buf.WriteString("    };\n")
	}
	if len(iface.Routes) > 0 {
		sort.Slice(iface.Routes, func(i, j int) bool {
			if iface.Routes[i].Destination == iface.Routes[j].Destination {
				return iface.Routes[i].Gateway < iface.Routes[j].Gateway
			}
			return iface.Routes[i].Destination < iface.Routes[j].Destination
		})
		buf.WriteString("    routes = [\n")
		for _, route := range iface.Routes {
			buf.WriteString("      { routeConfig = {\n")
			buf.WriteString("        Destination = " + nixString(route.Destination) + ";\n")
			buf.WriteString("        Gateway = " + nixString(route.Gateway) + ";\n")
			if route.Metric != 0 {
				buf.WriteString("        Metric = " + strconv.Itoa(route.Metric) + ";\n")
			}
			buf.WriteString("      }; }\n")
		}
		buf.WriteString("    ];\n")
	}
	if iface.AdminUp || len(iface.Addresses) == 0 {
		required := "no"
		if iface.DHCPv4 || len(iface.Addresses) > 0 {
			required = "routable"
		}
		buf.WriteString("    linkConfig.RequiredForOnline = " + nixString(required) + ";\n")
	}
	if iface.MTU != 0 {
		buf.WriteString("    linkConfig.MTUBytes = " + strconv.Itoa(iface.MTU) + ";\n")
	}
	buf.WriteString("  };\n")
}

func writeNixOSUser(buf *bytes.Buffer, user api.NixOSUserSpec) {
	buf.WriteString("  users.users." + user.Name + " = {\n")
	buf.WriteString("    isNormalUser = true;\n")
	if user.Description != "" {
		buf.WriteString("    description = " + nixString(user.Description) + ";\n")
	}
	if len(user.Groups) > 0 {
		buf.WriteString("    extraGroups = " + nixStringList(user.Groups) + ";\n")
	}
	if user.InitialPassword != "" {
		buf.WriteString("    initialPassword = " + nixString(user.InitialPassword) + ";\n")
	}
	if len(user.SSHAuthorizedKeys) > 0 {
		buf.WriteString("    openssh.authorizedKeys.keys = " + nixStringList(user.SSHAuthorizedKeys) + ";\n")
	}
	buf.WriteString("  };\n")
}

func writeNixOSRouterdService(buf *bytes.Buffer, spec api.NixOSRouterdServiceSpec, servicePackages []string, telemetryEnv []string) {
	binaryPath := defaultString(spec.BinaryPath, "/usr/local/sbin/routerd")
	configFile := defaultString(spec.ConfigFile, "/usr/local/etc/routerd/router.yaml")
	socket := defaultString(spec.Socket, "/run/routerd/routerd.sock")
	applyInterval := defaultString(spec.ApplyInterval, "60s")
	args := []string{
		binaryPath,
		"serve",
		"--config", configFile,
		"--socket", socket,
		"--apply-interval", applyInterval,
	}
	args = append(args, spec.ExtraFlags...)

	buf.WriteString("  systemd.services.routerd = {\n")
	buf.WriteString("    description = \"routerd declarative router controller\";\n")
	buf.WriteString("    wantedBy = [ \"multi-user.target\" ];\n")
	buf.WriteString("    after = [ \"network-pre.target\" ];\n")
	buf.WriteString("    wants = [ \"network-pre.target\" ];\n")
	if len(servicePackages) > 0 {
		buf.WriteString("    path = with pkgs; [\n")
		for _, pkg := range servicePackages {
			buf.WriteString("      " + pkg + "\n")
		}
		buf.WriteString("    ];\n")
	}
	if len(telemetryEnv) > 0 {
		buf.WriteString("    environment = " + nixEnvironmentAttrs(telemetryEnv) + ";\n")
	}
	buf.WriteString("    serviceConfig = {\n")
	buf.WriteString("      Type = \"simple\";\n")
	buf.WriteString("      ExecStart = lib.concatStringsSep \" \" [\n")
	for _, arg := range args {
		buf.WriteString("        " + nixString(arg) + "\n")
	}
	buf.WriteString("      ];\n")
	buf.WriteString("      Restart = \"always\";\n")
	buf.WriteString("      RestartSec = \"2s\";\n")
	buf.WriteString("      RuntimeDirectory = \"routerd\";\n")
	buf.WriteString("      RuntimeDirectoryPreserve = \"yes\";\n")
	buf.WriteString("      StateDirectory = \"routerd\";\n")
	buf.WriteString("    };\n")
	buf.WriteString("  };\n")
}

func writeNixOSDHCPv6ClientService(buf *bytes.Buffer, client nixOSDHCPv6Client) {
	unit := "routerd-dhcpv6-client@" + client.Name
	socket := "/run/routerd/dhcpv6-client/" + client.Name + ".sock"
	lease := "/var/lib/routerd/dhcpv6-client/" + client.Name + "/lease.json"
	events := "/var/lib/routerd/dhcpv6-client/" + client.Name + "/events.jsonl"
	args := []string{
		"/usr/local/sbin/routerd-dhcpv6-client",
		"--resource", client.Name,
		"--interface", client.IFName,
		"--socket", socket,
		"--lease-file", lease,
		"--event-file", events,
	}
	if client.ClientDUID != "" {
		args = append(args, "--client-duid", client.ClientDUID)
	}
	buf.WriteString("  systemd.services." + nixString(unit) + " = {\n")
	buf.WriteString("    description = " + nixString("routerd DHCPv6 client "+client.Name) + ";\n")
	buf.WriteString("    after = [ \"network-online.target\" ];\n")
	buf.WriteString("    wants = [ \"network-online.target\" ];\n")
	buf.WriteString("    wantedBy = [ \"multi-user.target\" ];\n")
	buf.WriteString("    path = with pkgs; [\n")
	buf.WriteString("      iproute2\n")
	buf.WriteString("    ];\n")
	buf.WriteString("    serviceConfig = {\n")
	buf.WriteString("      Type = \"simple\";\n")
	buf.WriteString("      ExecStart = lib.concatStringsSep \" \" [\n")
	for _, arg := range args {
		buf.WriteString("        " + nixString(arg) + "\n")
	}
	buf.WriteString("      ];\n")
	buf.WriteString("      Restart = \"always\";\n")
	buf.WriteString("      RestartSec = \"5s\";\n")
	buf.WriteString("      User = \"root\";\n")
	buf.WriteString("      RuntimeDirectory = \"routerd/dhcpv6-client\";\n")
	buf.WriteString("      StateDirectory = \"routerd/dhcpv6-client\";\n")
	buf.WriteString("      NoNewPrivileges = true;\n")
	buf.WriteString("      PrivateTmp = true;\n")
	buf.WriteString("      ProtectHome = true;\n")
	buf.WriteString("      ProtectSystem = \"strict\";\n")
	buf.WriteString("      ReadWritePaths = [\n")
	buf.WriteString("        \"/run/routerd\"\n")
	buf.WriteString("        \"/var/lib/routerd\"\n")
	buf.WriteString("      ];\n")
	buf.WriteString("      RestrictAddressFamilies = [\n")
	buf.WriteString("        \"AF_UNIX\"\n")
	buf.WriteString("        \"AF_INET\"\n")
	buf.WriteString("        \"AF_INET6\"\n")
	buf.WriteString("        \"AF_NETLINK\"\n")
	buf.WriteString("      ];\n")
	buf.WriteString("      CapabilityBoundingSet = [\n")
	buf.WriteString("        \"CAP_NET_RAW\"\n")
	buf.WriteString("        \"CAP_NET_ADMIN\"\n")
	buf.WriteString("        \"CAP_NET_BIND_SERVICE\"\n")
	buf.WriteString("      ];\n")
	buf.WriteString("      AmbientCapabilities = [\n")
	buf.WriteString("        \"CAP_NET_RAW\"\n")
	buf.WriteString("        \"CAP_NET_ADMIN\"\n")
	buf.WriteString("        \"CAP_NET_BIND_SERVICE\"\n")
	buf.WriteString("      ];\n")
	buf.WriteString("    };\n")
	buf.WriteString("  };\n")
}

func nixOSSystemdUnits(router *api.Router) ([]nixOSSystemdUnit, error) {
	var out []nixOSSystemdUnit
	explicit := map[string]bool{}
	host, err := nixOSHost(router)
	if err != nil {
		return nil, err
	}
	routerdSupervisesClients := nixOSRouterdSupervisesClientDaemons(host.RouterdService)
	telemetryEnv, err := TelemetryEnvironment(router)
	if err != nil {
		return nil, err
	}
	dpiSocket := ""
	if RouterWantsDPIClassifier(router) {
		dpiSocket = "/run/routerd/dpi-classifier/default.sock"
	}
	wantsNDPIAgent := RouterWantsNDPIAgent(router)
	if RouterWantsDPIClassifier(router) {
		out = append(out, nixOSSystemdUnit{Name: DPIClassifierUnitName, Spec: DPIClassifierSystemdSpec("/run")})
	}
	if wantsNDPIAgent && !explicit[NDPIAgentUnitName] {
		out = append(out, nixOSSystemdUnit{Name: NDPIAgentUnitName, Spec: NDPIAgentSystemdSpec("/run")})
	}
	aliases := linkAliases(router)
	for _, res := range router.Spec.Resources {
		if res.Kind != "TailscaleNode" {
			continue
		}
		spec, err := res.TailscaleNodeSpec()
		if err != nil {
			return nil, err
		}
		if firstNonEmpty(spec.State, "present") != "absent" {
			spec.BinaryPath = firstNonEmpty(spec.BinaryPath, "tailscale")
		}
		unit := renderTailscaleNixOSUnit(res.Metadata.Name, spec)
		if explicit[unit.Name] {
			continue
		}
		out = append(out, unit)
	}
	for _, res := range router.Spec.Resources {
		if res.Kind != "HealthCheck" {
			continue
		}
		spec, err := res.HealthCheckSpec()
		if err != nil {
			return nil, err
		}
		name := "routerd-healthcheck@" + res.Metadata.Name + ".service"
		if explicit[name] {
			continue
		}
		out = append(out, nixOSSystemdUnit{
			Name: name,
			Spec: HealthCheckDaemonSystemdSpec(HealthCheckDaemonUnitOptions{
				Resource:    res.Metadata.Name,
				Spec:        spec,
				Router:      router,
				Aliases:     aliases,
				Environment: telemetryEnv,
				RuntimeRoot: "/run",
				StateRoot:   "/var/lib",
				LogRoot:     "/var/log",
			}),
		})
	}
	for _, res := range router.Spec.Resources {
		if res.Kind != "DNSResolver" {
			continue
		}
		spec, err := res.DNSResolverSpec()
		if err != nil {
			return nil, err
		}
		name := "routerd-dns-resolver@" + res.Metadata.Name + ".service"
		if explicit[name] {
			continue
		}
		out = append(out, nixOSSystemdUnit{
			Name: name,
			Spec: DNSResolverSystemdSpec(res.Metadata.Name, spec, "/usr/local/sbin/routerd-dns-resolver", ""),
		})
	}
	for _, res := range router.Spec.Resources {
		if res.Kind != "DHCPv4Client" {
			continue
		}
		if routerdSupervisesClients {
			continue
		}
		spec, err := res.DHCPv4ClientSpec()
		if err != nil {
			return nil, err
		}
		ifname := aliases[spec.Interface]
		if ifname == "" {
			ifname = spec.Interface
		}
		if ifname == "" {
			return nil, fmt.Errorf("%s needs spec.interface", res.ID())
		}
		name := "routerd-dhcpv4-client@" + res.Metadata.Name + ".service"
		if explicit[name] {
			continue
		}
		out = append(out, nixOSSystemdUnit{
			Name: name,
			Spec: dhcpv4ClientSystemdSpec(res.Metadata.Name, ifname, spec, telemetryEnv),
		})
	}
	for _, res := range router.Spec.Resources {
		if res.Kind != "PPPoESession" {
			continue
		}
		spec, err := res.PPPoESessionSpec()
		if err != nil {
			return nil, err
		}
		ifname := aliases[spec.Interface]
		if ifname == "" {
			ifname = spec.Interface
		}
		if ifname == "" {
			return nil, fmt.Errorf("%s needs spec.interface", res.ID())
		}
		name := "routerd-pppoe-client@" + res.Metadata.Name + ".service"
		if explicit[name] {
			continue
		}
		unit, err := pppoeSessionSystemdSpec(res.Metadata.Name, ifname, spec, telemetryEnv)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", res.ID(), err)
		}
		out = append(out, nixOSSystemdUnit{Name: name, Spec: unit})
	}
	for _, res := range router.Spec.Resources {
		if res.Kind != "FirewallEventLog" {
			continue
		}
		spec, err := res.FirewallEventLogSpec()
		if err != nil {
			return nil, err
		}
		if !spec.Enabled {
			continue
		}
		name := "routerd-firewall-logger.service"
		if explicit[name] {
			continue
		}
		out = append(out, nixOSSystemdUnit{
			Name: name,
			Spec: FirewallLoggerSystemdSpec(spec, dpiSocket),
		})
	}
	if nixOSNeedsDnsmasq(router) {
		name := "routerd-dnsmasq.service"
		if !explicit[name] {
			out = append(out, nixOSSystemdUnit{
				Name: name,
				Spec: dnsmasqNixOSSystemdSpec(),
				Path: []string{"dnsmasq"},
			})
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out, nil
}

func dnsmasqNixOSSystemdSpec() api.SystemdUnitSpec {
	noNewPrivileges := true
	privateTmp := true
	return api.SystemdUnitSpec{
		Description:              "routerd managed dnsmasq DHCP service",
		ExecStart:                []string{"${pkgs.dnsmasq}/bin/dnsmasq", "--keep-in-foreground", "--user=root", "--group=root", "--conf-file=/usr/local/etc/routerd/dnsmasq.conf", "--pid-file=/run/routerd/dnsmasq.pid"},
		Wants:                    []string{"network-online.target"},
		After:                    []string{"network-online.target", "routerd.service"},
		WantedBy:                 []string{"multi-user.target"},
		Restart:                  "on-failure",
		RestartSec:               "2s",
		RuntimeDirectory:         []string{"routerd"},
		RuntimeDirectoryPreserve: "yes",
		StateDirectory:           []string{"routerd"},
		ReadWritePaths:           []string{"/run/routerd", "/var/lib/routerd", "/usr/local/etc/routerd"},
		AmbientCapabilities:      []string{"CAP_NET_BIND_SERVICE", "CAP_NET_RAW", "CAP_NET_ADMIN", "CAP_SETUID", "CAP_SETGID", "CAP_CHOWN"},
		CapabilityBoundingSet:    []string{"CAP_NET_BIND_SERVICE", "CAP_NET_RAW", "CAP_NET_ADMIN", "CAP_SETUID", "CAP_SETGID", "CAP_CHOWN"},
		RestrictAddressFamilies:  []string{"AF_UNIX", "AF_INET", "AF_INET6", "AF_NETLINK", "AF_PACKET"},
		ProtectSystem:            "strict",
		ProtectHome:              "true",
		NoNewPrivileges:          &noNewPrivileges,
		PrivateTmp:               &privateTmp,
	}
}

func dhcpv4ClientSystemdSpec(name, ifname string, spec api.DHCPv4ClientSpec, telemetryEnv []string) api.SystemdUnitSpec {
	noNewPrivileges := true
	privateTmp := true
	exec := []string{"/usr/local/sbin/routerd-dhcpv4-client", "daemon", "--resource", name, "--interface", ifname}
	if spec.Hostname != "" {
		exec = append(exec, "--hostname", spec.Hostname)
	}
	if spec.RequestedAddress != "" {
		exec = append(exec, "--requested-address", spec.RequestedAddress)
	}
	if spec.ClassID != "" {
		exec = append(exec, "--class-id", spec.ClassID)
	}
	if spec.ClientID != "" {
		exec = append(exec, "--client-id", spec.ClientID)
	}
	return api.SystemdUnitSpec{
		Description:              "routerd DHCPv4 client " + name,
		ExecStart:                exec,
		Wants:                    []string{"network-online.target"},
		After:                    []string{"network-online.target"},
		WantedBy:                 []string{"multi-user.target"},
		Restart:                  "always",
		RestartSec:               "5s",
		RuntimeDirectory:         []string{"routerd/dhcpv4-client"},
		RuntimeDirectoryPreserve: "yes",
		StateDirectory:           []string{"routerd/dhcpv4-client"},
		LogsDirectory:            []string{"routerd"},
		ReadWritePaths:           []string{"/run/routerd", "/var/lib/routerd", "/var/log/routerd"},
		Environment:              telemetryEnv,
		AmbientCapabilities:      []string{"CAP_NET_RAW", "CAP_NET_ADMIN", "CAP_NET_BIND_SERVICE"},
		CapabilityBoundingSet:    []string{"CAP_NET_RAW", "CAP_NET_ADMIN", "CAP_NET_BIND_SERVICE"},
		RestrictAddressFamilies:  []string{"AF_UNIX", "AF_INET", "AF_INET6", "AF_NETLINK", "AF_PACKET"},
		ProtectSystem:            "strict",
		ProtectHome:              "true",
		NoNewPrivileges:          &noNewPrivileges,
		PrivateTmp:               &privateTmp,
	}
}

func pppoeSessionSystemdSpec(name, ifname string, spec api.PPPoESessionSpec, telemetryEnv []string) (api.SystemdUnitSpec, error) {
	noNewPrivileges := true
	privateTmp := true
	exec := []string{"/usr/local/sbin/routerd-pppoe-client", "daemon", "--resource", name, "--interface", ifname, "--username", spec.Username}
	if spec.PasswordFile != "" {
		exec = append(exec, "--password-file", spec.PasswordFile)
	} else if spec.Password != "" {
		exec = append(exec, "--password", spec.Password)
	} else {
		return api.SystemdUnitSpec{}, fmt.Errorf("password or passwordFile is required")
	}
	if spec.AuthMethod != "" {
		exec = append(exec, "--auth-method", spec.AuthMethod)
	}
	if spec.MTU != 0 {
		exec = append(exec, "--mtu", strconv.Itoa(spec.MTU))
	}
	if spec.MRU != 0 {
		exec = append(exec, "--mru", strconv.Itoa(spec.MRU))
	}
	if spec.ServiceName != "" {
		exec = append(exec, "--service-name", spec.ServiceName)
	}
	if spec.ACName != "" {
		exec = append(exec, "--ac-name", spec.ACName)
	}
	if spec.LCPEchoInterval != 0 {
		exec = append(exec, "--lcp-echo-interval", strconv.Itoa(spec.LCPEchoInterval))
	}
	if spec.LCPEchoFailure != 0 {
		exec = append(exec, "--lcp-echo-failure", strconv.Itoa(spec.LCPEchoFailure))
	}
	return api.SystemdUnitSpec{
		Description:              "routerd PPPoE client " + name,
		ExecStart:                exec,
		Wants:                    []string{"network-online.target"},
		After:                    []string{"network-online.target"},
		WantedBy:                 []string{"multi-user.target"},
		Restart:                  "always",
		RestartSec:               "5s",
		RuntimeDirectory:         []string{"routerd/pppoe-client"},
		RuntimeDirectoryPreserve: "yes",
		StateDirectory:           []string{"routerd/pppoe-client"},
		LogsDirectory:            []string{"routerd"},
		ReadWritePaths:           []string{"/run/routerd", "/var/lib/routerd", "/var/log/routerd", "/etc/ppp"},
		Environment:              telemetryEnv,
		AmbientCapabilities:      []string{"CAP_NET_ADMIN", "CAP_NET_RAW", "CAP_SETUID", "CAP_SETGID", "CAP_CHOWN"},
		CapabilityBoundingSet:    []string{"CAP_NET_ADMIN", "CAP_NET_RAW", "CAP_SETUID", "CAP_SETGID", "CAP_CHOWN"},
		RestrictAddressFamilies:  []string{"AF_UNIX", "AF_INET", "AF_INET6", "AF_NETLINK"},
		ProtectSystem:            "strict",
		ProtectHome:              "true",
		NoNewPrivileges:          &noNewPrivileges,
		PrivateTmp:               &privateTmp,
	}, nil
}

func FirewallLoggerSystemdSpec(spec api.FirewallLogSpec, dpiSocket string) api.SystemdUnitSpec {
	path := spec.Path
	if path == "" {
		path = (platform.Defaults{StateDir: "/var/lib/routerd"}).FirewallLogFile()
	}
	group := spec.NFLogGroup
	if group == 0 {
		group = 1
	}
	exec := []string{
		"/usr/local/sbin/routerd-firewall-logger",
		"daemon",
		"--path", path,
		"--nflog-group", strconv.Itoa(group),
	}
	wants := []string{"network-online.target"}
	after := []string{"network-online.target", "routerd.service"}
	if dpiSocket != "" {
		exec = append(exec, "--dpi-socket", dpiSocket)
		wants = append(wants, "routerd-dpi-classifier.service")
		after = append(after, "routerd-dpi-classifier.service")
	}
	noNewPrivileges := true
	privateTmp := true
	return api.SystemdUnitSpec{
		Description:              "routerd firewall log collector",
		ExecStart:                exec,
		Wants:                    wants,
		After:                    after,
		WantedBy:                 []string{"multi-user.target"},
		Restart:                  "always",
		RestartSec:               "5s",
		RuntimeDirectory:         []string{"routerd"},
		RuntimeDirectoryPreserve: "yes",
		StateDirectory:           []string{"routerd"},
		ReadWritePaths:           []string{"/var/lib/routerd"},
		AmbientCapabilities:      []string{"CAP_NET_ADMIN", "CAP_NET_RAW"},
		CapabilityBoundingSet:    []string{"CAP_NET_ADMIN", "CAP_NET_RAW"},
		RestrictAddressFamilies:  []string{"AF_UNIX", "AF_INET", "AF_INET6", "AF_NETLINK"},
		ProtectSystem:            "strict",
		ProtectHome:              "true",
		NoNewPrivileges:          &noNewPrivileges,
		PrivateTmp:               &privateTmp,
	}
}

func renderTailscaleNixOSUnit(name string, spec api.TailscaleNodeSpec) nixOSSystemdUnit {
	return nixOSSystemdUnit{
		Name: TailscaleUnitName(name),
		Spec: TailscaleSystemdSpec(name, spec),
		Path: []string{"tailscale"},
	}
}

func writeNixOSSystemdUnit(buf *bytes.Buffer, unit nixOSSystemdUnit) {
	spec := unit.Spec
	name := nixOSSystemdServiceName(unit.Name)
	buf.WriteString("  systemd.services." + nixString(name) + " = {\n")
	if spec.Description != "" {
		buf.WriteString("    description = " + nixString(spec.Description) + ";\n")
	}
	if len(spec.WantedBy) > 0 {
		buf.WriteString("    wantedBy = " + nixStringList(spec.WantedBy) + ";\n")
	}
	if len(spec.After) > 0 {
		buf.WriteString("    after = " + nixStringList(spec.After) + ";\n")
	}
	if len(spec.Wants) > 0 {
		buf.WriteString("    wants = " + nixStringList(spec.Wants) + ";\n")
	}
	if len(unit.Path) > 0 {
		buf.WriteString("    path = with pkgs; [\n")
		for _, pkg := range unit.Path {
			buf.WriteString("      " + pkg + "\n")
		}
		buf.WriteString("    ];\n")
	}
	buf.WriteString("    serviceConfig = {\n")
	if len(spec.ExecStart) > 0 {
		buf.WriteString("      ExecStart = lib.concatStringsSep \" \" [\n")
		for _, arg := range spec.ExecStart {
			buf.WriteString("        " + nixString(arg) + "\n")
		}
		buf.WriteString("      ];\n")
	}
	writeNixOSSystemdString(buf, "Restart", spec.Restart)
	writeNixOSSystemdString(buf, "RestartSec", spec.RestartSec)
	writeNixOSSystemdString(buf, "Type", spec.Type)
	writeNixOSSystemdString(buf, "User", spec.User)
	writeNixOSSystemdString(buf, "Group", spec.Group)
	writeNixOSSystemdStringList(buf, "SupplementaryGroups", spec.SupplementaryGroups)
	writeNixOSSystemdString(buf, "WorkingDirectory", spec.WorkingDirectory)
	writeNixOSSystemdStringList(buf, "Environment", spec.Environment)
	writeNixOSSystemdStringList(buf, "EnvironmentFile", spec.EnvironmentFiles)
	writeNixOSSystemdStringList(buf, "RuntimeDirectory", spec.RuntimeDirectory)
	writeNixOSSystemdString(buf, "RuntimeDirectoryPreserve", spec.RuntimeDirectoryPreserve)
	writeNixOSSystemdStringList(buf, "StateDirectory", spec.StateDirectory)
	writeNixOSSystemdStringList(buf, "LogsDirectory", spec.LogsDirectory)
	writeNixOSSystemdStringList(buf, "ReadWritePaths", spec.ReadWritePaths)
	writeNixOSSystemdStringList(buf, "AmbientCapabilities", spec.AmbientCapabilities)
	writeNixOSSystemdStringList(buf, "CapabilityBoundingSet", spec.CapabilityBoundingSet)
	writeNixOSSystemdStringList(buf, "RestrictAddressFamilies", spec.RestrictAddressFamilies)
	writeNixOSSystemdString(buf, "ProtectSystem", spec.ProtectSystem)
	writeNixOSSystemdString(buf, "ProtectHome", spec.ProtectHome)
	if spec.NoNewPrivileges != nil {
		buf.WriteString("      NoNewPrivileges = " + nixBool(*spec.NoNewPrivileges) + ";\n")
	}
	if spec.PrivateTmp != nil {
		buf.WriteString("      PrivateTmp = " + nixBool(*spec.PrivateTmp) + ";\n")
	}
	if spec.RemainAfterExit != nil {
		buf.WriteString("      RemainAfterExit = " + nixBool(*spec.RemainAfterExit) + ";\n")
	}
	buf.WriteString("    };\n")
	buf.WriteString("  };\n")
}

func writeNixOSSystemdString(buf *bytes.Buffer, key, value string) {
	if value == "" {
		return
	}
	buf.WriteString("      " + key + " = " + nixString(value) + ";\n")
}

func writeNixOSSystemdStringList(buf *bytes.Buffer, key string, values []string) {
	if len(values) == 0 {
		return
	}
	buf.WriteString("      " + key + " = " + nixStringList(values) + ";\n")
}

func nixEnvironmentAttrs(values []string) string {
	var buf strings.Builder
	buf.WriteString("{")
	for _, value := range values {
		key, val, ok := strings.Cut(value, "=")
		if !ok || strings.TrimSpace(key) == "" {
			continue
		}
		buf.WriteString(" ")
		buf.WriteString(nixString(strings.TrimSpace(key)))
		buf.WriteString(" = ")
		buf.WriteString(nixString(val))
		buf.WriteString(";")
	}
	buf.WriteString(" }")
	return buf.String()
}

func nixOSSystemdServiceName(unitName string) string {
	return strings.TrimSuffix(unitName, ".service")
}

func nixOSResolvedStubDisabled(router *api.Router) bool {
	for _, res := range hostdeps.NetworkAdoptionResources(router) {
		spec, err := res.NetworkAdoptionSpec()
		if err != nil {
			continue
		}
		if defaultString(spec.State, "present") != "absent" && spec.SystemdResolved.DisableDNSStubListener {
			return true
		}
	}
	return false
}

func nixOSNeedsDnsmasq(router *api.Router) bool {
	for _, res := range router.Spec.Resources {
		switch res.Kind {
		case "DHCPv4Server", "DHCPv4Reservation", "DHCPv6Server", "IPv6RouterAdvertisement", "DHCPv4Relay":
			return true
		}
	}
	return false
}

func nixOSNeedsNftables(router *api.Router) bool {
	for _, res := range router.Spec.Resources {
		switch res.Kind {
		case "NAT44Rule", "EgressRoutePolicy", "DSLiteTunnel", "PPPoESession", "WireGuardInterface", "FirewallZone", "FirewallPolicy", "FirewallRule", "FirewallEventLog", "ClientPolicy":
			return true
		}
	}
	return false
}

func nixOSTailscaleEnabled(router *api.Router) bool {
	for _, res := range router.Spec.Resources {
		if res.Kind != "TailscaleNode" {
			continue
		}
		spec, err := res.TailscaleNodeSpec()
		if err == nil && firstNonEmpty(spec.State, "present") != "absent" {
			return true
		}
	}
	return false
}

func nixOSPackages(router *api.Router, host api.NixOSHostSpec) ([]string, []string, error) {
	service := map[string]bool{
		"conntrack-tools": true,
		"dnsmasq":         true,
		"dnsutils":        true,
		"iproute2":        true,
		"iputils":         true,
		"kmod":            true,
		"nettools":        true,
		"nftables":        true,
		"ppp":             true,
		"procps":          true,
		"strongswan":      true,
		"systemd":         true,
		"tcpdump":         true,
		"traceroute":      true,
		"wireguard-tools": true,
	}
	debug := map[string]bool{
		"jq": true,
	}
	hasDeclarativePackages := false
	for _, res := range router.Spec.Resources {
		if res.Kind == "Package" {
			hasDeclarativePackages = true
			spec, err := res.PackageSpec()
			if err != nil {
				return nil, nil, err
			}
			for _, set := range spec.Packages {
				if set.OS != "nixos" {
					continue
				}
				for _, pkg := range set.Names {
					if err := validateNixPackageIdent(pkg); err != nil {
						return nil, nil, err
					}
					debug[pkg] = true
				}
			}
		}
	}
	for _, res := range hostdeps.PackageResources(router) {
		spec, err := res.PackageSpec()
		if err != nil {
			return nil, nil, err
		}
		for _, set := range spec.Packages {
			if set.OS != "nixos" {
				continue
			}
			for _, pkg := range set.Names {
				if err := validateNixPackageIdent(pkg); err != nil {
					return nil, nil, err
				}
				service[pkg] = true
			}
		}
	}
	for _, res := range router.Spec.Resources {
		switch res.Kind {
		case "Bridge":
			spec, err := res.BridgeSpec()
			if err != nil {
				return nil, nil, err
			}
			if api.BoolDefault(spec.RSTP, true) {
				service["mstpd"] = true
				debug["mstpd"] = true
			}
		case "VXLANSegment":
			service["nftables"] = true
			debug["nftables"] = true
		case "DHCPv4Server", "DHCPv6Server":
			service["dnsmasq"] = true
			debug["dnsmasq"] = true
		case "EgressRoutePolicy", "DSLiteTunnel", "WireGuardInterface", "FirewallZone", "FirewallPolicy", "FirewallRule", "ClientPolicy":
			service["nftables"] = true
			debug["nftables"] = true
		case "PPPoESession":
			service["nftables"] = true
			debug["nftables"] = true
			spec, err := res.PPPoESessionSpec()
			if err != nil {
				return nil, nil, err
			}
			if api.BoolDefault(spec.Enabled, true) {
				service["ppp"] = true
				debug["ppp"] = true
			}
		case "TailscaleNode":
			spec, err := res.TailscaleNodeSpec()
			if err != nil {
				return nil, nil, err
			}
			if firstNonEmpty(spec.State, "present") != "absent" {
				service["tailscale"] = true
				debug["tailscale"] = true
			}
		}
	}
	for _, pkg := range host.AdditionalServicePath {
		if err := validateNixPackageIdent(pkg); err != nil {
			return nil, nil, err
		}
		service[pkg] = true
	}
	for _, pkg := range host.AdditionalPackages {
		if err := validateNixPackageIdent(pkg); err != nil {
			return nil, nil, err
		}
		debug[pkg] = true
	}
	if host.DebugSystemPackages {
		for pkg := range service {
			if pkg != "systemd" {
				debug[pkg] = true
			}
		}
		debug["conntrack-tools"] = true
	}
	serviceList := sortedMapKeys(service)
	var debugList []string
	if host.DebugSystemPackages || len(host.AdditionalPackages) > 0 || hasDeclarativePackages {
		debugList = sortedMapKeys(debug)
	}
	return debugList, serviceList, nil
}

func splitHostname(value string) (string, string) {
	host, domain, ok := strings.Cut(value, ".")
	if !ok {
		return value, ""
	}
	return host, domain
}

func sortedMapKeys(values map[string]bool) []string {
	out := make([]string, 0, len(values))
	for value := range values {
		out = append(out, value)
	}
	sort.Strings(out)
	return out
}

func sortedMapKeysString(values map[string]string) []string {
	out := make([]string, 0, len(values))
	for value := range values {
		out = append(out, value)
	}
	sort.Strings(out)
	return out
}

func nixBool(value bool) string {
	if value {
		return "true"
	}
	return "false"
}

func nixString(value string) string {
	return strconv.Quote(value)
}

func shellSingleQuote(value string) string {
	if value == "" {
		return "''"
	}
	return "'" + strings.ReplaceAll(value, "'", "'\"'\"'") + "'"
}

func nixSysctlValue(value string) string {
	if _, err := strconv.Atoi(value); err == nil {
		return value
	}
	switch value {
	case "true", "false":
		return value
	default:
		return nixString(value)
	}
}

func nixStringList(values []string) string {
	var b strings.Builder
	b.WriteString("[")
	for _, value := range values {
		b.WriteString(" ")
		b.WriteString(nixString(value))
	}
	b.WriteString(" ]")
	return b.String()
}

func nixIntListSpaced(values []int) string {
	var b strings.Builder
	for i, value := range values {
		if i > 0 {
			b.WriteString(" ")
		}
		b.WriteString(strconv.Itoa(value))
	}
	return b.String()
}

func nixOSFirewallAllowedUDPPorts(vxlans []nixOSVXLAN) []int {
	seen := map[int]bool{}
	var ports []int
	for _, v := range vxlans {
		if v.UDPPort == 0 || seen[v.UDPPort] {
			continue
		}
		seen[v.UDPPort] = true
		ports = append(ports, v.UDPPort)
	}
	sort.Ints(ports)
	return ports
}

func nixOSFirewallTrustedInterfaces(vxlans []nixOSVXLAN) []string {
	seen := map[string]bool{}
	var names []string
	for _, v := range vxlans {
		if v.Bridge == "" || seen[v.Bridge] {
			continue
		}
		seen[v.Bridge] = true
		names = append(names, v.Bridge)
	}
	sort.Strings(names)
	return names
}

func validateNixPackageIdent(value string) error {
	if value == "" || strings.ContainsAny(value, " \t\n\r;{}[]()\"'") {
		return fmt.Errorf("invalid Nix package identifier %q", value)
	}
	return nil
}
