package render

import (
	"bytes"
	"fmt"
	"sort"
	"strconv"
	"strings"

	"routerd/pkg/api"
)

type nixOSInterface struct {
	Name             string
	IfName           string
	AdminUp          bool
	Bridge           string
	DHCP4            bool
	DHCP4UseRoutes   *bool
	DHCP4UseDNS      *bool
	DHCP4RouteMetric int
	DHCP6            bool
	AcceptRA         bool
	Addresses        []string
	Routes           []nixOSRoute
}

type nixOSRoute struct {
	Destination string
	Gateway     string
	Metric      int
}

type nixOSBridge struct {
	Name              string
	IfName            string
	STP               bool
	RSTP              bool
	ForwardDelay      int
	HelloTime         int
	MACAddress        string
	MTU               int
	MulticastSnooping bool
}

type nixOSVXLAN struct {
	Name           string
	IfName         string
	VNI            int
	LocalAddress   string
	Remotes        []string
	MulticastGroup string
	UDPPort        int
	MTU            int
	Bridge         string
}

func NixOSModule(router *api.Router) ([]byte, error) {
	host, err := nixOSHost(router)
	if err != nil {
		return nil, err
	}
	interfaces, err := nixOSInterfaces(router)
	if err != nil {
		return nil, err
	}
	bridges, err := nixOSBridges(router)
	if err != nil {
		return nil, err
	}
	vxlans, err := nixOSVXLANS(router)
	if err != nil {
		return nil, err
	}
	ntpServers, err := nixOSNTPServers(router)
	if err != nil {
		return nil, err
	}
	sysctls, err := nixOSSysctls(router)
	if err != nil {
		return nil, err
	}
	packages, servicePackages, err := nixOSPackages(router, host)
	if err != nil {
		return nil, err
	}

	var buf bytes.Buffer
	buf.WriteString("# Generated by routerd. Do not edit by hand.\n")
	buf.WriteString("{ config, lib, pkgs, ... }:\n\n")
	buf.WriteString("{\n")
	if host.Hostname != "" {
		buf.WriteString("  networking.hostName = " + nixString(host.Hostname) + ";\n")
	}
	if host.Domain != "" {
		buf.WriteString("  networking.domain = " + nixString(host.Domain) + ";\n")
	}
	if host.Boot.Loader == "grub" || host.Boot.GrubDevice != "" {
		buf.WriteString("  boot.loader.grub.enable = true;\n")
		if host.Boot.GrubDevice != "" {
			buf.WriteString("  boot.loader.grub.device = " + nixString(host.Boot.GrubDevice) + ";\n")
		}
	}
	if len(interfaces) > 0 {
		buf.WriteString("  networking.useDHCP = false;\n")
		buf.WriteString("  networking.useNetworkd = true;\n")
		buf.WriteString("  networking.firewall.checkReversePath = false;\n")
		if udpPorts := nixOSFirewallAllowedUDPPorts(vxlans); len(udpPorts) > 0 {
			buf.WriteString("  networking.firewall.allowedUDPPorts = [ " + nixIntListSpaced(udpPorts) + " ];\n")
		}
		if trusted := nixOSFirewallTrustedInterfaces(vxlans); len(trusted) > 0 {
			buf.WriteString("  networking.firewall.trustedInterfaces = " + nixStringList(trusted) + ";\n")
		}
		buf.WriteString("  systemd.network.enable = true;\n")
		for _, bridge := range bridges {
			writeNixOSBridge(&buf, bridge)
		}
		for _, vxlan := range vxlans {
			writeNixOSVXLAN(&buf, vxlan)
		}
		for _, iface := range interfaces {
			writeNixOSNetwork(&buf, iface)
		}
	}
	if api.BoolDefault(host.SSH.Enabled, len(host.Users) > 0) {
		buf.WriteString("  services.openssh = {\n")
		buf.WriteString("    enable = true;\n")
		if host.SSH.PasswordAuthentication != nil || host.SSH.PermitRootLogin != "" {
			buf.WriteString("    settings = {\n")
			if host.SSH.PasswordAuthentication != nil {
				buf.WriteString("      PasswordAuthentication = " + nixBool(*host.SSH.PasswordAuthentication) + ";\n")
			}
			if host.SSH.PermitRootLogin != "" {
				buf.WriteString("      PermitRootLogin = " + nixString(host.SSH.PermitRootLogin) + ";\n")
			}
			buf.WriteString("    };\n")
		}
		buf.WriteString("  };\n")
	}
	for _, user := range host.Users {
		writeNixOSUser(&buf, user)
	}
	if host.Sudo.WheelNeedsPassword != nil {
		buf.WriteString("  security.sudo.wheelNeedsPassword = " + nixBool(*host.Sudo.WheelNeedsPassword) + ";\n")
	}
	if len(ntpServers) > 0 {
		buf.WriteString("  services.timesyncd.enable = true;\n")
		buf.WriteString("  services.timesyncd.servers = " + nixStringList(ntpServers) + ";\n")
	}
	if len(sysctls) > 0 {
		buf.WriteString("  boot.kernel.sysctl = {\n")
		for _, key := range sortedMapKeysString(sysctls) {
			buf.WriteString("    " + nixString(key) + " = " + nixSysctlValue(sysctls[key]) + ";\n")
		}
		buf.WriteString("  };\n")
	}
	if len(packages) > 0 {
		buf.WriteString("  environment.systemPackages = with pkgs; [\n")
		for _, pkg := range packages {
			buf.WriteString("    " + pkg + "\n")
		}
		buf.WriteString("  ];\n")
	}
	if api.BoolDefault(host.RouterdService.Enabled, false) {
		writeNixOSRouterdService(&buf, host.RouterdService, servicePackages)
	}
	if host.StateVersion != "" {
		buf.WriteString("  system.stateVersion = " + nixString(host.StateVersion) + ";\n")
	}
	buf.WriteString("}\n")
	return buf.Bytes(), nil
}

func nixOSHost(router *api.Router) (api.NixOSHostSpec, error) {
	var out api.NixOSHostSpec
	seen := false
	for _, res := range router.Spec.Resources {
		switch res.Kind {
		case "NixOSHost":
			if seen {
				return out, fmt.Errorf("multiple NixOSHost resources are not supported")
			}
			spec, err := res.NixOSHostSpec()
			if err != nil {
				return out, err
			}
			out = spec
			seen = true
		case "Hostname":
			spec, err := res.HostnameSpec()
			if err != nil {
				return out, err
			}
			if out.Hostname == "" && spec.Managed {
				host, domain := splitHostname(spec.Hostname)
				out.Hostname = host
				out.Domain = domain
			}
		}
	}
	return out, nil
}

func nixOSNTPServers(router *api.Router) ([]string, error) {
	var servers []string
	for _, res := range router.Spec.Resources {
		if res.Kind != "NTPClient" {
			continue
		}
		spec, err := res.NTPClientSpec()
		if err != nil {
			return nil, err
		}
		if !spec.Managed {
			continue
		}
		if provider := defaultString(spec.Provider, "systemd-timesyncd"); provider != "systemd-timesyncd" {
			return nil, fmt.Errorf("%s has unsupported provider %q", res.ID(), provider)
		}
		if source := defaultString(spec.Source, "static"); source != "static" {
			return nil, fmt.Errorf("%s has unsupported source %q", res.ID(), source)
		}
		for _, server := range spec.Servers {
			server = strings.TrimSpace(server)
			if server != "" {
				servers = append(servers, server)
			}
		}
	}
	sort.Strings(servers)
	return servers, nil
}

func nixOSSysctls(router *api.Router) (map[string]string, error) {
	values := map[string]string{}
	for _, res := range router.Spec.Resources {
		if res.Kind != "Sysctl" {
			continue
		}
		spec, err := res.SysctlSpec()
		if err != nil {
			return nil, err
		}
		if !spec.Persistent {
			continue
		}
		values[spec.Key] = spec.Value
	}
	return values, nil
}

func nixOSInterfaces(router *api.Router) ([]nixOSInterface, error) {
	interfaces := map[string]*nixOSInterface{}
	var names []string
	for _, res := range router.Spec.Resources {
		if res.Kind != "Interface" {
			continue
		}
		spec, err := res.InterfaceSpec()
		if err != nil {
			return nil, err
		}
		if spec.IfName == "" {
			return nil, fmt.Errorf("%s has empty ifname", res.ID())
		}
		interfaces[res.Metadata.Name] = &nixOSInterface{
			Name:    res.Metadata.Name,
			IfName:  spec.IfName,
			AdminUp: spec.AdminUp,
		}
		names = append(names, res.Metadata.Name)
	}
	for _, res := range router.Spec.Resources {
		if res.Kind != "Bridge" {
			continue
		}
		spec, err := res.BridgeSpec()
		if err != nil {
			return nil, err
		}
		interfaces[res.Metadata.Name] = &nixOSInterface{
			Name:    res.Metadata.Name,
			IfName:  defaultString(spec.IfName, res.Metadata.Name),
			AdminUp: true,
		}
		names = append(names, res.Metadata.Name)
	}
	for _, res := range router.Spec.Resources {
		if res.Kind != "VXLANSegment" {
			continue
		}
		spec, err := res.VXLANSegmentSpec()
		if err != nil {
			return nil, err
		}
		interfaces[res.Metadata.Name] = &nixOSInterface{
			Name:    res.Metadata.Name,
			IfName:  defaultString(spec.IfName, res.Metadata.Name),
			AdminUp: true,
		}
		names = append(names, res.Metadata.Name)
	}
	aliases := linkAliases(router)
	bridges, err := bridgeConfigs(router, aliases)
	if err != nil {
		return nil, err
	}
	for _, bridge := range bridges {
		for _, member := range bridge.Members {
			for _, iface := range interfaces {
				if iface.IfName == member {
					iface.Bridge = bridge.IfName
				}
			}
		}
	}
	for _, res := range router.Spec.Resources {
		switch res.Kind {
		case "IPv4StaticAddress":
			spec, err := res.IPv4StaticAddressSpec()
			if err != nil {
				return nil, err
			}
			if iface := interfaces[spec.Interface]; iface != nil {
				iface.Addresses = append(iface.Addresses, spec.Address)
			}
		case "IPv4DHCPAddress":
			spec, err := res.IPv4DHCPAddressSpec()
			if err != nil {
				return nil, err
			}
			if iface := interfaces[spec.Interface]; iface != nil {
				iface.DHCP4 = true
				iface.DHCP4UseRoutes = spec.UseRoutes
				iface.DHCP4UseDNS = spec.UseDNS
				iface.DHCP4RouteMetric = spec.RouteMetric
			}
		case "IPv4StaticRoute":
			spec, err := res.IPv4StaticRouteSpec()
			if err != nil {
				return nil, err
			}
			if iface := interfaces[spec.Interface]; iface != nil {
				iface.Routes = append(iface.Routes, nixOSRoute{Destination: spec.Destination, Gateway: spec.Via, Metric: spec.Metric})
			}
		case "IPv6StaticRoute":
			spec, err := res.IPv6StaticRouteSpec()
			if err != nil {
				return nil, err
			}
			if iface := interfaces[spec.Interface]; iface != nil {
				iface.Routes = append(iface.Routes, nixOSRoute{Destination: spec.Destination, Gateway: spec.Via, Metric: spec.Metric})
			}
		case "IPv6DHCPAddress":
			spec, err := res.IPv6DHCPAddressSpec()
			if err != nil {
				return nil, err
			}
			if iface := interfaces[spec.Interface]; iface != nil {
				iface.DHCP6 = true
				iface.AcceptRA = true
			}
		case "IPv6RAAddress":
			spec, err := res.IPv6RAAddressSpec()
			if err != nil {
				return nil, err
			}
			if iface := interfaces[spec.Interface]; iface != nil && api.BoolDefault(spec.Managed, true) {
				iface.AcceptRA = true
			}
		case "IPv6PrefixDelegation":
			spec, err := res.IPv6PrefixDelegationSpec()
			if err != nil {
				return nil, err
			}
			if iface := interfaces[spec.Interface]; iface != nil {
				if effectiveNixOSIPv6PDClient(spec) == "networkd" {
					iface.DHCP6 = true
				}
				iface.AcceptRA = true
			}
		}
	}
	sort.Strings(names)
	out := make([]nixOSInterface, 0, len(names))
	for _, name := range names {
		out = append(out, *interfaces[name])
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].IfName == out[j].IfName {
			return out[i].Name < out[j].Name
		}
		return out[i].IfName < out[j].IfName
	})
	return out, nil
}

func nixOSBridges(router *api.Router) ([]nixOSBridge, error) {
	bridges, err := bridgeConfigs(router, linkAliases(router))
	if err != nil {
		return nil, err
	}
	out := make([]nixOSBridge, 0, len(bridges))
	for _, bridge := range bridges {
		out = append(out, nixOSBridge{
			Name:              bridge.Name,
			IfName:            bridge.IfName,
			STP:               bridge.STP,
			RSTP:              bridge.RSTP,
			ForwardDelay:      bridge.ForwardDelay,
			HelloTime:         bridge.HelloTime,
			MACAddress:        bridge.MACAddress,
			MTU:               bridge.MTU,
			MulticastSnooping: bridge.MulticastSnooping,
		})
	}
	return out, nil
}

func nixOSVXLANS(router *api.Router) ([]nixOSVXLAN, error) {
	vxlans, err := vxlanConfigs(router, linkAliases(router))
	if err != nil {
		return nil, err
	}
	out := make([]nixOSVXLAN, 0, len(vxlans))
	for _, vxlan := range vxlans {
		out = append(out, nixOSVXLAN{
			Name:           vxlan.Name,
			IfName:         vxlan.IfName,
			VNI:            vxlan.VNI,
			LocalAddress:   vxlan.LocalAddress,
			Remotes:        vxlan.Remotes,
			MulticastGroup: vxlan.MulticastGroup,
			UDPPort:        vxlan.UDPPort,
			MTU:            vxlan.MTU,
			Bridge:         vxlan.BridgeIfName,
		})
	}
	return out, nil
}

func writeNixOSBridge(buf *bytes.Buffer, bridge nixOSBridge) {
	buf.WriteString("  systemd.network.netdevs." + nixString("30-routerd-"+bridge.IfName) + " = {\n")
	buf.WriteString("    netdevConfig = {\n")
	buf.WriteString("      Name = " + nixString(bridge.IfName) + ";\n")
	buf.WriteString("      Kind = \"bridge\";\n")
	if bridge.MACAddress != "" {
		buf.WriteString("      MACAddress = " + nixString(bridge.MACAddress) + ";\n")
	}
	if bridge.MTU != 0 {
		buf.WriteString("      MTUBytes = " + strconv.Itoa(bridge.MTU) + ";\n")
	}
	buf.WriteString("    };\n")
	buf.WriteString("    bridgeConfig = {\n")
	buf.WriteString("      STP = " + nixBool(bridge.STP) + ";\n")
	buf.WriteString("      MulticastSnooping = " + nixBool(bridge.MulticastSnooping) + ";\n")
	buf.WriteString("      ForwardDelaySec = " + strconv.Itoa(bridge.ForwardDelay) + ";\n")
	buf.WriteString("      HelloTimeSec = " + strconv.Itoa(bridge.HelloTime) + ";\n")
	buf.WriteString("    };\n")
	buf.WriteString("  };\n")
}

func writeNixOSVXLAN(buf *bytes.Buffer, vxlan nixOSVXLAN) {
	buf.WriteString("  systemd.network.netdevs." + nixString("31-routerd-"+vxlan.IfName) + " = {\n")
	buf.WriteString("    netdevConfig = {\n")
	buf.WriteString("      Name = " + nixString(vxlan.IfName) + ";\n")
	buf.WriteString("      Kind = \"vxlan\";\n")
	if vxlan.MTU != 0 {
		buf.WriteString("      MTUBytes = " + strconv.Itoa(vxlan.MTU) + ";\n")
	}
	buf.WriteString("    };\n")
	buf.WriteString("    vxlanConfig = {\n")
	buf.WriteString("      VNI = " + strconv.Itoa(vxlan.VNI) + ";\n")
	buf.WriteString("      Local = " + nixString(vxlan.LocalAddress) + ";\n")
	if vxlan.MulticastGroup != "" {
		buf.WriteString("      Group = " + nixString(vxlan.MulticastGroup) + ";\n")
	} else if len(vxlan.Remotes) == 1 {
		buf.WriteString("      Remote = " + nixString(vxlan.Remotes[0]) + ";\n")
	}
	buf.WriteString("      DestinationPort = " + strconv.Itoa(vxlan.UDPPort) + ";\n")
	buf.WriteString("    };\n")
	buf.WriteString("  };\n")
	if vxlan.Bridge != "" || len(vxlan.Remotes) > 1 {
		buf.WriteString("  systemd.network.networks." + nixString("31-routerd-"+vxlan.IfName) + " = {\n")
		buf.WriteString("    matchConfig.Name = " + nixString(vxlan.IfName) + ";\n")
		buf.WriteString("    networkConfig = {\n")
		if vxlan.Bridge != "" {
			buf.WriteString("      Bridge = " + nixString(vxlan.Bridge) + ";\n")
		}
		buf.WriteString("    };\n")
		if len(vxlan.Remotes) > 1 {
			buf.WriteString("    bridgeFDBs = [\n")
			for _, remote := range vxlan.Remotes {
				buf.WriteString("      { MACAddress = \"00:00:00:00:00:00\"; Destination = " + nixString(remote) + "; }\n")
			}
			buf.WriteString("    ];\n")
		}
		buf.WriteString("  };\n")
	}
}

func writeNixOSNetwork(buf *bytes.Buffer, iface nixOSInterface) {
	buf.WriteString("  systemd.network.networks." + nixString("10-netplan-"+iface.IfName) + " = {\n")
	buf.WriteString("    matchConfig.Name = " + nixString(iface.IfName) + ";\n")
	if iface.DHCP4 || iface.DHCP6 || iface.AcceptRA || iface.Bridge != "" || len(iface.Addresses) == 0 {
		buf.WriteString("    networkConfig = {\n")
		if iface.DHCP4 && iface.DHCP6 {
			buf.WriteString("      DHCP = \"yes\";\n")
		} else if iface.DHCP4 {
			buf.WriteString("      DHCP = \"ipv4\";\n")
		} else if iface.DHCP6 {
			buf.WriteString("      DHCP = \"ipv6\";\n")
		}
		if iface.AcceptRA {
			buf.WriteString("      IPv6AcceptRA = true;\n")
		}
		if len(iface.Addresses) == 0 && !iface.DHCP4 && !iface.DHCP6 && !iface.AcceptRA {
			buf.WriteString("      LinkLocalAddressing = \"no\";\n")
		}
		if iface.Bridge != "" {
			buf.WriteString("      Bridge = " + nixString(iface.Bridge) + ";\n")
		}
		buf.WriteString("    };\n")
	}
	if len(iface.Addresses) > 0 {
		buf.WriteString("    address = [\n")
		for _, address := range iface.Addresses {
			buf.WriteString("      " + nixString(address) + "\n")
		}
		buf.WriteString("    ];\n")
	}
	if iface.DHCP4UseRoutes != nil || iface.DHCP4UseDNS != nil || iface.DHCP4RouteMetric != 0 {
		buf.WriteString("    dhcpV4Config = {\n")
		if iface.DHCP4UseRoutes != nil {
			buf.WriteString("      UseRoutes = " + nixBool(*iface.DHCP4UseRoutes) + ";\n")
		}
		if iface.DHCP4UseDNS != nil {
			buf.WriteString("      UseDNS = " + nixBool(*iface.DHCP4UseDNS) + ";\n")
		}
		if iface.DHCP4RouteMetric != 0 {
			buf.WriteString("      RouteMetric = " + strconv.Itoa(iface.DHCP4RouteMetric) + ";\n")
		}
		buf.WriteString("    };\n")
	}
	if len(iface.Routes) > 0 {
		sort.Slice(iface.Routes, func(i, j int) bool {
			if iface.Routes[i].Destination == iface.Routes[j].Destination {
				return iface.Routes[i].Gateway < iface.Routes[j].Gateway
			}
			return iface.Routes[i].Destination < iface.Routes[j].Destination
		})
		buf.WriteString("    routes = [\n")
		for _, route := range iface.Routes {
			buf.WriteString("      { routeConfig = {\n")
			buf.WriteString("        Destination = " + nixString(route.Destination) + ";\n")
			buf.WriteString("        Gateway = " + nixString(route.Gateway) + ";\n")
			if route.Metric != 0 {
				buf.WriteString("        Metric = " + strconv.Itoa(route.Metric) + ";\n")
			}
			buf.WriteString("      }; }\n")
		}
		buf.WriteString("    ];\n")
	}
	if iface.AdminUp || len(iface.Addresses) == 0 {
		required := "no"
		if iface.DHCP4 || iface.DHCP6 || len(iface.Addresses) > 0 {
			required = "routable"
		}
		buf.WriteString("    linkConfig.RequiredForOnline = " + nixString(required) + ";\n")
	}
	buf.WriteString("  };\n")
}

func writeNixOSUser(buf *bytes.Buffer, user api.NixOSUserSpec) {
	buf.WriteString("  users.users." + user.Name + " = {\n")
	buf.WriteString("    isNormalUser = true;\n")
	if user.Description != "" {
		buf.WriteString("    description = " + nixString(user.Description) + ";\n")
	}
	if len(user.Groups) > 0 {
		buf.WriteString("    extraGroups = " + nixStringList(user.Groups) + ";\n")
	}
	if user.InitialPassword != "" {
		buf.WriteString("    initialPassword = " + nixString(user.InitialPassword) + ";\n")
	}
	if len(user.SSHAuthorizedKeys) > 0 {
		buf.WriteString("    openssh.authorizedKeys.keys = " + nixStringList(user.SSHAuthorizedKeys) + ";\n")
	}
	buf.WriteString("  };\n")
}

func writeNixOSRouterdService(buf *bytes.Buffer, spec api.NixOSRouterdServiceSpec, servicePackages []string) {
	binaryPath := defaultString(spec.BinaryPath, "/usr/local/sbin/routerd")
	configFile := defaultString(spec.ConfigFile, "/usr/local/etc/routerd/router.yaml")
	socket := defaultString(spec.Socket, "/run/routerd/routerd.sock")
	applyInterval := defaultString(spec.ApplyInterval, "60s")
	args := []string{
		binaryPath,
		"serve",
		"--config", configFile,
		"--socket", socket,
		"--apply-interval", applyInterval,
	}
	args = append(args, spec.ExtraFlags...)

	buf.WriteString("  systemd.services.routerd = {\n")
	buf.WriteString("    description = \"routerd declarative router controller\";\n")
	buf.WriteString("    wantedBy = [ \"multi-user.target\" ];\n")
	buf.WriteString("    after = [ \"network-pre.target\" ];\n")
	buf.WriteString("    wants = [ \"network-pre.target\" ];\n")
	if len(servicePackages) > 0 {
		buf.WriteString("    path = with pkgs; [\n")
		for _, pkg := range servicePackages {
			buf.WriteString("      " + pkg + "\n")
		}
		buf.WriteString("    ];\n")
	}
	buf.WriteString("    serviceConfig = {\n")
	buf.WriteString("      Type = \"simple\";\n")
	buf.WriteString("      ExecStart = lib.concatStringsSep \" \" [\n")
	for _, arg := range args {
		buf.WriteString("        " + nixString(arg) + "\n")
	}
	buf.WriteString("      ];\n")
	buf.WriteString("      Restart = \"always\";\n")
	buf.WriteString("      RestartSec = \"2s\";\n")
	buf.WriteString("      RuntimeDirectory = \"routerd\";\n")
	buf.WriteString("      StateDirectory = \"routerd\";\n")
	buf.WriteString("    };\n")
	buf.WriteString("  };\n")
}

func nixOSPackages(router *api.Router, host api.NixOSHostSpec) ([]string, []string, error) {
	service := map[string]bool{
		"conntrack-tools": true,
		"dnsutils":        true,
		"iproute2":        true,
		"iputils":         true,
		"procps":          true,
		"systemd":         true,
		"tcpdump":         true,
		"traceroute":      true,
	}
	debug := map[string]bool{
		"jq": true,
	}
	for _, res := range router.Spec.Resources {
		switch res.Kind {
		case "Bridge":
			spec, err := res.BridgeSpec()
			if err != nil {
				return nil, nil, err
			}
			if api.BoolDefault(spec.RSTP, true) {
				service["mstpd"] = true
				debug["mstpd"] = true
			}
		case "VXLANSegment":
			service["nftables"] = true
			debug["nftables"] = true
		case "IPv4DHCPServer", "IPv4DHCPScope", "IPv6DHCPServer", "IPv6DHCPScope", "DNSConditionalForwarder":
			service["dnsmasq"] = true
			debug["dnsmasq"] = true
		case "IPv4SourceNAT", "IPv4PolicyRoute", "IPv4PolicyRouteSet", "IPv4DefaultRoutePolicy", "FirewallPolicy", "ExposeService", "PathMTUPolicy":
			service["nftables"] = true
			debug["nftables"] = true
		case "PPPoEInterface":
			service["ppp"] = true
			debug["ppp"] = true
		case "IPv6PrefixDelegation":
			spec, err := res.IPv6PrefixDelegationSpec()
			if err != nil {
				return nil, nil, err
			}
			switch effectiveNixOSIPv6PDClient(spec) {
			case "dhcp6c":
				return nil, nil, fmt.Errorf("%s uses client=dhcp6c, but the built-in NixOS renderer does not provide a WIDE dhcp6c package path; use client=dhcpcd or provide a custom NixOS module outside routerd", res.ID())
			case "dhcpcd":
				service["dhcpcd"] = true
				debug["dhcpcd"] = true
			}
		}
	}
	for _, pkg := range host.AdditionalServicePath {
		if err := validateNixPackageIdent(pkg); err != nil {
			return nil, nil, err
		}
		service[pkg] = true
	}
	for _, pkg := range host.AdditionalPackages {
		if err := validateNixPackageIdent(pkg); err != nil {
			return nil, nil, err
		}
		debug[pkg] = true
	}
	if host.DebugSystemPackages {
		for pkg := range service {
			if pkg != "systemd" {
				debug[pkg] = true
			}
		}
		debug["conntrack-tools"] = true
	}
	serviceList := sortedMapKeys(service)
	var debugList []string
	if host.DebugSystemPackages || len(host.AdditionalPackages) > 0 {
		debugList = sortedMapKeys(debug)
	}
	return debugList, serviceList, nil
}

func splitHostname(value string) (string, string) {
	host, domain, ok := strings.Cut(value, ".")
	if !ok {
		return value, ""
	}
	return host, domain
}

func sortedMapKeys(values map[string]bool) []string {
	out := make([]string, 0, len(values))
	for value := range values {
		out = append(out, value)
	}
	sort.Strings(out)
	return out
}

func sortedMapKeysString(values map[string]string) []string {
	out := make([]string, 0, len(values))
	for value := range values {
		out = append(out, value)
	}
	sort.Strings(out)
	return out
}

func nixBool(value bool) string {
	if value {
		return "true"
	}
	return "false"
}

func effectiveNixOSIPv6PDClient(spec api.IPv6PrefixDelegationSpec) string {
	return api.EffectiveIPv6PDClient("linux", true, spec.Profile, spec.Client)
}

func nixString(value string) string {
	return strconv.Quote(value)
}

func nixSysctlValue(value string) string {
	if _, err := strconv.Atoi(value); err == nil {
		return value
	}
	switch value {
	case "true", "false":
		return value
	default:
		return nixString(value)
	}
}

func nixStringList(values []string) string {
	var b strings.Builder
	b.WriteString("[")
	for _, value := range values {
		b.WriteString(" ")
		b.WriteString(nixString(value))
	}
	b.WriteString(" ]")
	return b.String()
}

func nixIntListSpaced(values []int) string {
	var b strings.Builder
	for i, value := range values {
		if i > 0 {
			b.WriteString(" ")
		}
		b.WriteString(strconv.Itoa(value))
	}
	return b.String()
}

func nixOSFirewallAllowedUDPPorts(vxlans []nixOSVXLAN) []int {
	seen := map[int]bool{}
	var ports []int
	for _, v := range vxlans {
		if v.UDPPort == 0 || seen[v.UDPPort] {
			continue
		}
		seen[v.UDPPort] = true
		ports = append(ports, v.UDPPort)
	}
	sort.Ints(ports)
	return ports
}

func nixOSFirewallTrustedInterfaces(vxlans []nixOSVXLAN) []string {
	seen := map[string]bool{}
	var names []string
	for _, v := range vxlans {
		if v.Bridge == "" || seen[v.Bridge] {
			continue
		}
		seen[v.Bridge] = true
		names = append(names, v.Bridge)
	}
	sort.Strings(names)
	return names
}

func validateNixPackageIdent(value string) error {
	if value == "" || strings.ContainsAny(value, " \t\n\r;{}[]()\"'") {
		return fmt.Errorf("invalid Nix package identifier %q", value)
	}
	return nil
}
