package render

import (
	"bytes"
	"fmt"
	"sort"
	"strconv"
	"strings"

	"routerd/pkg/api"
)

type nixOSInterface struct {
	Name             string
	IfName           string
	AdminUp          bool
	DHCP4            bool
	DHCP4UseRoutes   *bool
	DHCP4UseDNS      *bool
	DHCP4RouteMetric int
	DHCP6            bool
	AcceptRA         bool
	Addresses        []string
}

func NixOSModule(router *api.Router) ([]byte, error) {
	host, err := nixOSHost(router)
	if err != nil {
		return nil, err
	}
	interfaces, err := nixOSInterfaces(router)
	if err != nil {
		return nil, err
	}
	ntpServers, err := nixOSNTPServers(router)
	if err != nil {
		return nil, err
	}
	sysctls, err := nixOSSysctls(router)
	if err != nil {
		return nil, err
	}
	packages, servicePackages, err := nixOSPackages(router, host)
	if err != nil {
		return nil, err
	}

	var buf bytes.Buffer
	buf.WriteString("# Generated by routerd. Do not edit by hand.\n")
	buf.WriteString("{ config, lib, pkgs, ... }:\n\n")
	buf.WriteString("{\n")
	if host.Hostname != "" {
		buf.WriteString("  networking.hostName = " + nixString(host.Hostname) + ";\n")
	}
	if host.Domain != "" {
		buf.WriteString("  networking.domain = " + nixString(host.Domain) + ";\n")
	}
	if host.Boot.Loader == "grub" || host.Boot.GrubDevice != "" {
		buf.WriteString("  boot.loader.grub.enable = true;\n")
		if host.Boot.GrubDevice != "" {
			buf.WriteString("  boot.loader.grub.device = " + nixString(host.Boot.GrubDevice) + ";\n")
		}
	}
	if len(interfaces) > 0 {
		buf.WriteString("  networking.useDHCP = false;\n")
		buf.WriteString("  networking.useNetworkd = true;\n")
		buf.WriteString("  networking.firewall.checkReversePath = false;\n")
		buf.WriteString("  systemd.network.enable = true;\n")
		for _, iface := range interfaces {
			writeNixOSNetwork(&buf, iface)
		}
	}
	if api.BoolDefault(host.SSH.Enabled, len(host.Users) > 0) {
		buf.WriteString("  services.openssh = {\n")
		buf.WriteString("    enable = true;\n")
		if host.SSH.PasswordAuthentication != nil || host.SSH.PermitRootLogin != "" {
			buf.WriteString("    settings = {\n")
			if host.SSH.PasswordAuthentication != nil {
				buf.WriteString("      PasswordAuthentication = " + nixBool(*host.SSH.PasswordAuthentication) + ";\n")
			}
			if host.SSH.PermitRootLogin != "" {
				buf.WriteString("      PermitRootLogin = " + nixString(host.SSH.PermitRootLogin) + ";\n")
			}
			buf.WriteString("    };\n")
		}
		buf.WriteString("  };\n")
	}
	for _, user := range host.Users {
		writeNixOSUser(&buf, user)
	}
	if host.Sudo.WheelNeedsPassword != nil {
		buf.WriteString("  security.sudo.wheelNeedsPassword = " + nixBool(*host.Sudo.WheelNeedsPassword) + ";\n")
	}
	if len(ntpServers) > 0 {
		buf.WriteString("  services.timesyncd.enable = true;\n")
		buf.WriteString("  services.timesyncd.servers = " + nixStringList(ntpServers) + ";\n")
	}
	if len(sysctls) > 0 {
		buf.WriteString("  boot.kernel.sysctl = {\n")
		for _, key := range sortedMapKeysString(sysctls) {
			buf.WriteString("    " + nixString(key) + " = " + nixSysctlValue(sysctls[key]) + ";\n")
		}
		buf.WriteString("  };\n")
	}
	if len(packages) > 0 {
		buf.WriteString("  environment.systemPackages = with pkgs; [\n")
		for _, pkg := range packages {
			buf.WriteString("    " + pkg + "\n")
		}
		buf.WriteString("  ];\n")
	}
	if api.BoolDefault(host.RouterdService.Enabled, false) {
		writeNixOSRouterdService(&buf, host.RouterdService, servicePackages)
	}
	if host.StateVersion != "" {
		buf.WriteString("  system.stateVersion = " + nixString(host.StateVersion) + ";\n")
	}
	buf.WriteString("}\n")
	return buf.Bytes(), nil
}

func nixOSHost(router *api.Router) (api.NixOSHostSpec, error) {
	var out api.NixOSHostSpec
	seen := false
	for _, res := range router.Spec.Resources {
		switch res.Kind {
		case "NixOSHost":
			if seen {
				return out, fmt.Errorf("multiple NixOSHost resources are not supported")
			}
			spec, err := res.NixOSHostSpec()
			if err != nil {
				return out, err
			}
			out = spec
			seen = true
		case "Hostname":
			spec, err := res.HostnameSpec()
			if err != nil {
				return out, err
			}
			if out.Hostname == "" && spec.Managed {
				host, domain := splitHostname(spec.Hostname)
				out.Hostname = host
				out.Domain = domain
			}
		}
	}
	return out, nil
}

func nixOSNTPServers(router *api.Router) ([]string, error) {
	var servers []string
	for _, res := range router.Spec.Resources {
		if res.Kind != "NTPClient" {
			continue
		}
		spec, err := res.NTPClientSpec()
		if err != nil {
			return nil, err
		}
		if !spec.Managed {
			continue
		}
		if provider := defaultString(spec.Provider, "systemd-timesyncd"); provider != "systemd-timesyncd" {
			return nil, fmt.Errorf("%s has unsupported provider %q", res.ID(), provider)
		}
		if source := defaultString(spec.Source, "static"); source != "static" {
			return nil, fmt.Errorf("%s has unsupported source %q", res.ID(), source)
		}
		for _, server := range spec.Servers {
			server = strings.TrimSpace(server)
			if server != "" {
				servers = append(servers, server)
			}
		}
	}
	sort.Strings(servers)
	return servers, nil
}

func nixOSSysctls(router *api.Router) (map[string]string, error) {
	values := map[string]string{}
	for _, res := range router.Spec.Resources {
		if res.Kind != "Sysctl" {
			continue
		}
		spec, err := res.SysctlSpec()
		if err != nil {
			return nil, err
		}
		if !spec.Persistent {
			continue
		}
		values[spec.Key] = spec.Value
	}
	return values, nil
}

func nixOSInterfaces(router *api.Router) ([]nixOSInterface, error) {
	interfaces := map[string]*nixOSInterface{}
	var names []string
	for _, res := range router.Spec.Resources {
		if res.Kind != "Interface" {
			continue
		}
		spec, err := res.InterfaceSpec()
		if err != nil {
			return nil, err
		}
		if spec.IfName == "" {
			return nil, fmt.Errorf("%s has empty ifname", res.ID())
		}
		interfaces[res.Metadata.Name] = &nixOSInterface{
			Name:    res.Metadata.Name,
			IfName:  spec.IfName,
			AdminUp: spec.AdminUp,
		}
		names = append(names, res.Metadata.Name)
	}
	for _, res := range router.Spec.Resources {
		switch res.Kind {
		case "IPv4StaticAddress":
			spec, err := res.IPv4StaticAddressSpec()
			if err != nil {
				return nil, err
			}
			if iface := interfaces[spec.Interface]; iface != nil {
				iface.Addresses = append(iface.Addresses, spec.Address)
			}
		case "IPv4DHCPAddress":
			spec, err := res.IPv4DHCPAddressSpec()
			if err != nil {
				return nil, err
			}
			if iface := interfaces[spec.Interface]; iface != nil {
				iface.DHCP4 = true
				iface.DHCP4UseRoutes = spec.UseRoutes
				iface.DHCP4UseDNS = spec.UseDNS
				iface.DHCP4RouteMetric = spec.RouteMetric
			}
		case "IPv6DHCPAddress":
			spec, err := res.IPv6DHCPAddressSpec()
			if err != nil {
				return nil, err
			}
			if iface := interfaces[spec.Interface]; iface != nil {
				iface.DHCP6 = true
				iface.AcceptRA = true
			}
		case "IPv6PrefixDelegation":
			spec, err := res.IPv6PrefixDelegationSpec()
			if err != nil {
				return nil, err
			}
			if iface := interfaces[spec.Interface]; iface != nil {
				iface.DHCP6 = true
				iface.AcceptRA = true
			}
		}
	}
	sort.Strings(names)
	out := make([]nixOSInterface, 0, len(names))
	for _, name := range names {
		out = append(out, *interfaces[name])
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].IfName == out[j].IfName {
			return out[i].Name < out[j].Name
		}
		return out[i].IfName < out[j].IfName
	})
	return out, nil
}

func writeNixOSNetwork(buf *bytes.Buffer, iface nixOSInterface) {
	buf.WriteString("  systemd.network.networks." + nixString("10-netplan-"+iface.IfName) + " = {\n")
	buf.WriteString("    matchConfig.Name = " + nixString(iface.IfName) + ";\n")
	if iface.DHCP4 || iface.DHCP6 || iface.AcceptRA || len(iface.Addresses) == 0 {
		buf.WriteString("    networkConfig = {\n")
		if iface.DHCP4 && iface.DHCP6 {
			buf.WriteString("      DHCP = \"yes\";\n")
		} else if iface.DHCP4 {
			buf.WriteString("      DHCP = \"ipv4\";\n")
		} else if iface.DHCP6 {
			buf.WriteString("      DHCP = \"ipv6\";\n")
		}
		if iface.AcceptRA {
			buf.WriteString("      IPv6AcceptRA = true;\n")
		}
		if len(iface.Addresses) == 0 && !iface.DHCP4 && !iface.DHCP6 && !iface.AcceptRA {
			buf.WriteString("      LinkLocalAddressing = \"no\";\n")
		}
		buf.WriteString("    };\n")
	}
	if len(iface.Addresses) > 0 {
		buf.WriteString("    address = [\n")
		for _, address := range iface.Addresses {
			buf.WriteString("      " + nixString(address) + "\n")
		}
		buf.WriteString("    ];\n")
	}
	if iface.DHCP4UseRoutes != nil || iface.DHCP4UseDNS != nil || iface.DHCP4RouteMetric != 0 {
		buf.WriteString("    dhcpV4Config = {\n")
		if iface.DHCP4UseRoutes != nil {
			buf.WriteString("      UseRoutes = " + nixBool(*iface.DHCP4UseRoutes) + ";\n")
		}
		if iface.DHCP4UseDNS != nil {
			buf.WriteString("      UseDNS = " + nixBool(*iface.DHCP4UseDNS) + ";\n")
		}
		if iface.DHCP4RouteMetric != 0 {
			buf.WriteString("      RouteMetric = " + strconv.Itoa(iface.DHCP4RouteMetric) + ";\n")
		}
		buf.WriteString("    };\n")
	}
	if iface.AdminUp || len(iface.Addresses) == 0 {
		required := "no"
		if iface.DHCP4 || iface.DHCP6 || len(iface.Addresses) > 0 {
			required = "routable"
		}
		buf.WriteString("    linkConfig.RequiredForOnline = " + nixString(required) + ";\n")
	}
	buf.WriteString("  };\n")
}

func writeNixOSUser(buf *bytes.Buffer, user api.NixOSUserSpec) {
	buf.WriteString("  users.users." + user.Name + " = {\n")
	buf.WriteString("    isNormalUser = true;\n")
	if user.Description != "" {
		buf.WriteString("    description = " + nixString(user.Description) + ";\n")
	}
	if len(user.Groups) > 0 {
		buf.WriteString("    extraGroups = " + nixStringList(user.Groups) + ";\n")
	}
	if user.InitialPassword != "" {
		buf.WriteString("    initialPassword = " + nixString(user.InitialPassword) + ";\n")
	}
	if len(user.SSHAuthorizedKeys) > 0 {
		buf.WriteString("    openssh.authorizedKeys.keys = " + nixStringList(user.SSHAuthorizedKeys) + ";\n")
	}
	buf.WriteString("  };\n")
}

func writeNixOSRouterdService(buf *bytes.Buffer, spec api.NixOSRouterdServiceSpec, servicePackages []string) {
	binaryPath := defaultString(spec.BinaryPath, "/usr/local/sbin/routerd")
	configFile := defaultString(spec.ConfigFile, "/usr/local/etc/routerd/router.yaml")
	socket := defaultString(spec.Socket, "/run/routerd/routerd.sock")
	applyInterval := defaultString(spec.ApplyInterval, "60s")
	args := []string{
		binaryPath,
		"serve",
		"--config", configFile,
		"--socket", socket,
		"--apply-interval", applyInterval,
	}
	args = append(args, spec.ExtraFlags...)

	buf.WriteString("  systemd.services.routerd = {\n")
	buf.WriteString("    description = \"routerd declarative router controller\";\n")
	buf.WriteString("    wantedBy = [ \"multi-user.target\" ];\n")
	buf.WriteString("    after = [ \"network-pre.target\" ];\n")
	buf.WriteString("    wants = [ \"network-pre.target\" ];\n")
	if len(servicePackages) > 0 {
		buf.WriteString("    path = with pkgs; [\n")
		for _, pkg := range servicePackages {
			buf.WriteString("      " + pkg + "\n")
		}
		buf.WriteString("    ];\n")
	}
	buf.WriteString("    serviceConfig = {\n")
	buf.WriteString("      Type = \"simple\";\n")
	buf.WriteString("      ExecStart = lib.concatStringsSep \" \" [\n")
	for _, arg := range args {
		buf.WriteString("        " + nixString(arg) + "\n")
	}
	buf.WriteString("      ];\n")
	buf.WriteString("      Restart = \"always\";\n")
	buf.WriteString("      RestartSec = \"2s\";\n")
	buf.WriteString("      RuntimeDirectory = \"routerd\";\n")
	buf.WriteString("      StateDirectory = \"routerd\";\n")
	buf.WriteString("    };\n")
	buf.WriteString("  };\n")
}

func nixOSPackages(router *api.Router, host api.NixOSHostSpec) ([]string, []string, error) {
	service := map[string]bool{
		"conntrack-tools": true,
		"iproute2":        true,
		"procps":          true,
		"systemd":         true,
	}
	debug := map[string]bool{
		"jq": true,
	}
	for _, res := range router.Spec.Resources {
		switch res.Kind {
		case "IPv4DHCPServer", "IPv4DHCPScope", "IPv6DHCPServer", "IPv6DHCPScope", "DNSConditionalForwarder":
			service["dnsmasq"] = true
			debug["dnsmasq"] = true
		case "IPv4SourceNAT", "IPv4PolicyRoute", "IPv4PolicyRouteSet", "IPv4DefaultRoutePolicy", "FirewallPolicy", "ExposeService", "PathMTUPolicy":
			service["nftables"] = true
			debug["nftables"] = true
		case "PPPoEInterface":
			service["ppp"] = true
			debug["ppp"] = true
		}
	}
	for _, pkg := range host.AdditionalServicePath {
		if err := validateNixPackageIdent(pkg); err != nil {
			return nil, nil, err
		}
		service[pkg] = true
	}
	for _, pkg := range host.AdditionalPackages {
		if err := validateNixPackageIdent(pkg); err != nil {
			return nil, nil, err
		}
		debug[pkg] = true
	}
	if host.DebugSystemPackages {
		for pkg := range service {
			if pkg != "systemd" {
				debug[pkg] = true
			}
		}
		debug["conntrack-tools"] = true
	}
	serviceList := sortedMapKeys(service)
	var debugList []string
	if host.DebugSystemPackages || len(host.AdditionalPackages) > 0 {
		debugList = sortedMapKeys(debug)
	}
	return debugList, serviceList, nil
}

func splitHostname(value string) (string, string) {
	host, domain, ok := strings.Cut(value, ".")
	if !ok {
		return value, ""
	}
	return host, domain
}

func sortedMapKeys(values map[string]bool) []string {
	out := make([]string, 0, len(values))
	for value := range values {
		out = append(out, value)
	}
	sort.Strings(out)
	return out
}

func sortedMapKeysString(values map[string]string) []string {
	out := make([]string, 0, len(values))
	for value := range values {
		out = append(out, value)
	}
	sort.Strings(out)
	return out
}

func nixBool(value bool) string {
	if value {
		return "true"
	}
	return "false"
}

func nixString(value string) string {
	return strconv.Quote(value)
}

func nixSysctlValue(value string) string {
	if _, err := strconv.Atoi(value); err == nil {
		return value
	}
	switch value {
	case "true", "false":
		return value
	default:
		return nixString(value)
	}
}

func nixStringList(values []string) string {
	var b strings.Builder
	b.WriteString("[")
	for _, value := range values {
		b.WriteString(" ")
		b.WriteString(nixString(value))
	}
	b.WriteString(" ]")
	return b.String()
}

func validateNixPackageIdent(value string) error {
	if value == "" || strings.ContainsAny(value, " \t\n\r;{}[]()\"'") {
		return fmt.Errorf("invalid Nix package identifier %q", value)
	}
	return nil
}
