// SPDX-License-Identifier: BSD-3-Clause

package render

import (
	"bytes"
	"fmt"
	"net/netip"
	"sort"
	"strconv"
	"strings"

	"routerd/pkg/api"
)

func PF(router *api.Router, holes []FirewallHole) ([]byte, error) {
	aliases, err := nftOutboundAliases(router)
	if err != nil {
		return nil, err
	}
	var nat44Rules []api.Resource
	var zones []api.Resource
	var policies []api.Resource
	var logs []api.Resource
	var rules []api.Resource
	var clientPolicies []api.Resource
	var ingressRules []ingressNATRule
	mssPolicies, err := pathMTUMSSPolicies(router)
	if err != nil {
		return nil, err
	}
	for _, res := range router.Spec.Resources {
		switch res.Kind {
		case "NAT44Rule":
			nat44Rules = append(nat44Rules, res)
		case "FirewallZone":
			if res.APIVersion == api.FirewallAPIVersion {
				zones = append(zones, res)
			}
		case "FirewallPolicy":
			if res.APIVersion == api.FirewallAPIVersion {
				policies = append(policies, res)
			}
		case "FirewallEventLog":
			if res.APIVersion == api.FirewallAPIVersion {
				logs = append(logs, res)
			}
		case "FirewallRule":
			if res.APIVersion == api.FirewallAPIVersion {
				rules = append(rules, res)
			}
		case "ClientPolicy":
			if res.APIVersion == api.FirewallAPIVersion {
				clientPolicies = append(clientPolicies, res)
			}
		}
	}
	ingressRules, err = ingressNATRules(router, aliases)
	if err != nil {
		return nil, err
	}
	if len(nat44Rules) == 0 && len(ingressRules) == 0 && len(zones) == 0 && len(rules) == 0 && len(holes) == 0 && len(mssPolicies) == 0 {
		return nil, nil
	}
	sort.Slice(nat44Rules, func(i, j int) bool { return nat44Rules[i].Metadata.Name < nat44Rules[j].Metadata.Name })
	sort.Slice(zones, func(i, j int) bool { return zones[i].Metadata.Name < zones[j].Metadata.Name })
	sort.Slice(policies, func(i, j int) bool { return policies[i].Metadata.Name < policies[j].Metadata.Name })
	sort.Slice(logs, func(i, j int) bool { return logs[i].Metadata.Name < logs[j].Metadata.Name })
	sort.Slice(rules, func(i, j int) bool { return rules[i].Metadata.Name < rules[j].Metadata.Name })
	sort.Slice(clientPolicies, func(i, j int) bool { return clientPolicies[i].Metadata.Name < clientPolicies[j].Metadata.Name })

	zoneMap, err := nftFirewallZones(aliases, zones)
	if err != nil {
		return nil, err
	}
	pfClientPolicies, err := pfClientPolicies(router, aliases, clientPolicies)
	if err != nil {
		return nil, err
	}
	policy := firewallPolicyOptions(policies)
	logging := firewallLogOptions(logs)

	var buf bytes.Buffer
	buf.WriteString("# Generated by routerd. Do not edit by hand.\n")
	buf.WriteString("set skip on lo0\n")
	for _, zone := range sortedFirewallZones(zoneMap) {
		if len(zone.IfNames) == 0 {
			continue
		}
		buf.WriteString(pfZoneMacro(zone) + " = " + pfInterfaceSet(zone.IfNames) + "\n")
	}
	if err := writePFMSSClamp(&buf, aliases, mssPolicies); err != nil {
		return nil, err
	}
	if hasRuntimeResolvedNAT44(nat44Rules) {
		buf.WriteString("nat-anchor \"routerd_nat\"\n")
	}
	if err := writePFIngress(&buf, ingressRules); err != nil {
		return nil, err
	}
	if err := writePFNAT(&buf, router, aliases, nat44Rules); err != nil {
		return nil, err
	}
	filterRequested := len(zoneMap) > 0 || len(rules) > 0 || len(holes) > 0 || len(logs) > 0
	if filterRequested {
		if err := writePFFilter(&buf, zoneMap, rules, holes, pfClientPolicies, policy, logging); err != nil {
			return nil, err
		}
	} else {
		buf.WriteString("pass all keep state\n")
	}
	return buf.Bytes(), nil
}

func hasRuntimeResolvedNAT44(resources []api.Resource) bool {
	for _, res := range resources {
		spec, err := res.NAT44RuleSpec()
		if err == nil && spec.EgressInterface == "" && spec.EgressPolicyRef != "" {
			return true
		}
	}
	return false
}

func writePFIngress(buf *bytes.Buffer, rules []ingressNATRule) error {
	for _, rule := range rules {
		if rule.ListenInterface == "" {
			return fmt.Errorf("%s references listen interface with empty ifname", rule.ResourceID)
		}
		destination := "any"
		if rule.ListenAddress != "" {
			destination = rule.ListenAddress
		}
		buf.WriteString("rdr pass on " + rule.ListenInterface + " inet proto " + rule.Protocol + " from any to " + destination + " port " + strconv.Itoa(rule.ListenPort) + " -> " + rule.TargetAddress + " port " + strconv.Itoa(rule.TargetPort) + "\n")
		for _, ifname := range rule.HairpinInterfaces {
			buf.WriteString("rdr pass on " + ifname + " inet proto " + rule.Protocol + " from any to " + rule.ListenAddress + " port " + strconv.Itoa(rule.ListenPort) + " -> " + rule.TargetAddress + " port " + strconv.Itoa(rule.TargetPort) + "\n")
			buf.WriteString("nat on " + ifname + " inet proto " + rule.Protocol + " from (" + ifname + ":network) to " + rule.TargetAddress + " port " + strconv.Itoa(rule.TargetPort) + " -> (" + ifname + ")\n")
		}
	}
	return nil
}

func writePFMSSClamp(buf *bytes.Buffer, aliases map[string]string, policies []pathMTUPolicy) error {
	for _, policy := range policies {
		if !pathMTUFamilyEnabled(policy.Spec.TCPMSSClamp.Families, "ipv4") {
			continue
		}
		fromIfname := aliases[policy.Spec.FromInterface]
		if fromIfname == "" {
			return fmt.Errorf("%s references fromInterface with empty ifname", policy.ResourceID)
		}
		mss := policy.MTU - 40
		if mss < 536 {
			return fmt.Errorf("%s computed IPv4 MSS %d is too small", policy.ResourceID, mss)
		}
		buf.WriteString("scrub in on " + fromIfname + " proto tcp max-mss " + strconv.Itoa(mss) + "\n")
		var toIfnames []string
		for _, name := range policy.Spec.ToInterfaces {
			ifname := aliases[name]
			if ifname == "" {
				return fmt.Errorf("%s references toInterface with empty ifname %q", policy.ResourceID, name)
			}
			toIfnames = append(toIfnames, ifname)
		}
		sort.Strings(toIfnames)
		for _, ifname := range compactStrings(toIfnames) {
			buf.WriteString("scrub out on " + ifname + " proto tcp max-mss " + strconv.Itoa(mss) + "\n")
		}
	}
	return nil
}

func writePFNAT(buf *bytes.Buffer, router *api.Router, aliases map[string]string, nat44Rules []api.Resource) error {
	for _, res := range nat44Rules {
		spec, err := res.NAT44RuleSpec()
		if err != nil {
			return err
		}
		if spec.OutboundInterface != "" || len(spec.SourceCIDRs) > 0 || spec.Translation.Type != "" {
			ifname := aliases[spec.OutboundInterface]
			if ifname == "" {
				return fmt.Errorf("%s references outbound interface with empty ifname", res.ID())
			}
			for _, cidr := range spec.SourceCIDRs {
				prefix, err := netip.ParsePrefix(cidr)
				if err != nil || !prefix.Addr().Is4() {
					return fmt.Errorf("%s has invalid IPv4 source CIDR %q", res.ID(), cidr)
				}
				target, err := pfNATTarget(spec.Translation, ifname)
				if err != nil {
					return fmt.Errorf("%s: %w", res.ID(), err)
				}
				buf.WriteString("nat on " + ifname + " from " + prefix.Masked().String() + " to any -> " + target + "\n")
			}
			continue
		}
		if spec.EgressInterface == "" {
			if spec.EgressPolicyRef != "" {
				buf.WriteString("# " + res.ID() + " skipped: egressInterface is resolved by " + spec.EgressPolicyRef + " at runtime\n")
				continue
			}
			return fmt.Errorf("%s needs resolved egressInterface for static pf render", res.ID())
		}
		ifname := aliases[spec.EgressInterface]
		if ifname == "" {
			return fmt.Errorf("%s references egress interface with empty ifname", res.ID())
		}
		for _, cidr := range spec.SourceRanges {
			prefix, err := netip.ParsePrefix(cidr)
			if err != nil || !prefix.Addr().Is4() {
				return fmt.Errorf("%s has invalid IPv4 source range %q", res.ID(), cidr)
			}
			excludedDestinations, err := pfIPv4AddressSet(res.ID(), "excluded destination", spec.ExcludeDestinationCIDRs)
			if err != nil {
				return err
			}
			if excludedDestinations != "" {
				buf.WriteString("no nat on " + ifname + " from " + prefix.Masked().String() + " to " + excludedDestinations + "\n")
			}
			destinations, err := pfNATDestinationMatches(res.ID(), spec.DestinationCIDRs)
			if err != nil {
				return err
			}
			target := "(" + ifname + ")"
			if spec.Type == "snat" {
				snatAddress := spec.SNATAddress
				if snatAddress == "" && spec.SNATAddressFrom.Resource != "" {
					var err error
					snatAddress, err = renderAddressFromResource(router, spec.SNATAddressFrom)
					if err != nil {
						return fmt.Errorf("%s spec.snatAddressFrom: %w", res.ID(), err)
					}
				}
				if snatAddress == "" {
					return fmt.Errorf("%s needs snat address", res.ID())
				}
				target = snatAddress
			}
			for _, destination := range destinations {
				buf.WriteString("nat on " + ifname + " from " + prefix.Masked().String() + " to " + destination + " -> " + target + "\n")
			}
		}
	}
	return nil
}

func PFNAT44Rules(rules []NAT44RenderRule) ([]byte, error) {
	rules = append([]NAT44RenderRule(nil), rules...)
	sort.Slice(rules, func(i, j int) bool { return rules[i].Name < rules[j].Name })
	var buf bytes.Buffer
	buf.WriteString("# Generated by routerd. Do not edit by hand.\n")
	for _, rule := range rules {
		if err := writePFNAT44RenderRule(&buf, rule); err != nil {
			return nil, err
		}
	}
	return buf.Bytes(), nil
}

func writePFNAT44RenderRule(buf *bytes.Buffer, rule NAT44RenderRule) error {
	if rule.EgressInterface == "" {
		return fmt.Errorf("%s needs egress interface", rule.Name)
	}
	for _, cidr := range rule.SourceRanges {
		prefix, err := netip.ParsePrefix(cidr)
		if err != nil || !prefix.Addr().Is4() {
			return fmt.Errorf("%s has invalid IPv4 source range %q", rule.Name, cidr)
		}
		excludedDestinations, err := pfIPv4AddressSet(rule.Name, "excluded destination", rule.ExcludeDestinationCIDRs)
		if err != nil {
			return err
		}
		if excludedDestinations != "" {
			buf.WriteString("no nat on " + rule.EgressInterface + " from " + prefix.Masked().String() + " to " + excludedDestinations + "\n")
		}
		destinations, err := pfNATDestinationMatches(rule.Name, rule.DestinationCIDRs)
		if err != nil {
			return err
		}
		target := "(" + rule.EgressInterface + ")"
		if rule.Type == "snat" {
			if rule.SNATAddress == "" {
				return fmt.Errorf("%s needs snat address", rule.Name)
			}
			target = rule.SNATAddress
		}
		for _, destination := range destinations {
			buf.WriteString("nat on " + rule.EgressInterface + " from " + prefix.Masked().String() + " to " + destination + " -> " + target + "\n")
		}
	}
	return nil
}

func pfNATDestinationMatches(resourceID string, destinationCIDRs []string) ([]string, error) {
	if len(destinationCIDRs) > 0 {
		var out []string
		for _, cidr := range destinationCIDRs {
			prefix, err := netip.ParsePrefix(cidr)
			if err != nil || !prefix.Addr().Is4() {
				return nil, fmt.Errorf("%s has invalid IPv4 destination CIDR %q", resourceID, cidr)
			}
			out = append(out, prefix.Masked().String())
		}
		return out, nil
	}
	return []string{"any"}, nil
}

func pfIPv4AddressSet(resourceID, label string, cidrs []string) (string, error) {
	if len(cidrs) == 0 {
		return "", nil
	}
	var values []string
	for _, cidr := range cidrs {
		prefix, err := netip.ParsePrefix(cidr)
		if err != nil || !prefix.Addr().Is4() {
			return "", fmt.Errorf("%s has invalid IPv4 %s CIDR %q", resourceID, label, cidr)
		}
		values = append(values, prefix.Masked().String())
	}
	sort.Strings(values)
	if len(values) == 1 {
		return values[0], nil
	}
	return "{ " + strings.Join(values, ", ") + " }", nil
}

type pfClientPolicy struct {
	Name          string
	Mode          string
	IfNames       []string
	Addresses     []string
	GuestServices []string
	EgressDeny    []string
	EgressAllow   []string
}

func pfClientPolicies(router *api.Router, aliases map[string]string, resources []api.Resource) ([]pfClientPolicy, error) {
	reservations := map[string]api.DHCPv4ReservationSpec{}
	for _, res := range router.Spec.Resources {
		if res.APIVersion != api.NetAPIVersion || res.Kind != "DHCPv4Reservation" {
			continue
		}
		spec, err := res.DHCPv4ReservationSpec()
		if err != nil {
			return nil, err
		}
		reservations["DHCPv4Reservation/"+res.Metadata.Name] = spec
		reservations[res.Metadata.Name] = spec
	}
	var out []pfClientPolicy
	for _, res := range resources {
		spec, err := res.ClientPolicySpec()
		if err != nil {
			return nil, err
		}
		var ifnames []string
		for _, iface := range spec.Interfaces {
			ref := iface
			if kind, name, ok := strings.Cut(iface, "/"); ok {
				if kind != "Interface" {
					return nil, fmt.Errorf("%s references unsupported client policy interface %q", res.ID(), iface)
				}
				ref = name
			}
			ifname := aliases[ref]
			if ifname == "" {
				return nil, fmt.Errorf("%s references interface with empty ifname %q", res.ID(), iface)
			}
			ifnames = append(ifnames, ifname)
		}
		sort.Strings(ifnames)
		policy := pfClientPolicy{
			Name:          res.Metadata.Name,
			Mode:          spec.Mode,
			IfNames:       compactStrings(ifnames),
			GuestServices: clientPolicyGuestServices(spec.GuestServices),
			EgressDeny:    pfIPv4ClientPolicyCIDRs(clientPolicyEgressCIDRs(spec.GuestEgressDeny, []string{"10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16", "fc00::/7"})),
			EgressAllow:   clientPolicyEgressCIDRs(spec.GuestEgressAllow, nil),
		}
		for _, entry := range spec.Classification {
			if entry.IPv4Reservation == "" {
				if spec.Mode == "include" && (entry.Mode == "guest" || entry.Mode == "isolated") {
					return nil, fmt.Errorf("%s classification %q needs ipv4Reservation on FreeBSD because pf cannot match client selectors", res.ID(), entry.Name)
				}
				continue
			}
			reservation, ok := reservations[entry.IPv4Reservation]
			if !ok {
				return nil, fmt.Errorf("%s references unknown DHCPv4 reservation %q", res.ID(), entry.IPv4Reservation)
			}
			if reservation.IPAddress == "" {
				return nil, fmt.Errorf("%s references DHCPv4 reservation %q with empty ipAddress", res.ID(), entry.IPv4Reservation)
			}
			switch spec.Mode {
			case "include":
				if entry.Mode == "guest" || entry.Mode == "isolated" {
					policy.Addresses = append(policy.Addresses, reservation.IPAddress)
				}
			case "exclude":
				if entry.Mode == "trusted" {
					policy.Addresses = append(policy.Addresses, reservation.IPAddress)
				}
			default:
				return nil, fmt.Errorf("%s has unsupported client policy mode %q", res.ID(), spec.Mode)
			}
		}
		sort.Strings(policy.Addresses)
		policy.Addresses = compactStrings(policy.Addresses)
		out = append(out, policy)
	}
	return out, nil
}

func writePFFilter(buf *bytes.Buffer, zones map[string]firewallZone, rules []api.Resource, holes []FirewallHole, clientPolicies []pfClientPolicy, policy firewallPolicy, logging firewallLogging) error {
	buf.WriteString("block drop all\n")
	buf.WriteString("pass quick on lo0 all\n")
	buf.WriteString("pass out quick all keep state\n")
	buf.WriteString("pass quick inet6 proto icmp6 all keep state\n")
	for _, zone := range sortedFirewallZones(zones) {
		if len(zone.IfNames) == 0 {
			continue
		}
		selfAccepted := implicitFirewallAction(zone.Role, "self", policy) == "accept"
		if selfAccepted {
			buf.WriteString("pass in quick on $" + pfZoneMacro(zone) + " to self keep state\n")
		}
		for _, hole := range holes {
			if hole.FromZone == zone.Name && hole.ToZone == "self" {
				if selfAccepted {
					continue
				}
				for _, expr := range pfFirewallHoleExprs(zone, hole, logging) {
					buf.WriteString(expr + "\n")
				}
			}
		}
		for _, res := range rules {
			spec, err := res.FirewallRuleSpec()
			if err != nil {
				return err
			}
			if spec.FromZone == zone.Name && spec.ToZone == "self" {
				buf.WriteString(pfFirewallRuleExpr(zone, res.Metadata.Name, spec, logging) + "\n")
			}
		}
		for _, clientPolicy := range clientPolicies {
			for _, expr := range pfClientPolicyInputExprs(zone, clientPolicy, logging) {
				buf.WriteString(expr + "\n")
			}
		}
	}
	for _, from := range sortedFirewallZones(zones) {
		if len(from.IfNames) == 0 {
			continue
		}
		for _, clientPolicy := range clientPolicies {
			for _, expr := range pfClientPolicyForwardExprs(from, clientPolicy, logging) {
				buf.WriteString(expr + "\n")
			}
		}
		if err := writePFDisallowedForwardDestinations(buf, from, zones, policy); err != nil {
			return err
		}
		for _, to := range sortedFirewallZones(zones) {
			if implicitFirewallAction(from.Role, to.Role, policy) != "accept" {
				continue
			}
			if from.Name == to.Name && !policy.SameRoleAccept {
				continue
			}
			if !pfCanRenderBroadForwardPass(from, to) {
				continue
			}
			logExpr := ""
			if logging.Enabled && logging.AcceptSampleRate > 0 {
				logExpr = " log"
			}
			buf.WriteString("pass in" + logExpr + " quick on $" + pfZoneMacro(from) + " keep state label " + pfQuote("routerd:"+from.Name+"-to-"+to.Name) + "\n")
		}
		for _, hole := range holes {
			if hole.FromZone == from.Name && hole.ToZone != "self" {
				for _, expr := range pfFirewallHoleExprs(from, hole, logging) {
					buf.WriteString(expr + "\n")
				}
			}
		}
		for _, res := range rules {
			spec, err := res.FirewallRuleSpec()
			if err != nil {
				return err
			}
			if spec.FromZone == from.Name && spec.ToZone != "self" {
				buf.WriteString(pfFirewallRuleExpr(from, res.Metadata.Name, spec, logging) + "\n")
			}
		}
	}
	return nil
}

func writePFDisallowedForwardDestinations(buf *bytes.Buffer, from firewallZone, zones map[string]firewallZone, policy firewallPolicy) error {
	if from.Role != "trust" {
		return nil
	}
	for _, to := range sortedFirewallZones(zones) {
		if len(to.IfNames) == 0 || implicitFirewallAction(from.Role, to.Role, policy) != "drop" {
			continue
		}
		for _, ifname := range to.IfNames {
			buf.WriteString("block drop in quick on $" + pfZoneMacro(from) + " to (" + ifname + ":network) label " + pfQuote("routerd:"+from.Name+"-to-"+to.Name+"-deny") + "\n")
		}
	}
	return nil
}

func pfClientPolicyInputExprs(zone firewallZone, policy pfClientPolicy, logging firewallLogging) []string {
	if len(policy.Addresses) == 0 || !pfClientPolicyAppliesToZone(zone, policy) {
		return nil
	}
	match := pfClientPolicySourceMatch(policy)
	if match == "" {
		return nil
	}
	var exprs []string
	for _, ifname := range policy.IfNames {
		onExpr := ifname
		if stringInSlice("dns", policy.GuestServices) {
			exprs = append(exprs, pfClientPolicyServiceExpr(onExpr, policy.Name, match, "udp", 53, "dns", logging))
			exprs = append(exprs, pfClientPolicyServiceExpr(onExpr, policy.Name, match, "tcp", 53, "dns", logging))
		}
		if stringInSlice("dhcp", policy.GuestServices) {
			exprs = append(exprs, pfClientPolicyServiceExpr(onExpr, policy.Name, match, "udp", 67, "dhcp", logging))
		}
		if stringInSlice("ntp", policy.GuestServices) {
			exprs = append(exprs, pfClientPolicyServiceExpr(onExpr, policy.Name, match, "udp", 123, "ntp", logging))
		}
		if stringInSlice("mdns", policy.GuestServices) {
			exprs = append(exprs, pfClientPolicyServiceExpr(onExpr, policy.Name, match, "udp", 5353, "mdns", logging))
		}
		if stringInSlice("ssdp", policy.GuestServices) {
			exprs = append(exprs, pfClientPolicyServiceExpr(onExpr, policy.Name, match, "udp", 1900, "ssdp", logging))
		}
		exprs = append(exprs, "block drop in "+pfLogExpr(logging)+" quick on "+onExpr+" from "+match+" to self label "+pfQuote("routerd:client-policy:"+policy.Name+":self-deny"))
	}
	return exprs
}

func pfClientPolicyForwardExprs(zone firewallZone, policy pfClientPolicy, logging firewallLogging) []string {
	if len(policy.Addresses) == 0 || !pfClientPolicyAppliesToZone(zone, policy) {
		return nil
	}
	match := pfClientPolicySourceMatch(policy)
	if match == "" {
		return nil
	}
	var exprs []string
	for _, ifname := range policy.IfNames {
		onExpr := ifname
		for _, cidr := range policy.EgressAllow {
			exprs = append(exprs, "pass in quick on "+onExpr+" from "+match+" to "+cidr+" keep state label "+pfQuote("routerd:client-policy:"+policy.Name+":allow"))
		}
		for _, cidr := range policy.EgressDeny {
			exprs = append(exprs, "block drop in "+pfLogExpr(logging)+" quick on "+onExpr+" from "+match+" to "+cidr+" label "+pfQuote("routerd:client-policy:"+policy.Name+":deny"))
		}
	}
	return exprs
}

func pfClientPolicyAppliesToZone(zone firewallZone, policy pfClientPolicy) bool {
	for _, zoneIfname := range zone.IfNames {
		if stringInSlice(zoneIfname, policy.IfNames) {
			return true
		}
	}
	return false
}

func pfClientPolicySourceMatch(policy pfClientPolicy) string {
	addresses := append([]string(nil), policy.Addresses...)
	sort.Strings(addresses)
	if policy.Mode == "exclude" {
		if len(addresses) == 0 {
			return "any"
		}
		return "! " + pfAddressSet(addresses)
	}
	if len(addresses) == 0 {
		return ""
	}
	return pfAddressSet(addresses)
}

func pfAddressSet(values []string) string {
	if len(values) == 1 {
		return values[0]
	}
	return "{ " + strings.Join(values, ", ") + " }"
}

func pfIPv4ClientPolicyCIDRs(values []string) []string {
	out := make([]string, 0, len(values))
	for _, value := range values {
		if strings.Contains(value, ":") {
			continue
		}
		out = append(out, value)
	}
	return out
}

func pfClientPolicyServiceExpr(onExpr, name, source, proto string, port int, service string, logging firewallLogging) string {
	return "pass in quick on " + onExpr + " proto " + proto + " from " + source + " to self port " + strconv.Itoa(port) + " keep state label " + pfQuote("routerd:client-policy:"+name+":"+service)
}

func pfCanRenderBroadForwardPass(from, to firewallZone) bool {
	if from.Role == "untrust" && to.Role == "untrust" {
		return false
	}
	return true
}

func pfNATTarget(spec api.IPv4NATTranslationSpec, ifname string) (string, error) {
	switch spec.Type {
	case "interfaceAddress":
		return "(" + ifname + ")", nil
	case "address":
		if spec.Address == "" {
			return "", fmt.Errorf("address translation needs address")
		}
		return spec.Address, nil
	default:
		return "", fmt.Errorf("unsupported pf NAT translation type %q", spec.Type)
	}
}

func pfFirewallRuleExpr(zone firewallZone, name string, spec api.FirewallRuleSpec, logging firewallLogging) string {
	return pfFirewallRuleExprOn("$"+pfZoneMacro(zone), name, spec, logging)
}

func pfFirewallRuleExprOn(onExpr, name string, spec api.FirewallRuleSpec, logging firewallLogging) string {
	return pfFirewallRuleExprOnSelf(onExpr, "self", name, spec, logging)
}

func pfFirewallRuleExprOnSelf(onExpr, selfExpr, name string, spec api.FirewallRuleSpec, logging firewallLogging) string {
	action := "block drop"
	if spec.Action == "accept" {
		action = "pass"
	} else if spec.Action == "reject" {
		action = "block return"
	}
	var parts []string
	parts = append(parts, action, "in")
	if spec.Log {
		parts = append(parts, pfLogExpr(logging))
	}
	parts = append(parts, "quick", "on", onExpr)
	if proto := pfFirewallProtocol(spec.Protocol); proto != "" {
		parts = append(parts, proto)
	}
	if icmpType := pfFirewallICMPType(spec); icmpType != "" {
		parts = append(parts, icmpType)
	}
	if len(spec.SourceCIDRs) > 0 || len(spec.SourcePorts) > 0 {
		source := "any"
		if len(spec.SourceCIDRs) > 0 {
			source = pfCIDRSet(spec.SourceCIDRs)
		}
		parts = append(parts, "from", source)
		if ports := pfFirewallSourcePorts(spec); len(ports) > 0 {
			parts = append(parts, "port", pfPortSet(ports))
		}
	}
	if len(spec.DestinationCIDRs) > 0 {
		parts = append(parts, "to", pfCIDRSet(spec.DestinationCIDRs))
	} else if spec.ToZone == "self" {
		parts = append(parts, "to", selfExpr)
	}
	if ports := pfFirewallDestinationPorts(spec); len(ports) > 0 {
		parts = append(parts, "port", pfPortSet(ports))
	}
	parts = append(parts, "keep", "state", "label", pfQuote("routerd:"+name))
	return strings.Join(parts, " ")
}

func pfFirewallDestinationPorts(spec api.FirewallRuleSpec) []string {
	var ports []string
	if len(spec.DestinationPorts) > 0 {
		for _, port := range spec.DestinationPorts {
			value := strings.TrimSpace(string(port))
			if value != "" {
				ports = append(ports, strings.ReplaceAll(value, "-", ":"))
			}
		}
		return ports
	}
	if spec.Port != 0 {
		return []string{strconv.Itoa(spec.Port)}
	}
	return nil
}

func pfFirewallSourcePorts(spec api.FirewallRuleSpec) []string {
	ports := make([]string, 0, len(spec.SourcePorts))
	for _, port := range spec.SourcePorts {
		value := strings.TrimSpace(string(port))
		if value != "" {
			ports = append(ports, strings.ReplaceAll(value, "-", ":"))
		}
	}
	return ports
}

func pfPortSet(ports []string) string {
	if len(ports) == 1 {
		return ports[0]
	}
	return "{ " + strings.Join(ports, " ") + " }"
}

func pfFirewallHoleExprs(zone firewallZone, hole FirewallHole, logging firewallLogging) []string {
	action := defaultString(hole.Action, "accept")
	spec := api.FirewallRuleSpec{
		FromZone: hole.FromZone,
		ToZone:   hole.ToZone,
		Protocol: hole.Protocol,
		Port:     hole.Port,
		Action:   action,
		Log:      false,
	}
	name := hole.Name
	if name == "" {
		name = hole.Comment
	}
	if len(hole.IfNames) == 0 {
		return []string{pfFirewallRuleExpr(zone, name, spec, logging)}
	}
	ifnames := compactStrings(hole.IfNames)
	sort.Strings(ifnames)
	exprs := make([]string, 0, len(ifnames))
	for _, ifname := range ifnames {
		selfExpr := "self"
		if hole.ToZone == "self" {
			selfExpr = "(" + ifname + ")"
		}
		exprs = append(exprs, pfFirewallRuleExprOnSelf(ifname, selfExpr, name, spec, logging))
	}
	return exprs
}

func pfFirewallProtocol(protocol string) string {
	switch protocol {
	case "tcp", "udp":
		return "proto " + protocol
	case "icmp":
		return "inet proto icmp"
	case "icmpv6", "ipv6-icmp":
		return "inet6 proto icmp6"
	case "ipip":
		return "inet6 proto 4"
	case "vrrp":
		return "inet proto 112"
	case "vrrp6":
		return "inet6 proto 112"
	default:
		return ""
	}
}

func pfFirewallICMPType(spec api.FirewallRuleSpec) string {
	switch spec.Protocol {
	case "icmp":
		if icmpType := pfFirewallRuleICMPType(spec); icmpType != "" {
			return "icmp-type " + pfICMPTypeName(icmpType)
		}
	case "icmpv6", "ipv6-icmp":
		if icmpType := pfFirewallRuleICMPv6Type(spec); icmpType != "" {
			return "icmp6-type " + pfICMPv6TypeName(icmpType)
		}
	}
	return ""
}

func pfFirewallRuleICMPType(spec api.FirewallRuleSpec) string {
	if strings.TrimSpace(spec.ICMPType) != "" {
		return strings.TrimSpace(spec.ICMPType)
	}
	return strings.TrimSpace(spec.ICMPTypeKebab)
}

func pfFirewallRuleICMPv6Type(spec api.FirewallRuleSpec) string {
	if strings.TrimSpace(spec.ICMPv6Type) != "" {
		return strings.TrimSpace(spec.ICMPv6Type)
	}
	return strings.TrimSpace(spec.ICMPv6TypeKebab)
}

func pfICMPTypeName(value string) string {
	switch strings.TrimSpace(value) {
	case "echo-request":
		return "echoreq"
	case "echo-reply":
		return "echorep"
	default:
		return strings.TrimSpace(value)
	}
}

func pfICMPv6TypeName(value string) string {
	switch strings.TrimSpace(value) {
	case "echo-request":
		return "echoreq"
	case "echo-reply":
		return "echorep"
	case "router-solicit", "nd-router-solicit":
		return "routersol"
	case "router-advert", "nd-router-advert":
		return "routeradv"
	case "neighbor-solicit", "nd-neighbor-solicit":
		return "neighbrsol"
	case "neighbor-advert", "nd-neighbor-advert":
		return "neighbradv"
	default:
		return strings.TrimSpace(value)
	}
}

func pfLogExpr(logging firewallLogging) string {
	if logging.Enabled {
		return "log"
	}
	return "log"
}

func pfCIDRSet(cidrs []string) string {
	values := make([]string, 0, len(cidrs))
	for _, cidr := range cidrs {
		values = append(values, cidr)
	}
	sort.Strings(values)
	if len(values) == 1 {
		return values[0]
	}
	return "{ " + strings.Join(values, ", ") + " }"
}

func pfInterfaceSet(ifnames []string) string {
	values := append([]string(nil), ifnames...)
	sort.Strings(values)
	if len(values) == 1 {
		return pfQuote(values[0])
	}
	return pfQuote("{ " + strings.Join(values, ", ") + " }")
}

func pfZoneMacro(zone firewallZone) string {
	return pfIdent(zone.Name) + "_if"
}

func pfIdent(value string) string {
	replacer := strings.NewReplacer("-", "_", ".", "_", "/", "_")
	return replacer.Replace(value)
}

func pfQuote(value string) string {
	return strconv.Quote(value)
}
