// SPDX-License-Identifier: BSD-3-Clause

package render

import (
	"bytes"
	"fmt"
	"net/netip"
	"sort"
	"strconv"
	"strings"

	"github.com/imksoo/routerd/pkg/api"
)

func PF(router *api.Router, holes []FirewallHole) ([]byte, error) {
	aliases, err := nftOutboundAliases(router)
	if err != nil {
		return nil, err
	}
	var nat44Rules []api.Resource
	var zones []api.Resource
	var policies []api.Resource
	var logs []api.Resource
	var rules []api.Resource
	var clientPolicies []api.Resource
	var egressPolicies []api.Resource
	var ingressRules []ingressNATRule
	mssPolicies, err := pathMTUMSSPolicies(router)
	if err != nil {
		return nil, err
	}
	for _, res := range router.Spec.Resources {
		switch res.Kind {
		case "NAT44Rule":
			nat44Rules = append(nat44Rules, res)
		case "FirewallZone":
			if res.APIVersion == api.FirewallAPIVersion {
				zones = append(zones, res)
			}
		case "FirewallPolicy":
			if res.APIVersion == api.FirewallAPIVersion {
				policies = append(policies, res)
			}
		case "FirewallEventLog":
			if res.APIVersion == api.FirewallAPIVersion {
				logs = append(logs, res)
			}
		case "FirewallRule":
			if res.APIVersion == api.FirewallAPIVersion {
				rules = append(rules, res)
			}
		case "ClientPolicy":
			if res.APIVersion == api.FirewallAPIVersion {
				clientPolicies = append(clientPolicies, res)
			}
		case "EgressRoutePolicy":
			if res.APIVersion == api.NetAPIVersion {
				egressPolicies = append(egressPolicies, res)
			}
		}
	}
	ingressRules, err = ingressNATRules(router, aliases)
	if err != nil {
		return nil, err
	}
	if len(nat44Rules) == 0 && len(ingressRules) == 0 && len(zones) == 0 && len(rules) == 0 && len(holes) == 0 && len(mssPolicies) == 0 && len(egressPolicies) == 0 {
		return nil, nil
	}
	sort.Slice(nat44Rules, func(i, j int) bool { return nat44Rules[i].Metadata.Name < nat44Rules[j].Metadata.Name })
	sort.Slice(zones, func(i, j int) bool { return zones[i].Metadata.Name < zones[j].Metadata.Name })
	sort.Slice(policies, func(i, j int) bool { return policies[i].Metadata.Name < policies[j].Metadata.Name })
	sort.Slice(logs, func(i, j int) bool { return logs[i].Metadata.Name < logs[j].Metadata.Name })
	sort.Slice(rules, func(i, j int) bool { return rules[i].Metadata.Name < rules[j].Metadata.Name })
	sort.Slice(clientPolicies, func(i, j int) bool { return clientPolicies[i].Metadata.Name < clientPolicies[j].Metadata.Name })
	sort.Slice(egressPolicies, func(i, j int) bool { return egressPolicies[i].Metadata.Name < egressPolicies[j].Metadata.Name })

	zoneMap, err := nftFirewallZones(aliases, zones)
	if err != nil {
		return nil, err
	}
	pfClientPolicies, err := pfClientPolicies(router, aliases, clientPolicies)
	if err != nil {
		return nil, err
	}
	policy := firewallPolicyOptions(policies)
	logging := firewallLogOptions(logs)
	routeToRules, err := pfEgressRouteToRules(egressPolicies, aliases)
	if err != nil {
		return nil, err
	}

	var buf bytes.Buffer
	buf.WriteString("# Generated by routerd. Do not edit by hand.\n")
	buf.WriteString("set skip on lo0\n")
	for _, zone := range sortedFirewallZones(zoneMap) {
		if len(zone.IfNames) == 0 {
			continue
		}
		buf.WriteString(pfZoneMacro(zone) + " = " + pfInterfaceSet(zone.IfNames) + "\n")
	}
	if err := writePFMSSClamp(&buf, aliases, mssPolicies); err != nil {
		return nil, err
	}
	if hasRuntimeResolvedNAT44(nat44Rules) {
		buf.WriteString("nat-anchor \"routerd_nat\"\n")
	}
	if err := writePFIngress(&buf, ingressRules); err != nil {
		return nil, err
	}
	if err := writePFNAT(&buf, router, aliases, nat44Rules); err != nil {
		return nil, err
	}
	filterRequested := len(zoneMap) > 0 || len(rules) > 0 || len(holes) > 0 || len(logs) > 0 || len(clientPolicies) > 0
	if len(routeToRules) > 0 && (len(rules) > 0 || len(holes) > 0 || len(logs) > 0 || len(clientPolicies) > 0) {
		return nil, fmt.Errorf("FreeBSD EgressRoutePolicy hash route-to cannot coexist with explicit routerd firewall rules, holes, logs, or ClientPolicy")
	}
	if filterRequested {
		if err := writePFFilter(&buf, zoneMap, rules, holes, pfClientPolicies, policy, logging, routeToRules, pfRouterInterfaceAddressSet(aliases)); err != nil {
			return nil, err
		}
	} else {
		for _, rule := range routeToRules {
			buf.WriteString(rule.render("") + "\n")
		}
		buf.WriteString("pass all keep state\n")
	}
	return buf.Bytes(), nil
}

// pfEgressRouteToRules renders the deliberately narrow FreeBSD policy-route
// slice. FreeBSD 14.3 pf permits a multi-routehost route-to pool only with
// round-robin; sticky-address gives per-source affinity but is not Linux
// jhash parity. Every unsupported shape is rejected instead of degraded.
type pfEgressRouteToRule struct {
	name        string
	hosts       []string
	family      string
	source      string
	destination string
}

func (rule pfEgressRouteToRule) render(onExpr string) string {
	on := ""
	if onExpr != "" {
		on = " on " + onExpr
	}
	return "pass in quick" + on + " route-to { " + strings.Join(rule.hosts, ", ") + " } round-robin sticky-address " + rule.family + " from " + rule.source + " to " + rule.destination + " keep state label " + pfQuote("routerd:egress-route:"+rule.name)
}

func pfEgressRouteToRules(resources []api.Resource, aliases map[string]string) ([]pfEgressRouteToRule, error) {
	var rules []pfEgressRouteToRule
	for _, res := range resources {
		spec, err := res.EgressRoutePolicySpec()
		if err != nil {
			return nil, err
		}
		if spec.Mode != "hash" {
			continue
		}
		if len(spec.HashFields) != 1 || spec.HashFields[0] != "sourceAddress" {
			return nil, fmt.Errorf("%s FreeBSD route-to requires hashFields: [sourceAddress]", res.ID())
		}
		if len(spec.SourceCIDRs) == 0 {
			return nil, fmt.Errorf("%s FreeBSD route-to requires sourceCIDRs", res.ID())
		}
		if len(spec.DestinationSetRefs) != 0 || len(spec.ExcludeDestinationSetRefs) != 0 {
			return nil, fmt.Errorf("%s FreeBSD route-to does not support destination address-set references", res.ID())
		}
		if len(spec.ExcludeDestinationCIDRs) > 1 {
			return nil, fmt.Errorf("%s FreeBSD route-to supports at most one excluded destination CIDR", res.ID())
		}
		if len(spec.DestinationCIDRs) != 0 && len(spec.ExcludeDestinationCIDRs) != 0 {
			return nil, fmt.Errorf("%s FreeBSD route-to does not support combined destinationCIDRs and excludeDestinationCIDRs", res.ID())
		}
		if spec.Selection != "" || spec.Hysteresis != "" {
			return nil, fmt.Errorf("%s FreeBSD route-to does not support selection or hysteresis", res.ID())
		}
		if len(spec.Candidates) != 1 {
			return nil, fmt.Errorf("%s FreeBSD route-to requires exactly one candidate with static targets", res.ID())
		}
		candidate := spec.Candidates[0]
		if !api.BoolDefault(candidate.Enabled, true) || candidate.Source != "" || candidate.EffectiveInterface() != "" || candidate.DeviceFrom.Resource != "" || candidate.Gateway != "" || candidate.GatewayFrom.Resource != "" || candidate.GatewaySource != "" || candidate.EffectiveTable() != 0 || candidate.Priority != 0 || candidate.Mark != 0 || candidate.EffectiveMetric() != 0 || candidate.Weight != 0 || candidate.HealthCheck != "" || len(candidate.DependsOn) != 0 || len(candidate.ReadyWhen) != 0 || len(candidate.When.State) != 0 || len(candidate.When.All) != 0 || len(candidate.When.Any) != 0 {
			return nil, fmt.Errorf("%s FreeBSD route-to candidate contains unsupported direct or dynamic fields", res.ID())
		}
		if len(candidate.Targets) < 2 {
			return nil, fmt.Errorf("%s FreeBSD route-to requires at least two targets", res.ID())
		}
		family := defaultString(spec.Family, "ipv4")
		if family != "ipv4" {
			return nil, fmt.Errorf("%s FreeBSD route-to supports only family ipv4", res.ID())
		}
		source, err := pfAddressSetForFamily(res.ID(), "source", spec.SourceCIDRs, false)
		if err != nil {
			return nil, err
		}
		destination, err := pfAddressSetForFamily(res.ID(), "destination", spec.DestinationCIDRs, false)
		if err != nil {
			return nil, err
		}
		exclude, err := pfAddressSetForFamily(res.ID(), "excluded destination", spec.ExcludeDestinationCIDRs, false)
		if err != nil {
			return nil, err
		}
		if exclude != "" {
			destination = "! " + exclude
		}
		if destination == "" {
			destination = "any"
		}
		hosts := make([]string, 0, len(candidate.Targets))
		for _, target := range candidate.Targets {
			if target.Interface != "" && target.OutboundInterface != "" {
				return nil, fmt.Errorf("%s FreeBSD route-to target %q must not set both interface and outboundInterface", res.ID(), target.Name)
			}
			if target.HealthCheck != "" || target.GatewayFrom != (api.StatusValueSourceSpec{}) || target.GatewaySource != "static" || target.EffectiveTable() != 0 || target.Priority != 0 || target.Mark != 0 || target.EffectiveMetric() != 0 {
				return nil, fmt.Errorf("%s FreeBSD route-to target %q requires a static gateway without healthCheck", res.ID(), target.Name)
			}
			ifname := aliases[target.EffectiveInterface()]
			if ifname == "" {
				return nil, fmt.Errorf("%s FreeBSD route-to target %q has an unresolved interface", res.ID(), target.Name)
			}
			gateway, err := netip.ParseAddr(target.Gateway)
			if err != nil || !gateway.Is4() {
				return nil, fmt.Errorf("%s FreeBSD route-to target %q requires an ipv4 static gateway", res.ID(), target.Name)
			}
			hosts = append(hosts, "("+ifname+" "+gateway.String()+")")
		}
		sort.Strings(hosts)
		hosts = compactStrings(hosts)
		if len(hosts) < 2 {
			return nil, fmt.Errorf("%s FreeBSD route-to requires two distinct static routehosts", res.ID())
		}
		rules = append(rules, pfEgressRouteToRule{name: res.Metadata.Name, hosts: hosts, family: "inet", source: source, destination: destination})
	}
	return rules, nil
}

func hasRuntimeResolvedNAT44(resources []api.Resource) bool {
	for _, res := range resources {
		spec, err := res.NAT44RuleSpec()
		if err == nil && spec.EgressInterface == "" && spec.EgressPolicyRef != "" {
			return true
		}
	}
	return false
}

func writePFIngress(buf *bytes.Buffer, rules []ingressNATRule) error {
	for _, rule := range rules {
		if rule.ListenInterface == "" {
			return fmt.Errorf("%s references listen interface with empty ifname", rule.ResourceID)
		}
		destination := "any"
		if rule.ListenAddress != "" {
			destination = rule.ListenAddress
		}
		buf.WriteString("rdr pass on " + rule.ListenInterface + " inet proto " + rule.Protocol + " from any to " + destination + " port " + strconv.Itoa(rule.ListenPort) + " -> " + rule.TargetAddress + " port " + strconv.Itoa(rule.TargetPort) + "\n")
		for _, ifname := range rule.HairpinInterfaces {
			buf.WriteString("rdr pass on " + ifname + " inet proto " + rule.Protocol + " from any to " + rule.ListenAddress + " port " + strconv.Itoa(rule.ListenPort) + " -> " + rule.TargetAddress + " port " + strconv.Itoa(rule.TargetPort) + "\n")
			buf.WriteString("nat on " + ifname + " inet proto " + rule.Protocol + " from (" + ifname + ":network) to " + rule.TargetAddress + " port " + strconv.Itoa(rule.TargetPort) + " -> (" + ifname + ")\n")
		}
	}
	return nil
}

func writePFMSSClamp(buf *bytes.Buffer, aliases map[string]string, policies []pathMTUPolicy) error {
	for _, policy := range policies {
		if !pathMTUFamilyEnabled(policy.Spec.TCPMSSClamp.Families, "ipv4") {
			continue
		}
		fromIfname := aliases[policy.Spec.FromInterface]
		if fromIfname == "" {
			return fmt.Errorf("%s references fromInterface with empty ifname", policy.ResourceID)
		}
		mss := policy.MTU - 40
		if mss < 536 {
			return fmt.Errorf("%s computed IPv4 MSS %d is too small", policy.ResourceID, mss)
		}
		var toIfnames []string
		for _, name := range policy.Spec.ToInterfaces {
			ifname := aliases[name]
			if ifname == "" {
				return fmt.Errorf("%s references toInterface with empty ifname %q", policy.ResourceID, name)
			}
			toIfnames = append(toIfnames, ifname)
		}
		sort.Strings(toIfnames)
		for _, ifname := range compactStrings(toIfnames) {
			buf.WriteString("scrub out on " + ifname + " proto tcp max-mss " + strconv.Itoa(mss) + "\n")
		}
	}
	return nil
}

func writePFNAT(buf *bytes.Buffer, router *api.Router, aliases map[string]string, nat44Rules []api.Resource) error {
	for _, res := range nat44Rules {
		spec, err := res.NAT44RuleSpec()
		if err != nil {
			return err
		}
		if spec.OutboundInterface != "" || len(spec.SourceCIDRs) > 0 || spec.Translation.Type != "" {
			ifname := aliases[spec.OutboundInterface]
			if ifname == "" {
				return fmt.Errorf("%s references outbound interface with empty ifname", res.ID())
			}
			for _, cidr := range spec.SourceCIDRs {
				prefix, err := netip.ParsePrefix(cidr)
				if err != nil || !prefix.Addr().Is4() {
					return fmt.Errorf("%s has invalid IPv4 source CIDR %q", res.ID(), cidr)
				}
				target, err := pfNATTarget(spec.Translation, ifname)
				if err != nil {
					return fmt.Errorf("%s: %w", res.ID(), err)
				}
				buf.WriteString("nat on " + ifname + " from " + prefix.Masked().String() + " to any -> " + target + "\n")
			}
			continue
		}
		if spec.EgressInterface == "" {
			if spec.EgressPolicyRef != "" {
				buf.WriteString("# " + res.ID() + " skipped: egressInterface is resolved by " + spec.EgressPolicyRef + " at runtime\n")
				continue
			}
			return fmt.Errorf("%s needs resolved egressInterface for static pf render", res.ID())
		}
		ifname := aliases[spec.EgressInterface]
		if ifname == "" {
			return fmt.Errorf("%s references egress interface with empty ifname", res.ID())
		}
		for _, cidr := range spec.SourceRanges {
			prefix, err := netip.ParsePrefix(cidr)
			if err != nil || !prefix.Addr().Is4() {
				return fmt.Errorf("%s has invalid IPv4 source range %q", res.ID(), cidr)
			}
			excludedDestinations, err := pfIPv4AddressSet(res.ID(), "excluded destination", spec.ExcludeDestinationCIDRs)
			if err != nil {
				return err
			}
			if excludedDestinations != "" {
				buf.WriteString("no nat on " + ifname + " from " + prefix.Masked().String() + " to " + excludedDestinations + "\n")
			}
			destinations, err := pfNATDestinationMatches(res.ID(), spec.DestinationCIDRs)
			if err != nil {
				return err
			}
			target := "(" + ifname + ")"
			if spec.Type == "snat" {
				snatAddress := spec.SNATAddress
				if snatAddress == "" && spec.SNATAddressFrom.Resource != "" {
					var err error
					snatAddress, err = renderAddressFromResource(router, spec.SNATAddressFrom)
					if err != nil {
						return fmt.Errorf("%s spec.snatAddressFrom: %w", res.ID(), err)
					}
				}
				if snatAddress == "" {
					return fmt.Errorf("%s needs snat address", res.ID())
				}
				target = snatAddress
			}
			for _, destination := range destinations {
				buf.WriteString("nat on " + ifname + " from " + prefix.Masked().String() + " to " + destination + " -> " + target + "\n")
			}
		}
	}
	return nil
}

func PFNAT44Rules(rules []NAT44RenderRule) ([]byte, error) {
	rules = append([]NAT44RenderRule(nil), rules...)
	sort.Slice(rules, func(i, j int) bool { return rules[i].Name < rules[j].Name })
	var buf bytes.Buffer
	buf.WriteString("# Generated by routerd. Do not edit by hand.\n")
	for _, rule := range rules {
		if err := writePFNAT44RenderRule(&buf, rule); err != nil {
			return nil, err
		}
	}
	return buf.Bytes(), nil
}

func writePFNAT44RenderRule(buf *bytes.Buffer, rule NAT44RenderRule) error {
	if rule.EgressInterface == "" {
		return fmt.Errorf("%s needs egress interface", rule.Name)
	}
	for _, cidr := range rule.SourceRanges {
		prefix, err := netip.ParsePrefix(cidr)
		if err != nil || !prefix.Addr().Is4() {
			return fmt.Errorf("%s has invalid IPv4 source range %q", rule.Name, cidr)
		}
		excludedDestinations, err := pfIPv4AddressSet(rule.Name, "excluded destination", rule.ExcludeDestinationCIDRs)
		if err != nil {
			return err
		}
		if excludedDestinations != "" {
			buf.WriteString("no nat on " + rule.EgressInterface + " from " + prefix.Masked().String() + " to " + excludedDestinations + "\n")
		}
		destinations, err := pfNATDestinationMatches(rule.Name, rule.DestinationCIDRs)
		if err != nil {
			return err
		}
		target := "(" + rule.EgressInterface + ")"
		if rule.Type == "snat" {
			if rule.SNATAddress == "" {
				return fmt.Errorf("%s needs snat address", rule.Name)
			}
			target = rule.SNATAddress
		}
		for _, destination := range destinations {
			buf.WriteString("nat on " + rule.EgressInterface + " from " + prefix.Masked().String() + " to " + destination + " -> " + target + "\n")
		}
	}
	return nil
}

func pfNATDestinationMatches(resourceID string, destinationCIDRs []string) ([]string, error) {
	if len(destinationCIDRs) > 0 {
		var out []string
		for _, cidr := range destinationCIDRs {
			prefix, err := netip.ParsePrefix(cidr)
			if err != nil || !prefix.Addr().Is4() {
				return nil, fmt.Errorf("%s has invalid IPv4 destination CIDR %q", resourceID, cidr)
			}
			out = append(out, prefix.Masked().String())
		}
		return out, nil
	}
	return []string{"any"}, nil
}

func pfIPv4AddressSet(resourceID, label string, cidrs []string) (string, error) {
	return pfAddressSetForFamily(resourceID, label, cidrs, false)
}

func pfAddressSetForFamily(resourceID, label string, cidrs []string, wantIPv6 bool) (string, error) {
	if len(cidrs) == 0 {
		return "", nil
	}
	var values []string
	for _, cidr := range cidrs {
		prefix, err := netip.ParsePrefix(cidr)
		if err != nil || prefix.Addr().Is6() != wantIPv6 {
			family := "IPv4"
			if wantIPv6 {
				family = "IPv6"
			}
			return "", fmt.Errorf("%s has invalid %s %s CIDR %q", resourceID, family, label, cidr)
		}
		values = append(values, prefix.Masked().String())
	}
	sort.Strings(values)
	if len(values) == 1 {
		return values[0], nil
	}
	return "{ " + strings.Join(values, ", ") + " }", nil
}

type pfClientPolicy struct {
	Name            string
	Mode            string
	IfNames         []string
	IPv4Addresses   []string
	IPv6Addresses   []string
	GuestServices   []string
	IPv4EgressDeny  []string
	IPv6EgressDeny  []string
	IPv4EgressAllow []string
	IPv6EgressAllow []string
}

func pfClientPolicies(router *api.Router, aliases map[string]string, resources []api.Resource) ([]pfClientPolicy, error) {
	reservations := map[string]api.DHCPv4ReservationSpec{}
	for _, res := range router.Spec.Resources {
		if res.APIVersion != api.NetAPIVersion || res.Kind != "DHCPv4Reservation" {
			continue
		}
		spec, err := res.DHCPv4ReservationSpec()
		if err != nil {
			return nil, err
		}
		reservations["DHCPv4Reservation/"+res.Metadata.Name] = spec
		reservations[res.Metadata.Name] = spec
	}
	var out []pfClientPolicy
	for _, res := range resources {
		spec, err := res.ClientPolicySpec()
		if err != nil {
			return nil, err
		}
		if err := validatePFClientPolicyIdentity(res, spec); err != nil {
			return nil, err
		}
		var ifnames []string
		for _, iface := range spec.Interfaces {
			ref := iface
			if kind, name, ok := strings.Cut(iface, "/"); ok {
				if kind != "Interface" {
					return nil, fmt.Errorf("%s references unsupported client policy interface %q", res.ID(), iface)
				}
				ref = name
			}
			ifname := aliases[ref]
			if ifname == "" {
				return nil, fmt.Errorf("%s references interface with empty ifname %q", res.ID(), iface)
			}
			ifnames = append(ifnames, ifname)
		}
		sort.Strings(ifnames)
		egressDeny := clientPolicyEgressCIDRs(spec.GuestEgressDeny, []string{"10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16", "fc00::/7"})
		egressAllow := clientPolicyEgressCIDRs(spec.GuestEgressAllow, nil)
		policy := pfClientPolicy{
			Name:            res.Metadata.Name,
			Mode:            spec.Mode,
			IfNames:         compactStrings(ifnames),
			GuestServices:   clientPolicyGuestServices(spec.GuestServices),
			IPv4EgressDeny:  pfClientPolicyCIDRs(egressDeny, false),
			IPv6EgressDeny:  pfClientPolicyCIDRs(egressDeny, true),
			IPv4EgressAllow: pfClientPolicyCIDRs(egressAllow, false),
			IPv6EgressAllow: pfClientPolicyCIDRs(egressAllow, true),
		}
		for _, entry := range spec.Classification {
			if entry.IPv4Reservation == "" && len(entry.IPv6Addresses) == 0 && spec.Mode == "include" && (entry.Mode == "guest" || entry.Mode == "isolated") {
				return nil, fmt.Errorf("%s classification %q needs ipv4Reservation or ipv6Addresses on FreeBSD because pf cannot match client selectors", res.ID(), entry.Name)
			}
			switch spec.Mode {
			case "include":
				if entry.Mode == "guest" || entry.Mode == "isolated" {
					if entry.IPv4Reservation != "" {
						reservation, err := pfClientPolicyReservation(res, entry.IPv4Reservation, reservations)
						if err != nil {
							return nil, err
						}
						policy.IPv4Addresses = append(policy.IPv4Addresses, reservation.IPAddress)
					}
					policy.IPv6Addresses = append(policy.IPv6Addresses, entry.IPv6Addresses...)
				}
			case "exclude":
				if entry.Mode == "trusted" {
					if entry.IPv4Reservation != "" {
						reservation, err := pfClientPolicyReservation(res, entry.IPv4Reservation, reservations)
						if err != nil {
							return nil, err
						}
						policy.IPv4Addresses = append(policy.IPv4Addresses, reservation.IPAddress)
					}
					policy.IPv6Addresses = append(policy.IPv6Addresses, entry.IPv6Addresses...)
				}
			default:
				return nil, fmt.Errorf("%s has unsupported client policy mode %q", res.ID(), spec.Mode)
			}
		}
		policy.IPv4Addresses = pfCompactAddresses(policy.IPv4Addresses)
		policy.IPv6Addresses = pfCompactAddresses(policy.IPv6Addresses)
		out = append(out, policy)
	}
	return out, nil
}

func validatePFClientPolicyIdentity(res api.Resource, spec api.ClientPolicySpec) error {
	if len(spec.MACs) > 0 {
		return fmt.Errorf("%s spec.macs is not supported on FreeBSD because pf cannot enforce MAC/L2 identity; use explicit classification IP identities", res.ID())
	}
	for _, entry := range spec.Classification {
		hasSelector := len(entry.Match.MACs) > 0 || len(entry.Match.OUIPrefixes) > 0 || len(entry.Match.HostnamePatterns) > 0 || len(entry.Match.DHCPFingerprints) > 0
		if hasSelector {
			return fmt.Errorf("%s classification %q uses client selectors that FreeBSD pf cannot enforce; use ipv4Reservation and/or explicit ipv6Addresses without match selectors", res.ID(), entry.Name)
		}
		if entry.IPv4Reservation == "" && len(entry.IPv6Addresses) == 0 {
			return fmt.Errorf("%s classification %q needs ipv4Reservation or explicit ipv6Addresses on FreeBSD", res.ID(), entry.Name)
		}
	}
	return nil
}

func pfClientPolicyReservation(res api.Resource, name string, reservations map[string]api.DHCPv4ReservationSpec) (api.DHCPv4ReservationSpec, error) {
	reservation, ok := reservations[name]
	if !ok {
		return api.DHCPv4ReservationSpec{}, fmt.Errorf("%s references unknown DHCPv4 reservation %q", res.ID(), name)
	}
	if reservation.IPAddress == "" {
		return api.DHCPv4ReservationSpec{}, fmt.Errorf("%s references DHCPv4 reservation %q with empty ipAddress", res.ID(), name)
	}
	return reservation, nil
}

func writePFFilter(buf *bytes.Buffer, zones map[string]firewallZone, rules []api.Resource, holes []FirewallHole, clientPolicies []pfClientPolicy, policy firewallPolicy, logging firewallLogging, routeToRules []pfEgressRouteToRule, allLocal string) error {
	buf.WriteString("block drop all\n")
	buf.WriteString("pass quick on lo0 all\n")
	buf.WriteString("pass out quick all keep state\n")
	for _, zone := range sortedFirewallZones(zones) {
		for _, clientPolicy := range clientPolicies {
			for _, expr := range pfClientPolicyIPv6DenyExprs(zone, clientPolicy, logging) {
				buf.WriteString(expr + "\n")
			}
		}
	}
	for _, zone := range sortedFirewallZones(zones) {
		if len(zone.IfNames) == 0 {
			continue
		}
		// Keep neighbor discovery and router discovery local to the ingress
		// link. A global ICMPv6 quick pass would otherwise bypass zone policy
		// and route-to for routed IPv6 traffic.
		buf.WriteString(pfIPv6ControlExpr(zone) + "\n")
	}
	for _, zone := range sortedFirewallZones(zones) {
		if len(zone.IfNames) == 0 {
			continue
		}
		selfAccepted := implicitFirewallAction(zone.Role, "self", policy) == "accept"
		if selfAccepted {
			buf.WriteString("pass in quick on $" + pfZoneMacro(zone) + " to " + pfZoneSelfExpr(zone) + " keep state\n")
		}
		for _, hole := range holes {
			if hole.FromZone == zone.Name && hole.ToZone == "self" {
				if selfAccepted {
					continue
				}
				for _, expr := range pfFirewallHoleExprs(zone, hole, logging) {
					buf.WriteString(expr + "\n")
				}
			}
		}
		for _, res := range rules {
			spec, err := res.FirewallRuleSpec()
			if err != nil {
				return err
			}
			if spec.FromZone == zone.Name && spec.ToZone == "self" {
				buf.WriteString(pfFirewallRuleExpr(zone, res.Metadata.Name, spec, logging) + "\n")
			}
		}
		for _, clientPolicy := range clientPolicies {
			for _, expr := range pfClientPolicyInputExprs(zone, clientPolicy, logging) {
				buf.WriteString(expr + "\n")
			}
		}
	}
	routeToEmitted := false
	for _, from := range sortedFirewallZones(zones) {
		if len(from.IfNames) == 0 {
			continue
		}
		for _, clientPolicy := range clientPolicies {
			for _, expr := range pfClientPolicyForwardExprs(from, clientPolicy, logging) {
				buf.WriteString(expr + "\n")
			}
		}
		if err := writePFDisallowedForwardDestinations(buf, from, zones, policy); err != nil {
			return err
		}
		accepted := pfImplicitForwardDestinations(from, zones, policy)
		if len(routeToRules) > 0 {
			if len(accepted) == 0 {
				continue
			}
			if implicitFirewallAction(from.Role, "self", policy) == "accept" {
				// Protect every router-owned interface address, including another
				// zone or a routehost interface absent from zoneMap, before the
				// route-to pass can be evaluated.
				buf.WriteString("pass in quick on $" + pfZoneMacro(from) + " to " + allLocal + " keep state label " + pfQuote("routerd:"+from.Name+":route-to-self") + "\n")
			} else {
				buf.WriteString("block drop in quick on $" + pfZoneMacro(from) + " to " + allLocal + " label " + pfQuote("routerd:"+from.Name+":route-to-self-deny") + "\n")
			}
			if internal := pfForwardDestinationNetworkSet(accepted); internal != "" {
				// These pass rules are no broader than the broad forward passes
				// emitted below, but prevent route-to from steering connected
				// zone traffic toward an external routehost.
				buf.WriteString("pass in quick on $" + pfZoneMacro(from) + " to " + internal + " keep state label " + pfQuote("routerd:"+from.Name+":route-to-connected") + "\n")
			}
			for _, routeTo := range routeToRules {
				buf.WriteString(routeTo.render("$"+pfZoneMacro(from)) + "\n")
			}
			routeToEmitted = true
		}
		for _, to := range accepted {
			logExpr := ""
			if logging.Enabled && logging.AcceptSampleRate > 0 {
				logExpr = " log"
			}
			buf.WriteString("pass in" + logExpr + " quick on $" + pfZoneMacro(from) + " keep state label " + pfQuote("routerd:"+from.Name+"-to-"+to.Name) + "\n")
		}
		for _, hole := range holes {
			if hole.FromZone == from.Name && hole.ToZone != "self" {
				for _, expr := range pfFirewallHoleExprs(from, hole, logging) {
					buf.WriteString(expr + "\n")
				}
			}
		}
		for _, res := range rules {
			spec, err := res.FirewallRuleSpec()
			if err != nil {
				return err
			}
			if spec.FromZone == from.Name && spec.ToZone != "self" {
				buf.WriteString(pfFirewallRuleExpr(from, res.Metadata.Name, spec, logging) + "\n")
			}
		}
	}
	if len(routeToRules) > 0 && !routeToEmitted {
		return fmt.Errorf("FreeBSD EgressRoutePolicy hash route-to cannot coexist with filtering without a broad accepted forward path")
	}
	return nil
}

func pfRouterInterfaceAddressSet(aliases map[string]string) string {
	values := make([]string, 0, len(aliases))
	for _, ifname := range aliases {
		if ifname != "" {
			values = append(values, "("+ifname+")")
		}
	}
	sort.Strings(values)
	values = compactStrings(values)
	return pfAddressSet(values)
}

func pfImplicitForwardDestinations(from firewallZone, zones map[string]firewallZone, policy firewallPolicy) []firewallZone {
	var accepted []firewallZone
	for _, to := range sortedFirewallZones(zones) {
		if implicitFirewallAction(from.Role, to.Role, policy) != "accept" {
			continue
		}
		if from.Name == to.Name && !policy.SameRoleAccept {
			continue
		}
		if !pfCanRenderBroadForwardPass(from, to) {
			continue
		}
		accepted = append(accepted, to)
	}
	return accepted
}

func pfForwardDestinationNetworkSet(zones []firewallZone) string {
	var values []string
	for _, zone := range zones {
		for _, ifname := range zone.IfNames {
			values = append(values, "("+ifname+":network)")
		}
	}
	sort.Strings(values)
	values = compactStrings(values)
	if len(values) == 0 {
		return ""
	}
	if len(values) == 1 {
		return values[0]
	}
	return "{ " + strings.Join(values, ", ") + " }"
}

func writePFDisallowedForwardDestinations(buf *bytes.Buffer, from firewallZone, zones map[string]firewallZone, policy firewallPolicy) error {
	for _, to := range sortedFirewallZones(zones) {
		if len(to.IfNames) == 0 || implicitFirewallAction(from.Role, to.Role, policy) != "drop" {
			continue
		}
		for _, ifname := range to.IfNames {
			buf.WriteString("block drop in quick on $" + pfZoneMacro(from) + " to (" + ifname + ":network) label " + pfQuote("routerd:"+from.Name+"-to-"+to.Name+"-deny") + "\n")
		}
	}
	return nil
}

func pfIPv6ControlExpr(zone firewallZone) string {
	values := make([]string, 0, len(zone.IfNames)+3)
	for _, ifname := range zone.IfNames {
		values = append(values, "("+ifname+")")
	}
	values = append(values, "ff02::1", "ff02::2", "ff02::1:ff00:0/104")
	return "pass in quick on $" + pfZoneMacro(zone) + " inet6 proto icmp6 to " + pfAddressSet(values) + " icmp6-type { routersol, routeradv, neighbrsol, neighbradv } keep state label " + pfQuote("routerd:"+zone.Name+":ipv6-control")
}

func pfClientPolicyInputExprs(zone firewallZone, policy pfClientPolicy, logging firewallLogging) []string {
	if len(policy.IPv4Addresses) == 0 || !pfClientPolicyAppliesToZone(zone, policy) {
		return nil
	}
	match := pfClientPolicySourceMatch(policy.Mode, policy.IPv4Addresses)
	if match == "" {
		return nil
	}
	var exprs []string
	for _, ifname := range policy.IfNames {
		onExpr := ifname
		selfExpr := "(" + ifname + ")"
		if stringInSlice("dns", policy.GuestServices) {
			exprs = append(exprs, pfClientPolicyServiceExpr(onExpr, selfExpr, policy.Name, match, "udp", 53, "dns", logging))
			exprs = append(exprs, pfClientPolicyServiceExpr(onExpr, selfExpr, policy.Name, match, "tcp", 53, "dns", logging))
		}
		if stringInSlice("dhcp", policy.GuestServices) {
			exprs = append(exprs, pfClientPolicyServiceExpr(onExpr, selfExpr, policy.Name, match, "udp", 67, "dhcp", logging))
		}
		if stringInSlice("ntp", policy.GuestServices) {
			exprs = append(exprs, pfClientPolicyServiceExpr(onExpr, selfExpr, policy.Name, match, "udp", 123, "ntp", logging))
		}
		if stringInSlice("mdns", policy.GuestServices) {
			exprs = append(exprs, pfClientPolicyServiceExpr(onExpr, selfExpr, policy.Name, match, "udp", 5353, "mdns", logging))
		}
		if stringInSlice("ssdp", policy.GuestServices) {
			exprs = append(exprs, pfClientPolicyServiceExpr(onExpr, selfExpr, policy.Name, match, "udp", 1900, "ssdp", logging))
		}
		exprs = append(exprs, "block drop in "+pfLogExpr(logging)+" quick on "+onExpr+" from "+match+" to "+selfExpr+" label "+pfQuote("routerd:client-policy:"+policy.Name+":self-deny"))
	}
	return exprs
}

func pfClientPolicyForwardExprs(zone firewallZone, policy pfClientPolicy, logging firewallLogging) []string {
	var exprs []string
	exprs = append(exprs, pfClientPolicyForwardFamilyExprs(zone, policy, false, policy.IPv4Addresses, policy.IPv4EgressAllow, policy.IPv4EgressDeny, logging)...)
	exprs = append(exprs, pfClientPolicyForwardFamilyExprs(zone, policy, true, policy.IPv6Addresses, policy.IPv6EgressAllow, nil, logging)...)
	return exprs
}

func pfClientPolicyIPv6DenyExprs(zone firewallZone, policy pfClientPolicy, logging firewallLogging) []string {
	return pfClientPolicyForwardFamilyExprs(zone, policy, true, policy.IPv6Addresses, nil, policy.IPv6EgressDeny, logging)
}

func pfClientPolicyForwardFamilyExprs(zone firewallZone, policy pfClientPolicy, ipv6 bool, addresses, allow, deny []string, logging firewallLogging) []string {
	if len(addresses) == 0 || !pfClientPolicyAppliesToZone(zone, policy) {
		return nil
	}
	match := pfClientPolicySourceMatch(policy.Mode, addresses)
	if match == "" {
		return nil
	}
	family := ""
	if ipv6 {
		family = " inet6"
	}
	var exprs []string
	for _, ifname := range policy.IfNames {
		for _, cidr := range allow {
			exprs = append(exprs, "pass in quick on "+ifname+family+" from "+match+" to "+cidr+" keep state label "+pfQuote("routerd:client-policy:"+policy.Name+":allow"))
		}
		for _, cidr := range deny {
			exprs = append(exprs, "block drop in "+pfLogExpr(logging)+" quick on "+ifname+family+" from "+match+" to "+cidr+" label "+pfQuote("routerd:client-policy:"+policy.Name+":deny"))
		}
	}
	return exprs
}

func pfClientPolicyAppliesToZone(zone firewallZone, policy pfClientPolicy) bool {
	for _, zoneIfname := range zone.IfNames {
		if stringInSlice(zoneIfname, policy.IfNames) {
			return true
		}
	}
	return false
}

func pfClientPolicySourceMatch(mode string, values []string) string {
	addresses := append([]string(nil), values...)
	sort.Strings(addresses)
	if mode == "exclude" {
		if len(addresses) == 0 {
			return "any"
		}
		return "! " + pfAddressSet(addresses)
	}
	if len(addresses) == 0 {
		return ""
	}
	return pfAddressSet(addresses)
}

func pfAddressSet(values []string) string {
	if len(values) == 1 {
		return values[0]
	}
	return "{ " + strings.Join(values, ", ") + " }"
}

func pfClientPolicyCIDRs(values []string, ipv6 bool) []string {
	out := make([]string, 0, len(values))
	for _, value := range values {
		isIPv6 := strings.Contains(value, ":")
		if isIPv6 != ipv6 {
			continue
		}
		out = append(out, value)
	}
	return out
}

func pfCompactAddresses(values []string) []string {
	sort.Strings(values)
	return compactStrings(values)
}

func pfClientPolicyServiceExpr(onExpr, selfExpr, name, source, proto string, port int, service string, logging firewallLogging) string {
	return "pass in quick on " + onExpr + " proto " + proto + " from " + source + " to " + selfExpr + " port " + strconv.Itoa(port) + " keep state label " + pfQuote("routerd:client-policy:"+name+":"+service)
}

func pfCanRenderBroadForwardPass(from, to firewallZone) bool {
	if from.Role == "untrust" && to.Role == "untrust" {
		return false
	}
	return true
}

func pfNATTarget(spec api.IPv4NATTranslationSpec, ifname string) (string, error) {
	switch spec.Type {
	case "interfaceAddress":
		return "(" + ifname + ")", nil
	case "address":
		if spec.Address == "" {
			return "", fmt.Errorf("address translation needs address")
		}
		return spec.Address, nil
	default:
		return "", fmt.Errorf("unsupported pf NAT translation type %q", spec.Type)
	}
}

func pfFirewallRuleExpr(zone firewallZone, name string, spec api.FirewallRuleSpec, logging firewallLogging) string {
	return pfFirewallRuleExprOnSelf("$"+pfZoneMacro(zone), pfZoneSelfExpr(zone), name, spec, logging)
}

func pfZoneSelfExpr(zone firewallZone) string {
	ifnames := compactStrings(zone.IfNames)
	sort.Strings(ifnames)
	if len(ifnames) == 1 {
		return "(" + ifnames[0] + ")"
	}
	parts := make([]string, 0, len(ifnames))
	for _, ifname := range ifnames {
		parts = append(parts, "("+ifname+")")
	}
	return "{ " + strings.Join(parts, ", ") + " }"
}

func pfFirewallRuleExprOn(onExpr, name string, spec api.FirewallRuleSpec, logging firewallLogging) string {
	return pfFirewallRuleExprOnSelf(onExpr, "self", name, spec, logging)
}

func pfFirewallRuleExprOnSelf(onExpr, selfExpr, name string, spec api.FirewallRuleSpec, logging firewallLogging) string {
	action := "block drop"
	if spec.Action == "accept" {
		action = "pass"
	} else if spec.Action == "reject" {
		action = "block return"
	}
	var parts []string
	parts = append(parts, action, "in")
	if spec.Log {
		parts = append(parts, pfLogExpr(logging))
	}
	parts = append(parts, "quick", "on", onExpr)
	if proto := pfFirewallProtocol(spec.Protocol); proto != "" {
		parts = append(parts, proto)
	}
	if icmpType := pfFirewallICMPType(spec); icmpType != "" {
		parts = append(parts, icmpType)
	}
	if len(spec.SourceCIDRs) > 0 || len(spec.SourcePorts) > 0 {
		source := "any"
		if len(spec.SourceCIDRs) > 0 {
			source = pfCIDRSet(spec.SourceCIDRs)
		}
		parts = append(parts, "from", source)
		if ports := pfFirewallSourcePorts(spec); len(ports) > 0 {
			parts = append(parts, "port", pfPortSet(ports))
		}
	}
	if len(spec.DestinationCIDRs) > 0 {
		parts = append(parts, "to", pfCIDRSet(spec.DestinationCIDRs))
	} else if spec.ToZone == "self" {
		parts = append(parts, "to", selfExpr)
	}
	if ports := pfFirewallDestinationPorts(spec); len(ports) > 0 {
		parts = append(parts, "port", pfPortSet(ports))
	}
	parts = append(parts, "keep", "state", "label", pfQuote("routerd:"+name))
	return strings.Join(parts, " ")
}

func pfFirewallDestinationPorts(spec api.FirewallRuleSpec) []string {
	var ports []string
	if len(spec.DestinationPorts) > 0 {
		for _, port := range spec.DestinationPorts {
			value := strings.TrimSpace(string(port))
			if value != "" {
				ports = append(ports, strings.ReplaceAll(value, "-", ":"))
			}
		}
		return ports
	}
	if spec.Port != 0 {
		return []string{strconv.Itoa(spec.Port)}
	}
	return nil
}

func pfFirewallSourcePorts(spec api.FirewallRuleSpec) []string {
	ports := make([]string, 0, len(spec.SourcePorts))
	for _, port := range spec.SourcePorts {
		value := strings.TrimSpace(string(port))
		if value != "" {
			ports = append(ports, strings.ReplaceAll(value, "-", ":"))
		}
	}
	return ports
}

func pfPortSet(ports []string) string {
	if len(ports) == 1 {
		return ports[0]
	}
	return "{ " + strings.Join(ports, " ") + " }"
}

func pfFirewallHoleExprs(zone firewallZone, hole FirewallHole, logging firewallLogging) []string {
	action := defaultString(hole.Action, "accept")
	spec := api.FirewallRuleSpec{
		FromZone: hole.FromZone,
		ToZone:   hole.ToZone,
		Protocol: hole.Protocol,
		Port:     hole.Port,
		Action:   action,
		Log:      false,
	}
	name := hole.Name
	if name == "" {
		name = hole.Comment
	}
	if len(hole.IfNames) == 0 {
		return []string{pfFirewallRuleExpr(zone, name, spec, logging)}
	}
	ifnames := compactStrings(hole.IfNames)
	sort.Strings(ifnames)
	exprs := make([]string, 0, len(ifnames))
	for _, ifname := range ifnames {
		selfExpr := "self"
		if hole.ToZone == "self" {
			selfExpr = "(" + ifname + ")"
		}
		exprs = append(exprs, pfFirewallRuleExprOnSelf(ifname, selfExpr, name, spec, logging))
	}
	return exprs
}

func pfFirewallProtocol(protocol string) string {
	switch protocol {
	case "tcp", "udp":
		return "proto " + protocol
	case "icmp":
		return "inet proto icmp"
	case "icmpv6", "ipv6-icmp":
		return "inet6 proto icmp6"
	case "ipip":
		return "inet6 proto 4"
	case "vrrp":
		return "inet proto 112"
	case "vrrp6":
		return "inet6 proto 112"
	default:
		return ""
	}
}

func pfFirewallICMPType(spec api.FirewallRuleSpec) string {
	switch spec.Protocol {
	case "icmp":
		if icmpType := pfFirewallRuleICMPType(spec); icmpType != "" {
			return "icmp-type " + pfICMPTypeName(icmpType)
		}
	case "icmpv6", "ipv6-icmp":
		if icmpType := pfFirewallRuleICMPv6Type(spec); icmpType != "" {
			return "icmp6-type " + pfICMPv6TypeName(icmpType)
		}
	}
	return ""
}

func pfFirewallRuleICMPType(spec api.FirewallRuleSpec) string {
	if strings.TrimSpace(spec.ICMPType) != "" {
		return strings.TrimSpace(spec.ICMPType)
	}
	return strings.TrimSpace(spec.ICMPTypeKebab)
}

func pfFirewallRuleICMPv6Type(spec api.FirewallRuleSpec) string {
	if strings.TrimSpace(spec.ICMPv6Type) != "" {
		return strings.TrimSpace(spec.ICMPv6Type)
	}
	return strings.TrimSpace(spec.ICMPv6TypeKebab)
}

func pfICMPTypeName(value string) string {
	switch strings.TrimSpace(value) {
	case "echo-request":
		return "echoreq"
	case "echo-reply":
		return "echorep"
	default:
		return strings.TrimSpace(value)
	}
}

func pfICMPv6TypeName(value string) string {
	switch strings.TrimSpace(value) {
	case "echo-request":
		return "echoreq"
	case "echo-reply":
		return "echorep"
	case "router-solicit", "nd-router-solicit":
		return "routersol"
	case "router-advert", "nd-router-advert":
		return "routeradv"
	case "neighbor-solicit", "nd-neighbor-solicit":
		return "neighbrsol"
	case "neighbor-advert", "nd-neighbor-advert":
		return "neighbradv"
	default:
		return strings.TrimSpace(value)
	}
}

func pfLogExpr(logging firewallLogging) string {
	if logging.Enabled {
		return "log"
	}
	return "log"
}

func pfCIDRSet(cidrs []string) string {
	values := make([]string, 0, len(cidrs))
	for _, cidr := range cidrs {
		values = append(values, cidr)
	}
	sort.Strings(values)
	if len(values) == 1 {
		return values[0]
	}
	return "{ " + strings.Join(values, ", ") + " }"
}

func pfInterfaceSet(ifnames []string) string {
	values := append([]string(nil), ifnames...)
	sort.Strings(values)
	if len(values) == 1 {
		return pfQuote(values[0])
	}
	return pfQuote("{ " + strings.Join(values, ", ") + " }")
}

func pfZoneMacro(zone firewallZone) string {
	return pfIdent(zone.Name) + "_if"
}

func pfIdent(value string) string {
	replacer := strings.NewReplacer("-", "_", ".", "_", "/", "_")
	return replacer.Replace(value)
}

func pfQuote(value string) string {
	return strconv.Quote(value)
}
