package render

import (
	"bytes"
	"fmt"
	"net/netip"
	"sort"
	"strconv"
	"strings"

	"routerd/pkg/api"
)

func PF(router *api.Router, holes []FirewallHole) ([]byte, error) {
	aliases, err := nftOutboundAliases(router)
	if err != nil {
		return nil, err
	}
	var nats []api.Resource
	var nat44Rules []api.Resource
	var zones []api.Resource
	var policies []api.Resource
	var logs []api.Resource
	var rules []api.Resource
	for _, res := range router.Spec.Resources {
		switch res.Kind {
		case "IPv4SourceNAT":
			nats = append(nats, res)
		case "NAT44Rule":
			nat44Rules = append(nat44Rules, res)
		case "FirewallZone":
			if res.APIVersion == api.FirewallAPIVersion {
				zones = append(zones, res)
			}
		case "FirewallPolicy":
			if res.APIVersion == api.FirewallAPIVersion {
				policies = append(policies, res)
			}
		case "FirewallLog":
			if res.APIVersion == api.FirewallAPIVersion {
				logs = append(logs, res)
			}
		case "FirewallRule":
			if res.APIVersion == api.FirewallAPIVersion {
				rules = append(rules, res)
			}
		}
	}
	if len(nats) == 0 && len(nat44Rules) == 0 && len(zones) == 0 && len(rules) == 0 && len(holes) == 0 {
		return nil, nil
	}
	sort.Slice(nats, func(i, j int) bool { return nats[i].Metadata.Name < nats[j].Metadata.Name })
	sort.Slice(nat44Rules, func(i, j int) bool { return nat44Rules[i].Metadata.Name < nat44Rules[j].Metadata.Name })
	sort.Slice(zones, func(i, j int) bool { return zones[i].Metadata.Name < zones[j].Metadata.Name })
	sort.Slice(policies, func(i, j int) bool { return policies[i].Metadata.Name < policies[j].Metadata.Name })
	sort.Slice(logs, func(i, j int) bool { return logs[i].Metadata.Name < logs[j].Metadata.Name })
	sort.Slice(rules, func(i, j int) bool { return rules[i].Metadata.Name < rules[j].Metadata.Name })

	zoneMap, err := nftFirewallZones(aliases, zones)
	if err != nil {
		return nil, err
	}
	policy := firewallPolicyOptions(policies)
	logging := firewallLogOptions(logs)

	var buf bytes.Buffer
	buf.WriteString("# Generated by routerd. Do not edit by hand.\n")
	buf.WriteString("set skip on lo0\n")
	for _, zone := range sortedFirewallZones(zoneMap) {
		if len(zone.IfNames) == 0 {
			continue
		}
		buf.WriteString(pfZoneMacro(zone) + " = " + pfInterfaceSet(zone.IfNames) + "\n")
	}
	if err := writePFNAT(&buf, aliases, nats, nat44Rules); err != nil {
		return nil, err
	}
	if err := writePFFilter(&buf, zoneMap, rules, holes, policy, logging); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func writePFNAT(buf *bytes.Buffer, aliases map[string]string, nats []api.Resource, nat44Rules []api.Resource) error {
	for _, res := range nats {
		spec, err := res.IPv4SourceNATSpec()
		if err != nil {
			return err
		}
		ifname := aliases[spec.OutboundInterface]
		if ifname == "" {
			return fmt.Errorf("%s references outbound interface with empty ifname", res.ID())
		}
		for _, cidr := range spec.SourceCIDRs {
			prefix, err := netip.ParsePrefix(cidr)
			if err != nil || !prefix.Addr().Is4() {
				return fmt.Errorf("%s has invalid IPv4 source CIDR %q", res.ID(), cidr)
			}
			target, err := pfNATTarget(spec.Translation, ifname)
			if err != nil {
				return fmt.Errorf("%s: %w", res.ID(), err)
			}
			buf.WriteString("nat on " + ifname + " from " + prefix.Masked().String() + " to any -> " + target + "\n")
		}
	}
	for _, res := range nat44Rules {
		spec, err := res.NAT44RuleSpec()
		if err != nil {
			return err
		}
		if spec.EgressInterface == "" {
			return fmt.Errorf("%s needs resolved egressInterface for static pf render", res.ID())
		}
		ifname := aliases[spec.EgressInterface]
		if ifname == "" {
			return fmt.Errorf("%s references egress interface with empty ifname", res.ID())
		}
		for _, cidr := range spec.SourceRanges {
			prefix, err := netip.ParsePrefix(cidr)
			if err != nil || !prefix.Addr().Is4() {
				return fmt.Errorf("%s has invalid IPv4 source range %q", res.ID(), cidr)
			}
			target := "(" + ifname + ")"
			if spec.Type == "snat" {
				if spec.SNATAddress == "" {
					return fmt.Errorf("%s needs snat address", res.ID())
				}
				target = spec.SNATAddress
			}
			buf.WriteString("nat on " + ifname + " from " + prefix.Masked().String() + " to any -> " + target + "\n")
		}
	}
	return nil
}

func writePFFilter(buf *bytes.Buffer, zones map[string]firewallZone, rules []api.Resource, holes []FirewallHole, policy firewallPolicy, logging firewallLogging) error {
	buf.WriteString("block drop all\n")
	buf.WriteString("pass quick on lo0 all\n")
	buf.WriteString("pass quick inet6 proto icmp6 all keep state\n")
	for _, zone := range sortedFirewallZones(zones) {
		if len(zone.IfNames) == 0 {
			continue
		}
		if implicitFirewallAction(zone.Role, "self", policy) == "accept" {
			buf.WriteString("pass in quick on $" + pfZoneMacro(zone) + " to self keep state\n")
		}
		for _, hole := range holes {
			if hole.FromZone == zone.Name && hole.ToZone == "self" {
				buf.WriteString(pfFirewallHoleExpr(zone, hole, logging) + "\n")
			}
		}
		for _, res := range rules {
			spec, err := res.FirewallRuleSpec()
			if err != nil {
				return err
			}
			if spec.FromZone == zone.Name && spec.ToZone == "self" {
				buf.WriteString(pfFirewallRuleExpr(zone, res.Metadata.Name, spec, logging) + "\n")
			}
		}
	}
	for _, from := range sortedFirewallZones(zones) {
		if len(from.IfNames) == 0 {
			continue
		}
		for _, to := range sortedFirewallZones(zones) {
			if implicitFirewallAction(from.Role, to.Role, policy) != "accept" {
				continue
			}
			if from.Name == to.Name && !policy.SameRoleAccept {
				continue
			}
			buf.WriteString("pass in quick on $" + pfZoneMacro(from) + " keep state label " + pfQuote("routerd:"+from.Name+"-to-"+to.Name) + "\n")
		}
		for _, hole := range holes {
			if hole.FromZone == from.Name && hole.ToZone != "self" {
				buf.WriteString(pfFirewallHoleExpr(from, hole, logging) + "\n")
			}
		}
		for _, res := range rules {
			spec, err := res.FirewallRuleSpec()
			if err != nil {
				return err
			}
			if spec.FromZone == from.Name && spec.ToZone != "self" {
				buf.WriteString(pfFirewallRuleExpr(from, res.Metadata.Name, spec, logging) + "\n")
			}
		}
	}
	return nil
}

func pfNATTarget(spec api.IPv4NATTranslationSpec, ifname string) (string, error) {
	switch spec.Type {
	case "interfaceAddress":
		return "(" + ifname + ")", nil
	case "address":
		if spec.Address == "" {
			return "", fmt.Errorf("address translation needs address")
		}
		return spec.Address, nil
	default:
		return "", fmt.Errorf("unsupported pf NAT translation type %q", spec.Type)
	}
}

func pfFirewallRuleExpr(zone firewallZone, name string, spec api.FirewallRuleSpec, logging firewallLogging) string {
	action := "block drop"
	if spec.Action == "accept" {
		action = "pass"
	} else if spec.Action == "reject" {
		action = "block return"
	}
	var parts []string
	parts = append(parts, action, "in")
	if spec.Log {
		parts = append(parts, pfLogExpr(logging))
	}
	parts = append(parts, "quick", "on", "$"+pfZoneMacro(zone))
	if proto := pfFirewallProtocol(spec.Protocol); proto != "" {
		parts = append(parts, proto)
	}
	if len(spec.SourceCIDRs) > 0 {
		parts = append(parts, "from", pfCIDRSet(spec.SourceCIDRs))
	}
	if spec.ToZone == "self" {
		parts = append(parts, "to", "self")
	}
	if spec.Port != 0 {
		parts = append(parts, "port", strconv.Itoa(spec.Port))
	}
	parts = append(parts, "keep", "state", "label", pfQuote("routerd:"+name))
	return strings.Join(parts, " ")
}

func pfFirewallHoleExpr(zone firewallZone, hole FirewallHole, logging firewallLogging) string {
	action := defaultString(hole.Action, "accept")
	spec := api.FirewallRuleSpec{
		FromZone: hole.FromZone,
		ToZone:   hole.ToZone,
		Protocol: hole.Protocol,
		Port:     hole.Port,
		Action:   action,
		Log:      false,
	}
	name := hole.Name
	if name == "" {
		name = hole.Comment
	}
	return pfFirewallRuleExpr(zone, name, spec, logging)
}

func pfFirewallProtocol(protocol string) string {
	switch protocol {
	case "tcp", "udp":
		return "proto " + protocol
	case "icmp":
		return "inet proto icmp"
	case "icmpv6", "ipv6-icmp":
		return "inet6 proto icmp6"
	case "ipip":
		return "inet6 proto 4"
	default:
		return ""
	}
}

func pfLogExpr(logging firewallLogging) string {
	if logging.Enabled {
		return "log"
	}
	return "log"
}

func pfCIDRSet(cidrs []string) string {
	values := make([]string, 0, len(cidrs))
	for _, cidr := range cidrs {
		values = append(values, cidr)
	}
	sort.Strings(values)
	if len(values) == 1 {
		return values[0]
	}
	return "{ " + strings.Join(values, ", ") + " }"
}

func pfInterfaceSet(ifnames []string) string {
	values := append([]string(nil), ifnames...)
	sort.Strings(values)
	if len(values) == 1 {
		return values[0]
	}
	return "{ " + strings.Join(values, ", ") + " }"
}

func pfZoneMacro(zone firewallZone) string {
	return pfIdent(zone.Name) + "_if"
}

func pfIdent(value string) string {
	replacer := strings.NewReplacer("-", "_", ".", "_", "/", "_")
	return replacer.Replace(value)
}

func pfQuote(value string) string {
	return strconv.Quote(value)
}
