package render

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"routerd/pkg/api"
)

type ManagedFile struct {
	Path string
	Data []byte
	Perm os.FileMode
}

type PPPoESecretEntry struct {
	Name     string
	Username string
	Password string
}

type PPPoEConfig struct {
	Files   []ManagedFile
	Secrets []PPPoESecretEntry
	Units   []string
}

func PPPoE(router *api.Router, passwordFor func(api.Resource, api.PPPoEInterfaceSpec) (string, error)) (PPPoEConfig, error) {
	aliases := map[string]string{}
	for _, res := range router.Spec.Resources {
		if res.Kind != "Interface" {
			continue
		}
		spec, err := res.InterfaceSpec()
		if err != nil {
			return PPPoEConfig{}, err
		}
		aliases[res.Metadata.Name] = spec.IfName
	}

	var resources []api.Resource
	for _, res := range router.Spec.Resources {
		if res.Kind == "PPPoEInterface" {
			resources = append(resources, res)
		}
	}
	sort.Slice(resources, func(i, j int) bool { return resources[i].Metadata.Name < resources[j].Metadata.Name })

	var config PPPoEConfig
	for _, res := range resources {
		spec, err := res.PPPoEInterfaceSpec()
		if err != nil {
			return PPPoEConfig{}, err
		}
		lowerIfName := aliases[spec.Interface]
		if lowerIfName == "" {
			return PPPoEConfig{}, fmt.Errorf("%s references interface with empty ifname", res.ID())
		}
		name := safePPPoEName(res.Metadata.Name)
		peerName := "routerd-" + name
		ifname := defaultString(spec.IfName, "ppp-"+res.Metadata.Name)
		if len(ifname) > 15 {
			return PPPoEConfig{}, fmt.Errorf("%s PPP interface name %q exceeds Linux limit", res.ID(), ifname)
		}
		password, err := passwordFor(res, spec)
		if err != nil {
			return PPPoEConfig{}, err
		}
		config.Files = append(config.Files, ManagedFile{
			Path: filepath.Join("/etc/ppp/peers", peerName),
			Data: pppoePeer(peerName, ifname, lowerIfName, spec),
			Perm: 0600,
		})
		unit := "routerd-pppoe-" + name + ".service"
		config.Files = append(config.Files, ManagedFile{
			Path: filepath.Join("/etc/systemd/system", unit),
			Data: PPPoEServiceUnit(peerName, res.Metadata.Name),
			Perm: 0644,
		})
		config.Secrets = append(config.Secrets, PPPoESecretEntry{
			Name:     name,
			Username: spec.Username,
			Password: password,
		})
		if spec.Managed {
			config.Units = append(config.Units, unit)
		}
	}
	return config, nil
}

func pppoePeer(peerName, ifname, lowerIfName string, spec api.PPPoEInterfaceSpec) []byte {
	mtu := spec.MTU
	if mtu == 0 {
		mtu = 1492
	}
	mru := spec.MRU
	if mru == 0 {
		mru = 1492
	}
	lcpInterval := spec.LCPInterval
	if lcpInterval == 0 {
		lcpInterval = 20
	}
	lcpFailure := spec.LCPFailure
	if lcpFailure == 0 {
		lcpFailure = 3
	}

	var buf bytes.Buffer
	buf.WriteString("# Generated by routerd. Do not edit by hand.\n")
	buf.WriteString("plugin rp-pppoe.so\n")
	buf.WriteString("nic-" + lowerIfName + "\n")
	buf.WriteString("ifname " + ifname + "\n")
	buf.WriteString("user " + strconv.Quote(spec.Username) + "\n")
	buf.WriteString("noauth\n")
	buf.WriteString("hide-password\n")
	buf.WriteString("noipdefault\n")
	if spec.DefaultRoute {
		buf.WriteString("defaultroute\n")
		buf.WriteString("replacedefaultroute\n")
	}
	if spec.UsePeerDNS {
		buf.WriteString("usepeerdns\n")
	}
	if api.BoolDefault(spec.Persist, true) {
		buf.WriteString("persist\n")
		buf.WriteString("maxfail 0\n")
		buf.WriteString("holdoff 5\n")
	}
	if spec.ServiceName != "" {
		buf.WriteString("rp_pppoe_service " + strconv.Quote(spec.ServiceName) + "\n")
	}
	if spec.ACName != "" {
		buf.WriteString("rp_pppoe_ac " + strconv.Quote(spec.ACName) + "\n")
	}
	buf.WriteString(fmt.Sprintf("mtu %d\n", mtu))
	buf.WriteString(fmt.Sprintf("mru %d\n", mru))
	buf.WriteString(fmt.Sprintf("lcp-echo-interval %d\n", lcpInterval))
	buf.WriteString(fmt.Sprintf("lcp-echo-failure %d\n", lcpFailure))
	if spec.IPv6 {
		buf.WriteString("+ipv6\n")
	}
	return buf.Bytes()
}

func PPPoEServiceUnit(peerName, resourceName string) []byte {
	return []byte(fmt.Sprintf(`[Unit]
Description=routerd PPPoE interface %s
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/sbin/pppd call %s nodetach
Restart=always
RestartSec=5s

[Install]
WantedBy=multi-user.target
`, resourceName, peerName))
}

func PPPoESecretLine(entry PPPoESecretEntry) string {
	return fmt.Sprintf("%s * %s *\n", strconv.Quote(entry.Username), strconv.Quote(entry.Password))
}

func safePPPoEName(name string) string {
	var b strings.Builder
	for _, r := range name {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '-' || r == '_' {
			b.WriteRune(r)
			continue
		}
		b.WriteByte('-')
	}
	if b.Len() == 0 {
		return "unnamed"
	}
	return b.String()
}
