package render

import (
	"bytes"
	"fmt"
	"strings"

	"routerd/pkg/api"
)

func TimesyncdConfig(router *api.Router) ([]byte, error) {
	var clients []api.Resource
	for _, res := range router.Spec.Resources {
		if res.Kind == "NTPClient" {
			spec, err := res.NTPClientSpec()
			if err != nil {
				return nil, err
			}
			if defaultString(spec.Provider, "systemd-timesyncd") == "systemd-timesyncd" {
				clients = append(clients, res)
			}
		}
	}
	if len(clients) == 0 {
		return nil, nil
	}
	if len(clients) > 1 {
		return nil, fmt.Errorf("only one NTPClient resource is supported")
	}
	spec, err := clients[0].NTPClientSpec()
	if err != nil {
		return nil, err
	}
	if !spec.Managed {
		return nil, nil
	}
	if provider := defaultString(spec.Provider, "systemd-timesyncd"); provider != "systemd-timesyncd" {
		return nil, fmt.Errorf("%s has unsupported provider %q", clients[0].ID(), provider)
	}
	source := defaultString(spec.Source, "static")
	switch source {
	case "static", "auto", "dhcp", "dhcpv6":
	default:
		return nil, fmt.Errorf("%s has unsupported source %q", clients[0].ID(), source)
	}
	servers := compactNTPServers(spec.Servers)
	fallbackServers := compactNTPServers(spec.FallbackServers)
	if len(servers) == 0 && len(fallbackServers) > 0 && source != "static" {
		servers = fallbackServers
	}
	if len(servers) == 0 && len(spec.ServerFrom) == 0 {
		return nil, fmt.Errorf("%s spec.servers is required", clients[0].ID())
	}
	if len(servers) == 0 {
		return nil, nil
	}
	var buf bytes.Buffer
	buf.WriteString("# Generated by routerd. Do not edit by hand.\n")
	buf.WriteString("[Time]\n")
	if spec.Interface == "" || source != "static" {
		buf.WriteString("NTP=" + strings.Join(servers, " ") + "\n")
	} else {
		buf.WriteString("NTP=\n")
	}
	if len(fallbackServers) > 0 {
		buf.WriteString("FallbackNTP=" + strings.Join(fallbackServers, " ") + "\n")
	}
	return buf.Bytes(), nil
}

func compactNTPServers(values []string) []string {
	out := make([]string, 0, len(values))
	seen := map[string]bool{}
	for _, value := range values {
		value = strings.TrimSpace(value)
		if value == "" || seen[value] {
			continue
		}
		seen[value] = true
		out = append(out, value)
	}
	return out
}
