package render

import (
	"bytes"
	"fmt"
	"strings"

	"routerd/pkg/api"
)

func TimesyncdConfig(router *api.Router) ([]byte, error) {
	var clients []api.Resource
	for _, res := range router.Spec.Resources {
		if res.Kind == "NTPClient" {
			clients = append(clients, res)
		}
	}
	if len(clients) == 0 {
		return nil, nil
	}
	if len(clients) > 1 {
		return nil, fmt.Errorf("only one NTPClient resource is supported")
	}
	spec, err := clients[0].NTPClientSpec()
	if err != nil {
		return nil, err
	}
	if !spec.Managed {
		return nil, nil
	}
	if provider := defaultString(spec.Provider, "systemd-timesyncd"); provider != "systemd-timesyncd" {
		return nil, fmt.Errorf("%s has unsupported provider %q", clients[0].ID(), provider)
	}
	if source := defaultString(spec.Source, "static"); source != "static" {
		return nil, fmt.Errorf("%s has unsupported source %q", clients[0].ID(), source)
	}
	var servers []string
	for _, server := range spec.Servers {
		server = strings.TrimSpace(server)
		if server != "" {
			servers = append(servers, server)
		}
	}
	if len(servers) == 0 {
		return nil, fmt.Errorf("%s spec.servers is required", clients[0].ID())
	}
	var buf bytes.Buffer
	buf.WriteString("# Generated by routerd. Do not edit by hand.\n")
	buf.WriteString("[Time]\n")
	if spec.Interface == "" {
		buf.WriteString("NTP=" + strings.Join(servers, " ") + "\n")
	} else {
		buf.WriteString("NTP=\n")
	}
	return buf.Bytes(), nil
}
