// SPDX-License-Identifier: BSD-3-Clause

package render

import (
	"bytes"
	"fmt"
	"net/netip"
	"sort"
	"strings"
	"time"

	"routerd/pkg/api"
)

type vrrpInstance struct {
	Name            string
	Kind            string
	Interface       string
	Address         string
	Family          string
	VirtualRouterID int
	Priority        int
	Preempt         *bool
	PreemptDelay    time.Duration
	Peers           []string
	AdvertInterval  time.Duration
	Authentication  string
}

type KeepalivedOptions struct {
	PriorityByResource map[string]int
}

func KeepalivedConfig(router *api.Router, aliases map[string]string) ([]byte, error) {
	return KeepalivedConfigWithOptions(router, aliases, KeepalivedOptions{})
}

func KeepalivedConfigWithOptions(router *api.Router, aliases map[string]string, opts KeepalivedOptions) ([]byte, error) {
	instances, err := vrrpInstances(router, aliases, opts)
	if err != nil {
		return nil, err
	}
	if len(instances) == 0 {
		return nil, nil
	}
	var buf bytes.Buffer
	buf.WriteString("# Generated by routerd. Do not edit by hand.\n")
	buf.WriteString("global_defs {\n")
	buf.WriteString("  router_id routerd\n")
	buf.WriteString("}\n\n")
	for _, instance := range instances {
		writeKeepalivedInstance(&buf, instance)
	}
	return buf.Bytes(), nil
}

func vrrpInstances(router *api.Router, aliases map[string]string, opts KeepalivedOptions) ([]vrrpInstance, error) {
	if router == nil {
		return nil, nil
	}
	var instances []vrrpInstance
	for _, res := range router.Spec.Resources {
		spec, ok, err := virtualAddressResourceSpec(res)
		if err != nil {
			return nil, err
		}
		if !ok {
			continue
		}
		if strings.TrimSpace(spec.Mode) == "" || spec.Mode == "static" {
			continue
		}
		if spec.Mode != "vrrp" {
			continue
		}
		ifname := aliases[spec.Interface]
		if ifname == "" {
			return nil, fmt.Errorf("%s references interface with empty ifname %q", res.ID(), spec.Interface)
		}
		address, err := virtualAddress(router, spec)
		if err != nil {
			return nil, fmt.Errorf("%s spec.address: %w", res.ID(), err)
		}
		advert := time.Second
		if spec.VRRP.AdvertInterval != "" {
			advert, err = time.ParseDuration(spec.VRRP.AdvertInterval)
			if err != nil {
				return nil, fmt.Errorf("%s spec.vrrp.advertInterval: %w", res.ID(), err)
			}
		}
		var preemptDelay time.Duration
		if spec.VRRP.PreemptDelay != "" {
			preemptDelay, err = time.ParseDuration(spec.VRRP.PreemptDelay)
			if err != nil {
				return nil, fmt.Errorf("%s spec.vrrp.preemptDelay: %w", res.ID(), err)
			}
		}
		priority := spec.VRRP.Priority
		if priority == 0 {
			priority = 100
		}
		if opts.PriorityByResource != nil && opts.PriorityByResource[res.Metadata.Name] > 0 {
			priority = opts.PriorityByResource[res.Metadata.Name]
		}
		peers := compactStrings(spec.VRRP.Peers)
		sort.Strings(peers)
		authentication, err := secretValue(spec.VRRP.Authentication, spec.VRRP.AuthenticationFrom)
		if err != nil {
			return nil, fmt.Errorf("%s spec.vrrp.authenticationFrom: %w", res.ID(), err)
		}
		instances = append(instances, vrrpInstance{
			Name:            res.Metadata.Name,
			Kind:            res.Kind,
			Interface:       ifname,
			Address:         address,
			Family:          spec.Family,
			VirtualRouterID: spec.VRRP.VirtualRouterID,
			Priority:        priority,
			Preempt:         spec.VRRP.Preempt,
			PreemptDelay:    preemptDelay,
			Peers:           peers,
			AdvertInterval:  advert,
			Authentication:  authentication,
		})
	}
	sort.Slice(instances, func(i, j int) bool { return instances[i].Name < instances[j].Name })
	return instances, nil
}

type virtualAddressSpec struct {
	Interface   string
	Address     string
	Hostname    string
	Mode        string
	VRRP        virtualVRRPSpec
	Track       []api.ResourceTrackSpec
	AddressFrom api.StatusValueSourceSpec
	Family      string
}

type virtualVRRPSpec struct {
	VirtualRouterID    int
	Priority           int
	Preempt            *bool
	PreemptDelay       string
	Peers              []string
	AdvertInterval     string
	Authentication     string
	AuthenticationFrom api.SecretValueSourceSpec
}

func virtualAddressResourceSpec(res api.Resource) (virtualAddressSpec, bool, error) {
	if res.APIVersion != api.NetAPIVersion {
		return virtualAddressSpec{}, false, nil
	}
	switch res.Kind {
	case "VirtualAddress":
		spec, err := res.VirtualAddressSpec()
		if err != nil {
			return virtualAddressSpec{}, false, err
		}
		return virtualAddressSpec{
			Interface:   spec.Interface,
			Address:     spec.Address,
			Hostname:    spec.Hostname,
			Mode:        spec.Mode,
			VRRP:        virtualAddressVRRPSpec(spec.VRRP),
			Track:       spec.Track,
			AddressFrom: spec.AddressFrom,
			Family:      spec.Family,
		}, true, nil
	default:
		return virtualAddressSpec{}, false, nil
	}
}

func virtualAddressVRRPSpec(spec api.VirtualAddressVRRPSpec) virtualVRRPSpec {
	return virtualVRRPSpec{
		VirtualRouterID:    spec.VirtualRouterID,
		Priority:           spec.Priority,
		Preempt:            spec.Preempt,
		PreemptDelay:       spec.PreemptDelay,
		Peers:              spec.Peers,
		AdvertInterval:     spec.AdvertInterval,
		Authentication:     spec.Authentication,
		AuthenticationFrom: spec.AuthenticationFrom,
	}
}

func VirtualAddress(router *api.Router, spec api.VirtualAddressSpec) (string, error) {
	return virtualAddress(router, virtualAddressSpec{
		Address:     spec.Address,
		AddressFrom: spec.AddressFrom,
		Family:      spec.Family,
	})
}

func virtualAddress(router *api.Router, spec virtualAddressSpec) (string, error) {
	address := strings.TrimSpace(spec.Address)
	if address == "" && strings.TrimSpace(spec.AddressFrom.Resource) != "" {
		resolved, err := renderAddressFromResource(router, spec.AddressFrom)
		if err != nil {
			return "", err
		}
		address = strings.TrimSpace(resolved)
	}
	if address == "" {
		return "", fmt.Errorf("must resolve to an %s host prefix", virtualAddressFamilyLabel(spec.Family))
	}
	prefix, err := netip.ParsePrefix(address)
	if err != nil {
		addr, addrErr := netip.ParseAddr(address)
		if addrErr == nil && spec.Family == "ipv4" && addr.Is4() {
			return netip.PrefixFrom(addr, 32).String(), nil
		}
		if addrErr == nil && spec.Family == "ipv6" && addr.Is6() {
			return netip.PrefixFrom(addr, 128).String(), nil
		}
		return "", fmt.Errorf("must resolve to an %s host prefix", virtualAddressFamilyLabel(spec.Family))
	}
	wantBits := 32
	if spec.Family == "ipv6" {
		wantBits = 128
	}
	if (spec.Family == "ipv4" && !prefix.Addr().Is4()) || (spec.Family == "ipv6" && !prefix.Addr().Is6()) || prefix.Bits() != wantBits {
		return "", fmt.Errorf("must resolve to an %s host prefix", virtualAddressFamilyLabel(spec.Family))
	}
	return prefix.Masked().String(), nil
}

func virtualAddressFamilyLabel(family string) string {
	if family == "ipv6" {
		return "IPv6 /128"
	}
	return "IPv4 /32"
}

func writeKeepalivedInstance(buf *bytes.Buffer, instance vrrpInstance) {
	buf.WriteString("vrrp_instance " + sanitizeKeepalivedName(instance.Name) + " {\n")
	buf.WriteString("  state BACKUP\n")
	buf.WriteString("  interface " + instance.Interface + "\n")
	buf.WriteString(fmt.Sprintf("  virtual_router_id %d\n", instance.VirtualRouterID))
	buf.WriteString(fmt.Sprintf("  priority %d\n", instance.Priority))
	if instance.Family == "ipv6" {
		buf.WriteString("  family inet6\n")
	}
	buf.WriteString(fmt.Sprintf("  advert_int %d\n", keepalivedAdvertSeconds(instance.AdvertInterval)))
	if instance.Preempt == nil || !*instance.Preempt {
		buf.WriteString("  nopreempt\n")
	} else if instance.PreemptDelay > 0 {
		buf.WriteString(fmt.Sprintf("  preempt_delay %d\n", keepalivedAdvertSeconds(instance.PreemptDelay)))
	}
	if len(instance.Peers) > 0 {
		buf.WriteString("  unicast_peer {\n")
		for _, peer := range instance.Peers {
			buf.WriteString("    " + peer + "\n")
		}
		buf.WriteString("  }\n")
	}
	if instance.Authentication != "" {
		buf.WriteString("  authentication {\n")
		buf.WriteString("    auth_type PASS\n")
		buf.WriteString("    auth_pass " + instance.Authentication + "\n")
		buf.WriteString("  }\n")
	}
	buf.WriteString("  virtual_ipaddress {\n")
	buf.WriteString("    " + instance.Address + " dev " + instance.Interface + "\n")
	buf.WriteString("  }\n")
	buf.WriteString("}\n\n")
}

func keepalivedAdvertSeconds(value time.Duration) int {
	seconds := int(value.Round(time.Second) / time.Second)
	if seconds < 1 {
		return 1
	}
	return seconds
}

func sanitizeKeepalivedName(value string) string {
	value = strings.TrimSpace(value)
	var b strings.Builder
	for _, r := range value {
		switch {
		case r >= 'a' && r <= 'z':
			b.WriteRune(r)
		case r >= 'A' && r <= 'Z':
			b.WriteRune(r)
		case r >= '0' && r <= '9':
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
	}
	out := strings.Trim(b.String(), "_")
	if out == "" {
		return "vip"
	}
	return out
}
