# yaml-language-server: $schema=../schemas/routerd-config-v1alpha1.schema.json
apiVersion: routerd.net/v1alpha1
kind: Router
metadata:
  name: bgp-transit-export

spec:
  resources:
    - apiVersion: net.routerd.net/v1alpha1
      kind: Interface
      metadata:
        name: lan
      spec:
        ifname: eth0
        managed: false

    - apiVersion: net.routerd.net/v1alpha1
      kind: BGPRouter
      metadata:
        name: lan
      spec:
        asn: 64512
        routerID: 192.168.1.248
        listen:
          address: 192.168.1.248
        importPolicy:
          allowedPrefixes:
            - 10.250.0.0/24
        exportPolicy:
          allowedPrefixes:
            - 10.250.0.0/24

    - apiVersion: net.routerd.net/v1alpha1
      kind: BGPPeer
      metadata:
        name: k8s-workers
      spec:
        routerRef: BGPRouter/lan
        peerASN: 64513
        peers:
          - 192.168.1.54
          - 192.168.1.55
          - 192.168.1.56

    - apiVersion: net.routerd.net/v1alpha1
      kind: BGPPeer
      metadata:
        name: upstream
      spec:
        routerRef: BGPRouter/lan
        peerASN: 64514
        peers:
          - 192.168.1.1
        exportPolicy:
          allowedPrefixes:
            - 10.250.0.0/24
