# yaml-language-server: $schema=https://routerd.net/schemas/routerd-config-v1alpha1.schema.json
apiVersion: routerd.net/v1alpha1
kind: Router
metadata:
  name: firewall-flow-pinhole

spec:
  resources:
    - apiVersion: net.routerd.net/v1alpha1
      kind: Interface
      metadata:
        name: wan
      spec:
        ifname: ens18
        managed: false
        owner: external

    - apiVersion: net.routerd.net/v1alpha1
      kind: Interface
      metadata:
        name: lan
      spec:
        ifname: ens19
        managed: false
        owner: external

    - apiVersion: net.routerd.net/v1alpha1
      kind: IPAddressSet
      metadata:
        name: camera-clients
      spec:
        addresses:
          - 172.18.1.92

    - apiVersion: firewall.routerd.net/v1alpha1
      kind: FirewallZone
      metadata:
        name: wan
      spec:
        role: untrust
        interfaces:
          - wan

    - apiVersion: firewall.routerd.net/v1alpha1
      kind: FirewallZone
      metadata:
        name: lan
      spec:
        role: trust
        interfaces:
          - lan

    - apiVersion: firewall.routerd.net/v1alpha1
      kind: FirewallFlowPinhole
      metadata:
        name: camera-cloud-udp
      spec:
        fromZone: lan
        toZone: wan
        outbound:
          sourceSetRef: IPAddressSet/camera-clients
          protocol: udp
          destinationCIDRs:
            - 3.114.54.243/32
          destinationPorts:
            - "32100"
        inbound:
          sourcePorts:
            - "32099"
        correlation:
          key: localEndpoint
        timeout: 3m
