# yaml-language-server: $schema=../schemas/routerd-config-v1alpha1.schema.json
apiVersion: routerd.net/v1alpha1
kind: Router
metadata:
  name: freebsd-edge
spec:
  resources:
    - apiVersion: net.routerd.net/v1alpha1
      kind: Interface
      metadata:
        name: wan
      spec:
        ifname: vtnet0
        managed: false
    - apiVersion: net.routerd.net/v1alpha1
      kind: DHCPv4Client
      metadata:
        name: wan-dhcpv4
      spec:
        interface: wan
    - apiVersion: net.routerd.net/v1alpha1
      kind: Interface
      metadata:
        name: lan
      spec:
        ifname: vtnet1
        role: trust
        managed: true
    - apiVersion: net.routerd.net/v1alpha1
      kind: IPv4StaticAddress
      metadata:
        name: lan-v4
      spec:
        interface: lan
        address: 192.0.2.1/24
    - apiVersion: net.routerd.net/v1alpha1
      kind: DHCPv6PrefixDelegation
      metadata:
        name: wan-pd
      spec:
        interface: wan
        prefixLength: 60
    - apiVersion: net.routerd.net/v1alpha1
      kind: IPv6DelegatedAddress
      metadata:
        name: lan-v6
      spec:
        prefixDelegation: wan-pd
        interface: lan
        subnetID: "0"
        addressSuffix: "::1"
    - apiVersion: net.routerd.net/v1alpha1
      kind: DSLiteTunnel
      metadata:
        name: ds-lite
      spec:
        interface: wan
        tunnelName: gif0
        aftrFQDN: gw.transix.jp
        localAddressSource: delegatedAddress
        localDelegatedAddress: lan-v6
        localAddressSuffix: "::100"
        defaultRoute: true
    - apiVersion: net.routerd.net/v1alpha1
      kind: NAT44Rule
      metadata:
        name: lan-to-wan
      spec:
        type: masquerade
        egressInterface: ds-lite
        sourceRanges: [192.0.2.0/24]
    - apiVersion: net.routerd.net/v1alpha1
      kind: DHCPv4Server
      metadata:
        name: lan-dhcpv4
      spec:
        interface: lan
        rangeStart: 192.0.2.110
        rangeEnd: 192.0.2.119
        leaseTime: 12h
        gatewayFrom:
          resource: IPv4StaticAddress/lan-v4
          field: address
        dnsServerFrom:
          - resource: IPv4StaticAddress/lan-v4
            field: address
    - apiVersion: firewall.routerd.net/v1alpha1
      kind: FirewallZone
      metadata:
        name: wan
      spec:
        role: untrust
        interfaces: [wan, ds-lite]
    - apiVersion: firewall.routerd.net/v1alpha1
      kind: FirewallZone
      metadata:
        name: lan
      spec:
        role: trust
        interfaces: [lan]
    - apiVersion: firewall.routerd.net/v1alpha1
      kind: FirewallPolicy
      metadata:
        name: default
      spec:
        logDeny: true
