# yaml-language-server: $schema=https://routerd.net/schemas/routerd-config-v1alpha1.schema.json
apiVersion: routerd.net/v1alpha1
kind: Router
metadata:
  name: multi-instance-bgp

spec:
  resources:
    - apiVersion: net.routerd.net/v1alpha1
      kind: Interface
      metadata:
        name: lan
      spec:
        ifname: ens19
        managed: false

    - apiVersion: net.routerd.net/v1alpha1
      kind: Interface
      metadata:
        name: wan
      spec:
        ifname: ens20
        managed: false

    - apiVersion: net.routerd.net/v1alpha1
      kind: VRF
      metadata:
        name: wan-peering
      spec:
        ifname: vrf-wan
        routeTable: 65001
        members:
          - wan

    - apiVersion: net.routerd.net/v1alpha1
      kind: BGPRouter
      metadata:
        name: lan
      spec:
        asn: 64512
        routerID: 192.168.50.1
        listen:
          address: 192.168.50.1
        importPolicy:
          allowedPrefixes:
            - 10.240.70.200/29

    - apiVersion: net.routerd.net/v1alpha1
      kind: BGPRouter
      metadata:
        name: wan-peering
      spec:
        asn: 65001
        routerID: 192.0.2.2
        vrf: wan-peering
        listen:
          address: 192.0.2.2
        redistribute:
          static:
            allowedPrefixes:
              - 198.51.100.0/24
        exportPolicy:
          allowedPrefixes:
            - 198.51.100.0/24

    - apiVersion: net.routerd.net/v1alpha1
      kind: BGPPeer
      metadata:
        name: lan-speakers
      spec:
        routerRef: BGPRouter/lan
        peerASN: 64513
        peers:
          - 192.168.50.21
          - 192.168.50.22

    - apiVersion: net.routerd.net/v1alpha1
      kind: BGPPeer
      metadata:
        name: wan-upstream
      spec:
        routerRef: BGPRouter/wan-peering
        peerASN: 65002
        peers:
          - 192.0.2.254
