# Sample hand-written NixOS configuration for the router02 lab.
# This file is not generated by routerd. Keep local machine-specific imports
# and emergency settings here, then let routerd own routerd-generated.nix.
{ config, pkgs, ... }:

{
  imports = [
    ./hardware-configuration.nix
    ./routerd-generated.nix
  ];

  # Keep this file small. Hostname, SSH, users, packages, and basic networkd
  # interface setup are rendered from examples/nixos-router02.yaml into
  # routerd-generated.nix by:
  #
  #   routerd render nixos --config examples/nixos-router02.yaml --out routerd-generated.nix
  #
  # Apply with:
  #
  #   sudo nixos-rebuild switch -I nixos-config=/etc/nixos/configuration.nix
}
