# yaml-language-server: $schema=../schemas/routerd-config-v1alpha1.schema.json
apiVersion: routerd.net/v1alpha1
kind: Router
metadata:
  name: lab-router

spec:
  resources:
    - apiVersion: system.routerd.net/v1alpha1
      kind: LogSink
      metadata:
        name: local-syslog
      spec:
        type: syslog
        minLevel: info
        syslog:
          facility: local6
          tag: routerd

    - apiVersion: system.routerd.net/v1alpha1
      kind: Sysctl
      metadata:
        name: ipv4-forwarding
      spec:
        key: net.ipv4.ip_forward
        value: "1"
        runtime: true
        persistent: false

    - apiVersion: system.routerd.net/v1alpha1
      kind: Sysctl
      metadata:
        name: ipv6-forwarding
      spec:
        key: net.ipv6.conf.all.forwarding
        value: "1"
        runtime: true
        persistent: false

    - apiVersion: net.routerd.net/v1alpha1
      kind: IPv4ReversePathFilter
      metadata:
        name: rp-filter-all
      spec:
        target: all
        mode: disabled

    - apiVersion: net.routerd.net/v1alpha1
      kind: IPv4ReversePathFilter
      metadata:
        name: rp-filter-default
      spec:
        target: default
        mode: disabled

    - apiVersion: net.routerd.net/v1alpha1
      kind: IPv4ReversePathFilter
      metadata:
        name: rp-filter-lan
      spec:
        target: interface
        interface: lan
        mode: disabled

    - apiVersion: net.routerd.net/v1alpha1
      kind: IPv4ReversePathFilter
      metadata:
        name: rp-filter-transix
      spec:
        target: interface
        interface: transix
        mode: disabled

    - apiVersion: net.routerd.net/v1alpha1
      kind: Hostname
      metadata:
        name: system-hostname
      spec:
        hostname: router.example
        managed: true

    - apiVersion: net.routerd.net/v1alpha1
      kind: Interface
      metadata:
        name: wan
      spec:
        ifname: ens18
        adminUp: true
        managed: false
        owner: external

    - apiVersion: net.routerd.net/v1alpha1
      kind: IPv4DHCPAddress
      metadata:
        name: wan-dhcp4
      spec:
        interface: wan
        client: dhcpcd
        required: true

    - apiVersion: net.routerd.net/v1alpha1
      kind: HealthCheck
      metadata:
        name: wan-dhcp4-v4
      spec:
        type: ping
        targetSource: defaultGateway
        interface: wan

    - apiVersion: net.routerd.net/v1alpha1
      kind: IPv4DefaultRoutePolicy
      metadata:
        name: default-v4
      spec:
        mode: priority
        sourceCIDRs:
          - 192.168.160.0/24
        destinationCIDRs:
          - 0.0.0.0/0
        candidates:
          - name: wan-dhcp4
            interface: wan
            gatewaySource: dhcp4
            priority: 10
            table: 100
            mark: 256
            routeMetric: 50
            healthCheck: wan-dhcp4-v4

    - apiVersion: net.routerd.net/v1alpha1
      kind: IPv4SourceNAT
      metadata:
        name: lan-to-wan
      spec:
        outboundInterface: transix
        sourceCIDRs:
          - 192.168.160.0/24
        translation:
          type: interfaceAddress
          portMapping:
            type: range
            start: 1024
            end: 65535

    - apiVersion: net.routerd.net/v1alpha1
      kind: IPv4PolicyRoute
      metadata:
        name: lan-via-transix
      spec:
        outboundInterface: transix
        table: 100
        priority: 10000
        mark: 256
        sourceCIDRs:
          - 192.168.160.0/24
        routeMetric: 50

    - apiVersion: net.routerd.net/v1alpha1
      kind: DNSConditionalForwarder
      metadata:
        name: transix-aftr
      spec:
        domain: gw.transix.jp
        upstreamSource: static
        upstreamServers:
          - 2404:1a8:7f01:a::3
          - 2404:1a8:7f01:b::3

    - apiVersion: net.routerd.net/v1alpha1
      kind: DSLiteTunnel
      metadata:
        name: transix
      spec:
        interface: wan
        tunnelName: ds-transix
        aftrFQDN: gw.transix.jp
        aftrDNSServers:
          - 2404:1a8:7f01:a::3
          - 2404:1a8:7f01:b::3
        aftrAddressOrdinal: 1
        aftrAddressSelection: ordinalModulo
        localAddressSource: delegatedAddress
        localDelegatedAddress: lan-ipv6-pd-address
        localAddressSuffix: "::100"
        defaultRoute: true
        routeMetric: 50
        mtu: 1460

    - apiVersion: net.routerd.net/v1alpha1
      kind: IPv6DHCPAddress
      metadata:
        name: wan-dhcp6
      spec:
        interface: wan
        client: networkd
        required: false

    - apiVersion: net.routerd.net/v1alpha1
      kind: IPv6PrefixDelegation
      metadata:
        name: wan-pd
      spec:
        interface: wan
        client: networkd
        profile: ntt-hgw-lan-pd
        required: false

    - apiVersion: net.routerd.net/v1alpha1
      kind: Interface
      metadata:
        name: lan
      spec:
        ifname: ens19
        adminUp: true
        managed: true
        owner: routerd

    - apiVersion: net.routerd.net/v1alpha1
      kind: IPv4StaticAddress
      metadata:
        name: lan-ipv4
      spec:
        interface: lan
        address: 192.168.160.3/24
        exclusive: false

    - apiVersion: net.routerd.net/v1alpha1
      kind: IPv6DelegatedAddress
      metadata:
        name: lan-ipv6-pd-address
      spec:
        prefixDelegation: wan-pd
        interface: lan
        subnetID: "0"
        addressSuffix: "::3"
        sendRA: false
        announce: true

    - apiVersion: net.routerd.net/v1alpha1
      kind: IPv6DHCPServer
      metadata:
        name: dhcp6
      spec:
        server: dnsmasq
        managed: true

    - apiVersion: net.routerd.net/v1alpha1
      kind: IPv6DHCPScope
      metadata:
        name: lan-dhcp6
      spec:
        server: dhcp6
        delegatedAddress: lan-ipv6-pd-address
        mode: stateless
        leaseTime: 12h
        defaultRoute: true
        dnsSource: self
        selfAddressPolicy: lan-ipv6-self

    - apiVersion: net.routerd.net/v1alpha1
      kind: SelfAddressPolicy
      metadata:
        name: lan-ipv6-self
      spec:
        addressFamily: ipv6
        candidates:
          - source: delegatedAddress
            delegatedAddress: lan-ipv6-pd-address
            addressSuffix: "::3"
          - source: interfaceAddress
            interface: lan
            matchSuffix: "::3"
          - source: interfaceAddress
            interface: lan
            ordinal: 1

    - apiVersion: net.routerd.net/v1alpha1
      kind: IPv4DHCPServer
      metadata:
        name: dhcp4
      spec:
        server: dnsmasq
        managed: true
        dns:
          enabled: true
          upstreamSource: dhcp4
          upstreamInterface: wan
          cacheSize: 1000

    - apiVersion: net.routerd.net/v1alpha1
      kind: IPv4DHCPScope
      metadata:
        name: lan-dhcp4
      spec:
        server: dhcp4
        interface: lan
        rangeStart: 192.168.160.100
        rangeEnd: 192.168.160.199
        leaseTime: 12h
        routerSource: interfaceAddress
        dnsSource: self
        authoritative: true
