apiVersion: routerd.net/v1alpha1
kind: Router
metadata:
  name: lab-router

spec:
  resources:
    - apiVersion: net.routerd.net/v1alpha1
      kind: Hostname
      metadata:
        name: system-hostname
      spec:
        hostname: router.example
        managed: true

    - apiVersion: net.routerd.net/v1alpha1
      kind: Interface
      metadata:
        name: wan
      spec:
        ifname: ens18
        adminUp: true
        managed: false
        owner: external

    - apiVersion: net.routerd.net/v1alpha1
      kind: IPv4DHCPAddress
      metadata:
        name: wan-dhcp4
      spec:
        interface: wan
        client: dhcpcd
        required: true

    - apiVersion: net.routerd.net/v1alpha1
      kind: IPv6DHCPAddress
      metadata:
        name: wan-dhcp6
      spec:
        interface: wan
        client: dhcpcd
        required: false

    - apiVersion: net.routerd.net/v1alpha1
      kind: Interface
      metadata:
        name: lan
      spec:
        ifname: ens19
        adminUp: true
        managed: true
        owner: routerd

    - apiVersion: net.routerd.net/v1alpha1
      kind: IPv4StaticAddress
      metadata:
        name: lan-ipv4
      spec:
        interface: lan
        address: 192.168.160.3/24
        exclusive: false
