# yaml-language-server: $schema=../schemas/routerd-config-v1alpha1.schema.json
apiVersion: routerd.net/v1alpha1
kind: Router
metadata:
  name: lab-router

spec:
  resources:
    - apiVersion: system.routerd.net/v1alpha1
      kind: Sysctl
      metadata:
        name: ipv4-forwarding
      spec:
        key: net.ipv4.ip_forward
        value: "1"
        runtime: true
        persistent: false

    - apiVersion: net.routerd.net/v1alpha1
      kind: Hostname
      metadata:
        name: system-hostname
      spec:
        hostname: router.example
        managed: true

    - apiVersion: net.routerd.net/v1alpha1
      kind: Interface
      metadata:
        name: wan
      spec:
        ifname: ens18
        adminUp: true
        managed: false
        owner: external

    - apiVersion: net.routerd.net/v1alpha1
      kind: IPv4DHCPAddress
      metadata:
        name: wan-dhcp4
      spec:
        interface: wan
        client: dhcpcd
        required: true

    - apiVersion: net.routerd.net/v1alpha1
      kind: IPv4DefaultRoute
      metadata:
        name: default-v4
      spec:
        interface: wan
        gatewaySource: dhcp4
        required: true

    - apiVersion: net.routerd.net/v1alpha1
      kind: IPv4SourceNAT
      metadata:
        name: lan-to-wan
      spec:
        outboundInterface: wan
        sourceCIDRs:
          - 192.168.160.0/24
        translation:
          type: interfaceAddress
          portMapping:
            type: range
            start: 1024
            end: 65535

    - apiVersion: net.routerd.net/v1alpha1
      kind: IPv6DHCPAddress
      metadata:
        name: wan-dhcp6
      spec:
        interface: wan
        client: dhcpcd
        required: false

    - apiVersion: net.routerd.net/v1alpha1
      kind: Interface
      metadata:
        name: lan
      spec:
        ifname: ens19
        adminUp: true
        managed: true
        owner: routerd

    - apiVersion: net.routerd.net/v1alpha1
      kind: IPv4StaticAddress
      metadata:
        name: lan-ipv4
      spec:
        interface: lan
        address: 192.168.160.3/24
        exclusive: false

    - apiVersion: net.routerd.net/v1alpha1
      kind: IPv4DHCPServer
      metadata:
        name: dhcp4
      spec:
        server: dnsmasq
        managed: true

    - apiVersion: net.routerd.net/v1alpha1
      kind: IPv4DHCPScope
      metadata:
        name: lan-dhcp4
      spec:
        server: dhcp4
        interface: lan
        rangeStart: 192.168.160.100
        rangeEnd: 192.168.160.199
        leaseTime: 12h
        routerSource: interfaceAddress
        dnsSource: dhcp4
        dnsInterface: wan
        authoritative: true
