# yaml-language-server: $schema=../schemas/routerd-config-v1alpha1.schema.json
apiVersion: routerd.net/v1alpha1
kind: Router
metadata:
  name: tailscale-edge

spec:
  resources:
    - apiVersion: system.routerd.net/v1alpha1
      kind: Package
      metadata:
        name: tailscale-runtime
      spec:
        packages:
          - os: ubuntu
            manager: apt
            names:
              - tailscale
          - os: nixos
            manager: nix
            names:
              - tailscale
          - os: alpine
            manager: apk
            names:
              - tailscale

    - apiVersion: net.routerd.net/v1alpha1
      kind: TailscaleNode
      metadata:
        name: home
      spec:
        hostname: edge-router
        advertiseExitNode: true
        advertiseRoutes:
          - 172.18.0.0/16
          - 192.168.123.0/24
        acceptDNS: false
        authKeyEnv: TS_AUTHKEY
        authKeyFile: /usr/local/etc/routerd/secrets/tailscale.env
