# yaml-language-server: $schema=https://routerd.net/schemas/routerd-config-v1alpha1.schema.json
apiVersion: routerd.net/v1alpha1
kind: Router
metadata:
  name: tailscale-edge

spec:
  resources:
    - apiVersion: net.routerd.net/v1alpha1
      kind: TailscaleNode
      metadata:
        name: home
      spec:
        hostname: edge-router
        advertiseExitNode: true
        advertiseRoutes:
          - 172.18.0.0/16
          - 192.168.20.0/24
        acceptDNS: false
        authKeyEnv: TS_AUTHKEY
        authKeyFile: /usr/local/etc/routerd/secrets/tailscale.env
