// SPDX-License-Identifier: BSD-3-Clause

package pppoeclient

import (
	"bytes"
	"fmt"
	"net/netip"
	"runtime"
	"strconv"
	"strings"
	"time"

	"github.com/imksoo/routerd/pkg/api"
)

const (
	DaemonKind = "routerd-pppoe-client"

	PhaseIdle           = "Idle"
	PhaseConnecting     = "Connecting"
	PhaseAuthenticating = "Authenticating"
	PhaseIPCP           = "IPCP"
	PhaseConnected      = "Connected"
	PhaseDisconnecting  = "Disconnecting"
	PhaseFailed         = "Failed"
)

type Config struct {
	Resource   string
	Interface  string
	IfName     string
	Spec       api.PPPoESessionSpec
	Password   string
	RuntimeDir string
}

type Snapshot struct {
	Resource       string    `json:"resource"`
	Interface      string    `json:"interface"`
	IfName         string    `json:"ifname,omitempty"`
	Phase          string    `json:"phase"`
	SessionID      string    `json:"sessionID,omitempty"`
	CurrentAddress string    `json:"currentAddress,omitempty"`
	PeerAddress    string    `json:"peerAddress,omitempty"`
	DNSServers     []string  `json:"dnsServers,omitempty"`
	BytesIn        uint64    `json:"bytesIn,omitempty"`
	BytesOut       uint64    `json:"bytesOut,omitempty"`
	ConnectedAt    time.Time `json:"connectedAt,omitempty"`
	UpdatedAt      time.Time `json:"updatedAt"`
	LastError      string    `json:"lastError,omitempty"`
}

func DefaultIfName(resource string) string {
	name := "ppp-" + resource
	if len(name) <= 15 {
		return name
	}
	return "ppp" + resourceHash(resource)
}

func LinuxPeer(cfg Config) []byte {
	spec := cfg.Spec
	mtu := intDefault(spec.MTU, 1454)
	mru := intDefault(spec.MRU, 1454)
	lcpInterval := intDefault(spec.LCPEchoInterval, 30)
	lcpFailure := intDefault(spec.LCPEchoFailure, 4)
	ifname := cfg.IfName
	if ifname == "" {
		ifname = DefaultIfName(cfg.Resource)
	}
	auth := spec.AuthMethod
	if auth == "" {
		auth = "chap"
	}

	var b bytes.Buffer
	b.WriteString("# Generated by routerd-pppoe-client. Do not edit by hand.\n")
	b.WriteString("plugin rp-pppoe.so\n")
	b.WriteString("nic-" + cfg.Interface + "\n")
	b.WriteString("ifname " + ifname + "\n")
	b.WriteString("user " + strconv.Quote(spec.Username) + "\n")
	password := cfg.Password
	if password == "" {
		password = spec.Password
	}
	if password != "" {
		b.WriteString("password " + strconv.Quote(password) + "\n")
	}
	b.WriteString("noauth\nhide-password\nnoipdefault\nusepeerdns\n")
	b.WriteString("nodetach\n")
	switch auth {
	case "pap":
		b.WriteString("-chap\n")
	case "chap":
		b.WriteString("-pap\n")
	}
	if spec.ServiceName != "" {
		b.WriteString("rp_pppoe_service " + strconv.Quote(spec.ServiceName) + "\n")
	}
	if spec.ACName != "" {
		b.WriteString("rp_pppoe_ac " + strconv.Quote(spec.ACName) + "\n")
	}
	b.WriteString(fmt.Sprintf("mtu %d\nmru %d\n", mtu, mru))
	b.WriteString(fmt.Sprintf("lcp-echo-interval %d\nlcp-echo-failure %d\n", lcpInterval, lcpFailure))
	return b.Bytes()
}

// FreeBSDMPDConf renders an isolated mpd5 client configuration. FreeBSD ppp(8)
// only reads its administrator-owned /etc/ppp/ppp.conf, so it cannot safely use
// a routerd private runtime directory.
func FreeBSDMPDConf(cfg Config) []byte {
	spec := cfg.Spec
	mtu := intDefault(spec.MTU, 1454)
	mru := intDefault(spec.MRU, 1454)
	lcpInterval := intDefault(spec.LCPEchoInterval, 20)
	lcpFailure := intDefault(spec.LCPEchoFailure, 3)
	label := SafeName(cfg.Resource)
	var b bytes.Buffer
	b.WriteString("# Generated by routerd-pppoe-client for mpd5. Do not edit by hand.\n")
	b.WriteString("default:\n")
	b.WriteString(" load " + label + "\n\n")
	b.WriteString(label + ":\n")
	b.WriteString(" create bundle static B" + label + "\n")
	b.WriteString(" set iface name " + cfg.IfName + "\n")
	b.WriteString(" set iface enable tcpmssfix\n")
	b.WriteString(" set ipcp ranges 0.0.0.0/0 0.0.0.0/0\n")
	b.WriteString(" create link static L" + label + " pppoe\n")
	b.WriteString(" set link action bundle B" + label + "\n")
	b.WriteString(" set auth authname " + strconv.Quote(spec.Username) + "\n")
	b.WriteString(" set auth password " + strconv.Quote(cfg.Password) + "\n")
	b.WriteString(" set link max-redial 0\n")
	b.WriteString(" set link mtu " + strconv.Itoa(mtu) + "\n")
	b.WriteString(" set link mru " + strconv.Itoa(mru) + "\n")
	b.WriteString(" set link keep-alive " + strconv.Itoa(lcpInterval) + " " + strconv.Itoa(lcpInterval*lcpFailure) + "\n")
	b.WriteString(" set pppoe iface " + cfg.Interface + "\n")
	if spec.ServiceName != "" {
		b.WriteString(" set pppoe service " + strconv.Quote(spec.ServiceName) + "\n")
	}
	if spec.ACName != "" {
		b.WriteString(" set pppoe acname " + strconv.Quote(spec.ACName) + "\n")
	}
	b.WriteString(" open\n")
	return b.Bytes()
}

func Command(cfg Config) (string, []string) {
	return CommandForOS(runtime.GOOS, cfg)
}

// CommandForOS exposes the platform command contract for tests without changing
// the runtime-selected behavior.
func CommandForOS(osName string, cfg Config) (string, []string) {
	if osName == "freebsd" {
		return "mpd5", []string{"-d", cfg.RuntimeDir, "-f", "mpd.conf", SafeName(cfg.Resource)}
	}
	return "pppd", []string{"file", cfg.RuntimeDir + "/peer.conf"}
}

func RuntimeConfigForOS(osName string, cfg Config) (string, []byte) {
	if osName == "freebsd" {
		return "mpd.conf", FreeBSDMPDConf(cfg)
	}
	return "peer.conf", LinuxPeer(cfg)
}

// RedactedRuntimeConfigForOS preserves the useful configuration shape in
// selftest output without returning a PPPoE password.
func RedactedRuntimeConfigForOS(osName string, cfg Config) []byte {
	_, config := RuntimeConfigForOS(osName, cfg)
	if cfg.Password == "" {
		return config
	}
	return []byte(strings.ReplaceAll(string(config), cfg.Password, "[REDACTED]"))
}

func ParseLogLine(snapshot Snapshot, line string, now time.Time) Snapshot {
	lower := strings.ToLower(line)
	snapshot.UpdatedAt = now.UTC()
	switch {
	case strings.Contains(lower, "chap authentication succeeded"), strings.Contains(lower, "pap authentication succeeded"):
		snapshot.Phase = PhaseIPCP
	case strings.Contains(lower, "ipcp"):
		if snapshot.Phase != PhaseConnected {
			snapshot.Phase = PhaseIPCP
		}
	case strings.Contains(lower, "local  ip address"):
		snapshot.CurrentAddress = lastIPv4(line)
		if snapshot.CurrentAddress != "" {
			snapshot.Phase = PhaseConnected
			if snapshot.ConnectedAt.IsZero() {
				snapshot.ConnectedAt = now.UTC()
			}
		}
	case strings.Contains(lower, "remote ip address"):
		snapshot.PeerAddress = lastIPv4(line)
	case strings.Contains(lower, "primary   dns address"), strings.Contains(lower, "secondary dns address"):
		if addr := lastIPv4(line); addr != "" && !contains(snapshot.DNSServers, addr) {
			snapshot.DNSServers = append(snapshot.DNSServers, addr)
		}
	case strings.Contains(lower, "authentication failed"), strings.Contains(lower, "connection terminated"):
		snapshot.Phase = PhaseFailed
		snapshot.LastError = strings.TrimSpace(line)
	}
	return snapshot
}

func SafeName(name string) string {
	var b strings.Builder
	for _, r := range name {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '-' || r == '_' {
			b.WriteRune(r)
			continue
		}
		b.WriteByte('-')
	}
	if b.Len() == 0 {
		return "unnamed"
	}
	return b.String()
}

func intDefault(value, fallback int) int {
	if value == 0 {
		return fallback
	}
	return value
}

func lastIPv4(line string) string {
	fields := strings.Fields(line)
	for i := len(fields) - 1; i >= 0; i-- {
		addr, err := netip.ParseAddr(strings.Trim(fields[i], ",;"))
		if err == nil && addr.Is4() {
			return addr.String()
		}
	}
	return ""
}

func contains(values []string, value string) bool {
	for _, candidate := range values {
		if candidate == value {
			return true
		}
	}
	return false
}

func resourceHash(value string) string {
	var h uint32 = 2166136261
	for i := 0; i < len(value); i++ {
		h ^= uint32(value[i])
		h *= 16777619
	}
	return fmt.Sprintf("%08x", h)[:8]
}
