// SPDX-License-Identifier: BSD-3-Clause

package dnsresolver

import (
	"reflect"
	"testing"

	"github.com/imksoo/routerd/pkg/api"
)

func TestParseDNSMasqHostRecords(t *testing.T) {
	data := []byte(`# Generated by routerd. Do not edit by hand.
18:ec:e7:33:12:6c,set:battery,nichicon-home-battery,172.18.0.150
9c:69:d3:ca:3a:aa,172.18.1.181,MacBookProM5Max,12h
fc:b2:14:8c:49:1a,172.18.1.127,MacBookProM5Max,12h
04:04:b8:0e:3b:50,172.18.1.142,12h
`)
	want := []RuntimeDHCPHostRecord{
		{Hostname: "MacBookProM5Max", IP: "172.18.1.127"},
		{Hostname: "MacBookProM5Max", IP: "172.18.1.181"},
		{Hostname: "nichicon-home-battery", IP: "172.18.0.150"},
	}
	if got := ParseDNSMasqHostRecords(data); !reflect.DeepEqual(got, want) {
		t.Fatalf("records = %#v, want %#v", got, want)
	}
}

func TestValidateAcceptsDNSResolverSources(t *testing.T) {
	err := Validate(api.DNSResolverSpec{
		Listen: []api.DNSResolverListenSpec{{Addresses: []string{"127.0.0.1"}, Port: 5053}},
		Sources: []api.DNSResolverSourceSpec{
			{Kind: "zone", Match: []string{"lab.example"}, ZoneRef: []string{"DNSZone/lan"}},
			{Kind: "forward", Match: []string{"transix.jp"}, Upstreams: []string{"udp://[2001:db8::53]:53"}},
			{Kind: "upstream", Match: []string{"."}, Upstreams: []string{"https://1.1.1.1/dns-query", "tls://dns.google", "quic://dns.google", "udp://8.8.8.8:53"}},
		},
	})
	if err != nil {
		t.Fatal(err)
	}
}

func TestValidateAcceptsListenAddressSources(t *testing.T) {
	err := Validate(api.DNSResolverSpec{
		Listen: []api.DNSResolverListenSpec{{
			Addresses:   []string{"172.18.0.1"},
			AddressFrom: []api.StatusValueSourceSpec{{Resource: "IPv6DelegatedAddress/lan-base", Field: "address"}},
			Port:        53,
		}},
		Sources: []api.DNSResolverSourceSpec{{Kind: "upstream", Match: []string{"."}, Upstreams: []string{"udp://1.1.1.1:53"}}},
	})
	if err != nil {
		t.Fatal(err)
	}
}

func TestNormalizeDNSResolverQueryLogDefaults(t *testing.T) {
	spec := NormalizeSpec(api.DNSResolverSpec{
		Listen:   []api.DNSResolverListenSpec{{Addresses: []string{"127.0.0.1"}, Port: 5053}},
		Sources:  []api.DNSResolverSourceSpec{{Kind: "upstream", Match: []string{"."}, Upstreams: []string{"udp://1.1.1.1:53"}}},
		QueryLog: api.DNSResolverQueryLogSpec{Enabled: true},
	})
	if spec.QueryLog.Path != "/var/lib/routerd/dns-queries.db" {
		t.Fatalf("query log defaults = %#v", spec.QueryLog)
	}
	if err := Validate(spec); err != nil {
		t.Fatalf("validate: %v", err)
	}
}

func TestValidateRejectsListenAddressStatusReference(t *testing.T) {
	err := Validate(api.DNSResolverSpec{
		Listen:  []api.DNSResolverListenSpec{{Addresses: []string{"${IPv6DelegatedAddress/lan-base.status.address}"}, Port: 53}},
		Sources: []api.DNSResolverSourceSpec{{Kind: "upstream", Match: []string{"."}, Upstreams: []string{"udp://1.1.1.1:53"}}},
	})
	if err == nil {
		t.Fatal("expected validation error")
	}
}

func TestValidateRejectsUnsupportedUpstreamScheme(t *testing.T) {
	err := Validate(api.DNSResolverSpec{
		Sources: []api.DNSResolverSourceSpec{{Kind: "upstream", Match: []string{"."}, Upstreams: []string{"http://dns.example/query"}}},
	})
	if err == nil {
		t.Fatal("expected validation error")
	}
}

func TestNormalizeUpstreamAcceptsBareAddresses(t *testing.T) {
	tests := map[string]string{
		"2001:db8::53":   "udp://[2001:db8::53]:53",
		"192.0.2.53":     "udp://192.0.2.53:53",
		"dns.example":    "udp://dns.example:53",
		"dns.example:54": "udp://dns.example:54",
	}
	for raw, want := range tests {
		if got := NormalizeUpstream(raw); got != want {
			t.Fatalf("NormalizeUpstream(%q) = %q, want %q", raw, got, want)
		}
		if err := ValidateUpstreamURL(raw); err != nil {
			t.Fatalf("ValidateUpstreamURL(%q): %v", raw, err)
		}
	}
}
