#!/bin/sh
# SPDX-License-Identifier: BSD-3-Clause
set -eu

out=${1:-THIRD_PARTY_LICENSES.md}
tmpdir=$(mktemp -d)
trap 'rm -rf "${tmpdir}"' EXIT INT TERM

license_file()
{
    dir=$1
    [ -d "${dir}" ] || {
        echo ""
        return 0
    }
    for file in LICENSE LICENSE.md LICENSE.txt COPYING COPYING.md COPYING.txt NOTICE NOTICE.txt; do
        if [ -f "${dir}/${file}" ]; then
            printf '%s\n' "${dir}/${file}"
            return 0
        fi
    done
    echo ""
}

license_label()
{
    file=$1
    [ -f "${file}" ] || {
        echo "unknown"
        return 0
    }
    if grep -qi 'Mozilla Public License[, ]*version 2.0' "${file}" || grep -qi 'Mozilla Public License Version 2.0' "${file}"; then
        echo "MPL-2.0"
    elif grep -qi 'GNU AFFERO GENERAL PUBLIC LICENSE' "${file}"; then
        echo "AGPL"
    elif grep -qi 'GNU LESSER GENERAL PUBLIC LICENSE' "${file}"; then
        echo "LGPL"
    elif grep -qi 'GNU GENERAL PUBLIC LICENSE' "${file}"; then
        echo "GPL"
    elif grep -qi 'Apache License' "${file}" && grep -qi 'Version 2.0' "${file}"; then
        echo "Apache-2.0"
    elif grep -qi 'Redistribution and use in source and binary forms' "${file}" && grep -qi 'Neither the name' "${file}"; then
        echo "BSD-3-Clause"
    elif grep -qi 'Redistribution and use in source and binary forms' "${file}"; then
        echo "BSD-style"
    elif grep -qi 'Permission is hereby granted, free of charge' "${file}"; then
        echo "MIT"
    elif grep -qi 'ISC License' "${file}"; then
        echo "ISC"
    else
        echo "unknown"
    fi
}

license_basename()
{
    file=$1
    [ -n "${file}" ] || {
        echo "not found in module cache"
        return 0
    }
    basename "${file}"
}

go_source_url()
{
    module=$1
    version=$2
    if [ "${module}" = "routerd" ]; then
        echo "https://github.com/imksoo/routerd"
        return 0
    fi
    if [ "${version}" = "(main module)" ] || [ -z "${version}" ]; then
        printf 'https://pkg.go.dev/%s\n' "${module}"
        return 0
    fi
    printf 'https://pkg.go.dev/%s@%s\n' "${module}" "${version}"
}

go_copyleft="${tmpdir}/go-copyleft"
: > "${go_copyleft}"

{
    echo "# Third-party licenses"
    echo
    echo "This file is generated by:"
    echo
    echo '```sh'
    echo "./scripts/collect-third-party-licenses.sh"
    echo '```'
    echo
    echo "routerd itself is distributed under the BSD 3-Clause License in"
    echo "[LICENSE](./LICENSE): Copyright (c) 2026 Kirino Minato"
    echo "<kirino.minato@gmail.com> (https://github.com/imksoo) and routerd"
    echo "contributors. Release archives and the live ISO also include third-party"
    echo "software. The live ISO is an aggregate distribution: each"
    echo "included operating-system package keeps its own upstream license and"
    echo "source availability path. The ISO is not relicensed as a single GPL work."
    echo
    echo "This file summarizes dependencies used to build, install, or boot routerd."
    echo "It is not a substitute for reviewing the original upstream license files."
    echo
    echo "## Go modules linked into routerd"
    echo
    echo "| Module | Version | Detected license | License file | Source URL |"
    echo "| --- | --- | --- | --- | --- |"
    go list -m -json all | awk '
        /"Path":/ {
            path = $2
            gsub(/[",]/, "", path)
        }
        /"Version":/ {
            version = $2
            gsub(/[",]/, "", version)
        }
        /"Dir":/ {
            dir = $2
            gsub(/[",]/, "", dir)
        }
        /^}/ {
            if (path != "") {
                if (version == "") version = "(main module)"
                if (dir == "") dir = "."
                print path "\t" version "\t" dir
            }
            path = ""; version = ""; dir = ""
        }
    ' | while IFS='	' read -r module version dir; do
        file=$(license_file "${dir}")
        label=$(license_label "${file}")
        case "${label}" in
            GPL|AGPL|LGPL)
                printf '%s %s %s\n' "${module}" "${version}" "${label}" >> "${go_copyleft}"
                ;;
        esac
        # shellcheck disable=SC2016 # Markdown backticks are literal output.
        printf '| `%s` | `%s` | `%s` | %s | %s |\n' "${module}" "${version}" "${label}" "$(license_basename "${file}")" "$(go_source_url "${module}" "${version}")"
    done
    echo
    echo "### Go module copyleft check"
    echo
    if [ -s "${go_copyleft}" ]; then
        echo "The following Go modules require manual review before binary distribution:"
        echo
        echo '```text'
        cat "${go_copyleft}"
        echo '```'
    else
        echo "No GPL, LGPL, or AGPL license text was detected in Go module license files."
        echo "This check is heuristic and should be reviewed before formal releases."
    fi
    echo
    echo "## Operating-system packages used by the live ISO"
    echo
    echo "The live ISO is based on Ubuntu Server. Ubuntu package source and license"
    echo "metadata is provided by the Ubuntu archive for the release used to build"
    echo "the ISO. The routerd live ISO build script copies routerd payload files into"
    echo "that base image and does not vendor those package sources into this"
    echo "repository."
    echo
    echo "## Optional runtime dependencies"
    echo
    echo "These packages are not bundled into routerd release archives or the"
    echo "default live ISO, but routerd can install or use them when the matching"
    echo "feature is explicitly enabled."
    echo
    echo "| Component | Package names | License | Source URL | Notes |"
    echo "| --- | --- | --- | --- | --- |"
    echo "| nDPI runtime | \`libndpi-bin\` (Debian/Ubuntu), \`ndpi\` (other package managers where available) | \`LGPL-3.0-only\` or upstream package license metadata | <https://github.com/ntop/nDPI> | Used by \`routerd-dpi-classifier\` as an external tool / IPC dependency; routerd does not statically link nDPI. |"
    echo
    echo "## Source availability"
    echo
    echo "- routerd source code is published at <https://github.com/imksoo/routerd>."
    echo "- routerd release tags use the \`vYYYYMMDD.HHmm\` format."
    echo "- Ubuntu package source information is available from Ubuntu archive"
    echo "  metadata for the release used as the live ISO base."
    echo "- The routerd live ISO combines routerd binaries, scripts, and base OS"
    echo "  packages as separate components with their own licenses."
} > "${out}"

if [ -s "${go_copyleft}" ]; then
    echo "warning: possible copyleft Go module license detected; review ${out}" >&2
fi

echo "wrote ${out}"
