// SPDX-License-Identifier: BSD-3-Clause

package chain

import (
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/imksoo/routerd/pkg/api"
	"github.com/imksoo/routerd/pkg/platform"
	"github.com/imksoo/routerd/pkg/resourcequery"
	routerstate "github.com/imksoo/routerd/pkg/state"
	"github.com/imksoo/routerd/pkg/vxlan"
)

const routerdGeneratedNetworkdHeader = "# Generated by routerd. Do not edit by hand."

type VXLANTunnelController struct {
	// Router is the effective router for this reconciliation generation.
	Router *api.Router
	// DeclaredRouter retains resources filtered from Router by spec.when. It is
	// required to perform fail-closed teardown on BACKUP and unknown HA roles.
	DeclaredRouter  *api.Router
	Store           Store
	DryRun          bool
	OperatingSystem platform.OS
	NetworkdDir     string
	Command         vxlan.CommandRunner
	ReadFile        func(string) ([]byte, error)
	RemoveFile      func(string) error
	StartedAt       time.Time
	Mu              *sync.Mutex
}

func (c VXLANTunnelController) Reconcile(ctx context.Context) error {
	if c.Mu != nil {
		c.Mu.Lock()
		defer c.Mu.Unlock()
	}
	if c.Store == nil {
		return nil
	}
	osName := c.OperatingSystem
	if osName == "" {
		osName = platform.CurrentOS()
	}
	if osName != platform.OSLinux {
		return nil
	}
	declared := c.DeclaredRouter
	if declared == nil {
		declared = c.Router
	}
	if declared == nil {
		return nil
	}
	if err := c.cleanupOrphanedOwnership(ctx, declared); err != nil {
		return err
	}

	effective := vxlansByName(c.Router)
	aliases := bridgeInterfaceAliases(declared)
	seen := map[string]bool{}
	for _, resource := range declared.Spec.Resources {
		if resource.Kind != "VXLANTunnel" {
			continue
		}
		seen[resource.Metadata.Name] = true
		gate := c.gateState(resource)
		active, retained := effective[resource.Metadata.Name]
		if !retained || gate != vxlanGateEnabled {
			reason := gate
			if gate == vxlanGateEnabled {
				reason = vxlanGateSuppressed
			}
			if err := c.teardownOne(ctx, resource, reason); err != nil {
				return err
			}
			continue
		}
		if err := c.reconcileResource(ctx, active, aliases); err != nil {
			return err
		}
	}

	// Dynamic effective resources are not necessarily present in the startup
	// router. Reconcile them too, but retain the same unknown-is-disabled gate.
	for name, resource := range effective {
		if seen[name] {
			continue
		}
		if gate := c.gateState(resource); gate != vxlanGateEnabled {
			if err := c.teardownOne(ctx, resource, gate); err != nil {
				return err
			}
			continue
		}
		if err := c.reconcileResource(ctx, resource, bridgeInterfaceAliases(c.Router)); err != nil {
			return err
		}
	}
	return nil
}

func (c VXLANTunnelController) cleanupOrphanedOwnership(ctx context.Context, declared *api.Router) error {
	retained := map[string]bool{}
	for _, resource := range declared.Spec.Resources {
		if resource.Kind == "VXLANTunnel" {
			spec, _ := resource.VXLANTunnelSpec()
			retained[firstNonEmpty(spec.IfName, resource.Metadata.Name)] = true
		}
	}
	base := strings.TrimSpace(c.NetworkdDir)
	if base == "" {
		defaults, _ := platform.Current()
		base = defaults.NetworkdDropinDir
	}
	if base == "" {
		base = "/etc/systemd/network"
	}
	entries, err := os.ReadDir(base)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return err
	}
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || !strings.HasPrefix(name, "31-routerd-") || !strings.HasSuffix(name, ".owner") {
			continue
		}
		ifname := strings.TrimSuffix(strings.TrimPrefix(name, "31-routerd-"), ".owner")
		if retained[ifname] {
			continue
		}
		data, err := c.readFile(filepath.Join(base, name))
		if err != nil {
			return err
		}
		cfg, ok := parseVXLANOwnership(data)
		if !ok || cfg.IfName != ifname {
			continue
		}
		resource := api.Resource{TypeMeta: api.TypeMeta{APIVersion: api.NetAPIVersion, Kind: "VXLANTunnel"}, Metadata: api.ObjectMeta{Name: "orphan-" + ifname}, Spec: api.VXLANTunnelSpec{IfName: ifname, VNI: cfg.VNI, LocalAddress: cfg.LocalAddress, Peers: cfg.Peers, UnderlayInterface: cfg.UnderlayInterface, UDPPort: cfg.UDPPort, MTU: cfg.MTU, Bridge: cfg.Bridge}}
		if err := c.teardownOne(ctx, resource, vxlanGateSuppressed); err != nil {
			return err
		}
	}
	return nil
}

func parseVXLANOwnership(data []byte) (vxlan.Config, bool) {
	if !strings.HasPrefix(string(data), routerdGeneratedNetworkdHeader) {
		return vxlan.Config{}, false
	}
	values := map[string]string{}
	for _, line := range strings.Split(string(data), "\n") {
		if key, value, ok := strings.Cut(line, "="); ok {
			values[key] = value
		}
	}
	vni, err1 := strconv.Atoi(values["vni"])
	port, err2 := strconv.Atoi(values["port"])
	mtu, err3 := strconv.Atoi(values["mtu"])
	if err1 != nil || err2 != nil || err3 != nil || values["ifname"] == "" {
		return vxlan.Config{}, false
	}
	peers := []string{}
	if values["peers"] != "" {
		peers = strings.Split(values["peers"], ",")
	}
	return vxlan.Config{IfName: values["ifname"], VNI: vni, LocalAddress: values["local"], UnderlayInterface: values["underlay"], UDPPort: port, MTU: mtu, Bridge: values["bridge"], Peers: peers}, true
}

type vxlanGateState string

const (
	vxlanGateEnabled    vxlanGateState = "Enabled"
	vxlanGateFalse      vxlanGateState = "WhenFalse"
	vxlanGateUnknown    vxlanGateState = "WhenUnknown"
	vxlanGateSuppressed vxlanGateState = "Suppressed"
)

func (c VXLANTunnelController) gateState(resource api.Resource) vxlanGateState {
	when := resourcequery.ResourceWhen(resource)
	if !resourcequery.ResourceWhenPresent(when) {
		return vxlanGateEnabled
	}
	state, ok := c.Store.(resourcequery.StateStore)
	if !ok || state == nil {
		return vxlanGateUnknown
	}
	if vxlanWhenAcceptsUnknown(when) {
		return vxlanGateUnknown
	}
	if resourcequery.ResourceWhenMatches(when, state) {
		if !c.whenFreshThisBoot(when, state) {
			return vxlanGateUnknown
		}
		return vxlanGateEnabled
	}
	if resourcequery.ResourceWhenIndeterminate(when, state) {
		return vxlanGateUnknown
	}
	return vxlanGateFalse
}

func vxlanWhenAcceptsUnknown(when api.ResourceWhenSpec) bool {
	for _, match := range when.State {
		if strings.EqualFold(match.Status, string(routerstate.StatusUnknown)) || strings.EqualFold(match.Equals, "unknown") {
			return true
		}
		for _, value := range match.In {
			if strings.EqualFold(value, "unknown") {
				return true
			}
		}
	}
	for _, child := range append(append([]api.ResourceWhenSpec(nil), when.All...), when.Any...) {
		if vxlanWhenAcceptsUnknown(child) {
			return true
		}
	}
	return false
}

func (c VXLANTunnelController) whenFreshThisBoot(when api.ResourceWhenSpec, state resourcequery.StateStore) bool {
	if c.StartedAt.IsZero() {
		return true
	}
	for name, match := range when.State {
		if !stateReferenceFresh(name, match, state, c.StartedAt) {
			return false
		}
	}
	for _, child := range append(append([]api.ResourceWhenSpec(nil), when.All...), when.Any...) {
		if !c.whenFreshThisBoot(child, state) {
			return false
		}
	}
	return true
}

func stateReferenceFresh(ref string, match api.StateMatchSpec, state resourcequery.StateStore, startedAt time.Time) bool {
	maxAge := 30 * time.Second
	if match.MaxAge != "" {
		parsed, err := time.ParseDuration(match.MaxAge)
		if err != nil || parsed <= 0 {
			return false
		}
		maxAge = parsed
	}
	now := state.Now().UTC()
	trimmed := strings.TrimSpace(strings.TrimSuffix(strings.TrimPrefix(ref, "${"), "}"))
	if left, _, ok := strings.Cut(trimmed, ".status."); ok {
		kind, name, valid := resourcequery.SplitResource(left)
		store, storeOK := state.(resourcequery.Store)
		if !valid || !storeOK {
			return false
		}
		status := store.ObjectStatus(resourcequery.APIVersionForKind(kind), kind, name)
		for _, key := range []string{"observedAt", "updatedAt", "lastTransitionAt"} {
			if observed, err := time.Parse(time.RFC3339Nano, strings.TrimSpace(fmt.Sprint(status[key]))); err == nil {
				return !observed.Before(startedAt) && now.Sub(observed) <= maxAge
			}
		}
		return false
	}
	value := state.Get(ref)
	return !value.UpdatedAt.IsZero() && !value.UpdatedAt.Before(startedAt) && now.Sub(value.UpdatedAt) <= maxAge
}

func vxlansByName(router *api.Router) map[string]api.Resource {
	out := map[string]api.Resource{}
	if router == nil {
		return out
	}
	for _, resource := range router.Spec.Resources {
		if resource.Kind == "VXLANTunnel" {
			out[resource.Metadata.Name] = resource
		}
	}
	return out
}

func (c VXLANTunnelController) reconcileResource(ctx context.Context, resource api.Resource, aliases map[string]string) error {
	spec, err := resource.VXLANTunnelSpec()
	if err != nil {
		return err
	}
	cfg := vxlan.Config{
		Name:              resource.Metadata.Name,
		IfName:            firstNonEmpty(spec.IfName, resource.Metadata.Name),
		VNI:               spec.VNI,
		LocalAddress:      spec.LocalAddress,
		Peers:             append([]string(nil), spec.Peers...),
		UnderlayInterface: aliases[spec.UnderlayInterface],
		UDPPort:           spec.UDPPort,
		MTU:               spec.MTU,
		Bridge:            aliases[spec.Bridge],
	}
	if cfg.UnderlayInterface == "" {
		cfg.UnderlayInterface = spec.UnderlayInterface
	}
	if spec.Bridge != "" && cfg.Bridge == "" {
		cfg.Bridge = spec.Bridge
	}
	return c.reconcileOne(ctx, resource, cfg)
}

func (c VXLANTunnelController) reconcileOne(ctx context.Context, resource api.Resource, cfg vxlan.Config) error {
	status := c.baseStatus(cfg)
	status["gateState"] = string(vxlanGateEnabled)
	if c.DryRun {
		status["phase"] = "Planned"
		return c.Store.SaveObjectStatus(api.NetAPIVersion, "VXLANTunnel", resource.Metadata.Name, status)
	}

	observed, showErr := c.command(ctx, "ip", "-details", "link", "show", "dev", cfg.IfName)
	if showErr != nil && !linkObservationMissing(observed, showErr) {
		status["phase"], status["reason"], status["forwarding"], status["error"] = "Error", "LinkObserveFailed", "unknown", showErr.Error()
		return c.Store.SaveObjectStatus(api.NetAPIVersion, "VXLANTunnel", resource.Metadata.Name, status)
	}
	ownedArtifact, foreignArtifact, err := c.artifactOwnership(cfg.IfName)
	if err != nil {
		return err
	}
	ownerCfg, hasOwnerCfg, err := c.ownershipConfig(cfg.IfName)
	if err != nil {
		return err
	}
	provenOwned := hasOwnerCfg && vxlanDetailsConfigMatch(string(observed), ownerCfg)
	if !hasOwnerCfg && ownedArtifact {
		provenOwned = vxlanDetailsConfigMatch(string(observed), cfg)
	}
	if showErr == nil && !provenOwned {
		status["phase"] = "RequiresAdoption"
		status["reason"] = "ForeignInterface"
		status["forwarding"] = "unknown"
		status["managedBy"] = "external"
		return c.Store.SaveObjectStatus(api.NetAPIVersion, "VXLANTunnel", resource.Metadata.Name, status)
	}
	if foreignArtifact {
		status["phase"] = "RequiresAdoption"
		status["reason"] = "ForeignPersistentArtifact"
		status["forwarding"] = "unknown"
		status["managedBy"] = "external"
		return c.Store.SaveObjectStatus(api.NetAPIVersion, "VXLANTunnel", resource.Metadata.Name, status)
	}
	legacyRemoved, err := c.removeOwnedLegacyArtifacts(cfg.IfName)
	if err != nil {
		return err
	}
	if legacyRemoved {
		if _, err := c.command(ctx, "networkctl", "reload"); err != nil {
			return fmt.Errorf("reload after removing legacy VXLAN artifacts: %w", err)
		}
	}
	changed, err := c.persistOwnership(cfg)
	if err != nil {
		return err
	}
	// Ownership is asserted only after foreign-state checks and a successful
	// write/read of routerd-marked persistent artifacts. Never stamp it into a
	// generic, planned, blocked, or adoption status: that status would become a
	// false ownership proof on the next reconciliation.
	status["managedBy"] = "routerd"
	status["restartPersistent"] = false
	_ = changed

	if showErr != nil {
		if err := c.createVXLANDown(ctx, cfg); err != nil {
			status["phase"] = "Error"
			status["reason"] = "CreateFailed"
			status["error"] = err.Error()
			_ = c.Store.SaveObjectStatus(api.NetAPIVersion, "VXLANTunnel", resource.Metadata.Name, status)
			return fmt.Errorf("VXLANTunnel/%s create failed: %w", resource.Metadata.Name, err)
		}
		status["created"] = true
	} else if !vxlanDetailsMatch(string(observed), cfg) {
		if _, err := c.command(ctx, "ip", "link", "set", "dev", cfg.IfName, "down"); err != nil {
			return err
		}
		if _, err := c.command(ctx, "ip", "link", "delete", "dev", cfg.IfName); err != nil {
			return err
		}
		if err := c.createVXLANDown(ctx, cfg); err != nil {
			return err
		}
		status["recreated"] = true
	} else {
		if cfg.MTU != 0 {
			if _, err := c.command(ctx, "ip", "link", "set", "dev", cfg.IfName, "mtu", fmt.Sprint(cfg.MTU)); err != nil {
				return err
			}
		}
		if cfg.Bridge != "" {
			if _, err := c.command(ctx, "ip", "link", "set", "dev", cfg.IfName, "master", cfg.Bridge); err != nil {
				return err
			}
		}
	}
	if c.gateState(resource) != vxlanGateEnabled {
		return c.teardownOne(ctx, resource, vxlanGateUnknown)
	}
	if err := c.reconcileFloodFDB(ctx, cfg); err != nil {
		return err
	}
	if c.gateState(resource) != vxlanGateEnabled {
		return c.teardownOne(ctx, resource, vxlanGateUnknown)
	}
	if _, err := c.command(ctx, "ip", "link", "set", "dev", cfg.IfName, "up"); err != nil {
		return err
	}
	observed, err = c.command(ctx, "ip", "-details", "link", "show", "dev", cfg.IfName)
	if err != nil || !vxlanDetailsMatch(string(observed), cfg) {
		status["phase"] = "Drifted"
		status["reason"] = "ReadbackMismatch"
		status["forwarding"] = false
		if err != nil {
			status["error"] = err.Error()
		}
		return c.Store.SaveObjectStatus(api.NetAPIVersion, "VXLANTunnel", resource.Metadata.Name, status)
	}
	if c.gateState(resource) != vxlanGateEnabled {
		return c.teardownOne(ctx, resource, vxlanGateUnknown)
	}
	status["phase"] = "Healthy"
	status["forwarding"] = true
	status["lastEnabledAt"] = time.Now().UTC().Format(time.RFC3339Nano)
	return c.Store.SaveObjectStatus(api.NetAPIVersion, "VXLANTunnel", resource.Metadata.Name, status)
}

func (c VXLANTunnelController) createVXLANDown(ctx context.Context, cfg vxlan.Config) error {
	for _, command := range vxlan.Commands(cfg) {
		joined := strings.Join(command, " ")
		if strings.Contains(joined, " link set dev "+cfg.IfName+" up") || (len(command) > 1 && command[0] == "bridge" && command[1] == "fdb") {
			continue
		}
		if _, err := c.command(ctx, command[0], command[1:]...); err != nil {
			return err
		}
	}
	return nil
}

func (c VXLANTunnelController) reconcileFloodFDB(ctx context.Context, cfg vxlan.Config) error {
	out, err := c.command(ctx, "bridge", "fdb", "show", "dev", cfg.IfName)
	if err != nil {
		return fmt.Errorf("read flood FDB on %s: %w", cfg.IfName, err)
	}
	desired := map[string]bool{}
	for _, peer := range cfg.Peers {
		desired[peer] = true
	}
	observed := allZeroFDBDestinations(string(out))
	for _, peer := range sortedFDBDestinations(observed) {
		if desired[peer] {
			continue
		}
		if _, err := c.command(ctx, "bridge", "fdb", "del", "00:00:00:00:00:00", "dev", cfg.IfName, "dst", peer); err != nil {
			return fmt.Errorf("delete stale flood FDB %s from %s: %w", peer, cfg.IfName, err)
		}
	}
	for _, peer := range cfg.Peers {
		if observed[peer] {
			continue
		}
		if _, err := c.command(ctx, "bridge", "fdb", "append", "00:00:00:00:00:00", "dev", cfg.IfName, "dst", peer); err != nil {
			return err
		}
	}
	readback, err := c.command(ctx, "bridge", "fdb", "show", "dev", cfg.IfName)
	if err != nil {
		return fmt.Errorf("read back flood FDB on %s: %w", cfg.IfName, err)
	}
	actual := allZeroFDBDestinations(string(readback))
	if len(actual) != len(desired) {
		return fmt.Errorf("flood FDB readback mismatch on %s", cfg.IfName)
	}
	for peer := range desired {
		if !actual[peer] {
			return fmt.Errorf("flood FDB peer %s missing on %s", peer, cfg.IfName)
		}
	}
	return nil
}

func sortedFDBDestinations(destinations map[string]bool) []string {
	peers := make([]string, 0, len(destinations))
	for peer := range destinations {
		peers = append(peers, peer)
	}
	sort.Strings(peers)
	return peers
}

func allZeroFDBDestinations(output string) map[string]bool {
	out := map[string]bool{}
	for _, line := range strings.Split(output, "\n") {
		fields := strings.Fields(line)
		if len(fields) < 3 || fields[0] != "00:00:00:00:00:00" {
			continue
		}
		for i := 1; i+1 < len(fields); i++ {
			if fields[i] == "dst" {
				out[fields[i+1]] = true
				break
			}
		}
	}
	return out
}

func (c VXLANTunnelController) teardownOne(ctx context.Context, resource api.Resource, gate vxlanGateState) error {
	spec, err := resource.VXLANTunnelSpec()
	if err != nil {
		return err
	}
	ifname := firstNonEmpty(spec.IfName, resource.Metadata.Name)
	status := c.baseStatus(vxlan.Config{Name: resource.Metadata.Name, IfName: ifname, VNI: spec.VNI, LocalAddress: spec.LocalAddress, Peers: spec.Peers, UnderlayInterface: spec.UnderlayInterface, MTU: spec.MTU, Bridge: spec.Bridge})
	status["gateState"] = string(gate)
	status["forwarding"] = false
	if c.DryRun {
		status["phase"] = "Planned"
		status["reason"] = "WouldDisable"
		return c.Store.SaveObjectStatus(api.NetAPIVersion, "VXLANTunnel", resource.Metadata.Name, status)
	}

	ownedArtifact, foreignArtifact, err := c.artifactOwnership(ifname)
	if err != nil {
		return err
	}
	aliases := bridgeInterfaceAliases(c.DeclaredRouter)
	cfg := vxlan.Config{Name: resource.Metadata.Name, IfName: ifname, VNI: spec.VNI, LocalAddress: spec.LocalAddress, Peers: spec.Peers, UnderlayInterface: aliases[spec.UnderlayInterface], UDPPort: spec.UDPPort, MTU: spec.MTU, Bridge: aliases[spec.Bridge]}
	if cfg.UnderlayInterface == "" {
		cfg.UnderlayInterface = spec.UnderlayInterface
	}
	if spec.Bridge != "" && cfg.Bridge == "" {
		cfg.Bridge = spec.Bridge
	}
	observed, showErr := c.command(ctx, "ip", "-details", "link", "show", "dev", ifname)
	if showErr != nil && !linkObservationMissing(observed, showErr) {
		return c.saveTeardownError(resource, status, "LinkObserveFailed", showErr)
	}
	linkExists := showErr == nil
	ownerCfg, hasOwnerCfg, err := c.ownershipConfig(ifname)
	if err != nil {
		return err
	}
	ownedLink := hasOwnerCfg && vxlanDetailsConfigMatch(string(observed), ownerCfg)
	if !hasOwnerCfg && ownedArtifact {
		ownedLink = vxlanDetailsConfigMatch(string(observed), cfg)
	}
	foreignPreserved := foreignArtifact
	if (foreignArtifact && !ownedLink) || (linkExists && !ownedLink) {
		if linkExists && ownedArtifact {
			_, _ = c.command(ctx, "ip", "link", "set", "dev", ifname, "down")
		}
		status["phase"] = "Blocked"
		status["reason"] = "ForeignStateWhileGated"
		status["forwarding"] = "unknown"
		status["managedBy"] = "external"
		status["error"] = "refusing to mutate an unowned VXLAN link or persistent artifact"
		return c.Store.SaveObjectStatus(api.NetAPIVersion, "VXLANTunnel", resource.Metadata.Name, status)
	}

	if linkExists {
		// Link-down is the first mutation: it closes forwarding before any
		// potentially slow FDB or persistent-artifact cleanup.
		if _, err := c.command(ctx, "ip", "link", "set", "dev", ifname, "down"); err != nil {
			return c.saveTeardownError(resource, status, "LinkDownFailed", err)
		}
	}
	removed, err := c.removeOwnedArtifacts(ifname)
	if err != nil {
		return c.saveTeardownError(resource, status, "ArtifactDeleteFailed", err)
	}
	if removed {
		if _, err := c.command(ctx, "networkctl", "reload"); err != nil {
			return c.saveTeardownError(resource, status, "NetworkdReloadFailed", err)
		}
	}
	if linkExists {
		fdb, _ := c.command(ctx, "bridge", "fdb", "show", "dev", ifname)
		for _, peer := range sortedFDBDestinations(allZeroFDBDestinations(string(fdb))) {
			if _, err := c.command(ctx, "bridge", "fdb", "del", "00:00:00:00:00:00", "dev", ifname, "dst", peer); err != nil {
				return c.saveTeardownError(resource, status, "FDBDeleteFailed", err)
			}
		}
		if _, err := c.command(ctx, "ip", "link", "set", "dev", ifname, "nomaster"); err != nil {
			return c.saveTeardownError(resource, status, "DetachFailed", err)
		}
		if _, err := c.command(ctx, "ip", "link", "delete", "dev", ifname); err != nil {
			return c.saveTeardownError(resource, status, "LinkDeleteFailed", err)
		}
		status["deleted"] = true
	}
	finalObserved, finalErr := c.command(ctx, "ip", "-details", "link", "show", "dev", ifname)
	if finalErr == nil {
		_, _ = c.command(ctx, "ip", "link", "set", "dev", ifname, "down")
		return c.saveTeardownError(resource, status, "LinkReappeared", fmt.Errorf("VXLAN link %s still exists after teardown", ifname))
	}
	if !linkObservationMissing(finalObserved, finalErr) {
		return c.saveTeardownError(resource, status, "LinkVerifyFailed", finalErr)
	}
	if foreignPreserved {
		status["phase"], status["reason"], status["forwarding"], status["managedBy"] = "Error", "ForeignArtifactPreserved", false, "external"
		status["error"] = "forwarding removed; foreign persistent artifact preserved"
		return c.Store.SaveObjectStatus(api.NetAPIVersion, "VXLANTunnel", resource.Metadata.Name, status)
	}
	status["phase"] = "Disabled"
	status["reason"] = string(gate)
	status["lastDisabledAt"] = time.Now().UTC().Format(time.RFC3339Nano)
	return c.Store.SaveObjectStatus(api.NetAPIVersion, "VXLANTunnel", resource.Metadata.Name, status)
}

func linkObservationMissing(output []byte, err error) bool {
	if err == nil {
		return false
	}
	text := strings.ToLower(string(output) + " " + err.Error())
	for _, marker := range []string{"not found", "does not exist", "cannot find device", "no such device"} {
		if strings.Contains(text, marker) {
			return true
		}
	}
	return false
}

func (c VXLANTunnelController) saveTeardownError(resource api.Resource, status map[string]any, reason string, err error) error {
	status["phase"] = "Error"
	status["reason"] = reason
	status["error"] = err.Error()
	_ = c.Store.SaveObjectStatus(api.NetAPIVersion, "VXLANTunnel", resource.Metadata.Name, status)
	return fmt.Errorf("VXLANTunnel/%s fail-closed teardown: %w", resource.Metadata.Name, err)
}

func (c VXLANTunnelController) baseStatus(cfg vxlan.Config) map[string]any {
	return map[string]any{
		"phase":          "Pending",
		"ifname":         cfg.IfName,
		"vni":            cfg.VNI,
		"localAddress":   cfg.LocalAddress,
		"underlayIfname": cfg.UnderlayInterface,
		"bridgeIfname":   cfg.Bridge,
		"peers":          append([]string(nil), cfg.Peers...),
		"observedAt":     time.Now().UTC().Format(time.RFC3339Nano),
	}
}

func (c VXLANTunnelController) persistOwnership(cfg vxlan.Config) (bool, error) {
	data := []byte(fmt.Sprintf("%s\nifname=%s\nvni=%d\nlocal=%s\nunderlay=%s\nport=%d\nmtu=%d\nbridge=%s\npeers=%s\n", routerdGeneratedNetworkdHeader, cfg.IfName, cfg.VNI, cfg.LocalAddress, cfg.UnderlayInterface, cfg.UDPPort, cfg.MTU, cfg.Bridge, strings.Join(cfg.Peers, ",")))
	path := c.artifactPaths(cfg.IfName)[0]
	if current, err := c.readFile(path); err == nil && string(current) == string(data) {
		return false, nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return false, err
	}
	tmp, err := os.CreateTemp(filepath.Dir(path), ".routerd-vxlan-owner-*")
	if err != nil {
		return false, err
	}
	tmpPath := tmp.Name()
	committed := false
	defer func() {
		if !committed {
			_ = os.Remove(tmpPath)
		}
	}()
	if err := tmp.Chmod(0o600); err != nil {
		_ = tmp.Close()
		return false, err
	}
	if _, err := tmp.Write(data); err != nil {
		_ = tmp.Close()
		return false, err
	}
	if err := tmp.Sync(); err != nil {
		_ = tmp.Close()
		return false, err
	}
	if err := tmp.Close(); err != nil {
		return false, err
	}
	if err := os.Rename(tmpPath, path); err != nil {
		return false, err
	}
	committed = true
	if dir, err := os.Open(filepath.Dir(path)); err == nil {
		_ = dir.Sync()
		_ = dir.Close()
	}
	return true, nil
}

func (c VXLANTunnelController) networkdPath(path string) string {
	base := strings.TrimSpace(c.NetworkdDir)
	if base == "" {
		defaults, _ := platform.Current()
		base = defaults.NetworkdDropinDir
	}
	if base == "" {
		base = "/etc/systemd/network"
	}
	rel := strings.TrimPrefix(filepath.Clean(path), filepath.Clean("/etc/systemd/network"))
	return filepath.Join(base, strings.TrimPrefix(rel, string(filepath.Separator)))
}

func (c VXLANTunnelController) artifactPaths(ifname string) []string {
	return []string{
		c.networkdPath(filepath.Join("/etc/systemd/network", "31-routerd-"+ifname+".owner")),
		// Legacy auto-activating artifacts are cleanup-only. Gated VXLANs are
		// runtime resources and must never be recreated before fresh predicates.
		c.networkdPath(filepath.Join("/etc/systemd/network", "31-routerd-"+ifname+".netdev")),
		c.networkdPath(filepath.Join("/etc/systemd/network", "31-routerd-"+ifname+".network")),
	}
}

func (c VXLANTunnelController) artifactOwnership(ifname string) (owned, foreign bool, err error) {
	for _, path := range c.artifactPaths(ifname) {
		data, readErr := c.readFile(path)
		if errors.Is(readErr, os.ErrNotExist) {
			continue
		}
		if readErr != nil {
			return false, false, readErr
		}
		if strings.HasPrefix(string(data), routerdGeneratedNetworkdHeader) {
			owned = true
		} else {
			foreign = true
		}
	}
	return owned, foreign, nil
}

func (c VXLANTunnelController) ownershipConfig(ifname string) (vxlan.Config, bool, error) {
	data, err := c.readFile(c.artifactPaths(ifname)[0])
	if errors.Is(err, os.ErrNotExist) {
		return vxlan.Config{}, false, nil
	}
	if err != nil {
		return vxlan.Config{}, false, err
	}
	cfg, ok := parseVXLANOwnership(data)
	return cfg, ok, nil
}

func (c VXLANTunnelController) removeOwnedArtifacts(ifname string) (bool, error) {
	removed := false
	for _, path := range c.artifactPaths(ifname) {
		data, err := c.readFile(path)
		if errors.Is(err, os.ErrNotExist) {
			continue
		}
		if err != nil {
			return removed, err
		}
		if !strings.HasPrefix(string(data), routerdGeneratedNetworkdHeader) {
			continue
		}
		if err := c.removeFile(path); err != nil && !errors.Is(err, os.ErrNotExist) {
			return removed, err
		}
		removed = true
	}
	return removed, nil
}

func (c VXLANTunnelController) removeOwnedLegacyArtifacts(ifname string) (bool, error) {
	removed := false
	paths := c.artifactPaths(ifname)
	for _, path := range paths[1:] {
		data, err := c.readFile(path)
		if errors.Is(err, os.ErrNotExist) {
			continue
		}
		if err != nil {
			return removed, err
		}
		if !strings.HasPrefix(string(data), routerdGeneratedNetworkdHeader) {
			continue
		}
		if err := c.removeFile(path); err != nil && !errors.Is(err, os.ErrNotExist) {
			return removed, err
		}
		removed = true
	}
	return removed, nil
}

func (c VXLANTunnelController) readFile(path string) ([]byte, error) {
	if c.ReadFile != nil {
		return c.ReadFile(path)
	}
	return os.ReadFile(path)
}

func (c VXLANTunnelController) removeFile(path string) error {
	if c.RemoveFile != nil {
		return c.RemoveFile(path)
	}
	return os.Remove(path)
}

func (c VXLANTunnelController) command(ctx context.Context, name string, args ...string) ([]byte, error) {
	if c.Command != nil {
		return c.Command(ctx, name, args...)
	}
	return exec.CommandContext(ctx, name, args...).CombinedOutput()
}

func vxlanDetailsMatch(observed string, cfg vxlan.Config) bool {
	return vxlanLinkFlag(observed, "UP") && vxlanDetailsConfigMatch(observed, cfg)
}

func vxlanLinkFlag(observed, wanted string) bool {
	start := strings.Index(observed, "<")
	end := strings.Index(observed, ">")
	if start < 0 || end <= start {
		return false
	}
	for _, flag := range strings.Split(observed[start+1:end], ",") {
		if strings.TrimSpace(flag) == wanted {
			return true
		}
	}
	return false
}

func vxlanDetailsConfigMatch(observed string, cfg vxlan.Config) bool {
	port := cfg.UDPPort
	if port == 0 {
		port = 4789
	}
	for _, want := range []string{
		"vxlan id " + fmt.Sprint(cfg.VNI),
		"local " + cfg.LocalAddress,
		"dev " + cfg.UnderlayInterface,
		"dstport " + fmt.Sprint(port),
		"nolearning",
	} {
		if !strings.Contains(observed, want) {
			return false
		}
	}
	if cfg.MTU != 0 && !strings.Contains(observed, " mtu "+fmt.Sprint(cfg.MTU)+" ") {
		return false
	}
	if cfg.Bridge != "" && !strings.Contains(observed, "master "+cfg.Bridge) {
		return false
	}
	return true
}
