// SPDX-License-Identifier: BSD-3-Clause

import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    'install-and-upgrade',
    {
      type: 'category',
      label: 'Concepts',
      collapsed: false,
      items: [
        'concepts/what-is-routerd',
        'concepts/positioning',
        'concepts/design-philosophy',
        'concepts/resource-model',
        'concepts/apply-and-render',
        'concepts/state-and-ownership',
        'concepts/path-mtu',
        'concepts/web-console',
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      collapsed: false,
      items: [
        'tutorials/index',
        'tutorials/getting-started',
        'tutorials/install',
        'tutorials/diskless-minipc-walkthrough',
        'tutorials/first-router',
        'tutorials/wan-side-services',
        'tutorials/lan-side-services',
        'tutorials/basic-firewall',
        'tutorials/nixos-getting-started',
        'tutorials/freebsd-getting-started',
      ],
    },
    {
      type: 'category',
      label: 'Configuration examples',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'config-examples'}],
    },
    {
      type: 'category',
      label: 'How-to',
      items: [
        'how-to/flets-ipv6-setup',
        'how-to/multi-wan',
        'how-to/os-bootstrap',
        'how-to/guest-mode',
        'how-to/tailscale',
        'how-to/opentelemetry',
        'how-to/pve-overlay',
        'how-to/troubleshooting',
      ],
    },
    {
      type: 'category',
      label: 'Knowledge base',
      items: [
        'knowledge-base/dhcpv6-pd-clients',
        'knowledge-base/ntt-ngn-pd-acquisition',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        'api-v1alpha1',
        'resource-ownership',
        'control-api-v1alpha1',
        'plugin-protocol',
        'platforms',
        'hardware-compatibility',
        'contributing',
        'legal',
      ],
    },
    {
      type: 'category',
      label: 'Operations',
      items: [
        'operations/reconcile',
        'operations/state-database',
        'operations/inventory',
        'operations/usb-persistence',
        'operations/secrets',
        'operations/ingress-maintenance',
        'operations/development',
        'operations/ndpi-agent-libndpi',
      ],
    },
    {
      type: 'category',
      label: 'Design notes',
      collapsed: true,
      items: [
        'design-notes',
      ],
    },
    {
      type: 'category',
      label: 'Releases',
      items: [
        'releases/changelog',
      ],
    },
  ],
};

export default sidebars;
