// SPDX-License-Identifier: BSD-3-Clause

import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Information architecture (IA):
// Goal-oriented labels. Each document appears exactly once (no duplicates).
// Start / Learn / Build / examples / tutorials / how-to / KB / operate /
// reference / releases / design / project.

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Start',
      collapsed: false,
      items: [
        'intro',
        'concepts/what-is-routerd',
        'concepts/positioning',
        'concepts/design-philosophy',
        'install-and-upgrade',
        'tutorials/index',
        'tutorials/getting-started',
        'tutorials/first-router',
      ],
    },
    {
      type: 'category',
      label: 'Learn',
      collapsed: false,
      items: [
        'concepts/glossary',
        'concepts/resource-model',
        'concepts/apply-and-render',
        'concepts/state-and-ownership',
        'resource-ownership',
        'operations/reconcile',
        'concepts/cloudedge-sam',
        'concepts/path-mtu',
        'concepts/web-console',
      ],
    },
    {
      type: 'category',
      label: 'Build',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'DNS resolver',
          items: [
            'concepts/dns-resolver',
            'how-to/dns-private-upstream',
            'how-to/dns-local-zone',
          ],
        },
        {
          type: 'category',
          label: 'Firewall',
          items: [
            'concepts/firewall',
            'how-to/firewall-zone',
            'how-to/firewall-rule',
          ],
        },
        {
          type: 'category',
          label: 'Egress & multi-WAN',
          items: [
            'concepts/egress-route',
            'how-to/multi-wan',
          ],
        },
        'design/bgp-frr-control-plane',
        'how-to/tailscale',
        'how-to/opentelemetry',
        'concepts/sysctl-profile',
        'concepts/log-storage',
      ],
    },
    {
      type: 'category',
      label: 'Configuration examples',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'config-examples'}],
    },
    {
      type: 'category',
      label: 'Tutorials',
      collapsed: true,
      items: [
        'tutorials/wan-side-services',
        'tutorials/lan-side-services',
        'tutorials/basic-firewall',
        'tutorials/nixos-getting-started',
        'tutorials/freebsd-getting-started',
        'tutorials/diskless-minipc-walkthrough',
        'tutorials/install',
      ],
    },
    {
      type: 'category',
      label: 'How-to guides',
      collapsed: true,
      items: [
        'how-to/flets-ipv6-setup',
        'how-to/ipv6-dual-stack',
        'how-to/dhcp-lease-sync',
        'how-to/nat44-session-sync',
        'how-to/vscode-yaml-schema',
        'how-to/guest-mode',
        'how-to/os-bootstrap',
        'how-to/pve-overlay',
        'how-to/hybrid-azure-pve-same-subnet',
        'how-to/event-federation-subscription',
        'how-to/cloudedge-sam-oci-firewall-bootstrap',
        'how-to/cloudedge-mobility-demo',
        'how-to/aws-provider-action-execution',
        'how-to/troubleshooting',
      ],
    },
    {
      type: 'category',
      label: 'Knowledge base',
      collapsed: true,
      items: [
        'knowledge-base/dhcpv6-pd-clients',
        'knowledge-base/ntt-ngn-pd-acquisition',
      ],
    },
    {
      type: 'category',
      label: 'Operate',
      collapsed: true,
      items: [
        'operations/routerctl-doctor',
        'operations/state-database',
        'operations/inventory',
        'operations/usb-persistence',
        'operations/alpine-deployment',
        'operations/secrets',
        'operations/observability',
        'operations/otel-dashboards',
        'operations/high-availability',
        'operations/ingress-maintenance',
        'operations/development',
        'operations/ndpi-agent-libndpi',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: true,
      items: [
        'api-v1alpha1',
        'reference/selective-address-mobility',
        'reference/cloudedge-sam-internals',
        'reference/event-federation',
        'control-api-v1alpha1',
        'plugin-protocol',
        'platforms',
        'hardware-compatibility',
      ],
    },
    {
      type: 'category',
      label: 'Releases',
      collapsed: false,
      items: [
        'releases/stable',
        'releases/changelog',
        'operations/release-process',
      ],
    },
    {
      type: 'category',
      label: 'Design notes',
      collapsed: true,
      items: [
        'design',
        'design-notes',
        'design/cloudedge-sam-provider-fabric',
      ],
    },
    {
      type: 'category',
      label: 'Project',
      collapsed: true,
      items: [
        'contributing',
        'legal',
      ],
    },
  ],
};

export default sidebars;
