// SPDX-License-Identifier: BSD-3-Clause

import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// 情報設計（IA）の方針:
// 商用ルーター（NEC IX / ヤマハ RTX）と VyOS、宣言型言語（Kubernetes/Terraform）の
// 構成を参考に、「はじめに → 導入 → 機能解説（宣言型モデル）→ 機能別設定リファレンス →
// 設定例集 → How-to → 運用 → リファレンス → リリース → 設計」の流れで並べる。
// 各ドキュメントは 1 か所だけに登場させる（重複禁止）。

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'はじめに',
      collapsed: false,
      items: [
        'intro',
        'concepts/what-is-routerd',
        'concepts/positioning',
        'concepts/design-philosophy',
      ],
    },
    {
      type: 'category',
      label: '導入（クイックスタート）',
      collapsed: false,
      items: [
        'install-and-upgrade',
        'tutorials/index',
        'tutorials/getting-started',
        'tutorials/install',
        'tutorials/first-router',
        'tutorials/wan-side-services',
        'tutorials/lan-side-services',
        'tutorials/basic-firewall',
        'tutorials/nixos-getting-started',
        'tutorials/freebsd-getting-started',
        'tutorials/diskless-minipc-walkthrough',
      ],
    },
    {
      type: 'category',
      label: '機能解説（宣言型モデル）',
      collapsed: false,
      items: [
        'concepts/glossary',
        'concepts/resource-model',
        'concepts/apply-and-render',
        'concepts/state-and-ownership',
        'resource-ownership',
        'operations/reconcile',
        'concepts/path-mtu',
        'concepts/web-console',
      ],
    },
    {
      type: 'category',
      label: '設定リファレンス（機能別）',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'DNS リゾルバ',
          items: [
            'concepts/dns-resolver',
            'how-to/dns-private-upstream',
            'how-to/dns-local-zone',
          ],
        },
        {
          type: 'category',
          label: 'ファイアウォール',
          items: [
            'concepts/firewall',
            'how-to/firewall-zone',
            'how-to/firewall-rule',
          ],
        },
        {
          type: 'category',
          label: 'Egress・マルチ WAN',
          items: [
            'concepts/egress-route',
            'how-to/multi-wan',
          ],
        },
        'design/bgp-frr-control-plane',
        'how-to/tailscale',
        'how-to/opentelemetry',
        'concepts/sysctl-profile',
        'concepts/log-storage',
      ],
    },
    {
      type: 'category',
      label: '設定例集（シナリオ別）',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'config-examples'}],
    },
    {
      type: 'category',
      label: 'How-to ガイド',
      collapsed: true,
      items: [
        'how-to/flets-ipv6-setup',
        'how-to/ipv6-dual-stack',
        'how-to/guest-mode',
        'how-to/os-bootstrap',
        'how-to/pve-overlay',
        'how-to/troubleshooting',
      ],
    },
    {
      type: 'category',
      label: 'ナレッジベース（実環境知見）',
      collapsed: true,
      items: [
        'knowledge-base/dhcpv6-pd-clients',
        'knowledge-base/ntt-ngn-pd-acquisition',
      ],
    },
    {
      type: 'category',
      label: '運用',
      collapsed: true,
      items: [
        'operations/state-database',
        'operations/inventory',
        'operations/usb-persistence',
        'operations/alpine-deployment',
        'operations/secrets',
        'operations/observability',
        'operations/otel-dashboards',
        'operations/high-availability',
        'operations/ingress-maintenance',
        'operations/development',
        'operations/ndpi-agent-libndpi',
      ],
    },
    {
      type: 'category',
      label: 'リファレンス（API・プロトコル・対応環境）',
      collapsed: true,
      items: [
        'api-v1alpha1',
        'control-api-v1alpha1',
        'plugin-protocol',
        'platforms',
        'hardware-compatibility',
      ],
    },
    {
      type: 'category',
      label: 'リリースと安定版',
      collapsed: false,
      items: [
        'releases/stable',
        'releases/changelog',
        'operations/release-process',
      ],
    },
    {
      type: 'category',
      label: '設計ノート',
      collapsed: true,
      items: [
        'design',
        'design-notes',
      ],
    },
    {
      type: 'category',
      label: 'プロジェクト',
      collapsed: true,
      items: [
        'contributing',
        'legal',
      ],
    },
  ],
};

export default sidebars;
